### ISSUE TITLE
Save cURL into clipboard

### ISSUE THREAD

**Issue by wprater** [Huachao/vscode-restclient#100]
would be great to have an option to save the last request into your clipboard as a curl request.  this way you can easily share that request with others.

**Comment by Huachao** [comment]
@wprater nice suggestion, I will implement it ASAP

**Comment by wprater** [comment]
we should not save this into clipboard automatically.  probably assign a hotkey? or at least a config if it will go into clipboard after request is made

**Comment by Huachao** [comment]
@wprater you can try the latest version 0.14.5 to test, and in my current implementation, you can right click the request in the editor, and select `Copy Request As cURL`. Or simply from command palette.

**Comment by wprater** [comment]
can you copy from the response side too, that would be helpful.

**Comment by Huachao** [comment]
Do you mean also add this option in the response panel? Since I think the curl command doesn't related to whether you sent the request, so I just put this function in request.

**Comment by wprater** [comment]
well, Im not always certain which request I made :) . I have a lots in my `.http` files usually ;)

**Comment by Huachao** [comment]
so your pain point is also related to #99 , since you want to know what's the actual request, right?

**Comment by wprater** [comment]
> so your pain point is also related to #99 , since you want to know what's the actual request, right?

exactly.

**Comment by Huachao** [comment]
However, why you will get a response which you don't know which request it's issued? So what's the value of a response that you are not sure what the request is in fact

**Comment by wprater** [comment]
mostly if I came back to it another day and I like the verbosity of seeing/knowing in the one interface.  not a huge complain/concern at all.

**Comment by Huachao** [comment]
OK, I see. I will add the request info in response later if you turn on some flag in config. And one quick to find last request is from request history 😄  Thanks for your feedback

**Comment by wprater** [comment]
> @wprater you can try the latest version 0.14.5 to test, and in my current implementation, you can right click the request in the editor, and select Copy Request As cURL. Or simply from command palette.

found an issues and I commented directly on your commit.

**Comment by Huachao** [comment]
@wprater I have fixed this issue and will publish this fix in a new version

**Comment by Huachao** [comment]
@wprater you can try the latest version 0.14.6 to verify.

**Comment by wprater** [comment]
works great, thanks for the fix!
