### ISSUE TITLE
No prompt for @prompt variables

### ISSUE THREAD

**Issue by alexgagnon** [Huachao/vscode-restclient#1010]
- REST Client Version: 0.24.6
- VSCode Version: 1.67.2 and 1.55.2
- OS Version: Windows 10, 1909

Steps to Reproduce:

1. Install extension
2. Create simple request with a prompt variable

```rest
# @prompt host
GET https://{{host}}
```

I am never prompted for a value, so the request fails

**Comment by mu-yu** [comment]
get same error with version 0.24.6

**Comment by zh-five** [comment]
same

**Comment by phaza** [comment]
This was merged in April, last release (0.24.6) was in November '21.  
Wont work until next release.

**Comment by Huachao** [comment]
@phaza @blatoo @zh-five @mu-yu @alexgagnon now you can try the latest version 0.25.0 :)

**Comment by diverdm** [comment]
Now it's not working at all! v0.25.1
