### ISSUE TITLE
Raw / text requests

### ISSUE THREAD

**Issue by thomastropper** [Huachao/vscode-restclient#1018]
Hi

how does a body need to be formed when Content-Type is set to "text/plan"?

kind regards
thomas

**Comment by Huachao** [comment]
@thomastropper you can type text as you want if you just want `text/plain`

**Comment by thomastropper** [comment]
thanks @Huachao 

this i understood, but how should the body then be formed? must this be wrapped like below?

`
 # @name myname
POST https://www.mydomain.net/api/someapie
Content-Type: text/plain

{
    myplaintextbody
}
`
