### ISSUE TITLE
Keyboard shortcut not working (Ctrl+Alt+R)

### ISSUE THREAD

**Issue by erhanalankus** [Huachao/vscode-restclient#102]
- VSCode Version: 1.12.2
- OS Version: Windows 10, version 1607, os build 14393.1198
- REST Client Version: 0.14.4

Steps to Reproduce:

1. Type url (https://api.github.com/users/erhanalankus/repos)
2. Press Ctrl+Alt+R

I can send the request if I select it from the F1 menu.

**Comment by Huachao** [comment]
@erhanalankus thanks for reporting, could you please check the actual pressed keys when pressing `Ctrl+Alt+R` with following steps.

To find out what a keybinding does:

1. Open Preferences > Keyboard Shortcuts
2. Click the `keybindings.json` in the sentence `For advanced customizations open adn edit keybindings.json`
3. Click on Define Keybinding
4. Press your desired key combination (Ctrl+Alt+R), and check what's showing in input field

**Comment by erhanalankus** [comment]
I followed the steps you wrote, tried again, and now it works. I think it was something about my pc.
