### ISSUE TITLE
Unable to use REST Client for curl in 0.25

### ISSUE THREAD

**Issue by jackblk** [Huachao/vscode-restclient#1026]
- REST Client Version: 0.25
- VSCode Version: 1.68.1 (2022-06-14)
- OS Version: MacOS 12.4 (ARM64)

```
Version: 1.68.1
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:48:37.209Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 21.5.0
```

Steps to Reproduce:

Use this snippet

```
curl 'https://github.com/Huachao/vscode-restclient' \
  -H 'authority: github.com' \
  -H 'accept: text/html, application/xhtml+xml' \
  -H 'accept-language: en-US,en;q=0.9,vi;q=0.8' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36' \
  --compressed
```

Sending request will cause this error:

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/12843654/177248642-3e6d19a7-e95b-4491-af5e-bc614b9c7fed.png">

I revert back to 0.24.6 and I can use it normally.

**Comment by Huachao** [comment]
@jackblk nice catch, I will publish this fix in the next release.
