### ISSUE TITLE
Variable autocompletion adds escaped brackets instead of brackets

### ISSUE THREAD

**Issue by pcastellazzi** [Huachao/vscode-restclient#103]
- VSCode Version: 1.13.0
- OS Version: macOS 10.12.5
- REST Client Version: 0.14.4

Steps to Reproduce:

1. Create a file named `test.http`

2. Add some variables with this snippet to your settings

```json
"rest-client.environmentVariables": {
        "default": {
            "app_server": "localhost",
            "app_token": "12345678"
        }
    }
}
```

3. Select the environment we just created with `Cmd+Option+E => default`

4. Write `GET app`. The autocompletion popup appears, select `app_server`, then press `ENTER`.

I expected to get `GET {{app_server}}`. Instead i got `GET \{\{app_server\}\}`.

**Comment by Huachao** [comment]
@pcastellazzi I have fixed the issue, and you can try the latest version 0.14.5 to verify: 😄

**Comment by pcastellazzi** [comment]
Thank you very much. Awesome work!
