### ISSUE TITLE
POST binary data add new line to uploaded file (request body)

### ISSUE THREAD

**Issue by isimonov** [Huachao/vscode-restclient#1031]
- REST Client Version: v0.25.0
- VSCode Version: 1.69.0
- OS Version: Windows 11 (Windows_NT x64 10.0.22000)

Steps to Reproduce:
```
POST http://localhost:8080/upload
Content-Type: application/octet-stream

< ./test.pdf
```

This test.pdf file on backend not equal file which was passed because it ended up with an empty string. Maybe this bug is related to https://github.com/Huachao/vscode-restclient/pull/999 Check, please.

**Comment by Huachao** [comment]
@isimonov can you work with version 0.24.6?

**Comment by smilix** [comment]
Hi, 

I've the same problem and using the latest version v0.25.1.

**Comment by Sobczyszyn** [comment]
version 0.24.6 does not add a new line.

**Comment by caimaoy** [comment]
I use nc to check this and found  `Connection: close` in the request before the boundary
```http
POST /detection/v1/caimaoy HTTP/1.1
user-agent: vscode-restclient
content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxTrZu0gW
accept-encoding: gzip, deflate
content-length: 818
Host: 127.0.0.1:8004
Connection: close

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="test.py"
```

**Comment by Huachao** [comment]
@isimonov @smilix @Sobczyszyn @gmeligio I have fixed the issue and will publish this in the next release
