### ISSUE TITLE
Cannot read properties of undefined (reading 'toString')

### ISSUE THREAD

**Issue by monisnap-julien** [Huachao/vscode-restclient#1033]
Hello, I'm getting this error

```
Cannot read properties of undefined (reading 'toString')
```

when doing a simple cURL request like this one 👍 

```
### Test
curl https://cat-fact.herokuapp.com/facts/random
```

Could you please help me understand what i'm doing wrong ?

**Comment by spone379** [comment]
the same issue!

**Comment by trbhoang** [comment]
same issue

**Comment by afiiif** [comment]
I'm getting this error too since updating it to `v0.25.0`.

My current solution is to install another version and choose `v0.24.6`. It worked just fine.

**Comment by afiiif** [comment]
@Huachao, I think this commit [d8528c2
](https://github.com/Huachao/vscode-restclient/commit/d8528c26581bb9c50a3114237fa20230108da481) should be released ASAP.

**Comment by whinc** [comment]
short-term solution: request with body to avoid body parse error according this commit d8528c2

```
### Test
curl https://cat-fact.herokuapp.com/facts/random --data "anything"
```

**Comment by doanthaibao** [comment]
Same issue.

**Comment by doggy8088** [comment]
Is there any PR for this issue?

**Comment by doggy8088** [comment]
@Huachao When will you release new version to the VSCode Marketplace?

**Comment by doanthaibao** [comment]
> @Huachao When will you release new version to the VSCode Marketplace?

I think you should downgrade to version 0.24.6 in a mean time.
![image](https://user-images.githubusercontent.com/9799644/185636158-66461dfc-62dc-497e-9de7-12e74db2ac62.png)

**Comment by Huachao** [comment]
@monisnap-julien @doggy8088 @doanthaibao @whinc @afiiif @trbhoang @spone379 @liongkj @sminder @jgoodw1n @doggy8088 @JtMotoX @y4code @robotroll @amine-prime sorry for the late reply, you can checkout the latest version 0.25.1 to verify the fix

**Comment by doggy8088** [comment]
I confirmed. It do works. Thank you! 👍

**Comment by goldo** [comment]
Hi @Huachao I still got this issue here. 
The problem is: I use cursor, and the latest version available is 0.25.0, which contains that bug.

Could you please deploy a new tag/version ? 🙏  thanks a lot !

**Comment by artur-zaseev** [comment]
Please deploy a new tag/version for Cursor 🙏

**Comment by mmospanenko** [comment]
Same issue on Antigravity IDE using the Open VSX version:
https://open-vsx.org/extension/humao/rest-client

- 0.25.0: has the bug
- 0.24.6: works correctly

Could you publish a fix?
