### ISSUE TITLE
Add a "Run" button on the left of the HTTP request

### ISSUE THREAD

**Issue by doggy8088** [Huachao/vscode-restclient#1038]
Does the VSCode able to add something like "Green Triangle" button (see below) to "Send Request" by simply click on the play button?

![image](https://user-images.githubusercontent.com/88981/180655912-3bbd7ada-19a2-4385-a8b2-3e0f2203abbb.png)

**Comment by yorkblansh** [comment]
Yot can see the **Send Request** button in vscode:
![image](https://user-images.githubusercontent.com/67924262/181224440-3cfbf7c1-7129-4c45-bfa6-b8390178a3b3.png)

**Comment by doggy8088** [comment]
After I turn on CodeLens, I can see it now. Thanks.
