### ISSUE TITLE
Variable substitution fails when there is spaces after/before the brackets

### ISSUE THREAD

**Issue by pcastellazzi** [Huachao/vscode-restclient#104]
- VSCode Version: 1.13.0
- OS Version: macOS 10.12.5
- REST Client Version: 0.14.4

Steps to Reproduce:

1. Create a file named `test.http`

2. Add some variables with this snippet to your settings

```json
"rest-client.environmentVariables": {
        "default": {
            "app_server": "https://www.google.com",
            "app_token": "12345678"
        }
    }
}
```

3. Select the environment we just created with `Cmd+Option+E => default`

4. Write `GET {{ app_server }}/#q=hello+world`.

5. Run the query with `Send request`

I expected to get the result pane with a 200 ok HTTP response and the content. Instead i got this error message: `Invalid URI "%7B%7B%20app_server%20%7D%7D/#q=hello+world"`

**Comment by Huachao** [comment]
@pcastellazzi nice catch, I have implemented this in version 0.14.5, and you can try it now 😄
