### ISSUE TITLE
Problem with Basic Auth

### ISSUE THREAD

**Issue by pratikkabade** [Huachao/vscode-restclient#1048]
I'm getting `500 Internal Server Error` everytime. Is there any problem in this code

```http
POST https://localhost:5001/api/authenticate/ HTTP/1.1

@username = "john doe"
@password = "foobar"

Authorization: Basic {{username}}:{{password}}
```

**Comment by lhasadad** [comment]
500 code says something is wrong on the receiving end (have you checked the logs of whatever is responding on port 5001?

**Comment by pratikkabade** [comment]
@lhasadad  Initially I've used thunderbird, there i didnt feel any issue but here I was facing this one, is there any **syntax** error?

**Comment by lhasadad** [comment]
@pratikkabade not following what you mean by "i've used thunderbird".

Is the 500 error what you are seeing in the response from executing the POST?   If so its typically an exception in the code servicing your request and the error that caused it will reported in that codes log files or console screen. 

Finally think I would mention is I suggest taking the HTTP/1.1 off the post.  I don't recall if its allowed there but it should work without it present.   That might be being interpreted as part of your URL and the receiving side may be having issue with the space character before the HTTP/1.1 string

**Comment by pratikkabade** [comment]
Thunderbird is a vs code extension similar to postman, just its integrated into vs code.

Thats the reason why I raised this issue, i can do POST operation from other services but just not from this one. 

Oh i see, Thanks anyways.

**Comment by lhasadad** [comment]
Ah, thanks for that info,   I was not aware of thunderbird myself.  will have to have a look too.  Hope something I said was useful

**Comment by pratikkabade** [comment]
Sure give it a try it VS Code extension.
Yeah ofcourse it was..

**Comment by lhasadad** [comment]
@pratikkabade Was the other extension Thunder Client?   I don't see a thunderbird extension for VS Code.

**Comment by pratikkabade** [comment]
@lhasadad Yes, it is Thunder Client, it was a long time so I fergot its name.
Did you try it?

**Comment by lhasadad** [comment]
@pratikkabade I have in the past and may in the future, but I like REST Client because I can set up the api calls in a file.

**Comment by pratikkabade** [comment]
Exactly, thats why i too was trying to use it.

**Comment by pratikkabade** [comment]
By the way if you want to see this is what I mean by 500

### thunder client
![image](https://user-images.githubusercontent.com/76637730/188778462-9fdf154c-5709-4995-8a5a-931aa3448afb.png)

### restclient
![image](https://user-images.githubusercontent.com/76637730/188778838-3d20e245-1b48-4cae-aefb-8b4d5f4b0ed1.png)

Again, i really appreciate your help!

**Comment by lhasadad** [comment]
@pratikkabade  the 500 is definitely coming back from the server that you are getting the token from.   one thing that is different between the two clients is the '/' character at the end of authenticate in the url

**Comment by pratikkabade** [comment]
@lhasadad no.. its not that big of a deal but still ill see removing it

**Comment by pratikkabade** [comment]
@lhasadad, I added an extra line between `POST` and `Authorization` that was causing this error. 

correct syntax

```http
POST https://localhost:5001/api/authenticate/ HTTP/1.1
Authorization: Basic johndoe:foobar
```
