### ISSUE TITLE
"Generate code snippet" does not include the POST body when Content-Type: application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by codeborn** [Huachao/vscode-restclient#105]
- VSCode Version: 1.13.0
- OS Version: 10.11.6 (El Capitain)
- REST Client Version: 0.14.5

Steps to Reproduce:

1. Write this request in a .http file:
###
POST https://example.com/some/endpoint
Content-Type: application/x-www-form-urlencoded
Authorization: Basic user password

some+data

###
2. Right-click and select "Generate code snippet"

Actual result:
curl --request POST \
  --url https://example.com/some/endpoint \
  --header 'authorization: Basic dXNlcjpwYXNzd29yZA==' \
  --header 'content-type: application/x-www-form-urlencoded'

Expected result:
curl --request POST \
  --url https://example.com/some/endpoint \
  --header 'authorization: Basic dXNlcjpwYXNzd29yZA==' \
  --header 'content-type: application/x-www-form-urlencoded'
  --data 'some+data'

Some additional observations:
* This works if Content-Type is omitted (which is my current workaround) or set to something like "application/json".
* Using PUT yields the same error.
* HTTP or HTTPS also do not affect the outcome. 
* Setting an invalid content-type (such as: "application/x-www-form-urlencodedzzz") actually works!

**Comment by Huachao** [comment]
@codeborn nice catch, I will publish this in next release

**Comment by Huachao** [comment]
@codeborn you can try the latest version 0.14.6 to verify

**Comment by codeborn** [comment]
OK, the body data is there now. Nice work!

It works with unencoded data, like:
> value=some data
Results in (correct!):
> value=some%20data
Also correct would be:
> value=some+data

But not with data that is already encoded, like:
> value=some+data
Results in (arguably ... wrong! The plus sign gets encoded into %2D):
> value=some%2Ddata

Also data that is already percent encoded, like:
> value=some%20data
Results in (arguably ... wrong! The percent sign gets encoded into %25):
> value=some%2520data

These both examples where it goes wrong could arguably be considered correct behavior and I would not make fuss about this unless it already worked when sending the requests directly from the plugin. It is just the "Generate code snippet" that messes up. I expect the generate code functionality to work the same as when sending directly from the plugin.

I think this is a bit of a gotcha if I have large request bodies. Is there an easy way to make "generate code snippet" to handle this the same way the plugins own HTTP does? Should I file a new issue for this?

**Comment by Huachao** [comment]
@codeborn you can file a new issue, my question is does the cases really work with `Send Request`?

**Comment by codeborn** [comment]
Yes, they work. Maybe this is more surprising actually. :)

If it did not work I would actually not consider this a problem. The thing is, I am migrating away from Postman, (https://www.getpostman.com/) as it is a bit unreliable and very "clicky" interface. In postman I have to do that encoding myself so I kind of expected having to do it in your plugin too.

**Comment by Huachao** [comment]
@codeborn I can't work in my test, can you provide me your request?

**Comment by codeborn** [comment]
I put together examples in a .http file and attached it here. Github does not allow the .http file suffix so I renamed to .http.txt :)

[body-encoding.http.txt](https://github.com/Huachao/vscode-restclient/files/1108328/body-encoding.http.txt)

**Comment by Huachao** [comment]
@codeborn I will fix the bug in both sending request and generating code snippet. One interesting thing I found is that although all the response body sent back from httpbin.org look the same, however, the `Content-Length` header are different in fact. So I think this maybe a bug from httpbin.org. Anyway, I think my code should be responsible for encoding(or not) the _x-www-fromurlencoded_ body in the correct way. I will update in this thread ASAP. And if something I was wrong, please feel free to tell me.

**Comment by Huachao** [comment]
@codeborn I'd like to close it, the implementation is described as above, if you still have any concern, pls feel free to reopen it.

**Comment by codeborn** [comment]
The examples you provided seem reasonable. Thanks!

**Comment by Huachao** [comment]
@codeborn you can try the latest version 0.15.0 to verify

**Comment by codeborn** [comment]
Sorry, I forgot about your message. I will have a look later today.

**Comment by codeborn** [comment]
I just tested with 0.15.2. This now works perfectly! Thanks!
