### ISSUE TITLE
How can I search/find in the response ?

### ISSUE THREAD

**Issue by srikanth-vm** [Huachao/vscode-restclient#106]
- VSCode Version: 1.13.1
- OS Version: OSX 10.12.4
- REST Client Version: 0.14.5

As of now I cannot find anything in the response opened in the tab. I need to save the json and then open it up.  

Sounds really stupid, but am I missing some thing here 😄

**Comment by Huachao** [comment]
@srikanth-vm Since vscode has limitation in search functionality in webview(By default, previewed response result is web view). If you want to search, one way is to set the vscode setting `rest-client.previewResponseInUntitledDocument` to `true`.

**Comment by srikanth-vm** [comment]
@Huachao Awesome ! Just needed that.

**Comment by Huachao** [comment]
@srikanth-vm in latest vscode 1.15.0, you can already search in preview page with keyboard shortcut `Cmd+F`. With this feature, you can set `rest-client.previewResponseInUntitledDocument` to `false` again.
