### ISSUE TITLE
Add "Content-Length" header

### ISSUE THREAD

**Issue by maxtar** [Huachao/vscode-restclient#107]
When I do POST request, I want to have automatically added "Content-Length" header. Like in browsers.

**Comment by Huachao** [comment]
@maxtar Do you mean that you didn't get the `Content-Length` header at server side? Do you use file syntax to provide request body like `< ./example.json`?

**Comment by maxtar** [comment]
Yeap. I use "<" for create body from file. And in this case server do not receive Content-Length

**Comment by Huachao** [comment]
@maxtar when we use "<" syntax to send request body, by default we will use [`Transfer-Encoding: trunked` header](https://en.wikipedia.org/wiki/Chunked_transfer_encoding) in request, which doesn't use `Content-Length` to indicate request body length. To overwrite the behavior, you can set the setting `rest-client.useTrunkedTransferEncodingForSendingFileContent` to `False`.

**Comment by maxtar** [comment]
Thanx! Looks like it works for me. :)
