### ISSUE TITLE
Support self-signed server certificates

### ISSUE THREAD

**Issue by defectus** [Huachao/vscode-restclient#108]
- VSCode Version: 1.13.1 (1.13.1)
- OS Version: macOS 10.12.5
- REST Client Version: 0.14.6

Steps to Reproduce:

1. create a HTTP file pointing to a server using a self-signed server certificate.
2. an error is thrown: `write EPROTO 140737217418176:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../../vendor/node/deps/openssl/openssl/ssl/s3_pkt.c:1487:SSL alert number 40`

Ideally there should be a setting allowing to connect to insecure HTTP servers. 
I believe the underlaying setting is `agentOptions.rejectUnauthorized` = `false` - see https://nodejs.org/api/tls.html#tls_tls_connect_options_callback.

**Comment by Huachao** [comment]
@defectus what's your value of `http.proxyStrictSSL` and `http.proxy` settings?

**Comment by defectus** [comment]
I don't use proxy so it's empty.

**Comment by Huachao** [comment]
> I believe the underlaying setting is agentOptions.rejectUnauthorized = false

@defectus in my code, if the proxy setting is not specified, and the `rejectUnauthorized` had already be set to `false`. So it may be other reasons. Could you provide me more details with the tool like __openssl__ or __curl__. Thanks in advance.

**Comment by defectus** [comment]
I don't see it to be set to `false` anywhere in the code and according to the documentation (https://nodejs.org/api/tls.html#tls_tls_connect_options_callback) it's set to `true` by default.

```
POST https://10.232.1.186/queue-num HTTP/1.1 
Content-Type: application/json

{"phoneNumber":"608766809", "IVRID":1}
```

This what I call. The service uses client certificates but should be good enough for you to test it.

**Comment by Huachao** [comment]
@defectus my code is in [httpClient.ts](https://github.com/Huachao/vscode-restclient/blob/master/src/httpClient.ts#L69), and this option is sent to the underlying request [library](https://github.com/request/request/blob/master/request.js#L255-L257) which I use, and it will convert `strictSSL === false` value to `rejectUnauthorized false`.

And I can't connect to the ip you've mentioned above (Event can't Ping).

**Comment by defectus** [comment]
This server is actually accessible from a narrow range of IPs only. Anyway, I just tried some sites with invalid certificates and they worked so it's probably something beyond the library you use.

If you don't want to spend more time investigating fell free to close this issues as I'm unable to provide you with a site where you could reproduce this issue. Sorry about that.

**Comment by Huachao** [comment]
@defectus don't feel sorry, I will close the issue for now and please feel free to reopen it if you have some new finding. 😄
