### ISSUE TITLE
Local variables definition in .http files

### ISSUE THREAD

**Issue by borekb** [Huachao/vscode-restclient#109]
It would be nice if I could define variables in some comment in the `.http` file. My user settings are synchronized via VSCode Settings Sync and I don't want everything there, neither it fits very well into the workspace settings which are committed to Git and shared in a team.

For example would look like this:

```
# "__variables" {
#    "server": "127.0.0.1:3010",
#    "param": "abc",
# }

GET http://{{server}}/api/{{param}}
```

This is basically an embedded JSON but could be anything, really.

**Comment by Huachao** [comment]
@borekb thanks for your great suggestion, this is duplicated with issue #84, I'd like to close it to update in that thread.

**Comment by Huachao** [comment]
Duplicate of #84
