### ISSUE TITLE
Add XML response format

### ISSUE THREAD

**Issue by StephD** [Huachao/vscode-restclient#11]
- VSCode Version: 1.3
- OS Version: Win 7

Enhancement

It could be great to format the answer which have the content-type: application/xml.
\<data>\<test>foobar\</test>\</data>
==>
\<data>
     \<test>foobar\</test>
\</data>

**Comment by Huachao** [comment]
@StephD, nice suggestion, I will implement it ASAP

**Comment by Huachao** [comment]
@StephD, fixed in latest version of REST Client with v0.5.3
