### ISSUE TITLE
Missing parameters in CURL/POST body 

### ISSUE THREAD

**Issue by drmistral** [Huachao/vscode-restclient#112]
- VSCode Version: 1.14.2
- OS Version: MacOS Sierra 10.12.3
- REST Client Version: 0.15.1

Steps to Reproduce:

1. From terminal just send following call:
`curl -i -X POST -d par1=one -d par2=two "https://httpbin.org/post"`

in the returned response we find:

`
...
  "data": "",
  "form": {
    "par1": "one", 
    "par2": "two"
  }, ...
`

2. Do the same call from vs rest client. In response we find:

`...
"data": "par1=onepar2=two"
"form": {},...
`

In my case a java server looks for form data in request parameters through request.getParameter("par1"), when calling from vs rest client result is null. I did several trials using --data, -F but result is the always the same, i.e form is empty.

**Comment by Huachao** [comment]
@drmistral nice catch, I will fix this ASAP.

**Comment by Huachao** [comment]
@drmistral you could use the latest version 0.15.2 to verify 😄

**Comment by drmistral** [comment]
Just checked, it's fine! Thanks!
