### ISSUE TITLE
RequestError: connect ECONNREFUSED 127.0.0.1:3000.

### ISSUE THREAD

**Issue by webwiserin** [Huachao/vscode-restclient#1130]
![Facing Error in VS](https://user-images.githubusercontent.com/108581626/218395801-7adc1838-48a9-4c39-a58f-272037c61d28.png)
![Not Working 127 1](https://user-images.githubusercontent.com/108581626/218395816-da583703-14eb-41e6-847e-1171944914b3.png)
![working with localhost](https://user-images.githubusercontent.com/108581626/218395822-038ad164-67b2-4fa7-aada-deec5fd81662.png)

**Comment by monisnap-julien** [comment]
Same issue here. We run on node 18 and downgrading to node 16 seems to solve it for now, but it would be better to have a solution to this quickly.
