### ISSUE TITLE
Ctrl-Alt keybinds conflicts

### ISSUE THREAD

**Issue by enkol** [Huachao/vscode-restclient#115]
On some international keyboard layouts, the AltGr key is used to type some characters.
Due to not all keyboards having an AltGr key, the combination Ctrl-Alt is a substitute for AltGr.

With german layout this is the case for the @ symbol, which is typed with AltGr-Q. 
Therefore, trying to type an @ symbol, conflicts with Rest-Clients Ctrl-Alt-Q shortcut. The same is the case for Ctrl-Alt-E, which conflicts with typing € symbol.

This results in not being able to type @ for delcaring a local variable in a .rest file, when using a german keyboard layout. 

Because of such conflicts, it's advised to not use Ctr-Alt for shortcuts. As there may be other conflicts with other languages layouts. See https://en.wikipedia.org/wiki/AltGr_key

To fix this, either change the default shortcuts or at least add a note in the extensions readme about this possible shortcut problems, so users are told why they may not be able to type @.  Should then also recommend to change the "Cancel Request" shortcut (and maybe others) via vscode settings, when expierincing such problems.

- VSCode Version: 1.14.2
- OS Version: Windows 10
- REST Client Version: 1.5.1

Steps to Reproduce:

1. Change OS keyboard layout to German
2. In vscode open a *.rest or *.http file
3. Try to type the @ symbol by pressing AltGr-Q or Ctrl-Alt-Q

**Comment by Huachao** [comment]
@enkol thanks for your suggestion, and I'd like to modify the keyboard shortcut `Ctrl+Alt+Q` to `Ctrl+Alt+D`. Do you think it's ok, and it seems it works for German keyboard

**Comment by enkol** [comment]
`Ctrl-Alt-K` is fine with German keyboard layout.

According to https://en.wikipedia.org/wiki/AltGr_key, `Ctrl-Alt-K` is used for South Slavic Latin, Latvian, Macedonian and Belgian layout. But it's not for a critical character, like it was with German layout (@).

**Comment by Huachao** [comment]
@enkol thanks so much, as you said for other keyboard layouts `Ctrl+Alt+K` is not critical, so I'd like to keep it.

**Comment by Huachao** [comment]
@enkol you could use the latest version 0.15.2 to verify 😄

**Comment by enkol** [comment]
I can verify that `Ctrl-Alt-Q` isn't used anymore, so there is no more conflict with typging the `@` Symbol.
I did not test `Ctrl-Alt-K` canceling a request (i've no quickly available text case).
