### ISSUE TITLE
 But all styles including: background color, foreground color, buttons, borders, s...

### ISSUE THREAD

**Issue by zhouxinghong** [Huachao/vscode-restclient#1151]
This extension is awesome! 👍👍👍 But all styles including: background color, foreground color, buttons, borders, scroll bars, input boxes, etc. should inherit from theme styles instead of another set of styles. . . Only in this way can it be consistent with the theme style. . . Better user experience! 😜😜
Windows10
0.25.1

**Comment by Huachao** [comment]
Duplicate of #1150
