### ISSUE TITLE
ECONNREFUSED 127.0.0.1:443 when url is a file variable in quotes

### ISSUE THREAD

**Issue by mateeni-dev** [Huachao/vscode-restclient#1153]
- REST Client Version: 0.25.1
- VSCode Version: 1.78.2
- OS Version: windows 11

Steps to Reproduce:

1. Any GET request with base url set as a file variable, and wrapped in quotes (either single, or double)

```
@baseUrl = "https://jsonplaceholder.typicode.com"

###

GET {{baseUrl}}/todos/1 HTTP/1.1
```

More Details:

I have tried using multiple file variables (with double quotes) in a POST request and only the `baseUrl` one gives me error. Removing quotes from `baseUrl` fixes it

![Screenshot 2023-05-17 010745](https://github.com/Huachao/vscode-restclient/assets/36093197/0420be8e-92ca-4be5-9b86-66f830e1565e)

**Comment by Huachao** [comment]
You can try to remove the double quote around the variable value

**Comment by mateeni-dev** [comment]
> You can try to remove the double quote around the variable value

Sure I can, and actually as I mentioned earlier that is what solves the issue. However, would it not be better to have a consistent behavior across all types of file variables?

Unless of-course you say that this is by design, in which case this could be caught before initiating the http request and a helpful error message would save everyone's time.
