### ISSUE TITLE
Period in variable name falsely marked as error

### ISSUE THREAD

**Issue by drmcclelland** [Huachao/vscode-restclient#1155]
- REST Client Version:   v0.25.1
- VSCode Version:   1.78.2
- OS Version:   Windows 11

Steps to Reproduce:

1. Create a request as follows:

```
@MyTest.API_HostAddress = https://localhost:44333

GET {{MyTest.API_HostAddress}}/v1/products
```

2. This is a perfectly valid request (the variable name syntax is valid), and it can be sent successfully - but it's marked as an error in the VSCode IDE:

Screenshot:

![image](https://github.com/Huachao/vscode-restclient/assets/6124858/d6ba2424-ba0b-4464-a377-c4832dee359e)

3. Changing the variable name to something without a period like `MyTest_API_HostAddress` shows no syntax error:

![image](https://github.com/Huachao/vscode-restclient/assets/6124858/5b4601b0-39d6-409b-a857-ababee5dd1d7)

**Comment by Huachao** [comment]
@drmcclelland this bug will be fixed in the next release
