### ISSUE TITLE
Unable to preview large response

### ISSUE THREAD

**Issue by alabaki** [Huachao/vscode-restclient#116]
- VSCode Version: 1.15.0 x64
- OS Version: Windows 10 x64
- REST Client Version: 0.15.1

Steps to Reproduce:

1. In the settings, set: "rest-client.previewResponseInUntitledDocument": true
2. Call a GET http method that returns a 7MB response.
3. No untitled document opens and the error below is displayed in the Dev Tools Console:

![image](https://user-images.githubusercontent.com/13958061/29331342-b6aab954-81c1-11e7-9f5c-c872d2e6458a.png)

For small response, the extension is working normally and the untitled document is opening.

**Comment by Huachao** [comment]
@alabaki I have created a bug in Microsoft/vscode#32608. And I will follow it.

**Comment by Huachao** [comment]
@alabaki this should have already been fixed in vscode 1.16, it has increase the limit to 50M
