### ISSUE TITLE
client puts an endline whitespace on the end of binary data

### ISSUE THREAD

**Issue by mmenzyns** [Huachao/vscode-restclient#1175]
- REST Client Version: v0.25.1
- VSCode Version: 1.79.2 (Universal)
- OS Version: Darwin arm64 22.4.0

Steps to Reproduce:

1. create a configuration that sends binary data, such as:
```
POST http://127.0.0.1:80/foo/bar

< ./challenge1
```
2. send and analyse the dataa

There is undesired 0x0A byte on the end of the body. When tested with Curl and JetBrains HTTP client, the data sent are correct (without 0A)

**Comment by Huachao** [comment]
@mmenzyns I have fixed the issue and will publish this in the next release

**Comment by cjlpowers** [comment]
@Huachao What is the ETA on the next release?
