### ISSUE TITLE
Support for Query String Split view for large url request 

### ISSUE THREAD

**Issue by karthikeyangss** [Huachao/vscode-restclient#118]
- VSCode Version:1.15.1
- OS Version: Windows 10
- REST Client Version: 0.15.2

Enhancement :
We often encounter large request url , if we can provide a view to see query params as proper name value pair. (or even if we provide enhancement in existing feature to support multi-line get param to format big url to new line view)
It would add additional utility to REST client.

eg: 
For input:
     https://example.com/comments?page=2&pageSize=10&start=25&name=test

New View:
https://example.com/comments
page=2
pageSize=10
start=25
name=test

**Comment by Huachao** [comment]
@karthikeyangss this is already supported in our extension, as described in `README`, the syntax looks like as follows:

GET https://example.com/comments
    ?page=2
    &pageSize=10
