### ISSUE TITLE
Info/Warning notifications blocking all tabs

### ISSUE THREAD

**Issue by kmurali676** [Huachao/vscode-restclient#119]
- VSCode Version: 1.16.0
- OS Version: Mac
- REST Client Version:0.15.2

Steps to Reproduce:
1. Call API that returns response header "application/json", but no body
2. It displays warning: "The content type of response is application/json, while response body is not a valid json string"

Every time when I send a request, it displays info ribbon that block all other tabs. I need to close notification manually every time which is really annoying. Please display notifications in the response view only. Or make notifications optional in the settings so that I can disable them.

Apart from that, I really like the extension and I am using it almost everyday.

Thanks

**Comment by Huachao** [comment]
@kmurali676 I have add a setting `rest-client.suppressResponseBodyContentTypeValidationWarning` to suppress such validation warnings. And I will publish this fix in next release

**Comment by kmurali676** [comment]
Thanks much @Huachao. I really appreciate it.

**Comment by kmurali676** [comment]
I am looking forward to the next release.

**Comment by Huachao** [comment]
@kmurali676 you can try the latest version 0.15.3, and you can set the setting `rest-client.suppressResponseBodyContentTypeValidationWarning` to `true` to disable the warning
