### ISSUE TITLE
Can't send localhost

### ISSUE THREAD

**Issue by Xdydy** [Huachao/vscode-restclient#1193]
When I use this command

```http
GET http://localhost:3000/
```

the extension is always displaying waiting and it doesn't response, but it's OK to GET baidu.com.

When I copy as cURL code and run in the terminal, it works correctly. 

How can I solve this problem

**Comment by kidbrax** [comment]
I am able to use `0.0.0.0` successfully in place of `localhost`.

**Comment by Xdydy** [comment]
> I am able to use `0.0.0.0` successfully in place of `localhost`.

It doesn't work. It will response as `Bad Gateway`. Are you sure that it can run `0.0.0.0`?

**Comment by kidbrax** [comment]
It works for me. It may be a symptom of your server and not restclient.

**Comment by Xdydy** [comment]
> It works for me. It may be a symptom of your server and not restclient.

Finally it works for me too! Maybe we should restart the vscode or restart the computer

**Comment by reine-ishyanami** [comment]
I can only access my local service by using 0.0.0.0, using localhost as well as 127.0.0.1 is always waiting in the bottom left corner, why is this happening?

**Comment by Xdydy** [comment]
> I can only access my local service by using 0.0.0.0, using localhost as well as 127.0.0.1 is always waiting in the bottom left corner, why is this happening?

Maybe this is a bug, you just try using 0.0.0.0

**Comment by 5hongbing** [comment]
In my hosts file ：

```
# 127.0.0.1       localhost
# ::1             localhost
```

uncomment it，the problem solved
