### ISSUE TITLE
Others enhancements

### ISSUE THREAD

**Issue by StephD** [Huachao/vscode-restclient#12]
- VSCode Version: 1.3
- OS Version: Win 7

I don't know if it's better to create different issue but here is some proposition and sorry for the english :).

Enhancement :
- [x] Create  a new document with the response content to avoid the white background. To be homogeneous with the application.
- [x] The scroll bar isn't display. It appear if I change the file tab and back to the content-preview (into same same editor).
- [x] The content-preview take some time to appear if I change the tab and back in the preview. Not instant at least.
- [x] Allow to download file as a browser would do or display the content of the file (if possible :))
- [x] crlt+alt+r send the current line request or until the next GET/POST
  I create a file with some request on each line to test my code and I have to highlight the whole line to send a request:
  GET http://......
  GET http://.....
- [x] Display error message if the request is not send due to a malformed request.
- [x] Add collapsible functionality for json and xml?
- [x] Display the line number?
- [x] Make at least three `#` at the beginning of the line as the delimiter

**Comment by Huachao** [comment]
@StephD, I think your suggestions are very nice, and I will investigate all of them, and reply in this thread later. And thanks so much @StephD , if you have interest in my project, it would be very appreciate that you can contribute to this code base

**Comment by StephD** [comment]
I'm not sure to have time and knowledge to improve the code and pull request. Sorry :(

**Comment by Huachao** [comment]
@StephD, don't feel sorry. It's really nice that you have already given so many great suggestions, thanks for your contributions :smiley:

**Comment by Huachao** [comment]
@StephD , the issue that don't show white background has been fixed in latest version 0.6.0, you can have a try :smile:

**Comment by StephD** [comment]
Thanks. It's way more friendly like that now

**Comment by Huachao** [comment]
@StephD for task 2, can you still repro?

**Comment by StephD** [comment]
Yes, but now, the scroll bar disappear after a second request and without changing the tab.
example : 
- Open the program
- Open my http file
- Execute the rest request, everything is fine (scroll bar)
- Re-execute the request, scroll bar disappear.
BUT
If I open a file or create a new one in the right column (where "Response" is). It will add a new tab and "hide" 'Response'. If I click on response tab or re-execute the request, it will reload the tab (time before text appear cf task n°3) and scroll will be there.

Something wrong about the text loading may be

ps: problem is still there after 1.4 update

Hope you understand that :)

**Comment by Huachao** [comment]
@StephD understand, and I think this is a bug related to VS Code itself for the command 'preview.html'. You can also repro this for markdown preview. I will open a issue for them

**Comment by StephD** [comment]
Well, let see how it will be improved by Microsoft

**Comment by Huachao** [comment]
@StephD for task 3, can you see the preview result quickly when you switch back to preview tab?

**Comment by StephD** [comment]
I don't really know. Hard to compare. I may look like faster...
It's not so annoying.
Because it look like an opened file, I thought that the loading time could be instant, like a file, but if it's another form of file, it's ok like that, for me

**Comment by Huachao** [comment]
ok, I will mark task 3 completed, I did some change which I think can improve the loading performance, since previously the style file is loaded from the web, now it's stored in local file.

**Comment by StephD** [comment]
Another enhancement : 
Display error message if the request is not send due to a malformed request.
Because you ask a blank line between headers and body, nothing appear if I try to execute this request without this blank line.

The execution look like a normal request but the server will never receive something and nothing will happen.

**Comment by StephD** [comment]
The new version display an error is there isn't any blank line. I'm not sure that this error is very explicit:
=> Request structure is not valid. Request body must be preceded by a blank line.

![2016-08-09 09_26_38-fl http - gateway - visual studio code](https://cloud.githubusercontent.com/assets/1171858/17508074/688f2a0c-5e13-11e6-8fd8-672e8c907104.png)

**Comment by Huachao** [comment]
@StephD I currently pass all the lines to be `request` package, and let it to check whether the headers are valid, I can improve this to check this from my code and show more user friendly error message

**Comment by StephD** [comment]
Yes, it's just about the friendliness of the message.

**Comment by Huachao** [comment]
@StephD I will improve it later, and mark the task not finished

**Comment by StephD** [comment]
Is it possible to add a collapsible functionality for json and xml (like a vscode file)?
And the number of lines?

**Comment by StephD** [comment]
Is it possible to add a collapsible functionality for json and xml (like a vscode file)?
And the number of lines?
Do you prefere to let me add questions to my post?

**Comment by Huachao** [comment]
@StephD , it's ok to add questions here, and I will investigate it how to implement collapsible and update in this thread later

**Comment by Huachao** [comment]
@StephD do you mean add collapsible functionality for request body or response body? I found for request body already has collapsible functionality.

And for number of lines, I found it's a function of VS Code, I can see number line in my VS Code for .http and .rest file

**Comment by StephD** [comment]
Both are for the response body.

**Comment by Huachao** [comment]
@StephD for response tab in my extension is html page actually, I will investigate it.

**Comment by StephD** [comment]
Hello :)

I come back to you about the 5th functionality.
I'd love to push ctrl+alt+r on any line and launch the current line/section/request instead of the first one of the file.

If I have two or more row with different request, I have to highline the full line and do the action if I want to execute the second, third request.
If I just click at the end of a get request and do the action, it's the first request of the file that will be executed.

I hope you understand what I'm trying to explain :)

Maybe add a detection until the next/previous GET/POST word and execute the whole group of line?

Cheers

**Comment by Huachao** [comment]
@StephD in my implementation, in fact I will have steps to run a request, first is `getting request text`, second is `parsing request`. In `getting request text` step, the logic is quite easy, if highlighted, text is highlighted text, if not, the whole topic. And I will remove all the comment lines in selected text. And pass these text to `parsing request` step. In `parsing request step`, I will parse the first request and execute it.

And we can discuss how to improve the whole flow. Any suggestions or ideas are warmly welcomed

**Comment by StephD** [comment]
The logic is good and quite easy :)
Is it possible to detect the selected line? 
If I click somewhere, vscode highlight (as background color) the whole line (not only the text).
Vscode know where my cursor is so maybe you can detect it and pass this variable to the parsing request step?
You introduce the possibility the have a GET request on multiple line, so I suppose that you can detect blank line.

May be something like 

```
select row = this
Readline as line : number
   If line include GET/POST
       saved req = number
   else 
       next line

   if saved line < select_row
      prev_req = saved_line
   elseif line > select_row
      next_req = savec_line
end readline

parsed_request = whole_text - (size from 0 to prev_req)
// Will remove all the line before the current request
// Parsing request step will execute the first request into the parsed text
```

**Comment by Huachao** [comment]
@StephD one scenario I found maybe confusing is that, if we only have one request in file, originally, use can set the cursor anywhere, and just press ctrl+alt+r to send the request, now, he has to move the cursor to first line of the request, right? Will this be a bad user experience?

**Comment by StephD** [comment]
I'm confuse about what you are explaining and didn't understand well.
Are you saying that if you make a change, user will have to click on the first line of the file if there is only one request?
If yes, I don't understand the bad user experience or what can be bad about that because with only one request in the file, with the algorithm I propose, it will be always the first request that will be sended

**Comment by Huachao** [comment]
My question is where the cursor should be placed if user wants to send out a request (The file only contains one request). In the first line of request or any line, of the request? (Don't use highlight way)

**Comment by StephD** [comment]
On any line. To let the user click on the second/third line if he use a multi-line GET syntax

**Comment by Huachao** [comment]
@StephD a trick to highlight current line in VS Code is to double click on the expected line. This doesn't solve the issue, but before I come up with a better solution, now you can use this trick to easy your operation

**Comment by StephD** [comment]
It's not a real highlight. It's just a display feature to show user which line is the cursor. Double-click will highlight the last word.

About the other rest client extension, do you think that a comment part can be part of the parsing algorithm to detect which request should be send? Or the comment is just there "like that", without a real function for the parser

**Comment by Huachao** [comment]
@StephD I've added the feature that displays line number in response view, and you can try it in the latest version 0.8.7

**Comment by StephD** [comment]
Nice :) Thanks

**Comment by Huachao** [comment]
@StephD I've already supported multiple requests in the same file which is separated by delimiter `###`, and you can simply kick off the request just placing the cursor anywhere between the delimiters. You can try the latest version 0.10.1, and you can view the usage details in `README.md`

**Comment by StephD** [comment]
Hi,
It seem to be a nice and easy feature but I cannot make it works even with you exemple :(

2 things :
First, if I try your exemple, the feature doesn't works. I mean, If I click somewhere between 2 delimiters, the line before GET, GET line or the line after and push the shortcut, it return my a 400 bad request or the first request. You can see the highlight line.
BAD
![2016-11-07 16_43_58-response 388ms - gateway - visual studio code](https://cloud.githubusercontent.com/assets/1171858/20064063/ac04c1ec-a509-11e6-9b5f-275dd536d4ce.png).
GOOD
![2016-11-07 16_46_34-response 431ms - gateway - visual studio code](https://cloud.githubusercontent.com/assets/1171858/20064094/c4a4ca30-a509-11e6-880a-fdcd8e9087c3.png)

Same probleme on my file, it but it send the first line request. I still have to hightlight the request line if I want to send the GET request, even between ### delimiter. So i suppose that there is still an issue about this functionnality.

Second, but I think that it a previous change, I cannot have one request per line anymore. I must have, at least, a blank line to delimit the requests, is it correct and normal?
![2016-11-07 16_48_41- untitled-1 - gateway - visual studio code](https://cloud.githubusercontent.com/assets/1171858/20064175/1261daec-a50a-11e6-9349-0b0137a63637.png)
I think it's easier for you to develop functionality and delimiter or header detection with the kind of syntax.

Small third thing. I do not more have the scroll bar problem (enhancement 2). Maybe vscode update fixed it.

**Comment by Huachao** [comment]
@StephD thanks for your quick response, in my test it works fine. Could you please make sure you've installed the latest version 0.10.1, since vs code sometimes has the cache issue? or simply uninstall and then reinstall it?

**Comment by StephD** [comment]
I thought that your extension was updated to last last version yesterday. But this morning, it was installing the last update (version 0.10.2) and the exemple you gave me works fine.

For the question 2, here is my exemple.
No blank line
![2016-11-08 09_03_15- hello rest - gateway - visual studio code](https://cloud.githubusercontent.com/assets/1171858/20091301/56c612ba-a592-11e6-8938-aed9a2b2aff5.png)
Blank or delimiter works
![2016-11-08 09_03_33-response 302ms - gateway - visual studio code](https://cloud.githubusercontent.com/assets/1171858/20091300/56c55e24-a592-11e6-9504-75e4043b493f.png)

For me, it doesn't bother me even if I don't know why I got header mistake because it only have to launch the first line as request (GET).

Btw, I will have to add `###` at each line to add your functionnality that is very appreciated :).

Question 3. The procedure I explained do not reproduce the error (tab changement). It has you want :)

I'm not more very active on my REST program so I do not follow all your changes for the moment. It still a very good extension and it seem to be appreciated by the community with your 60k+ download :)

**Comment by Huachao** [comment]
@StephD for question 2, since you need to add `###` to separate multiple requests, blank line can work is just due to my code works unexpected 😄 . Although you are not active on REST, and thanks so much for your suggestion and help for my extension, without your help, it can't go step further. Thank you!!!

**Comment by StephD** [comment]
I know you said the is not available right now, but is it possible (may be hard) to add text to the `###` feature? Like the following exemple
`###` test ###
GET http...

**Comment by Huachao** [comment]
@StephD nice suggestion, I will implement it which begins with `###`, and you can append any text after it

**Comment by Huachao** [comment]
@StephD the scroll bar issue is fixed in VS Code Microsoft/vscode#8256 of vs code 1.9

**Comment by Huachao** [comment]
@StephD I have implemented the feature that you can download the response body as a file, like if the response is `application/json`, when you click the `Save Response Body` icon, you can save the json file which contains the response body, and if the response is `image/jpeg`, when you save it, you will get a jpeg file.

**Comment by StephD** [comment]
I would love to see that :)

**Comment by Mashi** [comment]
I was wondering if it is possible to incorporate and execute the calls from inside a Markdown file.  I guess what I am looking for is a way to document the calls for the next poor person that has to take over my work.

**Comment by Huachao** [comment]
@Mashi do you mean add API document or description for each REST call?

**Comment by Mashi** [comment]
I would like to add human readable descriptions above each of the calls if possible.

**Comment by Huachao** [comment]
@Mashi nice suggestion, there's already a similar issue in #67

**Comment by Mashi** [comment]
Sorry for duplicating.  Yes, that's exactly what I was looking for.  :-)

**Comment by Huachao** [comment]
Close this to in favor of the only missing feature request #157
