### ISSUE TITLE
cURL -d option not working properly with @

### ISSUE THREAD

**Issue by pavelevap** [Huachao/vscode-restclient#120]
- VSCode Version: 1.16.1
- OS Version: Windows
- REST Client Version: 0.15.2

Steps to Reproduce:

cURL: `curl -X POST https://SOMEURL -d @filename.json --header "Content-Type: application/json"`

Result: `Unexpected token @ in JSON at position 0
`

**Comment by Huachao** [comment]
@pavelevap sorry for the inconvenience, I will publish this fix in next release.

**Comment by pavelevap** [comment]
Thank you! :+1:

**Comment by Huachao** [comment]
@pavelevap you can try the latest version 0.15.3 to have a try 😄
