### ISSUE TITLE
Connection is being rejected

### ISSUE THREAD

**Issue by ben-foster-cko** [Huachao/vscode-restclient#122]
- VSCode Version: Version 1.17.2 (1.17.2)
- OS Version: MacOS Sierra 10.12.4 (16E195)
- REST Client Version: Latest

Steps to Reproduce:

Try and send request

```
POST /api HTTP/1.1
Host: testapp.com
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache

{
	"name": "smith"
}
```

**Comment by Huachao** [comment]
@ben-foster-cko can you succeed without using the Host header, I mean set the full url like `http://testapp.com/api`. If not, can you succeed with `cURL`?

**Comment by kuncevic** [comment]
Having this simple request:
```
POST http://localhost:3000 HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}
```
Getting error 
`Connection is being rejected. The service isn’t running on the server, or a firewall is blocking requests. Details: Error: connect ECONNREFUSED 8.20.189.133:8080.`

**Comment by Huachao** [comment]
@kuncevic is your web service properly enabled to listen at port 3000?

**Comment by kuncevic** [comment]
Whatewer url I trying got this error.

**Comment by Huachao** [comment]
@kuncevic can you show me you rest client related settings in vscode setting file?

**Comment by kuncevic** [comment]
Thanks for pointing that out. I had just wrong http settings. All good now.

**Comment by Huachao** [comment]
@kuncevic NP, glad to hear that.

**Comment by Huachao** [comment]
@ben-foster-cko if you no longer met this issue, I'd like to close this issue. You could reopen it as you wish.

**Comment by mnrafg** [comment]
I'm also getting this error in-case of a simple GET request which works well in browser.

`
Connection is being rejected. The service isn’t running on the server, or incorrect proxy settings in vscode, or a firewall is blocking requests. Details: Error: connect ECONNREFUSED 
`

**Comment by Huachao** [comment]
@mnrafg do you have proxy setting

**Comment by mnrafg** [comment]
No I don't have any proxy settings.

**Comment by Huachao** [comment]
@mnrafg do you meet this case for any request

**Comment by MickaelTH** [comment]
Using Windows 10 I had the same issue.

My local server (Lumen) was running on localhost:8080, I set the request as below:

POST http://localhost:8080
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

And got the error Connection is being rejected.

I suspect this is not directly related to vscode-restclient but the way how localhost is now handled in Windows 10.

To fix this I just ran my Lumen server as 127.0.0.1:8080 instead of localhost:8080, all worked after that.

Hope this help someone in the future.

**Comment by lanette46** [comment]
setting my host to 127.0.0.1 instead of localhost in my laravel server also works, thanks for saving me @MickaelTH

**Comment by ali80** [comment]
Sending request for 
`192.168.1.7/debug` and getting the same error,
Added `http://` and the error is fixed for me
`192.168.1.7/debug`

**Comment by batrashi** [comment]
I had the same problem, but I realized that I have been request the url as a 'string' and you should not.
No quotations and it works.

**Comment by RogerThattt** [comment]
Hi 
I am also getting the below error 

Connection is being rejected. The service isn’t running on the server, or incorrect proxy settings in vscode, or a firewall is blocking requests. Details: RequestError: connect ECONNREFUSED 127.0.0.1:443.

How do i check for rest client related settings in vscode setting file

**Comment by Ramos-Diego** [comment]
For people using Express.js, I resolved this issue by specifying the host with `app.listen()`:

```js
app.listen(8080, 'localhost')
```

It's strange because I had been using REST client for weeks without issues and without specifying `localhost`.

**Comment by racedaemon** [comment]
I'm getting the same behavior with a Lumen server running trough `php -S localhost:8000 -t public` on Windows 10.
Solved it by using `php -S 127.0.0.1:8000 -t public`.
Postman had not problems with it. I suspect the underlying node package that sends the request is the culprit because I tried another rest client extension and got errors there as well.

**Comment by dipakbari4** [comment]
I did the same mistake as @batrashi mentioned above. In the baseUrl, I passed the base URL as a string which cause this issue to me. Thanks 🙏

**Comment by KumkumSharma07** [comment]
Hi

I'm facing the below error

`The connection was rejected. Either the requested service isn’t running on the requested server/port, the proxy settings in vscode are misconfigured, or a firewall is blocking requests. Details: RequestError: connect ECONNREFUSED 127.0.0.1:3001.`

This is my rest client settings
{
    "http.proxySupport": "on",
    "http.proxyAuthorization": null,
    "editor.guides.bracketPairs": true,
    "editor.fontSize": 20,
    "workbench.colorTheme": "Abyss",
    "editor.mouseWheelZoom": true,
    "files.autoSave": "onFocusChange",
    "rest-client.disableAddingHrefLinkForLargeResponse": false,
    "rest-client.showResponseInDifferentTab": true
}

**Comment by brokenthorn** [comment]
If you look at your browser request headers, you might see that the host the browser uses is not IPv4 format, but IPv6: `[::1]`.

Effectively this is the same as `localhost`.

For me, a bare bones SvelteKit app with a single route added didn't work from REST Client like this:

```text
GET http://localhost:5173/test HTTP/1.1
```

but worked immediately when I switched to this:

```text
GET http://[::1]:5173/test HTTP/1.1
```

Digging deeper, I noticed that the hosts file on Win 11 now no longer specifies the IP address for localhost, with a mention that it is not handled by DNS.

```text
# localhost name resolution is handled within DNS itself.
# 102.54.94.97 rhino.acme.com # source server
# 38.25.63.10  x.acme.com     # x client host
# 127.0.0.1    localhost
# ::1          localhost
```

I would have uncommented the line with 127.0.0.1 and test again but I think this requires a reboot I'm fine with `[::1]`. Besides, I think this is a security measure anyway.

**Comment by MarByteBeep** [comment]
@brokenthorn thanks for this! Indeed the extension always fails on Windows 11 when using localhost. Your solution worked for me. Perhaps it would be great if author fixes this in the documentation.
