### ISSUE TITLE
Install instructions do not work

### ISSUE THREAD

**Issue by warpdesign** [Huachao/vscode-restclient#123]
- VSCode Version: 1.17.2
- OS: Windows 10

This doesn't work with latest stable VSCode:

> Press `F1` then type ext install rest-client

![vscodeinstall](https://user-images.githubusercontent.com/199648/31766338-91b1a160-b4c7-11e7-9282-3091936369f3.png)

**Comment by Huachao** [comment]
@warpdesign nice catch, I've updated the doc to
> Press `F1`, type `ext install` then search for `rest-client`.
