### ISSUE TITLE
history view

### ISSUE THREAD

**Issue by bitbonk** [Huachao/vscode-restclient#124]
First of all: Great extension! Thank you for this!

There is one thing missing that other tools like postman or fiddler have and the only reason that prevents me to fully switch to this extension:

A history view! Please let me see all the reqeust and responses that I have sent snd recieved previously.

Extra bonus: Make it persistent, so wehn I close and reopen VS code, the history is still there. Just like unsaved files are still there.

**Comment by Huachao** [comment]
@bitbonk my extension already supports the history function, https://github.com/Huachao/vscode-restclient#request-history. And the only difference is that I don't keep the response result of each request.

**Comment by Huachao** [comment]
@bitbonk any updates on this? I think I have supported this extension in very early versions, and can satisfy your requirements, could you please have a try? I'd like to close it for now, if you still have any concern, please feel free to reopen it.

**Comment by qrqhuang** [comment]
@Huachao Can also save responses in history?
Very useful when compare previously with current~

**Comment by Huachao** [comment]
@it's a nice feature, and compare with previous responses is a cool feature. I'd like to create a new issue to track about this.
