### ISSUE TITLE
Multi-part requests: user should be able to set content-type for each part in a multi-part request. 

### ISSUE THREAD

**Issue by ash-eng-spin** [Huachao/vscode-restclient#1245]
When setting up a multipart request, Thunder Client automatically selects the content-type of the file part. The auto-assigned content-type is not always the desired content-type of the API spec, therefore our request will always result in a 400 Bad Request, because the content-type is wrong.

**Please allow a way for the user to set the content type for a file part or text part of a multi-part request.**

**Form Fields:** user should be able to set because this could application/json, application/xml, text/plain, blank or many other things.
**Files:** user should be able to set because this could be blank, application/pdf, application/octet-stream, application/vnd.ms-excel, text/csv or many other things.

Example: Multipart Form Data: PDF file content-type automatically set. No manual way for user to set content-type for a file.
Why is this a problem: API spec for the pdf file wants "application/octet-stream" for the content-type. Thunder Client automatically sets the content-type to "application/pdf". No way to manually set the content-type. Results in 400 bad request because content-type does not match API spec and there is no way to change in Thunder Client.

![image](https://github.com/Huachao/vscode-restclient/assets/131696171/1d1d2202-8580-4538-980f-d0194850906b)

## Versions
ThunderClient v.2.17.8
Visual Studio Code 1.86.2
OS: Windows_NYx64 10.0.22621

## Steps to reproduce 1
1. Create POST request
2. Go to Body > Form > Form Fields
3. Enter field name and value <---User cannot change content-type of the file

## Steps to reproduce 2
1. Create POST request
2. Go to Body > Form 
3. Select Files check box 
4. Go to Files section
5. Enter field name and value <---User cannot change content-type of the file

For reference this is how it works in Postman:
![image](https://github.com/Huachao/vscode-restclient/assets/131696171/2c0baa79-506f-40f7-b00d-dc2c0fc07566)

**Comment by baojd42** [comment]
It seems like you are having problems with thunder client, however this is REST client. 
Here you go https://github.com/rangav/thunder-client-support
I am also thinking about switching to thunder client, as it is way more actively maintained.

**Comment by ash-eng-spin** [comment]
Thank for you pointing this out. I will close this but first could you answer a quick question. Does this Rest Client only work on VS Code web version?

**Comment by baojd42** [comment]
Not just web version. I am using this extension in a desktop version of VS.

**Comment by s-prakashs** [comment]
> Thank for you pointing this out. I will close this but first could you answer a quick question. Does this Rest Client only work on VS Code web version?

I think you have to close this ticket , right ?

**Comment by ash-eng-spin** [comment]
yes
