### ISSUE TITLE
Goto Symbols Support for Multiple Requests in a File

### ISSUE THREAD

**Issue by dprice** [Huachao/vscode-restclient#126]
I wrote a PowerShell script that converted my Postman backup file to separate .http files for each collection. When I load that folder into VSCode, now I can easily find my collections via ctrl+p as I made the collection the filename. I would love to be able to quick navigate to a request in a file with multiple requests by pressing ctrl+shift+o (Go to Symbol in file) to see a list of all requests in that file.

**Comment by eppyjerk** [comment]
That PowerShell script might be a nifty thing to share as a PR into this repo or a gist

**Comment by Huachao** [comment]
@dprice nice suggestion, and I will implement it ASAP

**Comment by dprice** [comment]
I'll clean up that PowerShell script and pass it along. It's not perfect right now as it doesn't quite align with the current setup of the VSCode REST Client. For example, I make extensive use of Postman's global variable system. I define all my routes as a two-part global variable. This ends up reducing duplication across requests and makes it easy to adjust a route if it changes as there is basically one area to edit. 

For example, each of my environments has a {{serverUrl}} similar to the {{host}} variable in your example:
Dev-> serverUrl: "http://dev.com"
Localhost -> serverUrl: "http://localhost"

In the global variables, I have all my endpoints configured like this:
adminRoute: "/someAdminRoute"
adminUrl: "{{serverUrl}}{{adminRoute}}"
...

In my request, I just use something like:
GET {{adminUrl}}/account/1

Where it really shines is when I'm debugging using the localhost environment. In the localhost environment variables, I also have the routes variables defined to the debugging ports:
Localhost-> adminRoute: ":9000"

So if a route changes, I just need to update the global variables and the localhost route (maybe). That's it. VSCode REST Client doesn't really allow for a separate global variables file/section other than embedded in the .http file which ends up duplicating a ton of settings. For now, I just dump the global variables into its own JSON file.

I'm also still deciding on if I like saving a collection and all sub folder requests into a single file or each collection gets saved as a "<collection name>.<folder name>.http". The latter provides fast searching for requests of a particular folder using ctrl+p. It might be easier for the former if you could find requests as symbols in a single .http file.

By the way - excellent extension!

**Comment by Huachao** [comment]
@dprice really nice suggestion, I'd like to implement the shared environment feature that environments defined in it can be shared across all the environments. Thank you @dprice

**Comment by Huachao** [comment]
@dprice you can try the latest version 0.16.0 to verify. Thanks for your great suggestion

**Comment by dprice** [comment]
Awesome! I'll check it out when I'm in the office.

**Comment by dprice** [comment]
I just tried the update and I now see the multiple requests - nice work!
