### ISSUE TITLE
Include other .http file

### ISSUE THREAD

**Issue by immerhart** [Huachao/vscode-restclient#1281]
Thanks for this nice addon, is it possible to include other .http files into a .http file, I would like to extract a couple of requests with sensible data. Guess it would be also enough if the include allows you to specify variables. I don't want to use env vars for that...

**Comment by Huachao** [comment]
Duplicate of #182

**Comment by MominRaza** [comment]
Related update in #1422.

This PR introduces `@set` for response-to-shared-runtime-variable assignment, which helps with token/session propagation across files even though this thread also discusses external include approaches.
