### ISSUE TITLE
"click the Send Request link above the request" doesn't work (anymore)

### ISSUE THREAD

**Issue by HKochniss** [Huachao/vscode-restclient#129]
- VSCode Version: 1.17.2
- OS Version: Win10
- REST Client Version: 0.15.3

Steps to Reproduce:

1. Install the extension
2. paste from docs into new document (or save as .rest/.http and activate HTTP mode, doesn't matter)

POST https://example.com/comments HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

3. a link to click above the HTTP POST line doesn't occur (even if line is of course not first but second/third), it seems the extension can't generate these clickable links anymore

it worked a few days ago, is the nice new VS code versionb with the orange logo breaking it?

**Comment by HKochniss** [comment]
also, I'm not sure if it first worked at home or at work, in one of those I had a deinstall extension hickup with a VS code update running in between, so I supposed it was corrupted install. But after reinstalling VS code and extension it still remains, and the installer race was onbly on one of these systems

**Comment by HKochniss** [comment]
btw, the workspace is completely empty, i try to just a have a folder with a .rest file (and later on a .vscode folder with workspace settings file) as aa Postman collection replacement.

**Comment by HKochniss** [comment]
nevermind: I had the  "editor.codeLens" feature set to false in my work environment. I still dunno what it is at home, I'll check therte, but it would be good to add a hint that for the clickable links this (default-on, I know) feature has to be enabled.

**Comment by Huachao** [comment]
@HKochniss in my test, even I set this setting to false, the request can still be sent. Can you try the keyboard shortcut (ctrl+alt+r) to send the request to test if it works? Thanks in advance

**Comment by HKochniss** [comment]
Sure, shortcut always worked.

If you set the "editor.codeLens" in the respective workspace settings to false and restart VS Code, it wouldn't work. 
But maybe there's another issue. 

I don't know if that's intended, but you see the clikable button only on the _first_ request in a group that started with a ###

Meaning, subsequent request in that segment don't have the button, don't know if that's intended, but it's unexpected. That my be the reason, without some ### at the start of the file the first request doesn't have the clickable button.
But if that's meant as "a group of request that get executed by this button" it won't work, as the button still just executes the first request

![image](https://user-images.githubusercontent.com/1243055/32044172-12e5743a-ba3d-11e7-9932-771378f81403.png)

Probably a seperate issue, just wanted to mention that.

Thanks for all the work, will show this awesome extension today as an alternative to Postman in a dev meeting of ours.. (and created a converter script)

**Comment by HKochniss** [comment]
To be clear:
this issue is about the clickable button only, the shortcut always worked. It's probably more the "CodeLense has to be activated" that was surprising to me, as I turned it off beforehand.

**Comment by Huachao** [comment]
Use three consecutive `#` as a delimiter, we use `###` to start a new request block

**Comment by HKochniss** [comment]
I know. It's just that if you don't, then only the first request gets the button. But this button doesn't then execute alle the requests below, but just the first one. Either way would be finde, but the current behavior seems inconsistent (there should be a button above every request, or if not, for good reason).

**Comment by Huachao** [comment]
@HKochniss you didn't miss anything 😢  It's my current design that `###` is a request block separator that lines inside it will be identified and parsed as a single request.

**Comment by WellspringCS** [comment]
FWIW, @HKochniss  found the fix for my situation, which was to enable codeLens. Thanks, @Huachao for this awesome tool, and thanks @HKochniss for sharing the solution to that particular problem.
