### ISSUE TITLE
Making GraphQL Request: Broken?

### ISSUE THREAD

**Issue by seimic** [Huachao/vscode-restclient#1292]
Hi,

not sure why but all GraphQL queries which I used before are not converted to JSON anymore before sending a request.
I mean queries in format like this.
```
POST http://127.0.0.1:8080/gql
Content-Type: application/json
X-Request-Type: GraphQL

query ($name: String!) {
   ...
}
```
The error comes from backend (nestjs/graphql ) and indicates the request body has been sent as is without
any preprocessing at all.
```
{
  "message": "Unexpected token 'q', \"query ($na\"... is not valid JSON",
  "error": "Bad Request",
  "statusCode": 400
}
```

Tried all cases X-REQUEST-TYPE: GraphQL, x-request-type: GraphQL..., uninstalled the plugin and installed again.
Nothing works anymore. Any idea what could be wrong? I don't see any changes to REST Client since 2022, just curious
if someone else has same issues and maybe a solution to it.

Environment: Codium v1.92, REST Client v0.26.0.

Kind regards,
Michael

**Comment by tphani** [comment]
I faced this issue when updated to latest vscodium (v1.93.1). I rolled back to v1.92.2 (removed all existing profile data and installed) then it is working fine with extension version: 0.25.1. (I am on Mac M1)

**Comment by adn77** [comment]
I believe the issue is this line:
https://github.com/Huachao/vscode-restclient/blob/6649589e4d3f97d9c0d68a4f7ffe03fa2919c4df/src/utils/httpRequestParser.ts#L85

if you send the *GraphQL* in lower case it works!

````
X-Request-Type: graphql
````

**Comment by seimic** [comment]
Ohh.. really? Thanks. Seems that code always tells the truth ;)

This would maybe make more sense.
```const isGraphQlRequest = getHeader(headers, 'X-Request-Type')?.toLowerCase() === 'graphql';```
![image](https://github.com/user-attachments/assets/f8668de6-63fa-4913-a005-fd64199214d1)
[Source of the image](https://geek-and-poke.com/)

**Comment by adn77** [comment]
> This would maybe make more sense.
> `const isGraphQlRequest = getHeader(headers, 'X-Request-Type')?.toLowerCase() === 'graphql';`

getHeader needs to be casted as String() first, as I just learned myself 🙂
`const isGraphQlRequest = String(getHeader(headers, 'X-Request-Type')).toLowerCase() === 'graphql';`
