### ISSUE TITLE
Add loading icon

### ISSUE THREAD

**Issue by StephD** [Huachao/vscode-restclient#13]
- VSCode Version: 1.3
- OS Version: Win 7

When A request take some time (10s as exemple), we don't really know if the request has been correctly sended and if it just waiting for the answer. 
I type ctrl+alt+r 5-6 time because I thought that the request wasn't send.

May be display a loading information (like an update extensions bar on top of VSC) and hide it when it's done.

I just saw that there is a small cloud into the bottom bar and the display the duration. 
I don't know if it's very explicit for a loading time. May be add this information into the doc?

**Comment by Huachao** [comment]
@StephD, currently, when issuing a new request, as you said, I will display the cloud icon in the status bar at the bottom, I think I will first add it into document, and later I will think if it's easy to implement as you suggested

**Comment by Huachao** [comment]
@StephD I'd like to implement this request like following, that set the status bar with a spinner when waiting for the response
![status](https://cloud.githubusercontent.com/assets/2796177/17526228/f52a608c-5e98-11e6-910d-9e15f9300655.gif)
