### ISSUE TITLE
Need an example for rest-client.excludeHostsForProxy

### ISSUE THREAD

**Issue by necraidan** [Huachao/vscode-restclient#130]
Hello guys, 
I would like an example of a configuration for **rest-client.excludeHostsForProxy**

Thanks.

**Comment by Huachao** [comment]
@necraidan you can specify the host (w/o port) like following:
```json
"rest-client.excludeHostsForProxy": [
   "localhost",
   "example.com:8080"
]
```

**Comment by papanito** [comment]
Are wildcards supported? Or do I have to list any particular host?

**Comment by Huachao** [comment]
@papanito wildcards are not supported now, if you have interests, you can make a PR, that will be welcomed

**Comment by papanito** [comment]
Thanks if I find some time I will definitely do so
