### ISSUE TITLE
'Send Request' link only appears when file is saves

### ISSUE THREAD

**Issue by alexgoldstone** [Huachao/vscode-restclient#131]
- VSCode Version: 1.17.2
- OS Version: OS X 10.12.6
- REST Client Version: 0.15.3

The `Send Request` links only appear when the file has .http or .rest extension.

Perhaps this is intended behaviour but it was not clear from the instructions which mention support for these extensions but do not state that functionality will be reduced when files are not saved with one of these extensions.

Suggest adding this information to the instructions.

**Comment by Huachao** [comment]
@alexgoldstone in fact the `Send Request` link will be visible when your file is in `HTTP` language mode. And you can make your file with `HTTP` mode in following three ways:

1. File with extension `.http` or `.rest`
2. First line of file follows standard request line in [RFC 2616](http://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html), with `Method SP Request-URI SP HTTP-Version` format, like `GET http://api.github.com/users/Huachao`
3. If you want to enable language association in other cases, just change the language mode in the right bottom of `Visual Studio Code` to `HTTP`.
