### ISSUE TITLE
Apple ⌘+A doesn't work on MacOS

### ISSUE THREAD

**Issue by defectus** [Huachao/vscode-restclient#132]
- VSCode Version: 1.17.2 
- OS Version: MacOS 10.13 (17A405)
- REST Client Version: 0.16.0 (2017/10/30)

Steps to Reproduce:

1. Open an HTTP file and press ⌘+⎇+R to fire it.
2. Focus response window and press ⌘+A or from the menu `Selection>Select All`
3. Nothing is selected.

Expected behaviour:
The complete response is selected and can be copied.

**Comment by Huachao** [comment]
@defectus this is a known Microsoft/vscode#8794 in __vscode__. Since our previewed response panel is actually a HTML page, it's not a normal text doc in __vscode__.

**Comment by defectus** [comment]
Can we open the output in a regular editor then? As a workaround. Or at least give the option to open results in an editor rather than a preview pane.

**Comment by Huachao** [comment]
@defectus certainly, we already have a setting `rest-client.previewResponseInUntitledDocument`, just set this value to `true` will be ok. Wish this helps

**Comment by defectus** [comment]
Great! Thanks for that and sorry for wasting your time.

**Comment by Huachao** [comment]
@defectus since vscode version 1.26.0, the `⌘+A` already worked for the response in webview.
