### ISSUE TITLE
VS Code Multi-root Workspaces and REST Client

### ISSUE THREAD

**Issue by seanmcbreen** [Huachao/vscode-restclient#133]
Hi,

I'm from the VS Code team I also dropped you an email, I'm reaching out with some additional resources for adopting multi-root workspaces.

But first let me say thank you for working on and maintaining [REST Client](https://marketplace.visualstudio.com/items?itemName=humao.rest-client), we really appreciate the work you have done to make VS Code better.  We recently twetted about this extension and the reception has been great - it's a nice use of the tool!

The purpose of this issue is that we are very close to releasing a significant new feature for VS Code - Multi-root Workspaces - which is the [most requested](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request+sort%3Areactions-%2B1-desc) missing feature. If you have not heard of multi-root workspaces we have [described this in several of our recent updates](https://code.visualstudio.com/updates/v1_17#_preview-multi-root-workspaces).  Today it's only enabled in our insiders release but **our intent is to enable it for all users** in our [next update](https://github.com/Microsoft/vscode/issues/35875), targeted for release in the first week of November.

This is a pretty significant change and over the last four months we have updated pretty much all of VS Code to be Multi-root aware as well as updated all of our own extensions.  In the process of doing this we have created a set of [guidelines for Extension Authors](https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs) to follow to ensure their extension can fully leverage the awesomeness that is Multi-root workspaces.

**Our Request:**

There are a few things to review in your extension to ensure it can fully capitalize on Multi-root  Workspaces....

* Check you do not make use of the (now deprecated) `workspace.rootPath` property, there is a proposed migration path and sample for this case.
* Review any settings you contribute or change, specifically you need to review whether some of the settings can be applied on a resource (= file location) level instead of being global (= workspace level).

Once you are ready we would appreciate it if you can add a new tag to your extension.  Specifically - add multi-root ready to your `package.json` i.e. `"keywords": ["multi-root ready"]`. If you upgrade to `VSCE 1.32.0` this can be added to any existing keywords and will not be counted against the maximum of 5 allowed keywords.

**How Can We Help/Resources:**

We realize we are asking for your help here - our goal is to make sure that your extensions works well with multi-root and continues to be loved by the community.  [The guide above outlines the changes that are required](https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs) and we have a [samples](https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs#samples) as well.

But we are sure you will have questions and we thought one way we could look to help is by getting a number of the team members (myself included) to be ready to respond to questions on a Slack Channel that we will dedicate to this issue.  To join that channel simply [follow this link](https://vscode-dev-community.slack.com/join/shared_invite/enQtMjIxOTgxNDE3NzM0LWU5M2ZiZDU1YjBlMzdlZjA2YjBjYzRhYTM5NTgzMTAxMjdiNWU0ZmQzYWI3MWU5N2Q1YjBiYmQ4MzY0NDE1MzY).

Again thank you for being part of the VS Code community - we appreciate everything you have done.  With the release of Multi-root Workspaces we will be shipping our most requested feature, together we can really help this feature light up for users.

Happy Coding!
Sean McBreen

// cc @bpasero @octref

**Comment by Huachao** [comment]
@seanmcbreen done already, and the new version with _Multi-root Workspace Support_ is already published

**Comment by seanmcbreen** [comment]
Amazing thank you - one additional ask could we get you to add a new keyword.. with your next publish?

Specifically - add multi-root ready to your package.json i.e. "keywords": ["multi-root ready"]. If you upgrade to VSCE 1.32.0 this can be added to any existing keywords and will not be counted against the maximum of 5 allowed keywords.

**Comment by Huachao** [comment]
@seanmcbreen ok, done.
