### ISSUE TITLE
Support PATCH method

### ISSUE THREAD

**Issue by mrchief** [Huachao/vscode-restclient#138]
- VSCode Version: 1.18.0
- OS Version: Windows 7x64
- REST Client Version: 0.16.0

HTTP PATCH is new method [rfc5789](https://tools.ietf.org/html/rfc5789) very similar to PUT (as far as implementation goes from this extension's standpoint). Furthermore, the underlying `request` library already supports it.

It'd be nice if the extension supported this. We understand the standard is not baked yet and as such, bugs/caveats are acceptable.

Steps to Reproduce:

1. Create a `api.http` file.
2. Add `PATCH https://path/to/api/ HTTP/1.1`
3. Add required data

`Send Request` link doesn't activate.

**Comment by Huachao** [comment]
@mrchief can you show me the actual request, or your complete file content, since I can't repro it

**Comment by mrchief** [comment]
@Huachao here it is:

![image](https://user-images.githubusercontent.com/781818/32790044-498a8668-c92b-11e7-8a28-d92924788c49.png)

You can see GET has the code lens but PATCH doesn't.

**Comment by Huachao** [comment]
@mrchief, you need to add the request delimiter(###) between requests

**Comment by mrchief** [comment]
:man_facepalming: 

That fixes it, thanks!
