### ISSUE TITLE
In single line mode, continuous whitespaces were collapsed into one

### ISSUE THREAD

**Issue by susan51531** [Huachao/vscode-restclient#143]
- VSCode Version: 1.18.1
- OS Version: macOS High Sierra 10.13.1
- REST Client Version: 0.16.1

Steps to Reproduce:

1. make a single line GET request with query string value contain multiple continuous whitespaces 
2. log the request URL at server side

You'll find the continuous whitespaces were collapsed into %20
Like so:
![image](https://user-images.githubusercontent.com/2595468/33818767-bdc97032-de81-11e7-9443-3ad3df77542f.png)

In multiple query string mode, the result is right.
![image](https://user-images.githubusercontent.com/2595468/33818807-f67d06dc-de81-11e7-9832-11333a1b5604.png)

**Comment by Huachao** [comment]
@susan51531 this fix will also be fixed in next release

**Comment by Huachao** [comment]
@susan51531 you can try the laster version 0.16.2 to verify 😄
