### ISSUE TITLE
In multiple lines mode, query parameter without '=' and value is ignored

### ISSUE THREAD

**Issue by susan51531** [Huachao/vscode-restclient#144]
- VSCode Version: 1.18.1
- OS Version: macOS High Sierra 10.13.1
- REST Client Version: 0.16.1

Steps to Reproduce:

1. spread query parameters into multiple lines
2. make the last query parameter only include key, without specifying '=' and value
3. log the request query at server side

Result: query parameter without '=' and value is ignored
![image](https://user-images.githubusercontent.com/2595468/33819059-53c9a2ae-de83-11e7-90bc-c89eb8970a72.png)

**Comment by Huachao** [comment]
@susan51531 nice catch, 👍 . I will publish this fix in next release.

**Comment by Huachao** [comment]
@susan51531 you can try the latest version 0.16.2 to verify
