### ISSUE TITLE
希望能够直接在editable的buffer中打开response

### ISSUE THREAD

**Issue by dragonly** [Huachao/vscode-restclient#145]
- VSCode Version: Any
- OS Version: Any
- REST Client Version: Any

Steps to Reproduce: None

希望能够直接在editable的buffer中打开response, 否则JSON格式的response不能利用编辑器的折叠功能.

**Comment by Huachao** [comment]
@dragonly you can turn on the setting `rest-client.previewResponseInUntitledDocument`, and sets it to true which will open an untitled document to render the response.
