### ISSUE TITLE
Visual Preview in response output

### ISSUE THREAD

**Issue by shahidmau** [Huachao/vscode-restclient#146]
Hi, is it possible for you to show the html (visual) preview of the output result? Sometime apis return html content instead of proper json response if there is the error in input or for 404 requests. Right now its very difficult to read the html content in response output and to figure out about the actual issue.

Insomnia and postman have already this useful feature.

![screen shot 2017-12-19 at 12 05 00 pm](https://user-images.githubusercontent.com/195240/34143879-f415c1d4-e4b4-11e7-89d0-9e71654131b9.png)

Thanks

**Comment by Huachao** [comment]
@shahidmau what does _Visual Preview_ mean for 'HTML' response, do you mean it renders the HTML page instead of displaying the HTML source code?

**Comment by shahidmau** [comment]
---- what does Visual Preview mean for 'HTML' response, do you mean it renders the HTML page instead of displaying the HTML source code?

yes

**Comment by oji** [comment]
+1 I'd love this feature! Also it would be useful when the content type is an image, to see the image instead of the binary content.

**Comment by Huachao** [comment]
@oji for some common image types, the response will be rendered as image directly. Can you show me your response Content-Type when not working

**Comment by oji** [comment]
Hi @Huachao, I'm getting this with both `image/gif` and `image/png`. Here are a couple of screenshots:

![screen shot 2018-01-26 at 10 33 02](https://user-images.githubusercontent.com/1176268/35442025-78b42d76-0284-11e8-8de9-4409e0617faa.png)
![screen shot 2018-01-26 at 10 33 19](https://user-images.githubusercontent.com/1176268/35442026-78ecf688-0284-11e8-9f7b-8ebda11e0038.png)

Maybe I'm missing a setting...

**Comment by Huachao** [comment]
@oji, you need to set the settling 'rest-client.previewResponseInUntitledDocument' to __true__

**Comment by oji** [comment]
@Huachao thanks a lot for your quick responses! Your extension rocks!

**Comment by ankitbko** [comment]
@Huachao any plans for this?

**Comment by isapir** [comment]
This enhancement would be great.  Has it been implemented yet?  If not, any plans to do so?

**Comment by Huachao** [comment]
@isapir you can expect this in the next release

**Comment by isapir** [comment]
Thanks @Huachao - this is an amazing project!  By the way, the LinkedIn URL in your profile page is broken - it redirects to a custom 404 page.

![image](https://user-images.githubusercontent.com/885907/217605849-13a7c779-1248-46ad-a4aa-e5c43b5165e5.png)

![image](https://user-images.githubusercontent.com/885907/217605939-f6357274-57af-48d2-b094-b3f5d63f95ed.png)

**Comment by isapir** [comment]
@Huachao I have version 0.25.1 installed but I don't see how to open the response in HTML Preview.  I see `Enable Preview Editors` in the menu with a checkmark next to it, but I have an HTML content without the HTML rendering.  Any thoughts?

The changelog seems outdated and does not match the timeline: 
![image](https://github.com/Huachao/vscode-restclient/assets/885907/bb323fd0-2571-4ddc-9d10-e142294d0dab)

**Comment by sebastianMacheight** [comment]
I also see the `Enable Preview Editors` option with a check next to it, but I don't understand what it does.
Is this feature working yet?

**Comment by isapir** [comment]
The version history in the VSCode marketplace shows an as latest? 

![image](https://github.com/Huachao/vscode-restclient/assets/885907/a05bcf70-d8d5-45b6-a96f-45a8d4b0b257)

**Comment by monaye** [comment]
did anyone find out how to visually preview the text/html response?
