### ISSUE TITLE
[Feature request] Disable response formatting

### ISSUE THREAD

**Issue by svenax** [Huachao/vscode-restclient#147]
Formatting large responses, at least for JSON, is very slow. It would be nice if either it was possible to disable formatting manually, or if it was automatically disabled for responses above a certain size.

**Comment by Huachao** [comment]
@svenax in fact the slow performance is related to highlight and find url in response. Tt's really a nice suggestion to disable such kind of thing automatically when response is larger than some predefined threshold.

**Comment by Huachao** [comment]
@svenax this feature will be published in next release, thanks again for your great suggestion.

**Comment by Huachao** [comment]
@svenax you can try the latest version 0.17.0 to verify, by default, the response size larger than 5MB will disable the formatting, and you can refer to the following three settings for more control:
* `rest-client.disableHighlightResonseBodyForLargeResponse` (Default: __True__)
* `rest-client.disableAddingHrefLinkForLargeResponse` (Default is __True__)
*  `rest-client.largeResponseBodySizeLimitInMB` (Default is __5__)
