### ISSUE TITLE
Collapse of requests (body)

### ISSUE THREAD

**Issue by lostfields** [Huachao/vscode-restclient#155]
Not a big issue, but that about to support some kind of collapsing? scrolling a http-file will make your eye hurt if you have to scroll over huge post-bodies just to find the correct request.

**Comment by Huachao** [comment]
@lostfields good suggestion, I think this issue has some relationship with #135 , if we can format the request body, and it seems we can benefit the folding feature(based on indention) of vscode. BTW, we already support folding request in `.http` files. The only difference is that it folds the whole request.

**Comment by lostfields** [comment]
It didn't work for me because I named each request block after the tripple hashes (like  "### <request description>"). After removing the comments it works as described.

Thanks. Closing this one.
