### ISSUE TITLE
[Feature Request] Add collapsible functionality for json and xml response

### ISSUE THREAD

**Issue by hardija** [Huachao/vscode-restclient#157]
- VSCode Version: Version 1.19.2 (1.19.2)
- OS Version: macOS Sierra 10.12.6
- REST Client Version: 0.16.2

I saw feature request for folding requests, but it would also be nice to fold the json response.

**Comment by ffes** [comment]
Folding multiple requests separated with three hashes  in the `.http` source file would be great as well.

**Comment by Huachao** [comment]
@ffes I thought it was already supported in the extension, can you have a try?

**Comment by ffes** [comment]
It works a bit, but there is some room for improvement...

Look at the screenshot below and notice that the last block only can be collapsed at the JSON block and not at the `POST`.

![vscode-rest-extension-folding](https://user-images.githubusercontent.com/3225656/35793864-9e687f8c-0a53-11e8-9e3b-f83ebde584e2.png)

And notice that in the screenshot below only at the JSON block a `[-]` is shown and not at the `GET` or `POST `line

![example](https://user-images.githubusercontent.com/3225656/35794233-3b0aa774-0a55-11e8-9222-135f412584a6.png)

**Comment by Huachao** [comment]
@ffes this currently is a known issue in my extension, that append a new line of `###` at the end of the file.

**Comment by 3amSoftware** [comment]
This thread is about the response. Please start another thread to discuss the request. Thank you

**Comment by Huachao** [comment]
@3amSoftware nice suggestion, I have created #163 to follow request body folding

**Comment by Huachao** [comment]
@hardija @ffes @Naramsim @StephD @3amSoftware @suramma I have implemented the indent based response folding (also work for JSON and XML since my extension will pretty the JSON and xml response body). And I will publish this feature in next release.

![image](https://user-images.githubusercontent.com/2796177/36581468-16493e26-18a8-11e8-9a51-8d439ef08cd6.png)

**Comment by Naramsim** [comment]
Can't wait to try it! Thanks for the efforts!

**Comment by Huachao** [comment]
@hardija @ffes @Naramsim @StephD @3amSoftware @suramma you can upgrade to 0.18.0 to try this. Thanks!
