### ISSUE TITLE
Uploading binary file as body not working

### ISSUE THREAD

**Issue by oji** [Huachao/vscode-restclient#158]
- VSCode Version: 1.19.2
- OS Version: OSX Sierra
- REST Client Version: 0.16.2

Steps to Reproduce:

I'm trying to upload a .png file through a PUT request, but the server is rejecting the image. I tried with:

```
PUT {{uploadUrl}}
Content-Type: image/*

< ./test1.png
```

I also tried with this on the .rest file: 

```
curl -X PUT -H "Content-Type: image/*" --data-binary "@./test1.png" {{uploadUrl}}
```

However, if I run the above curl command on a terminal, it works. I don't know what is different, as I can't see what is the actual request that the extension is sending. 

Is there a way to see the actual request sent, like a `curl -v`?

Help woult be much appreciated.

**Comment by Huachao** [comment]
What's the rejection details?

**Comment by Huachao** [comment]
@oji Can you try to add setting `"rest-client.useTrunkedTransferEncodingForSendingFileContent": false` in setting file, and then try again

**Comment by oji** [comment]
Hi @Huachao changing the setting you mention to false did the trick. It was complaining about the transfer encoding header!

```html
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>NotImplemented</Code>
  <Message>A header you provided implies functionality that is not implemented</Message>
  <Header>Transfer-Encoding</Header>
  <RequestId>xxxx</RequestId>
 <HostId>xxxxxxx</HostId>
</Error>
```

Thanks a lot!

**Comment by Huachao** [comment]
And I also refactor my code, and in next release, you don't need to change this setting any more

**Comment by Huachao** [comment]
@oji you could try the latest version 0.17.0 which don't require you to set the setting any more

**Comment by oji** [comment]
Hi @Huachao, it worked fine with 0.17.0 without the setting. Thanks for the quick fix!
