### ISSUE TITLE
Can't put environment variable as first item

### ISSUE THREAD

**Issue by guycnicholas** [Huachao/vscode-restclient#159]
- VSCode Version: 1.19.2
- OS Version: Mac 10.12.6
- REST Client Version: 0.16.2

Steps to Reproduce:

1. enter url like GET {{protocol}}://{{host}}/{{app}}ping
2. with env vars like this
```
 	"rest-client.environmentVariables": {
		"$shared": {
			"protocol": "https",
			"host": "foobar.com",
			"app": "trk/"
		},
		"local": {
			"protocol": "http",
			"app": "",
			"host": "localhost"
		},
```

![image](https://user-images.githubusercontent.com/5494702/35372744-5e834ca0-0150-11e8-8eab-6500925e799f.png)

**Comment by Huachao** [comment]
@guycnicholas what's your selected environment?

**Comment by guycnicholas** [comment]
@Huachao I apologize for the noise. I tried to setup a simple test app on another machine and couldn't repro the issue. When I came back to my main machine to try again, I couldn't get it to fail.  I am closing this.
