### ISSUE TITLE
WARN: command 'rest-client.request' not found

### ISSUE THREAD

**Issue by v1rusw0rm** [Huachao/vscode-restclient#165]
- VSCode Version: 1.20.0
- OS Version: Windows 10 Pro 1709
- REST Client Version: 0.17.0

Steps to Reproduce:
Run (Ctrl+Alt+R) the following (or any other for that matter)

`GET https://example.com/ HTTP/1.1`

Also there is no `Send request` above the request. I downgraded REST Client to version 0.16.0 and it works.

**Comment by Huachao** [comment]
@v1rusw0rm can you open the developer console in `Help` tab, and check if any error occurs.

**Comment by v1rusw0rm** [comment]
After the update from 0.16.0 to 0.17.0 the problem doesn't appear 😕 When the problem was here I tried to uninstall the extensions, restart VSCode, install extension again, restart VSCode, and it doesn't help. But after upgrading from 0.16.0 to 0.17.0 I can't reproduce the bug. I think, the issue can be closed for now. If the problem appear again, I'll provide details from developer console.
