### ISSUE TITLE
Preserve focus of the http editor

### ISSUE THREAD

**Issue by lostfields** [Huachao/vscode-restclient#167]
Pretty please preserve focus of the http/rest editor. Whenever I open a new file it opens at the right side, that is annoying.

https://code.visualstudio.com/docs/extensionAPI/vscode-api#showTextDocument

showTextDocument(document: TextDocument, column?: ViewColumn, preserveFocus?: boolean): Thenable<TextEditor>

Set preserveFocus to true.

**Comment by Huachao** [comment]
@lostfields do you want to keep the request editor focus after the response view is shown. The reason for switching to the response view is that normally users want to inspect the response directly, scroll the response page up and down. Maybe I can provide a setting to control this, do you think it's OK for you?

**Comment by lostfields** [comment]
yes, that would be nice - and then it's probably possible to override in workspace-settings as well?

**Comment by Huachao** [comment]
yes, either user setting or workspace setting is ok

**Comment by Huachao** [comment]
@lostfields since response preview is in fact a webview page, and vscode doesn't allow the `preserveFocus` option currently.

**Comment by Huachao** [comment]
@lostfields VSCode will support this option in webview in May Release, so I will complete this as soon as it is released.

**Comment by Huachao** [comment]
@lostfields @jon301 @arturock I have added a setting named `previewResponsePanelTakeFocus`, by default its value is `true`. So you can set it to `false` to preserve http editor focus.

**Comment by arturock** [comment]
Great news @Huachao! Thank you so much!

**Comment by Huachao** [comment]
@lostfields @jon301 @arturock now you can use the new setting `rest-client.previewResponsePanelTakeFocus` to preserve focus of the http editor, by default it will be `true`, you can set it to `false` to achieve it.

**Comment by arturock** [comment]
Working perfectly! Thanks!
