### ISSUE TITLE
WARN: command 'rest-client.request' not found

### ISSUE THREAD

**Issue by timurmelnikov** [Huachao/vscode-restclient#168]
- VSCode Version: 1.20.1
- OS Version: Windows 10
- REST Client Version: 0.17.0

Steps to Reproduce:

1. Run (Ctrl+Alt+R)

GET https://test.com/ HTTP/1.1

**Comment by Huachao** [comment]
@timurmelnikov can you open the `Extension` panel to check if the extension is correctly installed?

**Comment by timurmelnikov** [comment]
Yes, it is installed correctly. I reinstalled it several times.

**Comment by Huachao** [comment]
@timurmelnikov can you open the developer console in Help tab, and check if any error occurs.

**Comment by timurmelnikov** [comment]
@Huachao http://prntscr.com/iku2hv

**Comment by Huachao** [comment]
Can you try to uninstall the extension, and restart vscode, after that download the package to local from [here](https://github.com/Huachao/vscode-restclient/releases/download/v0.17.0/rest-client-0.17.0.vsix ). And install it from local in the Extension panel, it has an option to install vsix package from local.

**Comment by timurmelnikov** [comment]
Installed from file rest-client-0.17.0.vsix. Working!
http://prntscr.com/ikw72r

**Comment by timurmelnikov** [comment]
After installation from the repository - it stops working.

**Comment by timurmelnikov** [comment]
Yes, it works! I can not understand what's the matter ...
But it only works after the installation from the file.
Before reinstalling several times - it did not help.
Now, the plugin works fine. Thanks for the help!

**Comment by Huachao** [comment]
NP, thanks for reporting this.

**Comment by elkhan** [comment]
Hi, I am facing the same issue. Here is the error.
<img width="787" alt="screenshot 2018-03-09 11 41 57" src="https://user-images.githubusercontent.com/3384773/37198371-25bfbdd4-238f-11e8-9dad-1e7d30656b67.png">

**Comment by elkhan** [comment]
I can confirm that installing from VSIX works.

**Comment by Huachao** [comment]
@elkhan OK, nice catch. I will keep eyes on this when publishing a new release, and check if this module exists in node_modules folder.

**Comment by elkhan** [comment]
@Huachao Thank you for this awesome extension.
I used it for the first time but it was there for a while I just didn't use it. I mean it could had been upgrading itself in the background.

**Comment by TimThrelkeld** [comment]
I'm getting the same error as well for version 0.18.1:
[Extension Host] Activating extension `humao.rest-client` failed:  Cannot find module 'yargs'

Using your VSIX package works.

My version info:
Version 1.22.1
Commit 950b8b0d37a9b7061b6f0d291837ccc4015f5ecd
Date 2018-04-06T02:26:57.615Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

[rest client fail callstack.txt](https://github.com/Huachao/vscode-restclient/files/1891993/rest.client.fail.callstack.txt)

**Comment by Huachao** [comment]
@TimThrelkeld thanks, could you please help to check if yargs in the `node_modules` folder `~/.vscode/extensions/humao.rest-client-0.18.1` with command `npm ls`.

**Comment by Huachao** [comment]
@TimThrelkeld this also maybe a common issue in vscode for now, see Microsoft/vscode#43813, maybe besides using my vsix package in GitHub, you could use the command `Developer: Reinstall Extension`

**Comment by circussocial** [comment]
Its not working for me also.

**Comment by Huachao** [comment]
@circussocial have you ever tried the command `Developer: Reinstall Extension` and select my extension?

**Comment by howar31** [comment]
Got error while pressing Ctrl Alt C (Generate Code Snippet)

> command 'rest-client.generate-codesnippet' not found

![image](https://user-images.githubusercontent.com/880459/46845614-be28a980-ce0e-11e8-9d36-787c75c0cc58.png)

Tried reinstall extension with developer command and manually.

**Comment by Huachao** [comment]
@howar31 could you please open the developer console in Help tab, and check if any error occurs?

**Comment by howar31** [comment]
Sorry for bothering.  I've found the issue that I accidentally put the cursor on the comment line while pressing the shortcut.

![image](https://user-images.githubusercontent.com/880459/46846361-1614df80-ce12-11e8-8ebb-bf09abf04824.png)

It's fine after moving the cursor to the correct request.

Thank you

**Comment by Huachao** [comment]
@howar31 Glad to hear that.

**Comment by snevula123456** [comment]
Hi @Huachao 
I am getting error while sending the request. Attached screenshot for ref.
![image](https://user-images.githubusercontent.com/25643849/103501166-71a86900-4e73-11eb-9160-cd00dd5a3e1d.png)

**Comment by Emanuel3003** [comment]
on UBUNTU i resolved using this steps:
- open treminal
- sudo mkdir .rest-client
- sudo chmod 777 .rest-client
and now in VS Code RestClient Works
