### ISSUE TITLE
Can't set "Host"

### ISSUE THREAD

**Issue by davidwudv** [Huachao/vscode-restclient#17]
- VSCode `Version: 1.3.1`
- OS Version: `Windows 10`
- REST Client Version: `0.6.1`

Steps to Reproduce:

![qq 20160725153153](https://cloud.githubusercontent.com/assets/4150570/17093631/f3970c3e-527c-11e6-963b-53e89182e112.png)

**Comment by Huachao** [comment]
@davidwudv in my opinion, if the host is test, the url should be `GET / HTTP/1.1`, the HOST head should be `test:8080`

**Comment by davidwudv** [comment]
But...in some cases, Host needs to be set to a different value...
Does this mean that the API design is unreasonable？

**Comment by Huachao** [comment]
@davidwudv I think this API design is a little unreasonable, as [HOST 14.23 section](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html) said, The Host field value MUST represent the naming authority of the origin server or gateway given by the original URL

**Comment by davidwudv** [comment]
@Huachao thanks
