### ISSUE TITLE
Extract data from response content into variables

### ISSUE THREAD

**Issue by colutti** [Huachao/vscode-restclient#170]
It would be nice if the extension could support extracting information from response content into variables that could be used in subsequents requests.

**Comment by Huachao** [comment]
@colutti this is duplicated with #74 and already resolved, will publish this feature in next release.

**Comment by Huachao** [comment]
@colutti  you can upgrade to latest version 0.18.0 to use this, and usage can be found in [README](https://github.com/Huachao/vscode-restclient#request-variables)
