### ISSUE TITLE
Zero Fractions are removed in Response Preview

### ISSUE THREAD

**Issue by marcel-benthin** [Huachao/vscode-restclient#171]
- VSCode Version: 1.21.0
- OS Version: Windows 10 Pro 16299.248
- REST Client Version: 0.17.0

Steps to Reproduce:

1. Request a API that returns a JSON where numbers are returned including a ` .0` fraction 
2. The Preview doesn’t show the `.0`. If I save/open the response the raw response is saved and the zero fraction is presevered

I know it’s not a big issue just a bit annoying for me while testing my API.

**Comment by Huachao** [comment]
@marcel-benthin nice suggestion, I will consider this carefully. The root cause is that in when prettify the response body,  there's no way to distinguish integer and floating number.

**Comment by marcel-benthin** [comment]
Thanks, yeah, I figured.
The problem is that JSON doesn’t distinguish between those two types (or doesn’t have them at all) and therefore the `.0` is not needed.

**Comment by Huachao** [comment]
I think we can solve this by using a JSON tokenizer and parser

**Comment by Huachao** [comment]
@marcel-benthin you can try the latest version 0.18.0 to verify this

**Comment by marcel-benthin** [comment]
way ahead of you… already tried it when it updated this morning. It’s awesome. 
I also like the folding.

Thank you very much.
