### ISSUE TITLE
Add option preventing reponse to be shown in split view

### ISSUE THREAD

**Issue by zdila** [Huachao/vscode-restclient#172]
- VSCode Version: 1.20.1
- OS Version: Win 8
- REST Client Version: 0.17.0

Please add option preventing reponse to be shown in split view. It would help for narrow displays (in my case vertically oriented monitor).

**Comment by Huachao** [comment]
@zdila Do you mean open the preview panel in current active view column, so in most cases just open a new tab next to the request file tab?

**Comment by zdila** [comment]
@Huachao exactly. I am able to drag the tab to the desired place manually but I would like to be placed like that automatically.

**Comment by Huachao** [comment]
@zdila done, and will publish this in next release

**Comment by Huachao** [comment]
@zdila you can upgrade to the latest version 0.18.0 to try this

**Comment by zdila** [comment]
It works. Thanks!

**Comment by Huachao** [comment]
@zdila I am sorry that in latest version 0.19.0, I make a breaking change that, original setting is deprecated and you should use the new setting `rest-client.previewColumn` to control which column to preview the response. And for your case, you should set the value to `current` which will keep the response previewed in the currently active column.
