### ISSUE TITLE
Auto remove the same history

### ISSUE THREAD

**Issue by bestswifter** [Huachao/vscode-restclient#175]
- VSCode Version: 1.21.1
- OS Version: 10.13.1
- REST Client Version: 0.17.0

Steps to Reproduce:

1. Send request from history
2. Another new history is recorded

I think it will be better to record the number of the same history, and show them by used number or frequency.

All these entries are the same and can be filterd

![wx20180315-181651](https://user-images.githubusercontent.com/8394612/37457512-2ec51224-287d-11e8-91ab-47b44d5c876f.png)

**Comment by bestswifter** [comment]
By the way, Can I resend the request directly by pressing ENTER, instead of open the file?

**Comment by Huachao** [comment]
If you just want to resend the last request, just press Cmd+Alt+L

**Comment by Huachao** [comment]
@bestswifter I think removing the duplicated requests doesn't make sense for **history**, we should record every request in history honestly.
