### ISSUE TITLE
Feature request: Add an ability to parse response body and store as variable

### ISSUE THREAD

**Issue by drkn** [Huachao/vscode-restclient#177]
It would be great to have an ability to parse response body and use its data as variable for another requests.

Example:
Request 1:

```
@user = johndoe
@pass = password

POST http://host:8000/api/login
Content-Type: application/json

{ username: "{{user}}", password: "{{password}}" }
```
Response:
```
...
{ "token": "12345678" }
```

Parse response using JS:
```
@token = response.body.json.token
```

Request2:

```
POST http://host:8000/api/getdata
AuthToken: "{{token}}"
...
```

**Comment by Huachao** [comment]
Duplicate with #74

**Comment by Huachao** [comment]
@drkn you can upgrade to latest version 0.18.0 to use this, and usage can be found in [README](https://github.com/Huachao/vscode-restclient#request-variables)
