### ISSUE TITLE
Rest client error - command 'rest-client.request' not found

### ISSUE THREAD

**Issue by tabishsoh** [Huachao/vscode-restclient#178]
- VSCode Version: 1.21.1 (1.21.1)
- OS Version:10.13.2 (17C205)
- REST Client Version: 0.17.0

Steps to Reproduce:

1. install from VS marketplace of VSIX on MAC. open your project and create a new file with extention html. try executing the request with (alt+cmd+r)
2. see the error below "command 'rest-client.request' not found"

**Comment by Huachao** [comment]
@tabishsoh can you open the developer console in Help tab, and check if any error occurs？ And the work around for now is that you try to uninstall the extension, and restart vscode, after that download the package to local from [here](https://github.com/Huachao/vscode-restclient/releases/download/v0.17.0/rest-client-0.17.0.vsix) And install it from local in the Extension panel, it has an option to install vsix package from local.

**Comment by tabishsoh** [comment]
i am getting this error in console log.

extensionService.ts:782 Activating extension 'humao.rest-client' failed: EACCES: permission denied, mkdir '/Users/TabishSohail/.rest-client'.

**Comment by Huachao** [comment]
@tabishsoh Can you check whether your current user has permission to create directory in your home directory? If not please grant the permission. Thanks

**Comment by tabishsoh** [comment]
I have tried with command line sudo command "sudo code --install-extension humao.rest-client
" and still no success. attached is the error for your reference.
<img width="1241" alt="screen shot 2018-03-26 at 11 52 54 am" src="https://user-images.githubusercontent.com/32664963/37896397-5d41deda-30ec-11e8-992d-192396da719f.png">

**Comment by Huachao** [comment]
@tabishsoh can you grant permission to allow current OS user to create directory in _/Users/TabishSohail_ directory

**Comment by tabishsoh** [comment]
Granted the permission to HomeDirectory. Now working fine thanks. (y)

**Comment by Huachao** [comment]
@tabishsoh glad to hear that.
