### ISSUE TITLE
Feature request: A system variable to generate date in ISO8601 or RFC1123 data format

### ISSUE THREAD

**Issue by peterquirk** [Huachao/vscode-restclient#180]
- VSCode Version:
Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:46:47.128Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version:
Windows 10 Pro version 1803
- REST Client Version:
0.18.1
The minio S3-compatible API requires a Date header in ISO 8601 of RFC 1123 format. The {{$timestamp}} system variable doesn't provide for format control. It would be helpful to add a format option to that system variable, or provide an alternate system variable that formats the date-time in a recognizable format.

Sample error code from minio:

HTTP/1.1 400 Bad Request
Accept-Ranges: bytes
Content-Type: application/xml
Server: Minio/RELEASE.2018-02-09T22-40-05Z (windows; amd64)
Vary: Origin
X-Amz-Request-Id: 15216EFD82DB700C
Date: Sun, 01 Apr 2018 22:03:04 GMT
Transfer-Encoding: chunked

<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>MalformedDate</Code>
  <Message>Invalid date format header, expected to be in ISO8601, RFC1123 or RFC1123Z time format.</Message>
  <Key></Key>
  <BucketName></BucketName>
  <Resource>/pqbucket1</Resource>
  <RequestId>3L137</RequestId>
  <HostId>3L137</HostId>
</Error>

**Comment by Huachao** [comment]
@peterquirk I add new new system variable named `datetime`, so that you can reference this variable with `{{$datetime iso8601}}` or `{{$datetime rfc1123}}`

**Comment by peterquirk** [comment]
Thank you - this is perfect!
Peter

**Comment by Huachao** [comment]
@peterquirk you can try the latest version 0.18.2 to verify

**Comment by hitalos** [comment]
Is it possible to add RFC3339 to the options?
