### ISSUE TITLE
Setting: 'previewOption' does not work in combination with 'previewResponseInUntitledDocument'

### ISSUE THREAD

**Issue by boris-ilijic** [Huachao/vscode-restclient#183]
- VSCode Version: 1.21.1
- OS Version: Windows 10
- REST Client Version: 0.18.1

Steps to Reproduce:

1.  In VS Code settings, set following:
```
"rest-client.previewOption": "exchange",
"rest-client.previewResponseInUntitledDocument": true
```
2. Execute request and result will be shown in new document, but in 'full' mode and not in 'exchange' mode
3. Set: "rest-client.previewResponseInUntitledDocument": false
4. Result will be shown correctly in 'exchange' mode

**Comment by Huachao** [comment]
nice catch, this is a known issue, I will support this in future releases

**Comment by Huachao** [comment]
@boris-ilijic @jenan-stripe you can try this feature in latest release 0.19.0
