### ISSUE TITLE
Requests variables and errors in file

### ISSUE THREAD

**Issue by colutti** [Huachao/vscode-restclient#184]
With the latest commit we can now use requests variables, and that is great. One thing that I would change is the warning message you get when the request has not yet been sent. When using requests variables, requests that have not been sent marks the file as an "error" which causes the project to appear having issues, which is not a fact.

![1](https://user-images.githubusercontent.com/9368892/38369207-7a75946c-38e7-11e8-80d6-59195f91766b.png)
![2](https://user-images.githubusercontent.com/9368892/38369212-7e0ace8a-38e7-11e8-98ac-60d8cfb91c3c.png)

**Comment by Huachao** [comment]
@colutti nice catch, I original purpose is that using referencing a not sent request should be realized by user. However what you advised makes sense, I will update the diagnostic severity to `Information` form `Error`. And in this case you can still get notified that this potential issue.

**Comment by Huachao** [comment]
@colutti I have fixed this in 0.18.2, and you can upgrade the extension and verify it.
