### ISSUE TITLE
Only one response variable gets resolved

### ISSUE THREAD

**Issue by lldata** [Huachao/vscode-restclient#189]
- VSCode Version: 1.12.1
- OS Version: win7
- REST Client Version: 0.18.1

Capture response variables only works for one variable.
You can mouseover in the editor and see that the variables are resolved correctly, but when the request is sent, the variables does not get resolved. Maybe the parser is greedy?

Steps to Reproduce:
```
# @name postjson
POST http://httpbin.org/post

{
    "key1" : "a",
    "key2" : "b"
}

###
# works fine
GET http://httpbin.org/get?key1={{postjson.response.body.json.key1}}

###

# variables doesn't resolve if there are more than one in a request
GET http://httpbin.org/get?key1={{postjson.response.body.json.key1}}&key2={{postjson.response.body.json.key2}}

```

**Comment by Huachao** [comment]
@lldata really nice catch, I will publish this fix in next release.

**Comment by Huachao** [comment]
@lldata @herkulano you can try the latest version 0.18.2 to verify

**Comment by lldata** [comment]
Works for me too.
