### ISSUE TITLE
Fonts in `\reponse-prevew` window not following configuration

### ISSUE THREAD

**Issue by shytikov** [Huachao/vscode-restclient#19]
- VSCode Version: 1.3.1
- OS Version: Windows 10
- REST Client Version: 0.6.1

Steps to Reproduce:

1.  Select none-standard font for `VSCode`.  Example of my `settings.json`:
```
// Place your settings in this file to overwrite the default settings
{
    "editor.fontFamily": "Arial, Consolas, 'Courier New', monospace",
    "editor.fontSize": 8,
    "editor.wrappingColumn": 0
}
```
2. Note that font has changed in request window;
3. Execute request;
4. Note that `\reponse-prevew` window still uses standard font (see attached screenshot);

![illustration](https://cloud.githubusercontent.com/assets/1185905/17101246/c3af9224-5273-11e6-9ced-bdbccd0f7c3c.png)

**Comment by Huachao** [comment]
@shytikov , sorry for the dealy. The settings of editor.font-family is not used by VS code in `vscode.previewhtml` command, if need to achieve this, I need to manually the user configuration and dynamically generate the css file, and render the response. I think, adding a new setting by VS Code to support font-family of preview is a more straightforward way.

**Comment by shytikov** [comment]
OK... So that window is HTML preview... That explains situation better... I will create separate issue for one of the cases I'm expecting.

**Comment by Huachao** [comment]
@shytikov , since you will create separate issue, I just close this one
