### ISSUE TITLE
Request with several values from an array of a previous response

### ISSUE THREAD

**Issue by herkulano** [Huachao/vscode-restclient#191]
- VSCode Version: 1.22.2
- OS Version: MacOS 10.13
- REST Client Version: 0.18.1

Steps to Reproduce:

Create a request that has several variables from an array of a previous response.
```
GET http://localhost:8080/api/source-types/{{example.response.body.$.sources[0].name}}/{{example.response.body.$.sources[0].type}}/{{example.response.body.$.sources[0].version}}
Authorization: Bearer {{token.response.body.access_token}}
```

It works if there's only one value taken from the array. Any of the values work separately but not together in the same request.
```
GET http://localhost:8080/api/source-types/{{example.response.body.$.sources[0].name}}
Authorization: Bearer {{token.response.body.access_token}}
```

**Comment by Huachao** [comment]
@herkulano Duplicated with #189.  Already fixed, and will publish this fix in next release.
