### ISSUE TITLE
How to specify path for saving response?

### ISSUE THREAD

**Issue by UsulPro** [Huachao/vscode-restclient#192]
Thank you for this great extension!

One thing that curious for me: It saves responses to a path like `~/.rest-client/responses/raw/Response-1523791868651.http` while I'd like to specify my project folder or at least to the same folder where .http file is located. Do I miss something in settings? (didn't find any for that)

- VSCode Version: 1.22.2
- OS Version: LinuxMint
- REST Client Version: 0.18.1

**Comment by Huachao** [comment]
@UsulPro you didn't miss anything, and it's in my plan, duplicated with #186, and close this to in favor of that. Thanks for your suggestion.
