### ISSUE TITLE
Configurable keyboard shortcuts

### ISSUE THREAD

**Issue by lalberto8085** [Huachao/vscode-restclient#195]
- VSCode Version: 1.22.2
- OS Version: W10
- REST Client Version: 0.18.2

I like using the keyboard shortcuts but I have global, machine wide, shortcuts for `crtl-alt-r` for instance, I'd like to be able to change this so I can use my own keyboard shortcuts. 

Thanks

**Comment by Huachao** [comment]
@lalberto8085 change keyboard shortcuts is a feature from vscode, and you can open the command `Preferences: Open Keyboard Shortcuts`, and then find your expected command and update it.
