### ISSUE TITLE
Correct typo in the responce window

### ISSUE THREAD

**Issue by shytikov** [Huachao/vscode-restclient#20]
- VSCode Version: 1.3.1
- OS Version: Windows 10
- REST Client Version: 0.6.1

Steps to Reproduce:

1. Note that output window is called `\reponse-prevew`. 
2. Is backslash in the beginning is a typo or this was done intentional?

**Comment by Huachao** [comment]
@shytikov ,for question 1, there's no typo on my machine. I can't repro it on my Win 10 PC.

**Comment by Huachao** [comment]
@shytikov, I have used leveraged from the vs code latest api change, and will specify title manually for each response, the title format will look like `OK(200) - 1286ms`, or `Forbidden(403) - 896ms`

**Comment by Huachao** [comment]
So this fix will be released in next publish.

**Comment by Huachao** [comment]
@shytikov , I found it seems I can't set the title if the response pane is already opened, I think this is a limitation of VS Code. So I would like to set to a const value, like `Response`

**Comment by shytikov** [comment]
@Huachao I've just checked, on front page of this repository there is the gif image showing process working with this extension. And there you can see that result window title contains backslash. 

It is `\reponse-prevew`, while I believe `\` does not belong there...

**Comment by Huachao** [comment]
@shytikov , the `\` is added by VS Code itself, now, what I don't quite understand is the typo, sorry for that I didn't explain well. And now the new version 0.6.2 has been published, and you can have a try, in that version, I have set the title to const value 'Response'.
