### ISSUE TITLE
Show save response body link for large response bodies 

### ISSUE THREAD

**Issue by schallm** [Huachao/vscode-restclient#201]
- VSCode Version: 1.22.2
- OS Version: Windows 10
- REST Client Version: 0.18.3

Steps to Reproduce:

1. Request url that returns large (binary in my case) response (i.e. https://www.cca.edu/sites/default/files/pdf/08/word-to-pdf.pdf)
2. Wait for response to show

Could we have a max-display-response size?  If the response size is larger than the setting, show a "Save Response Body" link that opens a "Save As" dialog.  

Or maybe based on Content-Type?

So instead of seeing:
![image](https://user-images.githubusercontent.com/331167/39550377-a9c5b87e-4e26-11e8-97c4-455436cd553b.png)

We could see a "link" similar to the "Send Request" that would save the response body:
![image](https://user-images.githubusercontent.com/331167/39550548-3cdc22f6-4e27-11e8-8c7d-b804a0f54690.png)

**Comment by Huachao** [comment]
@schallm, in fact, this is already supported by in my extension. You can click the `Save Response Body` icon in the upper right corner.
![image](https://user-images.githubusercontent.com/2796177/39556685-acce0448-4eb4-11e8-9420-8fe1aaa79d69.png)

**Comment by schallm** [comment]
That does work and I'm fine just clicking that... It would be nice however if you didn't load large response bodies into the Response document.  It can take a long time to display, especially for large documents.  I was testing a endpoint that downloads mp3 files.  The response came back almost immediately, but "rendering" the bytes of a multi-megabyte file took a very long time.  

I knew about the link on the tool bar, but  thought a link where the body would have been would more discoverable?

**Comment by Huachao** [comment]
@schallm actually before rending the page completely, you are already able to save the response body.

**Comment by schallm** [comment]
I did try that and it works. The “previous” request’s request/response was still showing in the response editor, but the “current” binary response is what was saved. So it did work. Just seems strange to “render” a huge binary file when most likely the developer just wants to save the file anyway. 

To be clear, I love this extension and the new ability to save responses and use JSONPath just rocks. Thanks for all your work!

**Comment by Huachao** [comment]
@schallm thanks for your suggestion about directly download the response body, I will consider it carefully 😄
