### ISSUE TITLE
Add support for default headers

### ISSUE THREAD

**Issue by Kronuz** [Huachao/vscode-restclient#205]
- VSCode Version: 1.22.2
- OS Version: macOS High Sierra 10.13.4
- REST Client Version: 0.18.3

Please add `rest-client.defaultHost`, `rest-client.defaultContentType`, `rest-client.defaultAccept`, etc.; so that, if configured, we don't have to specify `http://localhost:8080/` or `Host: localhost:8080`.

The idea is that for things like:

```http
PUT /documents/john
Host: localhost:8080
Content-Type: application/json
Accept: application/json; indent=4

{
    "firstname": "John",
    "lastName": "Smith"
}
```

One could simply configure the (workspace) settings:
```json
{
    "rest-client.defaultHost": "localhost:8080",
    "rest-client.defaultContentType": "application/json",
    "rest-client.defaultAccept": "application/json; indent=4"
}
```

and use:
```http
PUT /documents/john

{
    "firstname": "John",
    "lastName": "Smith"
}
```

The proposal is to convert settings of the form PascalCase to dash-separated (`defaultHeaderName` to `header-name`); so this would effectively extend `rest-client.defaultuseragent` (and rename it to `rest-client.defaultUserAgent`).

**Edit:**
I'd propose support for the following standard headers:

- Accept
- Accept-Charset
- Accept-Datetime
- Accept-Encoding
- Accept-Language
- Access-Control-Request-Headers
- Access-Control-Request-Method
- Authorization
- Cache-Control
- Content-Type
- Cookie
- Host
- Origin
- User-Agent

**Comment by Huachao** [comment]
@Kronuz I have added some comment in #206, and what about 
```json
{
    "rest-client.defaultHeaders": {
         "X-Custom-Header": "foo bar",
         "Host": "localhost"
    }
}
```
