### ISSUE TITLE
Ctrl-Shift-R do not work for JSON files

### ISSUE THREAD

**Issue by MaximA10rus** [Huachao/vscode-restclient#207]
- VSCode Version: 1.23.0
- OS Version: Win10
- REST Client Version: 0.0.6

Steps to Reproduce:

1. Create new file with JSON request, press Ctrl-Shift-R. JSON sending Ok. 
2. Save this file as JSON (*.json), press Ctrl-Shift-R. Nothing. JSON not sended. 

But, for example, Ctrl-Shift-H works anyway, for all files.

**Comment by Huachao** [comment]
This is by design, we want the shortcut limited to http and plain text. If you really want to send a request in other file formats, you need to use the mouse to select expected part, and press F1to select the send request command.
