### ISSUE TITLE
Use of file variables in file variables only works if declarations are in reverse

### ISSUE THREAD

**Issue by SimonDever** [Huachao/vscode-restclient#208]
- VSCode Version: 1.24.0-insider (commit: 987c3dcc..)
- OS Version: Windows 10 x64
- REST Client Version: 0.18.4

Steps to Reproduce:

1. Create test file: `lidarr.http`:
```
@root = http://localhost:8686/api/v1/
@calendar = calendar?start={{start}}&end={{end}}&includeArtist=true
@start = 2018-01-01
@end = 2018-12-31
###
GET {{root}}{{calendar}}
###
```
2. Right click on the GET URL and select "copy request as cURL", output is:
```
curl --request GET \
  --url 'http://localhost:8686/api/v1/calendar?includeArtist=true&end=2018-12-31&start=2018-01-01'
```
3. Move `@start` and `@end` variables to be above the `@calendar` variable like this:
```
@start = 2018-01-01
@end = 2018-12-31
@calendar = calendar?start={{start}}&end={{end}}&includeArtist=true
```
4. Again right click on the GET URL and select "copy request as cURL", output is:
```
curl --request GET \
  --url 'http://localhost:8686/api/v1/calendar?includeArtist=true&end=%7B%7Bend%7D%7D&start=%7B%7Bstart%7D%7D'
```

I am not terribly bothered by this now I've figured out a way around it but it isn't obvious as to why it works only like this. I'm not sure using variables in variables was even mentioned in any documentation I found. Not sure if it's relevant but the generated URL has also swapped the order of query parameters.

**Comment by SimonDever** [comment]
Modify to remove the ability to use variables in other variables or modify to be able to declare them in the reverse order as well?

**Comment by Huachao** [comment]
@SimonDever I am planning the feature that the actual value of a file variable can reference other request variables and file variables.

**Comment by vladvino** [comment]
Referencing environment variables from a file variable used to work for me. Looks like something in 2018/6/28 release broke it. Would be great to see it working again.

**Comment by Huachao** [comment]
@vladvino I will fix this ASAP.

**Comment by mchelen** [comment]
@Huachao Is there an issue for the feature enhancement of reusing one file variable in another file variable?

**Comment by Huachao** [comment]
@mchelen I am afraid not. And I will implement the feature that file variables can depend on any custom variables(environment, file and request variables) finally.

**Comment by schallm** [comment]
Would/Could this also support storing "resolved" dynamic variables in variables?  I would like to store a date in a variable so it can be used multiple times in an array of objects being posted
```
@enteredDate = {{$datetime iso8601}}
```
So it could be used in a post like the following
```json
[
  {
    "firstName": "joe",
    "enteredDate": "{{enteredDate}}"
  },
  {
    "firstName": "bob",
    "enteredDate": "{{enteredDate}}",
  }
]
```

**Comment by Huachao** [comment]
@schallm Thanks for your suggestion. The file variables definition can already support referencing request variables, and allowing supporting other types of variables like `System Variable`, `Environment Variables` and `File Variables` are in my todo list.

**Comment by Huachao** [comment]
@SimonDever @vladvino @mchelen @Mellbourn @schallm I have implemented the feature that file variables can reference other file variables. And the work that references environment variables is still WIP.

**Comment by Huachao** [comment]
@SimonDever @vladvino @mchelen @Mellbourn @schallm I have implemented the feature that file variables can reference file/system/request/environment variables. I will publish this feature in next release

**Comment by Huachao** [comment]
@SimonDever @vladvino @mchelen @Mellbourn @schallm you can try the latest version 0.20.4 to verify

**Comment by schallm** [comment]
I can confirm my use case is now supported.  One interesting/awesome thing is that the dynamic variables are re-evaluated each time "Send Request" is clicked.  So in my example above, `enteredDate` is updated to "now" with each request.

Thanks for implementing this feature!
