### ISSUE TITLE
How to declare integer variables?

### ISSUE THREAD

**Issue by colutti** [Huachao/vscode-restclient#213]
I have the follow payload I send to an endpoint:

{
    "subnet_name": "teste",
    "subnet_type": "frontend",
    "addressBlockSize": 27
}

As you can see, the parameter addressBlockSize is integer. When I replace it to a variable as follow:

 "addressBlockSize": {{frontend_subnet_size}}

It does not work. It seems to me that the syntax is wrong. How do I create a integer variable I could use in the payload?

![restclient](https://user-images.githubusercontent.com/9368892/40717962-85e848ce-640e-11e8-86ff-e80741d5e7c5.png)

**Comment by Huachao** [comment]
I think the way you do is ok, it should be an integer you want. The syntax looks not right is due to the request body doesn't follow the JSON syntax after introducing the double quote
