### ISSUE TITLE
help w/ custom header variable

### ISSUE THREAD

**Issue by bergerd1** [Huachao/vscode-restclient#214]
- VSCode Version: 1.23.1
- OS Version: Microsoft Windows 10 Pro, build 17134
- REST Client Version: 0.18.4

I've read through the README, and keep in mind that I am a rather inexperienced individual here.

I am wanting to automatically grab the response of a custom header value for subsequent requests.
In this case, the value for 'x-csrf-token' in the initial GET request to be used in the next requests.
How do I do this?

```
@host = <URI redacted>
@eptmain = <endpoint redacted>
@AuthB = <auth value redacted>
@contentType = application/json
@csrfToken = C:\filePathRedacted\REQUESTS\REQRES\x-csrf-token-resp
@REQ1 = GET
@REQ2 = PUT
@REQ3 = POST

###

Send Request
GET {{host}}/{{eptmain}} HTTP/1.1
Authorization: {{AuthB}} 
x-csrf-token: fetch

###

POST {{host}}/{{eptmain}} HTTP/1.1
Authorization: {{AuthB}}
Content-Type: {{contentType}}
x-csrf-token: {{$csrfToken}}
CamelHttpMethod: {{REQ3}}

{
    "ExampleRightHere": {
        "Example1": {
            "SomeVariable": "something here",
            "SomeOtherVar": "some sort of value name",
            "SomeOtherOtherVar": "some value",
            "AnotherVarExample": "value"
        }
    }
}
```

**Comment by Huachao** [comment]
@bergerd1 you can follow the doc in the [request variables](https://github.com/Huachao/vscode-restclient#request-variables) section of README, like

```http
@baseUrl = https://example.com/api

# @name login
POST {{baseUrl}}/api/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

name=foo&password=bar

###
GET {{baseUrl}}/comments/{{createComment.response.body.$.id}} HTTP/1.1
Authorization: {{login.response.headers.X-AuthToken}}
```
In the previous example, the second request references a header named `X-AuthToken` which is returned from the first request, which is named as `login`. In your case, you also need to create a name in your request, and references it later.
