### ISSUE TITLE
No Send Request Link on Mac

### ISSUE THREAD

**Issue by mindspanconsultants** [Huachao/vscode-restclient#220]
- VSCode Version: 1.24.0 (1.24.0)
- OS Version: macOS 10.13.5
- REST Client Version: 0.18.4

Steps to Reproduce:

1. GET http://hearthstonebakery.ca/BakersBlog/wp-json/wp/v2/posts

No link appears above the entry any of my Macs. Have uninstalled and reinstalled. Hitting command-option-r works on one of my Macs running El Capitan 10.11.6, but does nothing on my MacBook Pro running 10.13.5.

**Comment by Huachao** [comment]
What's the language of your file displayed at the right bottom of vscode?

**Comment by mindspanconsultants** [comment]
Javascript. Here is the screenshot.
![screen shot 2018-06-11 at 8 13 55 am](https://user-images.githubusercontent.com/8838572/41240494-78a51300-6d4f-11e8-9eb1-0127ce431a33.png)

**Comment by Huachao** [comment]
It should be HTTP. You can create a file with file extension http or rest, another way is manually set to HTTP with the changing language button
