### ISSUE TITLE
[Suggestion] Redirect Logging

### ISSUE THREAD

**Issue by jcdickinson** [Huachao/vscode-restclient#221]
- VSCode Version: 1.24.0
- OS Version: Windows 1709
- REST Client Version: 0.18.4

When redirects are automatically handled, it would be helpful if they were logged to the result window (according to a setting). For example: 

```http
302 > http://localhost:12345/api/v1/cas/e538eed54969c0b7d15e67cb423dc6d704e463ea

HTTP/1.1 200 OK
```

This is useful for people who enjoy the convenience of automatic redirection (the default setting right now), but are also interested in testing how that redirection occurs.

**Comment by Huachao** [comment]
@jcdickinson I have thought about this for quite a long time, nice feature, I will implement this when available.

**Comment by 12masta** [comment]
Definitely needed. Bumping topic. :)
