### ISSUE TITLE
support for multi line comments

### ISSUE THREAD

**Issue by lastlink** [Huachao/vscode-restclient#223]
It would be nice if we could have some kind of multi line comment support or non request separator
E.g. 
###! no **Send Request**

or 

 \```
 \```
= **multi line comment**

Sometimes I need to declare notes like the params to declare for environments to switch to or what the expected return response should be.

**Comment by Huachao** [comment]
@lastlink nice suggestion, I will consider this carefully.

**Comment by Huachao** [comment]
@lastlink @tfnaylor I'd like to close it since I think single-line comments are enough for use. Since `#` and `//` should fix your case, and only `###` is request delimiter.
