### ISSUE TITLE
AAD auth uses the wrong audience

### ISSUE THREAD

**Issue by bsrini** [Huachao/vscode-restclient#225]
- VSCode Version: 1.25.0
- OS Version: Windows 10, 1803 (17134.137)
- REST Client Version: 0.19.0

Steps to Reproduce:

1. Create an Authorization header using a custom audience, like - `Authorization: {{$aadToken microsoft.com aud:https://graph.windows.net}}`
2. Click on Send Request and attempt to login via the device-login prompt.
3. You'll notice an error message indicating that the audience chosen for the request was the domain of the request, rather than the custom audience defined in the header.

![image](https://user-images.githubusercontent.com/709154/42482998-cb4dc974-839f-11e8-81a4-aa211bd572ef.png)

**Comment by Huachao** [comment]
@bsrini can you also show me the request url?

**Comment by bsrini** [comment]
Here's a sample request, @Huachao:

`GET https://service.microsoft.com/api/resources/4e320e74-1c6a-45c5-9b6d-fae0cb23d1c0
Authorization: {{$aadToken microsoft.com aud:https://graph.windows.net}}`

**Comment by bsrini** [comment]
My apologies for the confusion @huachao. The URL was just an example and doesn't point to an actual service. However, the bug's side-effects are visible regardless of the actual service's presence, since the auth token generation happens before the request is sent to the service endpoint.

What I wanted to demonstrate from the screenshot was that the audience specified in the header was different from the audience that was actually sent to the STS during login.

If you'd like a working example, I can set up a tenant, a user and an http app, and share the credentials of that user with you.

**Comment by Huachao** [comment]
@bsrini if you can provide the repro environment, that would be very helpful, thanks in advance.

**Comment by bsrini** [comment]
Hey @Huachao,

Here's a zip file containing screenshots of the issue happening, along with the sample creds for you to try-out yourself:
[repro-with-screenshots.zip](https://github.com/Huachao/vscode-restclient/files/2190968/repro-with-screenshots.zip)

From what I can see, some requests seem to go go through fine, and while I'd expect the token to be cached for the next request, I get another login prompt. The resource specified for this 2nd login is what seems to fail due to the wrong resource being specified. If I cancel out of the login prompt on subsequent requests, the cached token is used and works successfully...

Thanks in advance for looking into it!

**Comment by Huachao** [comment]
@bsrini thanks for your information and I have fixed the issue and will publish this fix in next release.

**Comment by bsrini** [comment]
Thanks for fixing the bug so quickly, @Huachao! 🥇

**Comment by Huachao** [comment]
@bsrini you can try the latest version 0.19.1 to verify the fix.

**Comment by bsrini** [comment]
0.19.1 works perfectly, thanks for the quick fix @Huachao!
