### ISSUE TITLE
Prevent auto indenting Json

### ISSUE THREAD

**Issue by johnrobertporter** [Huachao/vscode-restclient#226]
I would like to be able to turn off the auto indenting of json to ensure my API is working correctly. I have an option to provide `pretty` json, or compressed as default, and I can't see if it is working with this extension.

**Comment by Huachao** [comment]
@johnrobertporter I will add this option, and before that, you have to remove the line breaks and whitespaces manually or to use some tools. Thanks for your suggestion, and I will update in this thread later.

**Comment by johnrobertporter** [comment]
Thanks

**Comment by Huachao** [comment]
@johnrobertporter I have added the `addRequestBodyLineIndentationAroundBrackets` setting to control this behavior, you can set it to `false` to achieve this. And this fix will be included in next release.

**Comment by johnrobertporter** [comment]
Thanks

**Comment by Huachao** [comment]
@johnrobertporter you can try this fix with the newly added setting `rest-client. addRequestBodyLineIndentationAroundBrackets` and set it to `false` in latest version 0.19.1.
