### ISSUE TITLE
On Windows, curl command can't be run

### ISSUE THREAD

**Issue by Riduidel** [Huachao/vscode-restclient#227]
- VSCode Version: 1.25.0
- OS Version: Windows 10 Professionnel
- REST Client Version: 0.19.0

Steps to Reproduce:

1.  Start VS Code on Windows
2.  Create a .http file
3. Create any kind of HTTP request (ideally with headers and content)
4. Generate the curl command (using the right-click menu item)
5. Paste that command in Windows command emulator

It will fail in various ways 

* "Classical" Windows command emulator doesn't support the `\` character used to separate lines
* PowerShell has a curl applet with a very different behaviour (see http://thesociablegeek.com/azure/using-curl-in-powershell/)

Could it be possible to not insert the `\` on Windows ? It would avoid the problem.

**Comment by Huachao** [comment]
@Riduidel I have fixed the issue and will publish this fix in next release.

**Comment by Huachao** [comment]
@Riduidel you can try the latest version 0.19.1 to verify.
