### ISSUE TITLE
Multiple requests functionality

### ISSUE THREAD

**Issue by shytikov** [Huachao/vscode-restclient#23]
Hi,

It would be also nice to have several output windows. Currently you cannot have two input documents that feed their output to two different output windows. You will always have only one response window, and you'll be loosing results of previous requests all the time.

What do you think about such improvement?

**Comment by Huachao** [comment]
@shytikov , thanks so much for your nice suggestion. I'd like to add an option in configuration that allows user to choose whether opens a new response pane for each request or just display all the response in a single response pane. Do you think it's OK?

**Comment by shytikov** [comment]
I think it's indeed very wise solution! I should suggest this on the first place!

**Comment by Odonno** [comment]
Why is it different of #21 ?

**Comment by Huachao** [comment]
@Odonno, you are right, I think they are the same for the concern I've mentioned. I'd like to complete #21 with basic feature that these requests are independent, that means one request won't consume previous requests' responses, do you think it's ok for now?

**Comment by shytikov** [comment]
My bad. It was longer issue with several topics, but later I extracted some thoughts and used them as comments in several different places. Now it looks like duplicate. Probably it should be closed then.

**Comment by Odonno** [comment]
@Huachao Yes, of course, I firstly intended to make requests independants.

**Comment by Huachao** [comment]
@shytikov, I have add the option to show response in different tab, please help to verify in latest version 0.6.3

**Comment by shytikov** [comment]
Hi, thanks!

Do we need to configure that behavior somehow?

**Comment by Huachao** [comment]
@shytikov, yes, by default the option is turned off, and you can set the `rest-client.showResponseInDifferentTab` to true as the [README.md](https://github.com/Huachao/vscode-restclient#settings)
