### ISSUE TITLE
不能解析json中的"="

### ISSUE THREAD

**Issue by kybom** [Huachao/vscode-restclient#230]
Issue Type: <b>Bug</b>

```
{
"token": "XXXXXXX+yCdu9FICIutsZMeuVtXP+XXXXXXXXXX+bXUxlS79XAvP3rtHToRGU6vOY4eAF9ifbM\u003d"
}
```
token最后的\u003d应该是个"="

Extension version: 0.19.0
VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (1.25GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|57%|

</details>

**Comment by kybom** [comment]
这是response body的一部分。这个请求是获取token的，包含一些私密信息，所以不便于贴出来。在postman中是可以正常显示的。

**Comment by kybom** [comment]
我的的账号是在“口袋48“app中注册的，这个请求是为通过账号获取token.
下载地址：[http://h5.48.cn/pocket48/index_pc.html](url)
请求格式是这样：
```
POST https://puser.48.cn/usersystem/api/user/v1/login/phone
Content-Type: application/json
os: android
IMEI: 你手机的IMEI
version: 5.5

{
  "latitude":"0",
  "longitude":"0",
  "account":"你的账号",
  "password":"你的密码"
}

```

**Comment by Huachao** [comment]
@kybom nice catch, I can repro it. As you can see in the postman, the actual response is really `\u003d`, while after prettify, the `\u003d` is prettified as the equal sign. And I will consider how to fix it since we don't use the same way as postman did. I will update in this thread if I come up with a solution.

And I have another question that if we use the token with `\u003d` and sent to the server, can the subsequent requests work as expected.

**Comment by kybom** [comment]
使用\u003d 服务器返回:
```
{
  "status": 401,
  "message": "授权验证失败"
}
```

**Comment by Huachao** [comment]
@kybom I have fixed the issue by adding a setting `rest-client.decodeEscapedUnicodeCharacters`. You can set it to `true` to fix this.

**Comment by Huachao** [comment]
@kybom you can try the latest version 0.19.1 to verify.

**Comment by kybom** [comment]
@Huachao 怎么升级到0.19.1

**Comment by Huachao** [comment]
@kybom by default VSCode will automatically update the extensions which are available for you. However, if you have disabled this behavior, you can do this manually in `Extension View`, and find out my extension, click `Update`. After that, you need to restart the VSCode instance.

**Comment by kybom** [comment]
可以显示“=”了。刚才我的vscode没有检测到更新，执行一下扩展的搜索功能就看到更新了。
