### ISSUE TITLE
Speed issues formatting complex JSON

### ISSUE THREAD

**Issue by ygraber** [Huachao/vscode-restclient#234]
- VSCode Version: 1.26.0
- OS Version: Windows 10
- REST Client Version: 0.19.1

Steps to Reproduce:
1. GET http://www.vizgr.org/historical-events/search.php?format=json&begin_date=-3000000&end_date=20151231&lang=en
2. Wait, Wait, Wait

The speed of formatting JSON using the current parser seems to be related to number of "edits" not size of JSON. I have switched to 'js-beautify' and have made a PR: https://github.com/Huachao/vscode-restclient/pull/233 I'm hoping it will be accepted. (after I fix my linting issues)

**Comment by Huachao** [comment]
Already merged!
