### ISSUE TITLE
Is it possible to issue a multipart POST with binary files?

### ISSUE THREAD

**Issue by opensas** [Huachao/vscode-restclient#235]
- VSCode Version: 1.22.2
- OS Version: win 7 enterprise
- REST Client Version: 0.18.4

I'm not sure how to issue a mutipart with binary content referencing files from my workstation.

In curl I do it like this:

```
curl \
  -X POST http://localhost:5000/api/info \
  -H "Content-Type:multipart/form-data" \
  -F 'data={"codigo": "new", "descripcion": "new"}' \
  -F "file1=@avatar.jpeg"
```

**Comment by Huachao** [comment]
@opensas as you can see in the `README.md`, the example should work for you:
```http
POST https://api.example.com/user/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="1.png"
Content-Type: image/png

< ./1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
```
In this case, the *1.png* in current directory is a binary file, and you can even specify the absolute path as you wish. You just need to put a leading **`< `** before the file path.

**Comment by opensas** [comment]
Excellent! It works great!

Thanks a lot for the prompt reply and for your hard work.

This is a VERY useful feature, perhaps it could be added to the [Main
Features](https://github.com/Huachao/vscode-restclient#main-features)
section.
