### ISSUE TITLE
Fails to Get/Parse Valid JSON

### ISSUE THREAD

**Issue by nahtnam** [Huachao/vscode-restclient#239]
- VSCode Version: 1.26.1
- OS Version: 10.13.5
- REST Client Version: 0.19.1

Steps to Reproduce:

1. Make a `test.http` file.
2. Add the following
```
GET https://gist.githubusercontent.com/nahtnam/cd842afc31d90c3417c060e926fca656/raw/dc9f6d41a4613e7c56d4cc8458719b0b6130cf39/sample.json
```
3. Run it

It will get stuck and not show anything and eventually slow down the rest of vscode as well.

**Comment by Huachao** [comment]
@nahtnam it seems that I can view the response successfully except that it will cost a longer time.

**Comment by nahtnam** [comment]
Ah I see, it takes about 25 seconds to load, and even then it is un-prettified. Is there any way to increase the performance? The API returns within 300ms so it should really only take a few seconds max right?

**Comment by nahtnam** [comment]
Awesome, any idea when this feature will be released into the market?

Really appreciate the work done here, this library is very useful!

**Comment by nahtnam** [comment]
Gotcha, awesome, thanks!

**Comment by nahtnam** [comment]
Actually @Huachao The issue is still there. Please try with this API URL: https://apituner.ecbsn.com/apituner/v1/store/reward/list?channel=4

On my computer, it takes forever and eventually ends up freezing VS Code. Is it because the JSON is big and VS Code cannot handle it or is it because you are processing the JSON?

**Comment by Huachao** [comment]
@nahtnam I have improved the performance of the second phase (`processing received response`), the duration costs less than 2 seconds on my local machine for your request. I'd like to close it. I will publish the fix in next release.

**Comment by Huachao** [comment]
@nahtnam you can try the latest version 0.21.0 to verify
