### ISSUE TITLE
req.body is empty using REST Client, but with Postman, it works fine

### ISSUE THREAD

**Issue by locohost** [Huachao/vscode-restclient#243]
- VSCode Version: 1.26.1
- OS Version: Windows 10
- REST Client Version: 0.19.1

Steps to Reproduce:

1.  Create a POST Json content
2. Post it

When I post with REST Client, in the express route, req.body is always empty. When I post the *exact* same message using Postman, the express route works fine as req.body is populated as expected.

Here is the text in Rest client...
NOTE: The appSecret is 412 characters long so I clipped...

```
POST http://localhost:3000/message HTTP/1.1

Content-Type: application/json
{ 
	"processHandle": "joe", 
	"appSecret": "dbc339a42526a898b76eee100a1a913c2fd0dac83b663bbb72..........", 
	"tags": "test-tag,blah-tag", 
	"data": "{ \"AnObject\": { \"Attrib\": \"SubObjData...\" }, \"FirstNumber\": 27, \"ThisIsData\": \"SomeData\", \"test\": \"Hello!\", \"LastNumber\": 42 }"
}

```

**Comment by Huachao** [comment]
The blank line should exist between request body and headers, not the request line and headers

**Comment by locohost** [comment]
That was it. Thank you for super fast reply :-)

**Comment by Nedjm** [comment]
hey guys I have the same problem but this didn't fix it`POST http://localhost:3000/login
Content-Type: : application/json

{
    "username": "kyle"
}
`

**Comment by Nedjm** [comment]
hey guys I guess I have the same problem and the body is just empty and I want to get the username, what am I doing wrong??

`
POST http://localhost:3000/login
Content-Type: : application/json

{
    "username": "kyle"
}

`

**Comment by DefaultJARR** [comment]
Same thing is happening to me with this :C

`POST http://localhost:7000/accountsmod/accounts HTTP/1.1
Content-Type: : application/json

{
    "nickname": "El Juanzo",
    "password": "adwfawd",
    "status": true,
    "role": "5f018c5afda9715ff8403736",
    "user": "5f0187ae32a664164809ac4a"
}`

what could be the mistake?

**Comment by Huachao** [comment]
@DefaultJARR could you please show me the complete http file?

**Comment by stevenson** [comment]
I am experiencing the same issue with a http file with a body.
I sent a request with header
````content-type: "application/json"```
but when I removed the quotes for application json it worked
```Content-Type: application/json```

**Comment by jkcdarunday** [comment]
@DefaultJARR 
Hi, I noticed that there are two colons after your Content-Type which causes the client to send an invalid type and the server to not know how to process the body.

**Comment by andrechalom** [comment]
Having the same issue on Windows 10 when running requests against localhost, maybe it's related?

example.rest as follows:

```
POST http://127.0.0.1:8000/users HTTP/1.1
content-type: "application/json"

{
    "name": "Joao",
    "lname": "da Silva",
    "email": "jdasilva@example.com",
    "phone": "(11) 555-1234"
}
```

**Comment by jkcdarunday** [comment]
@andrechalom Check out @stevenson's comment above. The value of content-type should not be wrapped in double quotes.

**Comment by andrechalom** [comment]
My bad, the actual problem was how I was trying to read the $_POST superglobal, when I should be looking at `file_get_contents("php://input")`

**Comment by Prathmes-Patil** [comment]
Request.body is undefined whenever I try to call '/signup' endpoint

> 
> `GET http://localhost:3000/users
> 
> ###
> 
> POST http://localhost:3000/signup
> Content-Type: application/json
> 
> {
>     "name":"Prathm",
>     "password":"1234"
> }`
> 

GET request for '/users' works perfectly.
Here's the screenshot of function

> `const express = require("express");
> const app = express();
> 
> const users = [{ name: "USERNAME" }];
> 
> app.get("/users", (req, res) => {
>   res.json(users);
> });
> 
> app.post("/signup", (req, res) => {
>   console.log("req body", req.body);
>   try {
>     const user = { name: req.body.name, password: req.body.password };
>     users.push(user);
>   
> 

>   res.status(201).send({});
>   } catch (error) {
>     res.status(500).send({ message: "Something went wrong!" });
>   }
> });
> 
> app.listen(3000, () => console.log("App running on localhost:3000"));
> `
> 
 Can somebody please help me with this issue ?

**Comment by Prathmes-Patil** [comment]
If anyone is facing same problem of getting "req.body" as "undefined" in express application with restclient then just call "app.use(express.json())" in your express application.

 This worked for me.

note: 'app' is the name of my express application.

**Comment by Huachao** [comment]
@Prathmes-Patil for json body, you should add `app.use(express.json());`

**Comment by Maciel64** [comment]
I'm current facing the same issue. My code in between Laravel and Rest Client. Laravel code is simple as

```php
public function store(Request $request)
    {
        return $request->all();
    }
````

JS code, a request that works fine:

![image](https://github.com/Huachao/vscode-restclient/assets/64281475/e2513b2f-4436-4bb9-b266-75ac260493ad)

But with http Rest Client all fields are null:

![image](https://github.com/Huachao/vscode-restclient/assets/64281475/089bdab8-5157-494d-8edb-f35647ee6bb8)

Does someone have any ideia?

**Comment by DamianSuess** [comment]
For future readers of this for Laravel v11, below is a sample of logging via POST in and using the `bearer` token to GET a list of products. It took me a while to figure out what I was doing wrong, but I finally got it.

The results are documented on the repo, [Rest API Login With Products Example](https://github.com/DamianSuess/Learn.Laravel/tree/master/3-RestApiLoginProductsExample).


### Login and store the auth token into the `login` variable

```http
// @name login
POST {{baseUrl}}/api/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

email=some@email.com&password=aaaa2
```

Sample Response Body:

```json
{
  "success": true,
  "data": {
    "token": "16|AsNzBwAN1LhF6hog4ALWrzu4b76GtGLs9aWpxBDQ0b8be49a",
    "name": "John5"
  },
  "message": "User login successfully."
}
```

### GET List of Products

Now, pass in the Bearer token from the JSON's `Data.Token`

```http
GET {{baseUrl}}/api/products HTTP/1.1
Authorization: Bearer {{login.response.body.$.data.token}}
```

Sample JSON Response:

```json
{
  "success": true,
  "data": [
    {
      "id": 2,
      "name": "Ball",
      "detail": "Its round.",
      "created_at": "08\/05\/2024",
      "updated_at": "08\/05\/2024"
    }
  ],
  "message": "Products retrieved successfully."
}
```

**Comment by khadiza21** [comment]
in resquest.rest in vscode . 
POST http://localhost:3000/signUp 

Content-Type: application/json

{ 
    "fullname":" BKl kHadiza "
}


and in the index.js file, I used the middleware ---> server.use(express.json())
server.post("/signUp", (req,res)=>{

  res.json(req.body);

})

After sending a request it shows a 200 status and an empty object. The full name(any) Property I didn't get

**Comment by khadiza21** [comment]
solved

**Comment by khadiza21** [comment]
solved
