### ISSUE TITLE
Is it possible to save the binary response of a web service as a file

### ISSUE THREAD

**Issue by opensas** [Huachao/vscode-restclient#244]
In curl I can do the following:

```
curl -X GET -H "Authorization: Bearer [...]"  \
'http://localhost:5000/api/archivo_data/1?_download=true' --output out.jpg
```

And curl saves the file out.jpg to the current directory

Can I achieve the same with restclient?

**Comment by Huachao** [comment]
After you received the response of corresponding request, in the response preview panel, you can click the ` Save Response Body` icon in the upper right corner.
