### ISSUE TITLE
environment cannot be selected after opening workspace via File > Open Recent

### ISSUE THREAD

**Issue by tom-thorne** [Huachao/vscode-restclient#245]
- VSCode Version: 1.26.1
- OS Version: macOd 10.13.6 (17G65)
- REST Client Version: 0.19.1

Steps to Reproduce:

1. Setup a workspace with REST environments `rest-client.environmentVariables` saved in 'Folder Settings'

```
{
  "rest-client.environmentVariables": {
    "EnvA": {
      "testvar": "enva"
    },
    "EnvB": {
      "testvar": "envb"
    }
}
```

2. Select an environment via bottom right status bar environment picker
3. Save and close vs code workspace
4. Reopen workspace via File > Open Recent
5. Click on environment bottom right status bar environment picker

-> No environments are listed in the drop down

Expected result: EnvA, EnvB are listed and can be selected

**Comment by Huachao** [comment]
@tom-thorne what is *Folder Settings*, can you also provide me a screenshot and the workspace structure if convenient?

**Comment by Huachao** [comment]
@tom-thorne solved, and I will publish this fix in the next release.

**Comment by Huachao** [comment]
@tom-thorne you can try the latest version 0.20.0 to verify this.

**Comment by tom-thorne** [comment]
@Huachao it now works as expected provided an http file has focus
