### ISSUE TITLE
socks5 proxy error

### ISSUE THREAD

**Issue by QianChenglong** [Huachao/vscode-restclient#249]
版本: 1.27.2 (user setup)
提交: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
日期: 2018-09-12T16:17:45.060Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
架构: x64

![image](https://user-images.githubusercontent.com/1881126/45530150-d6130a80-b81b-11e8-81ec-95ffc81af0d9.png)

**Comment by Huachao** [comment]
@QianChenglong actually this is a limitation from [VSCode](https://code.visualstudio.com/docs/setup/network#_authenticated-proxies). BTW, even the VSCode supports user to provide the socks proxy, or my extension will read the environment variable in the future, I still need some extra work to make my extension support the SOCKS5 proxy.
