### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by mad-mike** [Huachao/vscode-restclient#25]
- VSCode Version: 1.3.1
- OS Version: Windows 10
- REST Client Version: 0.6.2

Steps to Reproduce:
1. Enter a network environment where an HTTP proxy is required
2. Make the proxy settings in VSCode's settings.json ("http.proxy": "http://proxy:8080")
3. Try to make an HTTP request, e.g. 'GET http://example.org/'
4. There is an error message that says "Error: Error: connect ETIMEDOUT ..."

Given the fact that I can't find any discussions or related code in this project I'm assuming the REST Client currently does not support HTTP proxies.

**Comment by Huachao** [comment]
@mad-mike , currently we really don't support this, and will implement this later. And it's very welcome that you can contribute to this code. :smile:
