### ISSUE TITLE
Support environment variables when resolving values in settings files

### ISSUE THREAD

**Issue by tom-thorne** [Huachao/vscode-restclient#252]
It would be great to be able to write environment variables so that they can resolve local machine environment variables.  A typical use case would be for secret keys that we don't want to commit to source control.

For example: define shell environment variable

in `.bashrc` or similar on windows...

```
export SECRET_TOKEN=xxxxxxxxxxxxx
```

Then refer to it in settings block for REST Client

```
{
    "rest-client.environmentVariables": {

        "$shared" : {
            "mySecretToken": "${env:SECRET_TOKEN}",
        },
```

**Comment by mtnrbq** [comment]
@tom-thorne , @Huachao  happy for some feedback on #366, my PR to address local environment access from vscode-restclient (incorporating text from this issue in the doco  :wink:)

**Comment by Huachao** [comment]
@tom-thorne @michelemauro @shadoll @spitlo with the fantastic patch from @mtnrbq we can try this feature in next release, thanks @mtnrbq 

@mtnrbq I have fixed the #369 , don't worry

**Comment by Huachao** [comment]
@tom-thorne @michelemauro @shadoll @spitlo  you can experience this feature in the latest version 0.22.0

**Comment by borekb** [comment]
For anyone trying this, it's necessary to exit VSCode and start it again after each change of an environment variable – "Reload Window" is not enough to pick the new value up!
