### ISSUE TITLE
Does this plugin support changing color of response?

### ISSUE THREAD

**Issue by kucw** [Huachao/vscode-restclient#254]
Hi, I'm using the default light theme of vscode. Unfortunately, the color of response is too bright under this theme. Dose rest client support to change highlighting color of response? Thanks!
![image](https://user-images.githubusercontent.com/10337091/45821328-7b961480-bd1b-11e8-86b1-d93a74e18126.png)

**Comment by Huachao** [comment]
@kucw, it's not supported, I will consider let user to provide its own style

**Comment by kucw** [comment]
Thanks. By the way, can you just tell me where is the location that the color setting is? Maybe I can edit the setting by myself without going through vscode now.

**Comment by Huachao** [comment]
@kucw maybe you can find the *css* file in location like `~/.vscode/extensions/humao.rest-client-0.19.1/styles/rest-client.css`

**Comment by kucw** [comment]
Thanks. I've modified the default css and the result is under below.
Here is the css file, if you like it, you can take it. (remember to change .txt to .css, Github limits the filename extension of upload file)
[kucw-rest-client.txt](https://github.com/Huachao/vscode-restclient/files/2403767/kucw-rest-client.txt)

![](https://user-images.githubusercontent.com/10337091/45858092-50004200-bd8e-11e8-8695-74d8ccb12860.png)

**Comment by Huachao** [comment]
@kucw nice, I will reference your css and check it if fits for my extension, 👍
