### ISSUE TITLE
"Accept-Encoding: gzip, deflate" added even if not configured as default

### ISSUE THREAD

**Issue by manchas** [Huachao/vscode-restclient#256]
- VSCode Version: 1.27.2 x64
- OS Version: Win 10
- REST Client Version: 1.19.1

Steps to Reproduce:

1. Any get, for example: GET http://localhost:5000/unitconversion (nothing else)
2. Activate  exchange view for responses: rest-client.previewOption
3. Send request
On the response view you get:
GET http://localhost:5000/unitconversion HTTP/1.1
User-Agent: vscode-restclient
Accept-Encoding: gzip, deflate

HTTP/1.1 200 OK
Date: Fri, 21 Sep 2018 16:57:56 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
.....

The first header sent (User-Agent: vscode-restclient) is configured on default headers, so far so good... BUT where did the "Accept-Encoding: gzip, deflate header" comes from?  
It shouldn't be appended unless I did it explicitly on the request OR I configured it on default headers... but in this case none of the abobe happened, and the header is still appended.

BTW. the header is effectively sent, in my server (localhost:5000) I receive it in the request headers...

**Comment by Huachao** [comment]
@manchas nice catch, and it's actually injected and sent by the underlying request library. And does this behavior broke your server side?

**Comment by manchas** [comment]
@Huachao it doesn't broke my server per se, but it does broke my tests, cause I'm specifically testing how does my server behaves with and without the Accept-Encoding header in the request, and right now that's imposible to do with rest client (because of this issue), so I have to test that behavior of my server with other tools (fiddler, postman, etc) which is not desirable (I love restclient!!).
I still believe this is a bug, because the client is doing something unexpected, that you as a user, can't control. It always inserts that header, whether you want it/need it or not... 
IMHO It should do exactly what you told it to do (either by specifying the header by hand or by the defaultHeaders option) , and nothing else.

**Comment by Huachao** [comment]
@manchas make sense, I have updated the code to unset the `gzip` setting.

**Comment by Huachao** [comment]
@manchas you can try the latest version 0.20.0 to verify this fix.

**Comment by manchas** [comment]
Verified!!
Great work, thanks.
