### ISSUE TITLE
Activation time is too slow

### ISSUE THREAD

**Issue by mtxr** [Huachao/vscode-restclient#257]
Take a look..

![image](https://user-images.githubusercontent.com/707561/45896291-0aea0900-bdaa-11e8-9cf1-2d3d13d647b0.png)

- Extension Name: rest-client
- Extension Version: 0.19.1
- OS Version: Linux x64 4.4.0-134-generic
- VSCode version: 1.28.0-insider

 We have written the needed data into your clipboard. Please paste:

**Comment by Huachao** [comment]
@mtxr what is the size of your `http` file, and does the extension activated very slow when you open the `http` file each time, like what's the delay from opening the file and seeing the `Send Request` text?

**Comment by mtxr** [comment]
I don't remember exactly which file I opened that took 36k ms, but I opened a file like this one below 5 times, activation time was always around 13,5k ms.

```http
@url = *********
@username = ********
@password = *******

###
# @name login
POST {{url}}/auth/password HTTP/1.1
Accept: application/json, text/plain, */*
Content-Type: application/json

{
  "username":"********",
  "password":"**********"
}

###
# @name query
POST {{url}}/application/query HTTP/1.1
Accept: application/json, text/plain, */*
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.id}}

{JSON DATA}

```

**Comment by Huachao** [comment]
@mtxr Sorry for the late reply, I'd like to share with you some progress on this issue. I tested your http file, the average activation time was around **5s**. Althought the time seems much smaller than yours, I also think this is a bit unacceptable. I dive into my code, and add some measuring code. I found that the most time-cosing steps are `require` some 3rd party packages on startup, like `request`, `highlight.js` and `adal-node`, as weel as some global initializtion work like preparing the telemetry client. So I have some ideas about this perf issue:
1. Defer some packages to be loaded to the actual required time (using techniques like dynamic import)
2. Make the required 3rd party packages in a small list
3. Put some global objects initialization tasks to runtime

**Comment by pke** [comment]
so disabling telemetry (which should be a good citizen and be OFF by default btw) could already improve the performance now?

**Comment by Huachao** [comment]
@mtxr @pke I have used the Webpack technique in my extension, and it decreases the activation time to less than **1.5s**.

**Comment by Huachao** [comment]
@mtxr @pke you can try the latest version 0.21.0 to verify this performance issue fix.

**Comment by pke** [comment]
@Huachao how can I get the performance starts for extensions?

**Comment by Huachao** [comment]
@pke maybe a built-in command named like _Show Running Extensions_ of VSCode

**Comment by pke** [comment]
@Huachao 642ms now. Well done!

**Comment by mtxr** [comment]
@Huachao thank you very much! Great job!
