### ISSUE TITLE
Brackets in application/x-www-form-urlencoded encoded incorrectly

### ISSUE THREAD

**Issue by jenan-stripe** [Huachao/vscode-restclient#259]
- VSCode Version: 1.27.2
- OS Version: macOS 10.13.6
- REST Client Version: 0.19.1

Steps to Reproduce:

1. Create `example.rest`:
```
POST https://api.example.com/
Content-Type: application/x-www-form-urlencoded

foo[bar]=baz
```

2. Use "Rest Client: Copy Request as cURL" command.

Expected:

```
curl --request POST \
  --url https://api.example.com/ \
  --header 'content-type: application/x-www-form-urlencoded' \
  --data foo[bar]=baz
```

Found:
```
curl --request POST \
  --url https://api.example.com/ \
  --header 'content-type: application/x-www-form-urlencoded' \
  --data foo%5Bbar%5D=baz
```

`rest-client.formParamEncodingStrategy` seems to have no effect on this behavior.

**Comment by Huachao** [comment]
@jenan-stripe I don't agree with the expected result for `--data` parameter, since `data` argument should be supplied with the already well-encoded value. See [URL encoding](https://ec.haxx.se/http-post.html), so I think current behavior is right.

**Comment by jenan-stripe** [comment]
Ah yes! My mistake.
