### ISSUE TITLE
Change in login step not reflected on subsequent calls

### ISSUE THREAD

**Issue by pke** [Huachao/vscode-restclient#261]
- VSCode Version: 1.27.2 (system setup)
Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
Date: 2018-09-12T16:17:45.060Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

- OS Version: Windows 8.1
- REST Client Version: 0.19.1

Steps to Reproduce:

Create a .http file 2 requests. One for login and the other one to use the login response. When changing the login request, the second request does not recognise this and still uses the old/previous values.

```http
###

# @name login
POST {{host}}/login
Content-Type: application/x-www-form-urlencoded

name=name&password=1234567


###

# @name getBookings
GET {{host}}/bookings
Authorization: {{login.response.headers.AuthToken}}
```

The first run yield the expected result.
Now change the name in the login request to something else, even a non-existing one.
The response from the second request does not change. It seems the `AuthToken` is cached. When the login request is manually executed with wrong credentials, the second request also fails then with wrong credentials.

Cookies are not set and not preserved.

**Comment by Huachao** [comment]
@pke after changing the first http request, you need to sending the request again to refresh the response of `login` request. If not, the second request will still use the last cached response which I think it makes sense.

**Comment by pke** [comment]
Really? Did that makes sense? ;)
I think it could be helpful, the current flow is confusing to me. Maybe we can ask the community?

**Comment by pke** [comment]
So I just ran into this again, where I just wanted to run the second request and expected the first request to run again (because a variable depends on it).

What is the verdict here? Could this still be made possible (maybe via config: "re-evaluate requests if used variables depend on previous responses")?
