### ISSUE TITLE
Question: How to POST key/value?

### ISSUE THREAD

**Issue by Mark-Maslar** [Huachao/vscode-restclient#262]
In Postman, I can successfully post this key/value 
key: body
value: {"address": "1H6mbMCSsJ8CaeUcPxsg2g6sprQ9wzfEiS"}

How do I do the equivalent in Rest Client?
I try this, 
POST http://localhost:8000/requestValidation/ HTTP/1.1

Content-Type: application/text/plain

{"address": "someaddress"}

but get this response
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "Invalid request payload JSON format"
}

I tried Content-Type: application/json, but that produces the same result.

I'd appreciate any pointers! It's not an issue with the extension; just my format.

**Comment by Huachao** [comment]
@Mark-Maslar can you show me a snapshot of your request in body, actually I don't know whether you want to send a JSON request or a `x-www-form-urlencoded` request?

**Comment by Mark-Maslar** [comment]
![image](https://user-images.githubusercontent.com/41172082/46576996-00ce2a00-c9a8-11e8-9b4a-fd961ae236f3.png)
This is a snapshot of my Postman setup. I send the body as Text

**Comment by Huachao** [comment]
@Mark-Maslar in your case, the `Content-Type` of your request should be `multipart/form-data`, and your request should follow the `multipart/form-data` request format. One example looks like following:
```http
POST http://localhost:8000/requestVaildation/ HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="body"

{"address": "1H6mb"}
------WebKitFormBoundary7MA4YWxkTrZu0gW--
```
