### ISSUE TITLE
Broken works with certificates

### ISSUE THREAD

**Issue by maxtar** [Huachao/vscode-restclient#263]
- VSCode Version: 1.27.2 (system setup)
  - Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
  -  Date: 2018-09-12T16:17:45.060Z
  - Electron: 2.0.7
  - Chrome: 61.0.3163.100
  - Node.js: 8.9.3
  - V8: 6.1.534.41
  - Architecture: x64
- REST Client Version: 0.20.0 (2018/10/8)
- OS Version: Windows 10.

Steps to Reproduce:
1. Set settings in "rest-client.certificates" like  
```json
 "10.0.0.3": {
            "pfx": "d:\\Документы\\Сертиифкат.pfx",
            "passphrase": "password"
        },
```
2. Execute the request like this:
```http
GET https://10.0.0.3/api/v1.0/user/1/state HTTP/1.1
Accept: application/json
```
3. Got error `Hostname/IP doesn't match certificate's altnames: "IP: 10.0.0.3 is not in the cert's list: "`

If instead of IP in `rest-client.certificates` set hostname, after execute appearing the following error message: `unable to get local issuer certificate`.

Before upgrading to 0.20.0 (2018/10/8) version all have working ok,

**Comment by Huachao** [comment]
@maxtar nice catch, I will prepare a hot fix tomorrow, sorry for the inconvenience.

**Comment by maxtar** [comment]
@Huachao thanx, this is critical for us. :)

**Comment by Huachao** [comment]
Before that, you may have to download the previous versions on https://github.com/Huachao/vscode-restclient/releases page.

**Comment by maxtar** [comment]
@Huachao Thank you!

**Comment by dakaraphi** [comment]
@Huachao FYI, This may be the same problem.  I'm not using any certificates file and I can't make any request as I get an error "certificate expired".

**Comment by Huachao** [comment]
Should be same root cause

**Comment by Huachao** [comment]
@maxtar @dakaraphi you can try the latest version 0.20.1 to verify. Thanks

**Comment by dakaraphi** [comment]
@Huachao it is fixed for me. thx!

**Comment by maxtar** [comment]
@Huachao me too. Thank you.
