### ISSUE TITLE
Hole Body includes apostrophe, breaks further requests

### ISSUE THREAD

**Issue by pungggi** [Huachao/vscode-restclient#266]
- VSCode Version: 1.28
- OS Version: Windows 10
- REST Client Version: latest

![grafik](https://user-images.githubusercontent.com/5635709/46744340-40985880-ccab-11e8-8151-cb5b1b140536.png)

I am using the new great feature "Request Variables".
Look at the image.

I need the body but without trailing apostrophe because this breaks subsequent uses..

**Comment by pungggi** [comment]
Example Response:
`HTTP/1.1 200 OK
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; charset=utf-8
Expires: -1
Date: Wed, 10 Oct 2018 14:45:08 GMT
Content-Length: 315

"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiaW5mb0BhbWFubmluZm9ybWF0aWsuY2giLCJleHAiOiIxNTM5MTg0NTA4IiwibmJmIjoiMTUzOTE4MjcwOCIsIlVzZXJJZCI6IjUwMDE4Yjk1LWUxM2MtNGE0My04OTQ0LWYxNWUxZjkyMjg1ZSJ9.disUIIcm6bVT43VRx9WPL1iB5_9UTBBRhH9uPdRncvw"`

**Comment by Huachao** [comment]
@pungggi  nice catch, this JSON response body of `string` value is a special case for JSONPath, some libraries can support syntax like `$` to parse in this case, for request variable syntax it will go like `{{tokenResponse.response.body.$}}`. However, the library I use doesn't handle this weill, I will try to search a better one. And the way you use here `{{tokenResponse.response.body.*}}`, for `*` I will not do any pasring logic, just return the body string I received.

**Comment by pungggi** [comment]
Hi @Huachao  Any news on this?

**Comment by Huachao** [comment]
@pungggi @jerkovicl I have fixed the issue by replacing the original `jsonpath` package, and you can reference the string value with json path `$`, as for your case, the full variable value should be `{{tokenResponse.response.body.$}}`

**Comment by Huachao** [comment]
@pungggi @jerkovicl you can try this in latest version 0.22.0

**Comment by pungggi** [comment]
Thank you! Works.
