### ISSUE TITLE
Comments are still integrated to the request

### ISSUE THREAD

**Issue by StephD** [Huachao/vscode-restclient#28]
- VSCode Version: 1.4
- OS Version: Win 7
- REST Client Version: 0.7

Comments are integrated in the request.
- Because you need a blank line between Content-type and Body (in POST request), if I put a comment instead of this blank line, the request will be not send.
- If I put comment into the JSON body, my server will get that comment as a JSON form and a malformed JSON occur.

![2016-08-08 17_18_18-mingw64__c_var_www__files_front_trace](https://cloud.githubusercontent.com/assets/1171858/17484855/25e9ca54-5d8c-11e6-8266-36d42555284d.png)
Right side is my server log.

Proposition : Replace the comment with a blank line. BUT in a JSON form, blank line will generate a malformed JSON.

**Comment by Huachao** [comment]
@StephD I'd like to just ignore comment lines and won't treat them as blank lines. And the `#test` is sent to server is due to my bug.

**Comment by Huachao** [comment]
@StephD you can verify this in latest version 0.7.1. Thanks

**Comment by StephD** [comment]
Works well for the example I gave you.
