### ISSUE TITLE
Plugin is decoding response urls unexpectedly causing issues

### ISSUE THREAD

**Issue by gevorggalstyan** [Huachao/vscode-restclient#280]
Issue Type: <b>Bug</b>

Some tools like AWS S3 may generate signed URLs that include encoded URI Components and authorization strings. REST Client decodes all that causing authorization problems.

I have created a RunKit Endpoint `https://rest-client-bug-report-k73tkq2a9l9i.runkit.sh` to test against

If you make a request from a browser you will get

```json
{
"url": "https://test.com/download/file.zip?X-Api-Key=KEY%2F%2F%2F%2F%2FKey"
}
```

But if you make the same request from REST Client with

```http
GET https://untitled-k73tkq2a9l9i.runkit.sh/
```

you will get

```json
{"url":"https://test.com/download/file.zip?X-Api-Key=KEY/////Key"}
```

Please notice that `X-Api-Key=KEY%2F%2F%2F%2F%2FKey` has been converted to `X-Api-Key=KEY/////Key` which is not the correct key on the server.

I did not find any configuration to enable/disable this behavior, which leads to the conclusion that there is a bug in the plugin.

Extension version: 0.20.2
VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by Huachao** [comment]
@gevorggalstyan nice catch, I have fixed the issue and will publish this fix in next release.

**Comment by Huachao** [comment]
@gevorggalstyan you can try the latest version 0.20.3 to verify

**Comment by gevorggalstyan** [comment]
@Huachao That was it. Thanks for the fix.
