### ISSUE TITLE
Handle compressed responses

### ISSUE THREAD

**Issue by karamazov1** [Huachao/vscode-restclient#282]
- VSCode Version: 1.28.2
- OS Version: Win 10
- REST Client Version: 0.20.2

Does this extension handle compressed responses? When I tried, I get "The content type of response is application/json, while response body is not a valid json string"

**Comment by Huachao** [comment]
@karamazov1 Yes, it can handle, could you please provide the URL you're testing?

**Comment by karamazov1** [comment]
@Huachao this is an internal api. I know it worked in the past but also know microsoft also enabled compression on their responses recently.

GET https://xxxxxxx.azure-api.net/product/products/213140 HTTP/1.1
Product-Subscription-Key: xxxxxxxxxxxxxxxxxxxxxxxxx
Host: xxxxxxxxxxx.azure-api.net
Accept-Encoding: gzip
Content-Type: application/json; charset=utf-8

**Comment by Huachao** [comment]
@Can you confirm with other tools that the response is a valid JSON

**Comment by karamazov1** [comment]
I tried this same request using postman and the proper json is rendered. Not sure what the difference could be, no differences at the request level that I can see.

Thanks for your responses, this is not critical by any means and I was just curious if compressed responses were handled as this same request was working before and I'm not sure if an extension update could be the culprit or a change on the back end endpoint broke my tests.

**Comment by Huachao** [comment]
What's the content encoding header of the response

**Comment by Huachao** [comment]
@karamazov1 thanks, I can repro this issue, I will fix it ASAP.

**Comment by Huachao** [comment]
@karamazov1 I have fixed the bug and will publish this fix in next release.

**Comment by offero** [comment]
Just ran into this issue myself also. When is the next release?

**Comment by Huachao** [comment]
@karamazov1 @offero I have published the new release 0.20.3, and you can try the new version to verify

**Comment by karamazov1** [comment]
This is working for me now. Thanks!
