### ISSUE TITLE
Extend cookies handling

### ISSUE THREAD

**Issue by gigazet** [Huachao/vscode-restclient#283]
Now it's possible to remember cookies with rest-client.rememberCookiesForSubsequentRequests, it's nice.

It would be good to add a commands to clear all cookies (for specific host, or just all globally) manually and inside REST script.

**Comment by ozh555** [comment]
agree,I need clear cookies .

delete cookie.json too trouble.

**Comment by Huachao** [comment]
@ozh555 @gigazet I will implement a command to clear all/given host to cookies

**Comment by tsteckenborn** [comment]
Has there been progress on that feature?

**Comment by nightknighto** [comment]
How to use this??
