### ISSUE TITLE
Display cookie for the current session

### ISSUE THREAD

**Issue by davisskchan** [Huachao/vscode-restclient#284]
Is it possible to display the cookies received from a request for the current session?

**Comment by davisskchan** [comment]
Thanks for the response.

I see the set-cookie header.  But somehow it only shows the last one when I am expecting 2 cookies.
(It shows up 2 when I use Postman for the same request.)

**Comment by Huachao** [comment]
@davisskchan can you check if you have really received two cookies when you set `rest-client.rememberCookiesForSubsequentRequests` to `false`. In this case, my extension won't use any already saved cookies. If still not working, please provide me the request if available. Sorry for the late reply.

**Comment by davisskchan** [comment]
Part of the cookie.json file

  "fioridev1.dev.xxx.ca": {
    "/": {
      "sap-usercontext": {
        "key": "sap-usercontext",
        "value": "sap-client=200",
        "domain": "fioridev1.dev.xxx.ca",
        "path": "/",
        "hostOnly": true,
        "creation": "2018-11-01T15:19:26.431Z",
        "lastAccessed": "2018-11-06T15:02:28.392Z"
      },
      "SAP_SESSIONID_DG2_200": {
        "key": "SAP_SESSIONID_DG2_200",
        "value": "fueFT0gS3n7c1Q9TVPqGB_paYDfh1BHoi6EAUFapLew%3d",
        "domain": "fioridev1.dev.xxx.ca",
        "path": "/",
        "hostOnly": true,
        "creation": "2018-11-01T15:19:26.437Z",
        "lastAccessed": "2018-11-06T15:02:28.710Z"
      }
    }
  }

And the header from the response  -

HTTP/1.1 200 OK
set-cookie: SAP_SESSIONID_DG2_200=4lNz_VeQApKcCcT6qlZMzM2z3SfioxHoi0sAUFapLew%3d; path=/
content-type: application/atomsvc+xml
content-length: 879
x-csrf-token: iKzuppT56J219ZkvPZoSWQ==
sap-metadata-last-modified: Tue, 06 Nov 2018 15:50:05 GMT
last-modified: Tue, 06 Nov 2018 15:50:05 GMT
cache-control: no-store, no-cache, must-revalidate, max-age=0, post-check=0, pre-check=0
pragma: no-cache
expires: Tue, 03 Jul 2001 06:00:00 GMT
dataserviceversion: 2.0
sap-processing-info: ODataBEP=,crp=,st=,MedCacheHub=SHM,codeployed=,softstate=
sap-perf-fesrec: 53306.000000
content-encoding: gzip

**Comment by Huachao** [comment]
@davisskchan do you confirm the setting `rest-client.rememberCookiesForSubsequentRequests` to `false`

**Comment by davisskchan** [comment]
When the setting is false, I see 2 cookies.

set-cookie: sap-usercontext=sap-client=200; path=/,SAP_SESSIONID_DG2_200=HEjkWFAw_8FQGo2NrLSwMrWwX5XjaRHoiBEAUFapLew%3d; path=/

**Comment by Huachao** [comment]
So that means if you already had the sap-usercontext cookie, and carrying this cookie when sending new request, your server won't return this cookie. This seems making sense for me. So this is not a bug, only first time you would receive 2 cookies, after that only one

**Comment by davisskchan** [comment]
Not sure if I make the scenario clear.

I freshly start the VSCode and send ONE request.  I only see 1 cookie in the set-cookie header.  But I see 2 cookies in the cookie.json.

I haven't sent any 2nd request yet.

**Comment by Huachao** [comment]
You can manually remove the two cookies from the cookie.json, and send the request again, and you should see two

**Comment by zzc-tongji** [comment]
By the way, how to remove cookies that have already set? Where is `cookie.json`?

**Comment by CatsMiaow** [comment]
@zzc-tongji 
https://github.com/Huachao/vscode-restclient/blob/d7420d73d2dc180cf9bb0beb4b84fbcbbede6d4f/src/utils/userDataManager.ts#L8

In my case it was the `/Users/myusername/.rest-client/cookie.json` path.

**Comment by hilman23-dev** [comment]
how i can get the second cookies ?

i want get the refresh_token

set-cookie: access_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NjEzOWQ2NzRhYzM3MGViMTRjOWMzOCIsInJvbGUiOiJVc2VyIiwiaWF0IjoxNzM1ODc1NDQxLCJleHAiOjE3MzU4NzU2ODF9.fGYA6OMdS9k7U-Rq62nfLRCAeRUEufb0hdI9HvEgAlZ85m93hfIy4gd8My2Wjv9J4JuthyrNXqonXCcCH-O0g3Km5bVyYG9c9T36i2gnGVKO3nh4jgBRgW4u6wwApvu7WGHf9HWsZ5_E3iAHjcsCp4_xVNN6EWv_BstRpKkdtHbTQBBYv9ScadTplIt7W7hm6nXusLDp7GlGYm7eUkAFgbFm4fvd55Zc9gabWA; Max-Age=240000; Path=/; HttpOnly; Secure; SameSite=None,refresh_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NjEzOWQ2NzRhYzM3MGViMTRjOWMzOCIsInJvbGUiOiJVc2VyIiwiaWF0IjoxNzM1ODc1NDQxLCJleHAiOjE3Mzg0Njc0NDF9.liovD6Q4o77XdojwR61U3OW4sDI93_Od-dBXK6Xtf9I4usuBji_QVtYCpLbXgJXVBabr0kGl4RFDCi-DBnaPcubXJS4Ow8X6UMd2Q7AKJ-izqN3CtFAu41iI6Lcd-8q5o_7M1Uo1HIxZxM-jNIsFHmT7y4ZwLXHo51ywgQHp8yoczeyFb12qfGXkGatWsV2BJ6SjU-nzS0zu2w-WOSMLyeMe4YJ-hHiTl391A; Max-Age=2592000; Path=/; HttpOnly; Secure; SameSite=None

**Comment by saeid-elio** [comment]
> @davisskchan do you confirm the setting rest-client.rememberCookiesForSubsequentRequests to false

This solved a problem for me when rest client stopped sending my session cookie to server. After I set this setting to false things worked again. Why on earth is `rememberCookiesForSubsequentRequests` true by default? This means if you sent a request when you were logged out and then you login and send a new request with new session in Cookie header it will be ignored and you are considered still logged out. Or am I understanding something wrong?
