### ISSUE TITLE
Request not redirected even thought is set to true

### ISSUE THREAD

**Issue by defectus** [Huachao/vscode-restclient#285]
- VSCode Version:1.28.2
- OS Version: Ubuntu 18.04
- REST Client Version: 0.20.3

Steps to Reproduce:

1. connect to server that returns `HTTP/307`
2. rest-client should follow it (as per settings), instead it returns the redirect response

```
HTTP/1.1 307 Temporary Redirect
Server: nginx/1.10.3 (Ubuntu)
Date: Fri, 02 Nov 2018 09:38:16 GMT
Content-Length: 0
Connection: keep-alive
Location: https://api.xxxxxxxxxxxxx.cz
Strict-Transport-Security: max-age=15768000
```

Just to be sure, the `Follow HTTP 3xx responses as redirects` option is ON.

**Comment by Huachao** [comment]
@defectus What's the request method of your request, and can you show me the request url?

**Comment by Huachao** [comment]
@defectus If it's a non-GET method, I have fixed the issue

**Comment by defectus** [comment]
This is a private API so I can't give you the URL to play with, but its something like `POST https://api.stage.proxima.o2.cz:443/xxxxx HTTP/1.1`. That API resturns the `307` response as shown above but I'd expect it to actually follow the redirect and do `POST https://api.stage.gcloud.proxima.o2.cz/xxxx HTTP/1.1`.

**Comment by Huachao** [comment]
@defectus you can try the latest version 0.20.4 to verify.

**Comment by defectus** [comment]
All seem to be OK. Many thanks!

**Comment by Huachao** [comment]
@tbattiva this is related to the bug #948
