### ISSUE TITLE
Receiving "Running the contributed command:'rest-client.request' failed."

### ISSUE THREAD

**Issue by jchomarat** [Huachao/vscode-restclient#29]
- VSCode Version: 1.4.0
- OS Version: Window 10 anniversary update
- REST Client Version: 0.7.1

Steps to Reproduce:

1. Open any request file
2. Execute it (ctrl - alt R)

Hello, 

I really love your extension, however, since the latest windows 10 big update (anniversary), it does not work anymore

I tried reinstalling the extension, without any more success.
Is there a way to get logs for you?

Thanks for your help

**Comment by Huachao** [comment]
@jchomarat Thankd for your reporting. Do you use proxy in your msahine

**Comment by jchomarat** [comment]
Thanks for your answer. No proxy configured on my machine!.
 I suspect that windows 10 anniversary update broke something - but i did not find anything on the web ...

**Comment by jchomarat** [comment]
Hi again, I found out how to get more info on this:

![image](https://cloud.githubusercontent.com/assets/6317287/17703882/81afe43e-63d3-11e6-8dac-dd6dca998676.png)

**Comment by Huachao** [comment]
@jchomarat I can't repro on my windows 10 anniversary update machine

**Comment by jchomarat** [comment]
Ok, thanks for your help. I've deinstalled vscode + plugins, reinstalled everything and same thing. I'm gonna dig and open a vscode ticket.

**Comment by Huachao** [comment]
@jchomarat ok, I will close the issue now, and you still have questions, you can reopen it freely.

**Comment by jchomarat** [comment]
Hello @Huachao - just as follow up, with the rest-client version 0.7.3, the error I received was more epxlicit: cookies.json was corrupted (I was conviced I removed all the files for my tests).
Anyway, everything is ok now. Thanks!

**Comment by Huachao** [comment]
@jchomarat you still met the same error in new version? If so I'd like to reopen the issue, by now, you could just add the setting `"rest-client.rememberCookiesForSubsequentRequests":  false`

**Comment by surbhijain18** [comment]
I get this warning, command 'rest-client.request' not found
