### ISSUE TITLE
Option to disable codelens/links

### ISSUE THREAD

**Issue by ccidral** [Huachao/vscode-restclient#295]
It would be great to have a configuration option for disabling/hiding the codelens/links, eg: variable references, the "Send Request" link, etc. I particularly find them annoying, so I like to disable them wherever possible.

**Comment by Huachao** [comment]
@ccidral @xtuer I have implemented this feature by adding two new settings to control *Send Request* and *Variable References* codelens with `rest-client.enableSendRequestCodeLens` and `rest-client.enableCustomVariableReferencesCodeLens`.

**Comment by ccidral** [comment]
@Huachao This is awesome, thank you so much!
