### ISSUE TITLE
Ctrl + click should evaluate variables

### ISSUE THREAD

**Issue by danielwagn3r** [Huachao/vscode-restclient#299]
When hovering over an GET Requrest Ctrl + Click (follow link) should évaluate the request variables used.

**Comment by Huachao** [comment]
@dakaraphi `Ctrl` + `Click` the url is not a function of my extension, it's a built-in behavior of VSCode which will open the url in the browser directly. And currently I have no plan to overwrite this behavior, in my extension, you can click the `Send Request` link above each request or use shortcut `Ctrl+Alt+R`. For more usage information, you can check the `README` [here](https://github.com/Huachao/vscode-restclient/blob/master/README.md)
