### ISSUE TITLE
Support Curl -> RFC 2616 conversion

### ISSUE THREAD

**Issue by gpasq** [Huachao/vscode-restclient#3]
With Postman, I can find a service call in Chrome debuggers network tab, copy the call as curl, import it into Postman, and my method, url, headers and body are all setup for me.  HUGE time saver, especially when my QA people need me to reproduce an issue... they just send me that captured curl script.

Be nice if I could paste the same Curl into Restclient and have it generate the RFC 2616 format.

**Comment by Huachao** [comment]
@gpasq, I have added the capability to directly run curl request in rest client extension. By now, I haven't implemented the converter to transform curl request to RFC 2616 request, I think it's enough now. And if you really want to know the RFC 2616 format, one way is that after running the curl request in my extension, use the history feature to get the request, and it will display the request in RFC 2616 format
