### ISSUE TITLE
Expand/collapse JSON/XML response body

### ISSUE THREAD

**Issue by suresh-deevi** [Huachao/vscode-restclient#30]
Format result based on the content type so it is easy to identify components of response.
It would be nice to have expand collapse at node level like in most XML, JSON viewers.

**Comment by Huachao** [comment]
@suresh-deevi thanks for your suggestion, I'd like to update your issue title to expand/collapse JSON/XML response body. Since we already have the pretty print feature for a long time

**Comment by StephD** [comment]
I've added this enhancement into [https://github.com/Huachao/vscode-restclient/issues/12](url) weeks ago. I think this is the same functionality so it's duplicate.

**Comment by Huachao** [comment]
Duplicated with #12
