### ISSUE TITLE
Copy result body

### ISSUE THREAD

**Issue by asmith3006** [Huachao/vscode-restclient#300]
Along with "Save Response Body" in the top bar a "Copy Response Body" would be really helpful.

**Comment by viktor-evdokimov** [comment]
So this is huge. copying result body was working for me and stopped working lately, really ruined my workflow =(

**Comment by Huachao** [comment]
@viktor-evdokimov I haven't implemented this feature, what do you mean `was working for you`?

**Comment by viktor-evdokimov** [comment]
Up to some point i was able to select text from result tab and copy it to clipboard, and that no longer works

**Comment by viktor-evdokimov** [comment]
Created PR for this #317

**Comment by Huachao** [comment]
@viktor-evdokimov what's your VSCode and my extension versions respectively? Since I can't repro this on my machine.

**Comment by viktor-evdokimov** [comment]
I am on insider build of vscode and latest version of the plugin.

**Comment by Huachao** [comment]
@viktor-evdokimov this is an known issue of Microsoft/vscode#65452, I will keep track of it. BTW, I add a comment in your PR, please help to resolve it when available. Thanks in advance.

**Comment by Huachao** [comment]
@asmith3006 @Baoyx007 @pranayrauthu @michelemauro Thank for the help of @viktor-evdokimov , we have fixed this issue and will publish this feature in next release. And @viktor-evdokimov I will keep track of the issue you've mentioned.
