### ISSUE TITLE
Collapse the body object.

### ISSUE THREAD

**Issue by OhYee** [Huachao/vscode-restclient#301]
The REST client will format the json like this:

![tim 20181210140707](https://user-images.githubusercontent.com/13498329/49713752-0fc1a900-fc85-11e8-842d-df3dec3be060.png)

which I can not fold the key1 entirly.

And what I want is like 
![tim 20181210140716](https://user-images.githubusercontent.com/13498329/49713756-14865d00-fc85-11e8-9071-93f3a873a538.png)

When the first array is too long, it's hard to see the second array quickly

**Comment by Huachao** [comment]
Can you show me the response or its actual request ?

**Comment by OhYee** [comment]
This the what return in Django
```python
{
    "key1": [{"id": 1}, {"id": 2}, {"id": 3}, {"id": 4}, {"id": 5}],
    "key2": [{"id": 1}, {"id": 2}, {"id": 3}, {"id": 4}, {"id": 5}],
    "key3": [{"id": 1}, {"id": 2}, {"id": 3}, {"id": 4}, {"id": 5}],
}
```

And this is what restclient get
```json
HTTP/1.1 200 OK
Date: Mon, 10 Dec 2018 07:22:35 GMT
Server: WSGIServer/0.2 CPython/3.7.1
Content-Type: application/json
Vary: Origin, Cookie
X-Frame-Options: SAMEORIGIN
Content-Length: 195

{
  "key1": [{
    "id": 1
  }, {
    "id": 2
  }, {
    "id": 3
  }, {
    "id": 4
  }, {
    "id": 5
  }],
  "key2": [{
    "id": 1
  }, {
    "id": 2
  }, {
    "id": 3
  }, {
    "id": 4
  }, {
    "id": 5
  }],
  "key3": [{
    "id": 1
  }, {
    "id": 2
  }, {
    "id": 3
  }, {
    "id": 4
  }, {
    "id": 5
  }]
}
```


Because the first line is ` "key1": [{`, so I can not fold the `key1`. 
It will fold `{ "id": 1 },` instead of  `key1: [...]`

Maybe add a `\n` between `[` and `{` will help.

**Comment by OhYee** [comment]
大概用中文交流能方便点……
意思就是因为这里`"key1": [{`，所以在折叠的时候会优先折叠后面的`{`这就导致如果`key1`是一个很长的数组，我想看到`key2`，只有两种选择：
1. 靠运气拖动滚动条找到`key2`
2. 一个一个折叠`key1`对应的列表里的内容

如果可以直接折叠`key1`，如`'key1;:[...])`，就可以解决这个问题了

@Huachao

**Comment by Huachao** [comment]
@OhYee this seems related to issue of the json beautify library, see issue here beautify-web/js-beautify#1402

**Comment by Huachao** [comment]
@OhYee I have implemented this JSON prettify logic on my own instead of 3rd party library. It will be published in next release.

**Comment by Huachao** [comment]
@OhYee you can try the latest version 0.21.0 to verify the fix

**Comment by OhYee** [comment]
@Huachao 
Good job 👍
Thanks for your help.
