### ISSUE TITLE
parse error in VSCode 1.30.0

### ISSUE THREAD

**Issue by Hawken94** [Huachao/vscode-restclient#304]
- VSCode Version: 1.30.0
- OS Version: macOS 10.13.6
- REST Client Version :0.20.4

This is my test file(filename: .apitest.rest).
```
###
POST http://127.0.0.1:12003/goods_mgr/v3/goods_label/find_page
Content-Type: application/x-www-form-urlencoded

page_number=1
&page_size=20
```
Steps to Reproduce:

1. Click the 'Send Request'
2. VSCode show 'parse error'

By the way, it works on the last version(VSCode 1.29.1)

**Comment by Huachao** [comment]
@Hawken94 do you have the old VSCode instance and tried the same request with current extension version now? And I found that VSCode doesn't upgrade its NodeJs version in this release. Can you show me the actual sent out request in your Postman from the console, or you just checked the actual sent out request with `curl -v`. Thanks in advance.

**Comment by Hawken94** [comment]
@Huachao Sorry to reply too late. I just downloaded the old VSCode to test and I found it didn't work either. Then I remember I set the 'http.proxy', after I delete the setting. It works.

**Comment by Huachao** [comment]
@Hawken94 Cool, thanks for reporting this.
