### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by huhx** [Huachao/vscode-restclient#305]
- Issue Type: `Performance`
- Extension Name: `rest-client`
- Extension Version: `0.20.4`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.30.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/huxhu/
[humao.rest-client-unresponsive.cpuprofile.txt](https://github.com/Huachao/vscode-restclient/files/2697579/humao.rest-client-unresponsive.cpuprofile.txt)
humao.rest-client-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by Huachao** [comment]
@huhx could you please also provide the actual cpuprofile file to help me to investigate the root cause? Thanks in advance.

**Comment by Huachao** [comment]
@Huachao can you provide me the attachment, thanks in advance.

**Comment by Huachao** [comment]
@huhx I have found the cpuprofile file, I will investigate the issue.

**Comment by Huachao** [comment]
@huhx I have used the Webpack technique in my extension, and it improved the loading performance dramatically, from **~5s** to **1.2s**.

**Comment by Huachao** [comment]
@huhx you can try the latest version 0.21.0 to verify the fix
