### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by jenishj-crest** [Huachao/vscode-restclient#306]
[humao.rest-client-unresponsive.cpuprofile.txt](https://github.com/Huachao/vscode-restclient/files/2711845/humao.rest-client-unresponsive.cpuprofile.txt)
[humao.rest-client-unresponsive.cpuprofile.txt](https://github.com/Huachao/vscode-restclient/files/2711846/humao.rest-client-unresponsive.cpuprofile.txt)

- Issue Type: `Performance`
- Extension Name: `rest-client`
- Extension Version: `0.20.4`
- OS Version: `Linux x64 4.18.0-041800-generic`
- VSCode version: `1.30.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/crest/humao.rest-client-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by Huachao** [comment]
@jenishj-crest after I checked the cpuprofile you provided, I can only see the time cost at Node.Js which tries to load modules. And I am not sure if all the loaded modules come from my extension. And when did the VSCode get unresponsive, when loading my extension or sending the request?

**Comment by Huachao** [comment]
@jenishj-crest it seems similar to #305, I will try to investigate if I can improve the module load performance with technique like *Webpack*

**Comment by Huachao** [comment]
@jenishj-crest I have used the *Webpack*  technique in my extension, and it improved the loading performance dramatically, from **~5s** to **1.2s**

**Comment by Huachao** [comment]
@jenishj-crest you can try the latest version to 0.21.0 to verify the fix

**Comment by jenishj-crest** [comment]
Yes it seems to be fixed in latest version. @Huachao
