### ISSUE TITLE
Facing issue with Special characters /+=

### ISSUE THREAD

**Issue by crazyLearning** [Huachao/vscode-restclient#307]
- VSCode Version:1.30.1
- OS Version:Windows 10
- REST Client Version:0.21.0

Steps to Reproduce:

1. Here is my request - 
POST https://login.microsoftonline.com/{{TenantId}}/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{ClientId}}&client_secret={{Secret}}

And the secret variable has these special characters /+=

When i send this request from RestClient, i get an invalid secret error. However, same request from postman passes and gets me a valid AAD token.

Please Help !!

**Comment by Dibyasingh** [comment]
Same issue happening with me.

**Comment by Huachao** [comment]
@crazyLearning @Dibyasingh have you tried the setting `"rest-client.formParamEncodingStrategy": "always"`?

**Comment by crazyLearning** [comment]
how to set this ?

**Comment by Huachao** [comment]
@crazyLearning you can find the setting in VSCode setting panel

**Comment by crazyLearning** [comment]
worked like a charm, thanks :)

**Comment by AndyBrownlie** [comment]
I've got the same thing happening here. I've set the formParamEncodingStrategy setting too but still the same. I then manually encoded by password and it worked, but I thought this setting was supposed to do that?
