### ISSUE TITLE
bugs on sending multipart/form-data requests with duplicate field names

### ISSUE THREAD

**Issue by VictorSu000** [Huachao/vscode-restclient#311]
- VSCode Version: 1.30.1
- OS Version: Linux x64 4.15.0-29deepin-generic
- REST Client Version: 0.21.1

Steps to Reproduce:

requests:

```http

POST http://example.com/api
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="json"

{"test": "test"}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="1.docx"
Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document

< ./docs/1.docx
------WebKitFormBoundary7MA4YWxkTrZu0gW--
Content-Disposition: form-data; name="file"; filename="2.docx"
Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document

< ./docs/2.docx
------WebKitFormBoundary7MA4YWxkTrZu0gW--
```

The request has two files and they use the same field name "file". If I send this request in postman, the server will receive both files, 1.docx and 2.docx. But if I send it via REST Client, the server can only receive 1.docx.

**Comment by Huachao** [comment]
@VictorSu000 I think the root cause is your request body isn't right, only the last part can be delimited with double - suffix
