### ISSUE TITLE
response  preview  render 

### ISSUE THREAD

**Issue by rhythmk** [Huachao/vscode-restclient#315]
I send a request  to servers and get  a page status is 500. This page contains a glorified error message 。
Can I use this to see the results returned, as in the browser?

**Comment by Huachao** [comment]
@rhythmk you mean render the html page, currently it's not supported.

**Comment by rhythmk** [comment]
> @rhythmk you mean render the html page, currently it's not supported.

sorry, I didn't find the operation  method

**Comment by Huachao** [comment]
@rhythmk what's do you mean the *operation method*?

**Comment by skamansam** [comment]
Are there plans to support this? If not, would you consider accepting a PR for this feature?

**Comment by thecfguy** [comment]
I think HTML preview is best addition to this extension. I have almost stop using Postman since started using this extension but sometime I force to use postman just because of this capabilities not available.

**Comment by Huachao** [comment]
> Are there plans to support this? If not, would you consider accepting a PR for this feature? I was thinking just a `view as HTML` button in the editor toolbar.

@skamansam sorry for the late reply, a PR is warmly welcomed

**Comment by dufferzafar** [comment]
@Huachao What is the default way that Rest Client displays the response?

I'm guessing we could replace that view with the [WebView API](https://code.visualstudio.com/api/extension-guides/webview) and things would work?

**Comment by Huachao** [comment]
@dufferzafar actually the extension is built on the WebView API, however, I just treat all the response body as the code text that inserted into the `<pre><code>` HTML tag

**Comment by dufferzafar** [comment]
Okay. Can you please point me to where this actually happens in the code? I'll see what changes we'd have to make to get the full previews working in the webview.

**Comment by Huachao** [comment]
@actually this is by design since normally we want to view the actual response, I think we can add an option to render the HTML response instead of raw data.  https://github.com/Huachao/vscode-restclient/blob/666180c9aad50083477f246abc16489848d8051c/src/views/httpResponseWebview.ts#L188-L227

**Comment by Stetzon** [comment]
+1 for rendering HTML preview

**Comment by mk-git** [comment]
The pull request looks good, the feature was built, does anyone know why it was not integrated and when HTML Preview will be possible? Just when e.g. a Laravel API or a Symfony app does a dump/dump&die, the output will be scripted and has to be parsed through a webview first.

**Comment by WebRegul** [comment]
+1 for rendering HTML preview
