### ISSUE TITLE
POST request without headers fails

### ISSUE THREAD

**Issue by shytikov** [Huachao/vscode-restclient#32]
- VSCode Version: 1.4.0
- OS Version: Windows 10
- REST Client Version: 0.7.2

Steps to Reproduce:

1. Create POST request with body but no headers;
1. Ensure that there is an empty line between request URL and body;
1. Execute request;
1. VSCode will show error message `Header must be in 'header name: header value' format, please also make sure there is a blank line between headers and body`;
1. Add any valid header;
1. Ensure that there is an empty line between request URL and body;
1. Execute request;
1. Request succeeds.

As I mention, there is a workaround — create dummy (still valid) header and execute request. But behavior is clearly incorrect and error message is misleading.

**Comment by Huachao** [comment]
@shytikov nice catch, I will fix it ASAP and publish a new version

**Comment by Huachao** [comment]
@shytikov it has been fixed and you can try the latest version 0.7.3

**Comment by shytikov** [comment]
Wow, that was fast!.. I will finish my API debugging (doing it with the help of your extension), and will update version! 

Thank you!
