### ISSUE TITLE
send request button show too slow

### ISSUE THREAD

**Issue by readless** [Huachao/vscode-restclient#321]
i find that send request button show too slow。when i open the http file, send request button will show after 2 seconds 。Can it improve?

**Comment by Huachao** [comment]
@readless can you try to run the command `Show Running Extensions` and check the time of my extension, and how many requests stored inside your `http` file

**Comment by Huachao** [comment]
@readless Do you still meet this issue, I'd like to close it for now, please feel free to reopen it.
