### ISSUE TITLE
Query response with text/javascript content

### ISSUE THREAD

**Issue by asmith3006** [Huachao/vscode-restclient#327]
When you query Facebook Graph API the response is "text/javascript; charset=UTF-8" and I can't query the result using {{ConfirmToken.response.body.user_id}} it says "Only JSON request/body is supported to query the result" so I'm assuming it's looking for "application/json"?

Can you please include "text/javascript"?

Thanks.

**Comment by Huachao** [comment]
@asmith3006 does the Facebook API response is actually a JSON body, although the `Content-Type` of it is marked as `text/javascript`?

**Comment by vit100** [comment]
In my case I have request which returns HTML document and I need to extract property from <form > element.
But requests with extract doesn't work and shows message: Only JSON response/request body is supported to query the result.
Any idea?

**Comment by Huachao** [comment]
@asmith3006 I'd like to close this issue since I think the Facebook Graph API returned response is of `application/json`

**Comment by Huachao** [comment]
@asmith3006 @martinschayna with the help of @mingue , you can treat javascript mime type as JSON during variable parsing. in the next release

**Comment by Huachao** [comment]
@asmith3006 @martinschayna this feature has been published in the latest version 0.24.5 with the great contribution from @mingue
