### ISSUE TITLE
Cannot copy request as cURL or generate snippet if host looks invalid

### ISSUE THREAD

**Issue by jugaltheshah** [Huachao/vscode-restclient#328]
- VSCode Version: 1.31.1
- OS Version: Ubuntu 18.10
- REST Client Version: 0.21.1

Steps to Reproduce:

1. Create request to a host that doesn't look valid, e.g. an env var:
```text
POST $URL/service HTTP/1.1
Content-Type: application/json

{
    "name": "test-service",
    "url": "test-service-url"
}
```
2. Highlight it
3. Right click and select "Copy Request As cURL" or "Generate Code Snippet"

Expected behavior:
I'd expect a cURL request equivalent to the one highlighted to be copied to clipboard. Or if "Generate Code Snippet" was chosen, I'd expect the menu of choices to popup

Actual behavior:
Clipboard retains previous contents / no menu pops up.

If I change `$URL` to `http://localhost`, for example, it starts working again. Not sure if this is expected behavior, but to me it seems like a bug. IMO REST Client shouldn't be responsible for checking that hosts are valid, only for generating the correct requests per the information given. My use case here was to generate a cURL request for another system in which `$URL` _is_ valid.

**Comment by jugaltheshah** [comment]
Sorry, I believe "Copy Request As cURL" is not working regardless of the host being malformed-looking or not. Possibly related to #308? Though I thought that was one of the fixes for this release.

**Comment by Huachao** [comment]
@jugaltheshah I can repro the issue and it seems not related to #308. And what's the expected behavior for url `$URL/service`, should the generated code remain as is like `curl -XPOST $URL/service` or append the protocol like `curl -XPOST http://$URL/service`?

**Comment by jugaltheshah** [comment]
The expected behavior is that code generated from `$URL/service` remains as-is, i.e. `curl -X POST $URL/service`.

**Comment by Huachao** [comment]
@jugaltheshah I have fixed this issue and will publish this in next releasae

**Comment by jugaltheshah** [comment]
That's amazing, thanks @huachao. I don't think I could turn around a sandwich that fast. :)

**Comment by Huachao** [comment]
@jugaltheshah you can try the latest version 0.21.2 to verify

**Comment by jugaltheshah** [comment]
Sorry for the late reply. With 0.21.2 "Copy Request As cURL" is working as expected with arbitrary (non-url) strings.

Thanks!
