### ISSUE TITLE
release notes for 0.21+ are still in 2018

### ISSUE THREAD

**Issue by alembiq** [Huachao/vscode-restclient#329]
0.21.1 (2018/1/8)
Feature: Add fold/unfold full response body features in the response preview panel
Bug Fix: Copy request as cURL not working
Bug Fix: AAD Auth stopped to work in new version - 0.21.0
0.21.0 (2018/1/3)
Bug Fix: Unable to collapse the json response body
Improvement: Use Webpack to bundle extension to improve activation time and high CPU load
Improvement: Update RFC1322 to RFC1123

it should be 2019 i believe :)

**Comment by Huachao** [comment]
@alembiq if you saw this in VSCode extension, that's expected behavior, since I haven't published a newer release. I plan to publish a new release next week, and after that, it will be OK
