### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by StephD** [Huachao/vscode-restclient#33]
- VSCode Version: 1.4
- OS Version: 7
- REST Client Version: 0.7.3

Hi,

I'll try to explain a bit. I got a file that I want to download. I use a get request to do that.
When I put the link into a browser, I can download the file.

![2016-08-24 10_54_21-new tab - firefox developer edition](https://cloud.githubusercontent.com/assets/1171858/17924552/6d32fe26-69e9-11e6-955f-99e8fb9d46b8.png)

When I put the link into "resteasy" (firefox extension for rest client), I can see the content of the text file.

![2016-08-24 10_53_52-rest easy - firefox developer edition](https://cloud.githubusercontent.com/assets/1171858/17924556/6d37c06e-69e9-11e6-8abb-3a09577a5599.png)
![2016-08-24 10_54_01-rest easy - firefox developer edition](https://cloud.githubusercontent.com/assets/1171858/17924558/6d4557ba-69e9-11e6-921e-7a80af64180f.png)
When I put the link into vscode rest client, I got the response "Parse Error" displayed down.
![2016-08-24 10_55_41-php - gateway_library_dgateway_rest_rest php - zend studio - c__users_sdp_zend_w](https://cloud.githubusercontent.com/assets/1171858/17924553/6d337752-69e9-11e6-98c9-00bc81f352a3.png)
![2016-08-24 10_55_26- crmat http - gateway - visual studio code](https://cloud.githubusercontent.com/assets/1171858/17924557/6d3803c6-69e9-11e6-9c0c-48473b00be29.png)
BUT If I had, in php, an "exit()" function just after the file reader, the content if well displayed.
![2016-08-24 10_56_02-php - gateway_library_dgateway_rest_rest php - zend studio - c__users_sdp_zend_w](https://cloud.githubusercontent.com/assets/1171858/17924554/6d350de2-69e9-11e6-94c1-03665f7d1bd4.png)
![2016-08-24 10_56_10-response - gateway - visual studio code](https://cloud.githubusercontent.com/assets/1171858/17924555/6d366818-69e9-11e6-95d2-2f497af27fb1.png)

I don't know what cannot be parsed. May be add a raw functionality. Like display content and do not try to parse it. Or avoid parse if it can't parse?

Thanks

**Comment by Huachao** [comment]
Thanks @StephD , I will look into this bug

**Comment by Huachao** [comment]
@StephD I think this error is thrown from the [http library](https://github.com/request/request) I use. Could you please provide me the error call stack by clicking 'Toggle Developer Tools'?

**Comment by StephD** [comment]
debugViewer.ts:933 Parse Error
e.doShow @ debugViewer.ts:933
e.show @ debugViewer.ts:907
(anonymous function) @ main.contribution.ts:36
i.Class.derive._oncancel @ monarchCompile.ts:91
t.$showMessage @ main.contribution.ts:33
e.handle @ window.ts:48
s @ commonCodeEditor.ts:925
f @ commonCodeEditor.ts:977
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98

Good luck with that :)
Unfortunately, you can't try it from your side.

The different between with and without exit is that the content type is text/plain with exit and text/xml without.
In both case, the response is the content of the file. But without exit, response also contain an xml part.

![2016-08-24 14_02_20-firebug - rest easy](https://cloud.githubusercontent.com/assets/1171858/17929850/8cf36de4-6a03-11e6-80bc-966f9fa8a1e9.png)
![2016-08-24 14_02_47-firebug - rest easy](https://cloud.githubusercontent.com/assets/1171858/17929851/8cf2f0bc-6a03-11e6-9842-4d337832a79b.png)

What I want to ask is the possibility to get the raw version of the response.
![2016-08-24 14_04_37-rest easy - firefox developer edition](https://cloud.githubusercontent.com/assets/1171858/17929880/b806b248-6a03-11e6-8cfb-5afd9b0c525f.png)
![2016-08-24 14_04_31-rest easy - firefox developer edition](https://cloud.githubusercontent.com/assets/1171858/17929881/b80a0a88-6a03-11e6-91a7-6a619d7deb9d.png)

This error is generated from the server side (content-type, ..) so thanks to you, I can know that something goes wrong.
But I just ask you for raw functionality :)

**Comment by Huachao** [comment]
@StephD however I can't repro your failure by get a invalid xml file with `content-type: text/html;charset=UTF-8`. You can try to get this file `GET https://humao1576.blob.core.windows.net/test/test.txt HTTP/1.1`

**Comment by StephD** [comment]
You are correct, on your server, even if it's the same error with resteasy, vscode do not give me any parsing error.

I don't know. Thanks for your time

**Comment by Huachao** [comment]
So I still guess, the so-called `Parse Error` is from the node js http library which parses the response and find the response invalid, the invalid here seems not related to wrong content body, but should related to http response format. Maybe if you don't exit in your php code, the server maybe generate some invalid content in response, which cause nodejs http library error.

**Comment by StephD** [comment]
1: Response length modification let appear xml part : Test file<?xml version="1.0" encoding="UTF-8"?>
2: Connection:keep-alive do not change anything in vscode

**Comment by Huachao** [comment]
@StephD according to your first screenshot, the Content-Length returned from the server seems 9, and in your case as your mentioned above, the Content-Length shall be larger than 9 due to xml header? Can you try to make the Content-Length header reflects the real length? If I am wrong, sorry for the inconvenience.

**Comment by StephD** [comment]
I did it. I put it to 100 to let appear this xml part. This is why there is a parsing error I think because as xml, it's invalid.
Btw. Like I said, there was an error in my code so this error come from me, not your extension.

**Comment by Huachao** [comment]
@StephD I am just curious the reason. Thanks for your usage of my extension and many great suggestions.
