### ISSUE TITLE
um... VsCode - restFul response beautify code 

### ISSUE THREAD

**Issue by qqapp** [Huachao/vscode-restclient#334]
hi.
i used vscode Tools. 
and i used httpConnection rest-client plugin .
i want respose data beatify...
um ... 
sample data 
-- origin data 
    { "key1":"123", "key2":"134"}
-- change data
    {  
        "key1":"123", 
        "key2":"134"
     }

**Comment by Huachao** [comment]
@qqapp what's the `Content-Type` of your response?

**Comment by qqapp** [comment]
@Huachao Content-type value is 'application/json'

**Comment by Huachao** [comment]
@qqapp could you please take a screenshot of the response to help me to investigate, if you can also provide a public URL is better

**Comment by Huachao** [comment]
@qqapp could you please take a screenshot of the response to help me to investigate, if you can also provide a public URL is better

**Comment by Huachao** [comment]
@qqapp Do you still have this problem, I'd like to close it, and if you still have it, please feel free to reopen it and add some screenshots?
