### ISSUE TITLE
datetime iso8601 format wrong

### ISSUE THREAD

**Issue by JohannesBeranek** [Huachao/vscode-restclient#336]
- VSCode Version: 1.31.1
- OS Version: Win 10
- REST Client Version: 0.21.1

Steps to Reproduce:

1.  Use {{$datetime iso8601}}

iso8601 format is not implemented correctly, it currently includes milliseconds but should not.
E.g. expected: 
2019-02-25T15:18:38Z
but actual: 
2019-02-25T15:18:38.449Z

**Comment by Huachao** [comment]
@JohannesBeranek could you please provide the documentation about ISO 8601 time representation without  milliseconds

**Comment by sjamesexamsoft** [comment]
According to Wikipedia.
Decimal fractions may be added to any of the three time elements. However, a fraction may only be added to the lowest order time element in the representation.
So milliseconds are allowed.
https://en.wikipedia.org/wiki/ISO_8601

**Comment by Huachao** [comment]
> According to Wikipedia.
> Decimal fractions may be added to any of the three time elements. However, a fraction may only be added to the lowest order time element in the representation.
> So milliseconds are allowed.
> https://en.wikipedia.org/wiki/ISO_8601

@JohannesBeranek so I think this is an acceptable implementation now. I'd like to close it.
