### ISSUE TITLE
Store full JSON object as environment variable

### ISSUE THREAD

**Issue by nathan-bardwell** [Huachao/vscode-restclient#337]
I have multiple files that send requests using the same JSON object. Would it be possible to add a feature that allows me to store this JSON as an environment variable so I can make changes to this object in one place instead of having to update each file individually?

For example:
```
{
    "rest-client.environmentVariables": {
        "$shared": {
            "sharedObject": {
                "var1": "value1",
                "var2": "value2",
                "var3": "value3"
            }
        }
    }
}
```

```
POST http://url.com/my/test
Content-Type: application/json

{
    "object": {{sharedObject}}
}
```

**Comment by kiesner** [comment]
Any updates on this?
I need to use an array in the request body that has varying length depending on the environment, i.e.

```
{
   "rest-client.environmentVariables":{
      "dev":{
         "xs":[
            "abc",
            "cde"
         ]
      },
      "prod":{
         "xs":[
            "x",
            "y",
            "z"
         ]
      }
   }
}
```

Any ideas for a workaround?

**Comment by Huachao** [comment]
@nathan-bardwell @mickeypearce @kiesner this is already supported. Since the type of environment variable value is **JSON** `string`, you should enclose them in the *double quotes* and escape the inside `"` as following:
```json
"rest-client.environmentVariables": {
    "$shared": {
        "sharedObject": "{\"var1\": \"value1\",\"var2\": \"value2\",\"var3\": \"value3\"}",
    },
    "dev": {
        "xs": "[\"x\", \"y\", \"z\"]"
    },
    "prod": {
        "xs":"[\"abc\", \"cde\"]"
    }
}
```
To reference them, you can write following code in your request file:
```http
POST https://example.com/foo/bar
Content-Type: application/json

{
    "data": {{sharedObject}},
    "chars": {{xs}}
}

```
