### ISSUE TITLE
miss query string when generate code snippet  when use python(requests library) 

### ISSUE THREAD

**Issue by zmqcherish** [Huachao/vscode-restclient#338]
- VSCode Version:1.31.1
- OS Version:windows 10 ,10.0.17134
- REST Client Version:0.21.1

Steps to Reproduce:
1. create a test.http
2. just input the curl string: 
GET https://cn.bing.com/search?q=microsoft
3. Ctrl + Alt + C, then choose python -> Requests
4. right panel has show the code, but miss the param: microsoft
`import requests
url = "https://cn.bing.com/search"
response = requests.request("GET", url)
print(response.text)`

the screenshot:
![qq 20190227210822](https://user-images.githubusercontent.com/6880848/53492874-e15da800-3ad4-11e9-9892-1f3716895deb.jpg)

**Comment by Huachao** [comment]
@zmqcherish nice catch, I have fixed the issue and will publish this fix in next release.

**Comment by Huachao** [comment]
@zmqcherish you can try the latest version to verify

**Comment by zmqcherish** [comment]
it work well, thanks.

**Comment by SirMossi** [comment]
Version 0.23.1

Same problem when calling "send request"

**Comment by Huachao** [comment]
@SirMossi Can you paste your request
