### ISSUE TITLE
Allow automatic Decode of HTTP responses.  

### ISSUE THREAD

**Issue by GlennPope** [Huachao/vscode-restclient#34]
- VSCode Version: 1.5.2
- OS Version: W7
- REST Client Version: 0.7.5

Reception of a response may include encoded characters. Although there are other extensions that will decode html encoded characters, the response is read only.  To decode requires an extra set of steps to open a new window, manually select the response (CTRL+A does not work) and past into the new window before invoking the other extension. 
 Can you provide an option to decode encoded characters in the response? 

Thank you.

**Comment by Huachao** [comment]
@GlennPope thanks for your suggestion, and I will add it to my backlog and implement ASAP

**Comment by Huachao** [comment]
@GlennPope now we can a small step further, I added the function to save response to local file system, and you can decode it easily use other extensions before I add the decode function

**Comment by Huachao** [comment]
@GlennPope can you still repro the encode problem now, since I fixed some tags escape problem, thanks

**Comment by GlennPope** [comment]
It is working as expected. Great job!
 Thanks. 
Glenn 


-------- Original message --------From: Huachao Mao <notifications@github.com> Date: 10/13/16  8:07 PM  (GMT-06:00) To: Huachao/vscode-restclient <vscode-restclient@noreply.github.com> Cc: GlennPope <Glenn.Pope.ret@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [Huachao/vscode-restclient] Allow automatic Decode of HTTP
  responses. (#34) 
@GlennPope can you still repro the encode problem now, since I fixed some tags escape problem, thanks

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Huachao/vscode-restclient","title":"Huachao/vscode-restclient","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Huachao/vscode-restclient"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Huachao in #34: @GlennPope can you still repro the encode problem now, since I fixed some tags escape problem, thanks"}],"action":{"name":"View Issue","url":"https://github.com/Huachao/vscode-restclient/issues/34#issuecomment-253682965"}}}
