### ISSUE TITLE
the json in requstbody has blank line will be cut off

### ISSUE THREAD

**Issue by Watson-Shen** [Huachao/vscode-restclient#340]
- VSCode Version:  1.31.1
- OS Version: Windows_NT x64 10.0.17134
- REST Client Version: 0.21.2

Steps to Reproduce:

1. Create request to a host,make the json has blank line
```
POST https://example.com/comments HTTP/1.1
content-type: application/json

{
    "name": "sample",

    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}
```
2. the json data will be cut off from blank line,it will be like this:
```
{
    "name": "sample",

```

**Comment by Huachao** [comment]
@Watson-Shen this is by design, you should remove the blank lines in request body except for `multipart/xxx` MIME type
