### ISSUE TITLE
At send-request time, what happens when an SSL client cert is set for the target host?

### ISSUE THREAD

**Issue by Andrew-Webb** [Huachao/vscode-restclient#344]
I have set an SSL client cert for my target API (localhost:port) in the VS Code settings file, via a PFX file and passphrase, as per https://github.com/Huachao/vscode-restclient#ssl-client-certificates

When I send a request to the API, what does Rest Client actually do?  I thought maybe the client cert would be sent in a custom request header, but the server isn't receiving any more than the usual 7 req headers.  Does Rest Client send anything at all?

**Comment by Huachao** [comment]
@Andrew-Webb the client/server certificate verification is done at the TLS/SSL layer, which you can think as a step before issuing actual http request. And you need to use SSL client certificate authentication only if server-side needs this.
