### ISSUE TITLE
Support for Authorization header with Bearer tokenn

### ISSUE THREAD

**Issue by sjamesexamsoft** [Huachao/vscode-restclient#348]
Need to be able to send HTTP requests with an Authorization header of the type:
Authorization: bearer eyJhbGciOiJBMTI4S...129379hf

**Comment by Huachao** [comment]
@sjamesexamsoft bear authentication is supported out-of-box, doesn't it work for you?

**Comment by sjamesexamsoft** [comment]
My bad - user error - it is working.
