### ISSUE TITLE
Generate Code Snippet for Objective-C null不自动转空字符串导致无法生成OC代码

### ISSUE THREAD

**Issue by KeYuyi** [Huachao/vscode-restclient#349]
- VSCode Version: 1.32.3
- OS Version: Win7 SP1 64位
- REST Client Version: 0.21.2

Steps to Reproduce:

1. 一个正常的http请求，参数中带有null的话就无法生成Objective-C代码
2.将null手动改为“”空字符串,才可以正常生成

**Comment by Huachao** [comment]
@KeYuyi what do you mean that query string carries `null`, can you give me an example?

**Comment by KeYuyi** [comment]
@Huachao example:
PUT {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer XXXXXXX
Cache-Control: no-cache

{
    "username":"",
    "gender":null,
    "district":"",
    "address":""
}
这段代码无法直接生成为Objective-C 需要将 null 改为 "" 才可以

**Comment by Huachao** [comment]
@KeYuyi I have updated the dependent `httpsnippet` package version to fix this issue.

**Comment by Huachao** [comment]
@TaroLoveFoxes you can verify this in latest version 0.21.3
