### ISSUE TITLE
Does it support client certificate authentication?

### ISSUE THREAD

**Issue by zephrxx** [Huachao/vscode-restclient#35]
Some rest api requires client cert authentication.

**Comment by Huachao** [comment]
@zephrxx it's not supported now, thanks for your suggestion and I will put it in my backlog

**Comment by defectus** [comment]
This one should be fairly easy to implement. I can imagine 3 more items in the request:

* client certificate
* private key 
* private key password (_optional_)

All three can be in the plain text form, eligible for env. params substitution (environment aware).

https://www.npmjs.com/package/request#tlsssl-protocol for more.

**Comment by Huachao** [comment]
@defectus you are right, I am considering that how to let user to specify these items in request, the more direct way seems to put in request(that seems needs to create a new syntax to set these value), others ways are putting in setting files, or even add some dialogs to let user to CRUD these friendly

**Comment by defectus** [comment]
Just keep in mind that for many people (at least for me :-)) client certificates differ between environments. We use different client certificates in production, staging and integration.

Whatever way you plan to implement this feature please allow us to easily configure certificates based on the selected environment.

**Comment by kwaxi** [comment]
An idea good be to use the underlaying OS certificate store which should work fine for Windows and MacOS. Referencing the Certificate could be done be specifing the store and fingerprint.

**Comment by Huachao** [comment]
@zephrxx @defectus @kwaxi @VitorLuizC @mFingers @ytimenkov I have implemented the client certificate feature, and will publish it in next version

**Comment by Huachao** [comment]
@zephrxx @defectus @kwaxi @VitorLuizC @mFingers @ytimenkov I have implemented the client certificate feature, and will publish it in next version

**Comment by Huachao** [comment]
@zephrxx @defectus @kwaxi @VitorLuizC @mFingers @ytimenkov You can use the latest version 0.14.0, you can also follow the `README` for how to use it.

**Comment by defectus** [comment]
Just tested it, works nicely! Good job, many thanks!

**Comment by MichaelHumplEnBW** [comment]
> you can also follow the README for how to use it.
Im am sorry, but i can not find the referenced README. Can you plase help me to find them. Thank you.
