### ISSUE TITLE
Content-type not being passed in specific scenario

### ISSUE THREAD

**Issue by asmith3006** [Huachao/vscode-restclient#354]
- VSCode Version: 1.33.0
- OS Version: Windows 10
- REST Client Version: 0.21.2

Steps to Reproduce:
Change Preview Option to "exchange" so you can see all sent AND received headers. 

Perform this POST:
POST https://domain.myshopify.com/admin/orders/123456789/fulfillments.json
Authorization: Basic Username Password
Content-Type: application/json
Cookie: none

{"fulfillment": {"location_id":789456123,"tracking_number":"TRACKING","tracking_company":"OPERATOR","notify_customer":false}}

**Notice that "content-type" is not set**

Change the request domain to something else:
POST https://**myshopify.com**/admin/orders/123456789/fulfillments.json
Authorization: Basic Username Password
Content-Type: application/json
Cookie: none

{"fulfillment": {"location_id":789456123,"tracking_number":"TRACKING","tracking_company":"OPERATOR","notify_customer":false}}

**Content-Type is now set.**

I've tried this on three different computers and get the same results.

**Comment by Huachao** [comment]
@asmith3006 the underlying http client module `request` when remove the `Content-Type` header when redirect happens, here for your case, the first request redirects your request to login API. While `request` module enters into the maintenance state,  I am planning to migrate to other http client libraries. I think this bug will be fixed after that.

**Comment by asmith3006** [comment]
Thanks for the feedback.

Would it be possible to have the output tell us a redirect happened? I have no way of knowing what's going on in this instance.

**Comment by Huachao** [comment]
- @asmith3006 make sense, I will consider this carefully

**Comment by Huachao** [comment]
@asmith3006 after upgrade to the latest version 0.23.0, this issue should be fixed. If you still meet this issue, pls feel free to reopen it.
