### ISSUE TITLE
Label displayed when hovering scroll-to-top button says "null"

### ISSUE THREAD

**Issue by schneider8357** [Huachao/vscode-restclient#355]
![vscodeissue](https://user-images.githubusercontent.com/40526466/55964422-12400980-5c4b-11e9-9f50-5ec549621c49.png)

Don't know if it's intended. Just reporting.

**Comment by Huachao** [comment]
@schneider8357 nice catch, I have fixed the issue and will publish in next release.

**Comment by Huachao** [comment]
@schneider8357 you can check this fix in latest version 0.21.3
