### ISSUE TITLE
call requests in sequence

### ISSUE THREAD

**Issue by vit100** [Huachao/vscode-restclient#356]
Would be nice to call all requests in file in sequence automatically.
For example
1 get token
2 get resource (with token retrieved in step1)

**Comment by DaveJohnson8080** [comment]
This looks similar to #364 that was marked as an enhancement. 

This would be the Postman killer in my book.

**Comment by Huachao** [comment]
@vit100 @DaveJohnson8080 @JJB-123 Duplicate of #364, close this to in favor of that
