### ISSUE TITLE
The json field in the http response does not display correctly in Chinese.

### ISSUE THREAD

**Issue by wxing2008666** [Huachao/vscode-restclient#357]
Due to the encoding format problem, the Chinese of the json field in the http response cannot be displayed correctly.

**Comment by Huachao** [comment]
@wxing2008666 what's the content type header of the response, and can you also provide a public URL to verify if available

**Comment by wxing2008666** [comment]
The keywords field in the http response is Unicode encoding, how to change to utf-8 encoding, can display Chinese normally

**Comment by wxing2008666** [comment]
request：
![image](https://user-images.githubusercontent.com/11993921/56088225-b5448d80-5eae-11e9-829d-5569bc9e195a.png)
response：
![image](https://user-images.githubusercontent.com/11993921/56088228-c55c6d00-5eae-11e9-8389-38fb3837db2b.png)
