### ISSUE TITLE
【建议】get请求参数输入方式跟post 保持一直，中文的encode处理

### ISSUE THREAD

**Issue by wangyibu** [Huachao/vscode-restclient#36]
- VSCode Version:1.5.1
- OS Version:win10
- REST Client Version:0.7.4

Steps to Reproduce:
建议1. get请求参数的输入方式跟post 保持一直，在最下面

![image](https://cloud.githubusercontent.com/assets/14134768/18621790/d679e2ca-7e5a-11e6-8aff-b807ae5ed055.png)

建议2. 增加对中文的encode处理

![image](https://cloud.githubusercontent.com/assets/14134768/18621874/ae8b8c0e-7e5b-11e6-91a2-b6483f3bc3f0.png)

**Comment by Huachao** [comment]
@wangyibu , the advice in suggestion 1 that put query string in the bottom doesn't follow RFC 2616 standard, and also there is a corner case that GET request can contain body. For suggestion 2, it's a nice suggestion. I will implement ASAP

**Comment by foxundermoon** [comment]
query放在末尾干嘛，它属于url的一部分。智障宝宝😊

**Comment by wangyibu** [comment]
@foxundermoon 
当然知道query 是参数的一部分，我描述不准确，我建议是提供多种参数格式例如json

例如url： https://search.jd.com/search?keyword=%E7%94%B5%E8%84%91&enc=utf-8&qrst=1&rt=1&stop=1&vt=2&wq=%E7%94%B5%E8%84%91&cid2=671&cid3=12798&ev=212_1675%40933_40614%40149_17976%40&uc=0#J_crumbsBar

```http
GET http://search.jd.com/search HTTP/1.1
    ?keyword=%E7%94%B5%E8%84%91
    &enc=utf-8
    &qrst=1
    &rt=1
    &stop=1
    &vt=2
    &wq=%E7%94%B5%E8%84%91
    &cid2=671
    &cid3=12798
    &ev=212_1675%40933_40614%40149_17976%40
    &uc=0 
Host: search.jd.com
Connection: keep-alive
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.101 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Referer: https://search.jd.com/search?keyword=%E7%94%B5%E8%84%91&enc=utf-8&qrst=1&rt=1&stop=1&vt=2&wq=%E7%94%B5%E8%84%91&cid2=671&cid3=12798&ev=212_1675%40933_40614%40&uc=0
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: zh-CN,zh;q=0.8,en;q=0.6,ja;q=0.4
Cookie: __jdv=122270672|direct|-|none|-; areaId=1; __jda=122270672.105260706.1473833634.1473833634.1474279307.1; __jdb=122270672.12.105260706|1.1474279307; __jdc=122270672; rkv=V0900; ipLoc-djd=1-72-2799-0; ipLocation=%u5317%u4EAC; __jdu=105260706; xtest=17152.7252.d9798cdf31c02d86b8b81cc119d94836.b7a782741f667201b54880c925faec4b; mx=0_X

```

```json
[
  { "name": "keyword", "value": "电脑" },
  { "name": "enc", "value": "utf-8" },
  { "name": "qrst", "value": "1" }
  ...
]
```

**Comment by Huachao** [comment]
@wangyibu I know your pain, however my concern is still that since GET request can also have request body, how can we distinguish and write such request?

**Comment by Huachao** [comment]
@wangyibu suggestion 2 has been fixed and will be available in next release

**Comment by Huachao** [comment]
@wangyibu you can try the latest version 0.8.2, and always hope to see you feedback and suggestions 😄

**Comment by YourGranny123** [comment]
> query放在末尾干嘛，它属于url的一部分。智障宝宝😊

果然自己菜的人，看谁都是菜的，狗眼看人低，智障宝宝。
