### ISSUE TITLE
JsonPath get id of first object in array from previous request

### ISSUE THREAD

**Issue by LucaGabi** [Huachao/vscode-restclient#362]
Hi, 

Haw to solve the situation in the screenshoot:

Haw to get the id value from the json and pass it to the second request?

![image](https://user-images.githubusercontent.com/37976898/57975875-8e143b00-79db-11e9-9da6-d2d270904e5a.png)

**Comment by Huachao** [comment]
@LucaGabi it seems this path is OK `{{all.response.body.$[0].id}}`
