### ISSUE TITLE
GET can not have a body

### ISSUE THREAD

**Issue by haohongran** [Huachao/vscode-restclient#363]
- VSCode Version:
- OS Version:
- REST Client Version:

Steps to Reproduce:

1. 
2.

**Comment by Huachao** [comment]
@haohongran what do you mean `GET can not have a body`, do you mean you can't send a GET request with body?

**Comment by haohongran** [comment]
> @haohongran what do you mean `GET can not have a body`, do you mean you can't send a GET request with body?

yes

**Comment by Huachao** [comment]
@haohongran the extension imposes no such restrictions on sending GET request includes a body, the error may come from the web server which doesn't allow this case. Could you please provide some screenshot of your request and response, or the reason you think my extension is incapable of sending GET request includes body.

**Comment by Huachao** [comment]
@haohongran any update, I'd like to close this issue since my extension imposes no such restrictions.
