### ISSUE TITLE
Custom Date Time Format - stripping leading zero from day value

### ISSUE THREAD

**Issue by cmjchrisjones** [Huachao/vscode-restclient#367]
- VSCode Version: 1.33.1 (User Setup)
- OS Version: Win 10 Enterprise
- REST Client Version: 0.21.3

### Background

@connelhooley recently made a change to resolve #325 which allows us to use a custom date format as well as specifying a dynamic date in PR #361, although, again this is specific to just our use case, I noticed that when doing `"{{$datetime 'YYYY-MM-DD' 5 d}}"` today (30th May, 5 days from now being 4th June), it isn't including the leading 0 for the day, we are getting the following response from our internal API

` "message": "Supplied value could not be accepted. Supplied date '2019-06-4' is invalid, ensure to supply in yyyy-MM-dd format."`

**Comment by Huachao** [comment]
@cmjchrisjones nice catch, I have fixed the issue and will publish it in next release.

**Comment by cmjchrisjones** [comment]
Thanks, looking forward to the next release 👍

**Comment by MrXhh** [comment]
Replace "%USERNAME%\.vscode\extensions\humao.rest-client-0.21.3\dist\extension.js" with the file in "extension.zip" if you need it urgently.
My plugin version is: 0.21.3



[extension.zip](https://github.com/Huachao/vscode-restclient/files/3251685/extension.zip)

**Comment by connelhooley** [comment]
Is there any update on when this will be released? I'd rather not get our entire team to download the zip and manually update the extension if possible.

Thanks

**Comment by Huachao** [comment]
@connelhooley it should be released in this week 😄

**Comment by Huachao** [comment]
@connelhooley @cmjchrisjones @MrXhh this fix has been published in latest version 0.22.0, you can try it.
