### ISSUE TITLE
Headers are not parsed correctly with LF line endings

### ISSUE THREAD

**Issue by eojthejudge** [Huachao/vscode-restclient#37]
- VSCode Version: 1.5.2
- OS Version: Windows 7
- REST Client Version: 0.7.5

Steps to Reproduce:

1. create a file including rest calls with lf line endings
2. Execute the call, the Header lines are added to the URI

When I change the line endings to CRLF, everything works as expected

**Comment by Huachao** [comment]
thanks @eojthejudge I will deliver this fix in next release

**Comment by Huachao** [comment]
@eojthejudge you can try the latest version 0.8.0

**Comment by eojthejudge** [comment]
Tested with 0.8.1, works both lineendings. Thanks!
