### ISSUE TITLE
Option to show responses with binary / unsupported file types

### ISSUE THREAD

**Issue by rscharfer** [Huachao/vscode-restclient#374]
When I make a request for an image/gif from the server, the response is successful, but other than the header which indicates how long the request took the tab is **blank**.  I can save the response and open it with VSC which says that because the response includes binary or an unsupported file type, it cannot be displayed, with the option to "open it anyway".  When I open it anyway, I can see the response.  It would be nice if I could do this immediately, without having to first save the file somewhere. 

For some reason, even when I configure the extension to only show the headers (which is all I need), I still get a **blank** response.

**Comment by Huachao** [comment]
@rscharfer could you please provide me the actual request you sent, since the extension will automatically preview the gif image

**Comment by rscharfer** [comment]
Hi there. Actually, you may be right. Because the image is only one pixel, maybe the preview is there like it should be. I was expecting being able to see the response headers as well, which I don't see.  Here is an example URL :https://paas.finanzcheck-shared.de/v1/log?configuration=erzZBpdsmNJd&da=erzZBpdsmNJd&bid=055b459a7b195c35fac8ac9bb5d57834&sid=a710b16dd92243dcfb6c74e328&referrer=https%3A%2F%2Fpr-784-d19e29.website.finanzcheck-shared.de%2F%3Fp%3Dangebote&&deviceWidth=1680&deviceHeight=1050&embedWidth=1680

**Comment by Huachao** [comment]
@rscharfer the response is actually received, and you can verify this by turning on *text view* flag for previewing response(default is webview), `"rest-client.previewResponseInUntitledDocument": true`. After that, sending the request, you can see the binary response in  an untitled document.
