### ISSUE TITLE
Cannot access process environment variable

### ISSUE THREAD

**Issue by uriel-sf** [Huachao/vscode-restclient#377]
- VSCode Version: 1.35.1
- OS Version: mac osx mojave
- REST Client Version: latest 0.21.3
- shell: zsh

Steps to Reproduce:

1. Open shell. `FOOBAR=hello code`
2. Reference `{{$processEnv FOOBAR}}` in HTTP file. 

FOOBAR will be blank

**Comment by Huachao** [comment]
@uriel-sf this feature hasn't been published and will be delivered in the next release.
