### ISSUE TITLE
$dateTime does not parse/encode correctly

### ISSUE THREAD

**Issue by uriel-sf** [Huachao/vscode-restclient#380]
- VSCode Version: 1.35.1
- OS Version: macosx mojave
- REST Client Version: 0.21.3

Steps to Reproduce:

1. Use the following in a URL: `?foobar={{$datetime "MM/DD/YYYY}}`

Expected results:
* As per the docs, it should be `?foobar=06%2F27%2F2019`

Actual results:
* `?foobar=06%2F27%2F192019`

There's a bug in either the implementation or the docs.

**Comment by Huachao** [comment]
> ?foobar={{$datetime "MM/DD/YYYY}}

@uriel-sf above code snippet misses a quote sign `"` after Y, it should be `?foobar={{$datetime "MM/DD/YYYY"}}`

**Comment by uriel-sf** [comment]
OMG, why did u close this? that's not the cause of the bug. I manually
recreated from a properly formatted string

**Comment by Huachao** [comment]
@uriel-sf I l already have fixed this issue in commit https://github.com/Huachao/vscode-restclient/commit/d81f4e99a08d17621c324241ecb35cd25151e674 and will publish in next release.
