### ISSUE TITLE
Image upload by using customize key 

### ISSUE THREAD

**Issue by SudhakaranRamalingam** [Huachao/vscode-restclient#381]
In my project we are using customize keys to upload the images.
 
In postman we are using key in body content.  How to use the customize key in the rest client? 
![image](https://user-images.githubusercontent.com/52189410/60069937-73e42000-9732-11e9-90aa-89a7edee7ec7.png)

**Comment by Huachao** [comment]
@SudhakaranRamalingam an exampled copied from **README**, following is a multipart/form-data request with two keys, one is `text` of value `title`, the other is `image` whose value is the content of `1.png`.

```http
POST https://api.example.com/user/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="1.png"
Content-Type: image/png

< ./1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
```
