### ISSUE TITLE
display integrity resqust headers?

### ISSUE THREAD

**Issue by shinhwagk** [Huachao/vscode-restclient#383]

**Comment by Huachao** [comment]
Could you please provide more details？

**Comment by shinhwagk** [comment]
When I click 'send request', I actually can't see the actual request header.

**Comment by Huachao** [comment]
@shinhwagk you can set the `rest-client.previewOption` to `exchange` to view the underlying sent request

**Comment by shinhwagk** [comment]
:+1:
