### ISSUE TITLE
Default Content-Type or Content-Type Setting

### ISSUE THREAD

**Issue by adarshmadrecha** [Huachao/vscode-restclient#386]
Many use this extension to test the APIs. In order to test the API which expects the `Content-Type` to be set as `application/json`. Which I believe is true for most of the `JSON` based APIs. Needs to add an extra line to every `Send` Request.

It would save time and also give convenience to users if they could set the default `Content-Type` value in settings of this plugin.

**Comment by Huachao** [comment]
@adarshmadrecha actually you could use the `rest-client.defaultHeaders` setting to add your default headers for all outgoing requests, like 
```json
"rest-client.defaultHeaders": {
      "Content-Type": "application/json"
}
```
