### ISSUE TITLE
Parameter value not encoded correctly

### ISSUE THREAD

**Issue by jjeejj** [Huachao/vscode-restclient#388]
- VSCode Version: 1.36.0
- OS Version: Win: Windows_NT x64 6.1.7601
- REST Client Version: 0.21.3

when i send a requet:
```
POST {{baseUrl}}/test
Content-Type: application/x-www-form-urlencoded

base64_code_str=sdsdsds+sdsdsd
```
The `+` in the base64_code_str parameter is replaced by a space 
`base64_code_str=sdsdsds sdsdsd`

**Comment by Huachao** [comment]
@jjeejj You can use set the setting `rest-client.formParamEncodingStrategy` to `never` to keep the request body as is.
