### ISSUE TITLE
upper case name headers are sended in lower case

### ISSUE THREAD

**Issue by lebretr** [Huachao/vscode-restclient#39]
- VSCode Version: 1.5.3
- OS Version: Linux Mint 18
- REST Client Version: 0.8.3

Steps to Reproduce:

1. create a new rest message with specific headers with upper case
exemple:

```
POST http://myserver/ws/myapi/v1 HTTP/1.1
Content-Type:application/json
Accept:application/json
Company-Bu-Code:010
TEST:010

{
  "messasge": "0000010001"
}
```

2. send the message (ctrl+alt+R)

Problem, the specifics headers are send in lower case:
Company-Bu-Code => company-bu-code
TEST => test

**Comment by Huachao** [comment]
@lebretr thanks so much, and this fix will be deployed in next release. 😄

**Comment by Huachao** [comment]
@lebretr you can try the latest version 0.8.4 now, thanks

**Comment by lebretr** [comment]
It's OK.

Thanks

**Comment by qiaoxingxing** [comment]
This bug has reappeared in v0.25.1
