### ISSUE TITLE
Copy Request as HTTPie

### ISSUE THREAD

**Issue by sopel** [Huachao/vscode-restclient#392]
Hi @Huachao, first and foremost, many thanks for putting this brilliant extension together!

Given your focus on simplicity and a respectively _intuitive UI_, I'm surprised that you only seem to support copying requests as cURL and not also as the likewise brilliant [HTTPie](https://httpie.org/), which aims to be a modern and intuitive alternative to cURL and is thus perfectly aligned with your extension's goals.

I've found a [reference to HTTPie](https://github.com/Huachao/vscode-restclient/search?q=httpie&unscoped_q=httpie) in the changelog for [0.14.3 (2017/5/12)](https://github.com/Huachao/vscode-restclient/blob/master/CHANGELOG.md#0143-2017512), but haven't been able to correlate this with any code or hidden feature:

> **Bug Fix**: Fix bug to allow generate code snippet for `cURL`, `httpie `and `wget`

Has this already been available at some point? If not, would you consider adding it?

Cheers,
Steffen

**Comment by Huachao** [comment]
@sopel the `Copy Request As cURL` is an easy way to use [`Generate Code Snippet`](https://github.com/Huachao/vscode-restclient/#generate-code-snippet), we support various languages and libraries to generate the code snippet, and you can copy the generated code snippet. I think the usage `HTTPie` is not very common as `cURL`, so I'd like to not put it as a separate command.
