### ISSUE TITLE
can not execute

### ISSUE THREAD

**Issue by Yvonne-Z** [Huachao/vscode-restclient#393]
- VSCode Version: 1.36.1(user setup)
- OS Version: Win10
- REST Client Version: 0.21.3

Steps to Reproduce:

When I prepared a request(ctrl + Alt + R), "command 'git.openChange' not found" is shown.
![キャプチャ](https://user-images.githubusercontent.com/53161574/61603883-fdbfd400-ac71-11e9-8901-bd5e87433b37.PNG)

Is there any solution?

**Comment by Huachao** [comment]
@Yvonne-Z open the keybinding setting panel of VSCode, and reset the keybinding of `git.openChage`, on my machine, `git.openChange` has no default keybinding
