### ISSUE TITLE
Explorer UI for .rest/.http files

### ISSUE THREAD

**Issue by OysteinAmundsen** [Huachao/vscode-restclient#401]
Hi.

This extension is great. The option to store requests as a way to document api's right inside the source folder for my api is fantastic. But what would be even more fantastic, is if there was a UI explorer available to browse all my *.rest files - like the `Test Explorer UI`. 

For me, this feature would make tools like "Postman" or "Insomnia" completely redundant.

**Comment by Huachao** [comment]
Duplicate of #360
