### ISSUE TITLE
package.json schema error

### ISSUE THREAD

**Issue by 502647092** [Huachao/vscode-restclient#405]
https://json-schema.org/understanding-json-schema/reference/numeric.html?highlight=exclusiveminimum#range
```
        "rest-client.largeResponseBodySizeLimitInMB": {
          "type": "number",
          "default": 5,
          "minimum": 0,
          "exclusiveMinimum": true, <= this need change to 0
          "scope": "resource",
          "markdownDescription": "Set the response body size threshold of MB to identify whether a response is a so-called 'large response', only used when `rest-client.disableHighlightResonseBodyForLargeResponse` and/or `rest-client.disableAddingHrefLinkForLargeResponse` is set to true"
        },
```

**Comment by Huachao** [comment]
@502647092 as you can see in the link you've provided, the `exclusiveMinimum` can be boolean and work with `minimum` together, if true, the `minimum` value is excluded.

**Comment by Huachao** [comment]
@502647092 as you can see in the link you've provided, the `exclusiveMinimum` can be boolean and work with `minimum` together, if true, the `minimum` value is excluded.
