### ISSUE TITLE
waiting icon is not align

### ISSUE THREAD

**Issue by 502647092** [Huachao/vscode-restclient#407]
- VSCode Version: 1.37.1
- OS Version: Windows
- REST Client Version: 0.22.0

Steps to Reproduce:

1. Send Request
2. waiting icon is not align
![temp](https://user-images.githubusercontent.com/10203793/63340255-2e7e5080-c379-11e9-87fb-770e8970ad3c.gif)

![temp](https://user-images.githubusercontent.com/10203793/63340275-3d650300-c379-11e9-8a44-0baca7032ab5.gif)

**Comment by Huachao** [comment]
@502647092 do you mean the icon is not align in the second screenshot or both?

**Comment by 502647092** [comment]
@Huachao 
both
first screenshot is in vscode
second screenshot is in theia(compatible vscode ext)

**Comment by Huachao** [comment]
@502647092 I can't repro this in vscode, and since I am using the official octicon, and the spin style is suggested by VSCode itself. So I'd like to close it.
