### ISSUE TITLE
XML结果集中的< 和 > 会显示成 &lt; 和 &gt

### ISSUE THREAD

**Issue by purlintan** [Huachao/vscode-restclient#41]
- VSCode Version:1.5.3
- OS Version:win10
- REST Client Version:0.8.3

返回的结果集是XML，但会 < 和 > 会显示成 &lt; 和 &gt; ， 能不能让返回结果集显示回 < 和 > 呢？

**Comment by Huachao** [comment]
@purlintan sorry for the delay, can you provide me the raw response, and you can get the raw response by click saving button

**Comment by purlintan** [comment]
<img width="890" alt="image" src="https://cloud.githubusercontent.com/assets/16349756/19257750/aac46000-8fa4-11e6-8113-6aa106331e7c.png">

**Comment by Huachao** [comment]
@purlintan thanks so much and you can try the latest version 0.8.5 for verifying 😄
