### ISSUE TITLE
Request variable did not work

### ISSUE THREAD

**Issue by incubus8** [Huachao/vscode-restclient#411]
- VSCode Version:1.37.1
- OS Version: MacOs  10.12.6
- REST Client Version: 0.22.0

**Steps to Reproduce:**

1.  The following:
```

@host = someservice
@username = XXX
@password = XXXX

# @name login

POST {{host}}/login HTTP/1.1
Content-Type: application/json

{
	"password": "{{password}}",
	"username": "{{username}}"
}

###

@accessToken = {{login.response.body.accessToken}} // did not work, see screenshot
@sessionId = {{login.response.body.sessionId}} // did not work, see screenshot

# @name logoutApi

POST {{host}}/logout HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
	"id_session": "{{sessionId}}"
}

```
2. Execute named `login` request
3. Execute named `logout` request
4. Error missing variable
5. Linter also showed error (see screenshot)
<img width="413" alt="Screen Shot 2019-08-28 at 10 55 43 AM" src="https://user-images.githubusercontent.com/5300674/63824754-71948100-c982-11e9-88bd-593119f5aba7.png">

**Expectation:**
Should not give error and the variable assignation should work

**Comment by Huachao** [comment]
@incubus8 can you show me the response of `login` request?

**Comment by incubus8** [comment]
Login response

```
HTTP/1.1 200 OK
Date: Wed, 28 Aug 2019 13:34:39 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: close
Vary: Accept-Encoding
Cache-Control: no-store
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains; always
Content-Encoding: gzip
Set-Cookie: XYZ01100d5f=XYZ; Path=/

{
  "access_token": "3832a09ab8b3d2883832a09ab8b3d288",
  "sessionID": "0yketi"
}
```

**Comment by Huachao** [comment]
So the json path of the request variable should be access_token instead of accessToken

**Comment by incubus8** [comment]
@Huachao my bad.. I'm newbie on this, thanks for the help
