### ISSUE TITLE
Options to not working with plaintext

### ISSUE THREAD

**Issue by SardineFish** [Huachao/vscode-restclient#415]
Currently, the snipets in this extension is working in plaintext such as *.txt, which will be trigger unexpectly when typing with normal text. 
Is it possible to remove the snipets with plaintext in `package.json` or provide settings to specific which file type to enable this extension.

**Comment by Huachao** [comment]
@SardineFish nice catch, I prefer removing the snippet support for plaintext file

**Comment by Huachao** [comment]
@SardineFish you can try the latest version 0.22.1

**Comment by SardineFish** [comment]
Thanks a lot :smiley:
