### ISSUE TITLE
How to redirect response.body into a specific file?

### ISSUE THREAD

**Issue by snyang** [Huachao/vscode-restclient#417]
- VSCode Version: 1.38
- OS Version: Windows
- REST Client Version: Present

We implemented a rest api which will output a specific file with content-type:  application/octet-stream.
How to use the extension to save response.body into a specific file?

**Comment by Huachao** [comment]
@snyang you can check out the [Save the Response Body](https://github.com/Huachao/vscode-restclient#save-response-body) doc.
