### ISSUE TITLE
Native .env file support?

### ISSUE THREAD

**Issue by mattwaler** [Huachao/vscode-restclient#418]
I'm using `.env` files to do all of my secret hiding. It kinda stinks to have to translate the values to JSON in the settings folder. Is it feasible/possible to be able to access `.env` file values at the root of the folder to be accessible by the extension? Maybe via `{{$dotenv PORT}}` for a file named `.env` and `{{$dotenvLocal PORT}}` for a `.env.local` file?

**Comment by Huachao** [comment]
@mattwaler nice suggestion, I will implement it and update in this thread later

**Comment by Huachao** [comment]
@mattwaler @Ruegen @yfwz100 @devalnor  I have supported the `{{$dotenv variableName}}` syntax, and you just need to put the .env file in the same folder of your `.http` file. However, `.env.local` file is not supported currently.

**Comment by mattwaler** [comment]
Awesome! Thank you so much for this amazing extension.

**Comment by Huachao** [comment]
@mattwaler @Ruegen @yfwz100 @devalnor  you can try the latest version 0.23.0 to verify it.

**Comment by yfwz100** [comment]
It works, Thanks!

**Comment by tomdavidson** [comment]
Is the use case of  {{$dotenv variableName}} in an environment variable value supported?

**Comment by mattwaler** [comment]
@tomdavidson Yes, when the .env file and .http file are in the same directory this works as intended.

**Comment by tomdavidson** [comment]
@mattwaler thanks, ill open up an issue then.

**Comment by rufreakde** [comment]
@Huachao does this syntax also work in the workspace config?

```json
  "rest-client.certificates": {
    "<domain>": {
      "pfx": "test/some/path/dev/cert", //change the p12 cert paths for different landscapes
      "passphrase": "{{$dotenv pass}}" //p12 passphrase
```

This seems not to work any pointers here?

**Comment by shaunakv1** [comment]
@Huachao  can we specify the location of .env file? or walk up to the root of current vscode project?  My `.env` file usually lives in the root of code, and .http files are in a test directory

**Comment by nazarEnzo** [comment]
.env does not have to be in the same folder anymore. I used existing .env in the root of the project while making requests from subfolders and it works perfectly fine 👍
