### ISSUE TITLE
POST send json data case sensitive

### ISSUE THREAD

**Issue by CwjXFH** [Huachao/vscode-restclient#419]
- VSCode Version: 1.38.1
- OS Version: Windows10
- REST Client Version: 0.22.0

When JSON key starts with a capital letter, in post request, it can't send JSON data to the server.

**Comment by Huachao** [comment]
@CwjXFH could you please provide for details for the underlying request?

**Comment by CwjXFH** [comment]
Sorry for the late reply.

Because of some history reason, my project deserialization is case-sensitive. So, I think this is what causes the HTTP request error.

Thanks!

**Comment by Huachao** [comment]
👌
