### ISSUE TITLE
Header auto completion is broken in the newest version

### ISSUE THREAD

**Issue by Emory-M** [Huachao/vscode-restclient#422]
- VSCode Version: 1.38.1
- OS Version: macOS 10.14.4
- REST Client Version: 0.22.1

Steps to Reproduce:

1. switch vscode to http language.
2. type some http header  like Content-Type, not any code completion tips.
3. downgrade version to 0.22.0 the auto completion is working.

**Comment by Huachao** [comment]
@Emory-M already fixed ffbd8f2 and will be published in next release

**Comment by Huachao** [comment]
@Emory-M you can download the latest version 0.22.2 to verify it.

**Comment by Emory-M** [comment]
@Huachao It's working, Thank you!
otherwise, about the http code snippet 
use ${2:${3:header name}: ${4:header value}} in the header section can be better to use.
fast to delete whole header section if not have any custom header, and then back to use autocomplete to fill.

**Comment by Huachao** [comment]
@Emory-M I add the header related lines for `POST` and `PUT` requests, and I think these requests should contain a body as well as the `Content-Type` header.

**Comment by MisLink** [comment]
Hi, I have the same issue.

It's very strange. In my some new projects, auto complete is broken:
<img width="430" alt="图片" src="https://user-images.githubusercontent.com/8280169/75270648-de0b1280-5835-11ea-82ea-10e65624712c.png">
But in a my old project it works.

I tried to rollback to 0.23.0 and 0.22.2, it still doesn't work. Then I found this issue, I tried to rollback to 0.22.0, it works.

**Comment by Huachao** [comment]
@MisLink what's the language of your file?

**Comment by MisLink** [comment]
Well.. which kind of language? My vscode language is zh-cn, http file's language is associated to http, all my projects are pure python..

**Comment by Huachao** [comment]
@MisLink could you please check the output window of VSCode of the `REST` channel to see if any error message exists
![屏幕快照 2020-02-26 下午3 05 27](https://user-images.githubusercontent.com/2796177/75320394-860df380-58a9-11ea-8e80-4da94e962995.png)

**Comment by MisLink** [comment]
@Huachao I changed the `"rest-client.logLevel"` to `verbose`, but there are not any messages while I trigger the suggest.

**Comment by Huachao** [comment]
@MisLink Is your `.http` file a blank file, and did you try to type some characters to see the completion item list?

**Comment by MisLink** [comment]
Nope, it's not blank, there are some requests created by snippets.

I think I found the difference: my old project has these workspace config about rest-client but new one hasn't:
```json
"rest-client.environmentVariables": {
    "$shared": {
      "content_type": "application/json"
    },
    "local": {
      "host": "http://127.0.0.1:5000"
    },
    "dev": {
      "host": "***:5001"
    },
    "prod": {
      "host": "***"
    }
  }
```
Commenting these lines causes auto-complete to fail.
In my new project, add these line to workspace config:
```json
"rest-client.environmentVariables": {
    "$shared": {},
    "local": {}
  }
```
auto-complete back to normal.
