### ISSUE TITLE
Focus of cursor moves to response tab once you send the request

### ISSUE THREAD

**Issue by rohitkrishna094** [Huachao/vscode-restclient#423]
- VSCode Version: `1.38.1`
- OS Version: `Windows 10`
- REST Client Version: `0.22.2`

#### Steps to Reproduce:

1. Type any request(GET or POST etc) and click `Send Request` or press `CTRL + ALT + R`
2. Now the response is shown, but its shown in the right side tab. However the cursor's focus, which was supposed to be in the rest client's (.http or .rest file's I mean) editor, is now gone.

#### What should happen?
When someone clicks or triggers `Send Request`, the focus should stay within the editor where they are typing these requests to begin with.

#### Why would you need this?
When we just want to trigger requests rapidly just to see if the endpoint is working or to check TTL time go down(in case this is sent by server), or see some change in json fields(response) as we hit enter. This can be achieved in postman for example by rapidly hitting Send button or pressing `CTRL + ENTER`.

##### Note:
I am not sure if this is a duplicate(if so please tag that issue and close this one). I am also not sure if this was by design or if this is not possible to do in vscode as of today. Hence I put it as a bug instead of feature. Let me know, I will change this to a feature issue.

**Comment by Huachao** [comment]
@rohitkrishna094 you can achieve this by set the setting `rest-client.previewResponsePanelTakeFocus` to `false`. Thanks for your detailed issue description.
