### ISSUE TITLE
http header content-length should be recalculated before sending out requests just like fiddler does, otherwise it's value is incorrect and causing server errors

### ISSUE THREAD

**Issue by RobertWu-TIBCO** [Huachao/vscode-restclient#424]
- VSCode Version:
- OS Version:

版本: 1.38.1 (system setup)
提交: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
日期: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.15063

- REST Client Version: 0.22.2

Summary： 如果content-length存在，rest client不会重新计算，编辑内容后重发就会导致发出的content-length值错误，服务端就会出问题。

如果不存在，rest client会自动生成正确的。
content-length应该始终重新计算，即自动生成，而不是使用传入的。否则导致服务器端问题。

Summary : Rest client itself should always generate content-length like fiddler does even if user provides such http header (which may become incorrect once content changed , hence causing server side errors)

Steps to Reproduce:
1.  prepare any post request like below:

POST /updateMaterialv2 HTTP/1.1
User-Agent: Fiddler
Host: localhost:4000
Content-Length: 437
Content-Type: application/json; charset=utf-8
Accept-Encoding: gzip
Connection: close

{"comp": "400","item": "00904100005","logn": "b555551","wldhData": {},"wljhData": {"fltm": 1.00,"otmf": 75,"plid": "240976","ptmf": 75},"wltjData": {"wltj": "---"},"zxbzData": {}}

2. use tcptrace to listent to port 4000 and forward to any port that allows post data.

3. send the data via rest client and then send in fiddler

4. compare the tcptrace , you will see  Content-Length field would not be calculated in rest client, but recalculated in fiddler:

左边是vscode使用rest client插件发送的，右边是fiddler发送的.
rest client插件没有重新计算content-length并重写之，导致到达flask的请求全部无法使用parseParams函数解析.

![5b086810abddf875bee22daef1ca7c6](https://user-images.githubusercontent.com/20295019/65748559-d6382c80-e136-11e9-8948-6ab432f3a3b1.png)

```
def parseParams(request):
    params = request.json if request.method == "POST" else request.args
    log.logger.warn('###parse params : {}'.format(str(params)))
    return params
```
简言之，如果content-length存在，不会重新计算，这样编辑内容后重发就会导致发出的content-length值错误。在服务端就会出问题。如果不存在，rest client会自动生成正确的。
是否需要调整为，content-length始终重新计算即自动生成，而不是使用传入的。否则导致服务器端问题。
注意： Accept-Encoding: gzip 会自动加上。

**Comment by Huachao** [comment]
@RobertWu-TIBCO you can try the latest version 0.23.0 to verify
