### ISSUE TITLE
JSONPath filter not working

### ISSUE THREAD

**Issue by ilog2000** [Huachao/vscode-restclient#425]
- VSCode Version: 1.38.1
- OS Version: Windows 10 1903
- REST Client Version: latest

Steps to Reproduce:

1.  Simulate JSON response for variable `env` as
```
[
  {
    "Id": "1",
    "Name": "Name 1"
  },
  {
    "Id": "2",
    "Name": "Name 2"
  },
  {
    "Id": "3",
    "Name": "Name 3"
  }
]
```
2. Try to use variable `env` as
```
{{env.response.body.$[?(@.Name="Name 2")].Id}}
```
I always get the first object in array which is wrong.

**Comment by Huachao** [comment]
@ilog2000 I think the reason is that your JSON path is not correct, it should be `{{env.response.body.$[?(@.Name=="Name 2")].Id}}`, since it uses `==` for equality check

**Comment by ilog2000** [comment]
I tried == as well but it did not help. In this case the expression itself comes to query string non-parsed, which is completely wrong. I mean variable value contains the expression.

**Comment by ilog2000** [comment]
Here is how request looks like
```
GET https://domain.com/api/environments/%7B%7Benv.response.body.$[?(@.Name==%22Name 2%22)].Id%7D%7D HTTP/1.1
Accept: application/json
```

**Comment by ilog2000** [comment]
Oh, sorry, my bad. It works with `==`, there was a typo in Name. Thank you very much for prompt response.
