### ISSUE TITLE
When sending a request with request body from a file, variables aren't parsed and replaced

### ISSUE THREAD

**Issue by tom-thorne** [Huachao/vscode-restclient#427]
- VSCode Version: 1.38.1
- OS Version: Mac osx 10.14.5
- REST Client Version: 0.22.2

1. Setup a request like this:
```
POST https://foobar.co/resources

< ./resource.json
```

2. put variables in the resource.json file, eg

```
{
  "id": {{orderId}},
  "locationId": "{{locationId}}",
 ...
}
```

3. send the request

Actual behaviour
* the file is sent as a request as is

Desired behaviour
* the file is parsed to substitute variables, and then sent as a request

**Comment by Huachao** [comment]
@tom-thorne this is by design, we don't intend to touch the imported files
