### ISSUE TITLE
Add code snippet for request / request-promise or axios in NodeJS

### ISSUE THREAD

**Issue by DefJunx** [Huachao/vscode-restclient#428]
Let me begin by saing that this extension is the real deal and so nice to use in a pinch.

With that out of the way, I was wondering if it could be possible to add a snippet generator which uses request / request-promise or axios, considering they're arguably the most used packages nowadays I believe.

**Comment by Huachao** [comment]
@DefJunx I use the `httpsnippet` package to generate code snippet, I will assign the `upstream` label to this issue and continuously track the progress.

**Comment by chevtek** [comment]
I would definitely love an axios code snippet. Also, I agree that this extension is top notch!

**Comment by Huachao** [comment]
@DefJunx @chevtek @hellorayza @Spanhaak this will be supported in the next release.

**Comment by Huachao** [comment]
@DefJunx @chevtek @hellorayza @Spanhaak you can try the latest version 0.24.2
