### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by gritcsenko** [Huachao/vscode-restclient#429]
[humao.rest-client-unresponsive.cpuprofile.txt](https://github.com/Huachao/vscode-restclient/files/3682833/humao.rest-client-unresponsive.cpuprofile.txt)

- Issue Type: `Performance`
- Extension Name: `rest-client`
- Extension Version: `0.22.2`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.38.1`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by Huachao** [comment]
@gritcsenko does this unresponsive situation continuously occurs?

**Comment by gritcsenko** [comment]
@Huachao no, looks like it is fixed, thanks.
