### ISSUE TITLE
Handle urls with urlencoded query params

### ISSUE THREAD

**Issue by dogoku** [Huachao/vscode-restclient#43]
- VSCode Version: 1.5.3
- OS Version: Win7 64bit
- REST Client Version: 0.8.5

Steps to Reproduce:
1.  Give a url that is already urlencoded `http://example.com.com/api/users/list?params=NC%2CN%2CVL%2CV`

Expected that the result will be the same as cur/browser, but instead, it encodes the url again, resulting in the backend receiving `NC%2CN%2CVL%2CV` instead of `NC,N,VL,V`

Same issue if encoded values are part of the path instead of just the query string.

P.s: I tried using the dev tools to find the actual request being made, but it does not appear in the network tab. Is there a way to see the actual requests (that doesnt involve sniffing with an external program)

**Comment by Huachao** [comment]
@dogoku thanks so much, and I have fixed the issue, you can try the latest version 0.8.6 to verify

**Comment by dogoku** [comment]
That was fast, i'll have a go at it when i see the update in my vscode
