### ISSUE TITLE
Header name must be a valid HTTP token ["{"]

### ISSUE THREAD

**Issue by dcsan** [Huachao/vscode-restclient#430]
I had a previous simple test file that was working
I tried to add a couple of requests in the same file
but now I just get the error above on any request... 

I tried reverting any changes to the `.http` file
but still the extension just gives this invalid error each time i try to load a resource.

- VSCode Version: Version: 1.38.1

- OS Version: OSX 10.14.6
- REST Client Version: 0.22.2

Steps to Reproduce:

1.  make a file with some simple tests like

```
POST http://localhost:55200/test HTTP/1.1
content-type: application/json
{
    "cname": "weile"
}
```

all will work fine. wait a while. do something?
then error occurs:

2. try and run click 'send request'

error message pops up as toast.

**Comment by dcsan** [comment]
OK looks like the error is:

```
POST http://localhost:55200/test HTTP/1.1
content-type: application/json
{
    "cname": "weile"
}
```

where as this is OK:
```
POST http://localhost:55200/test HTTP/1.1
content-type: application/json

{
    "cname": "weile"
}
```

**Comment by dcsan** [comment]
so the extra line is critical.  a bit of a pedantic bug...

**Comment by Huachao** [comment]
@dcsan this follows the rules in RFC, and there should be a separated blank line between header and body parts.

**Comment by viT-1** [comment]
Error text about the blank line in message box should be clear.

**Comment by intoku** [comment]
Exactly @viT-1  - The error is so vague, took me lot of time to find this out - Just a simple notification error would help many users;

**Comment by akshayjai1** [comment]
Just so that a newbee gets it, 

`GET http://localhost:3099/subscribers
GET http://localhost:3099/subscribers`
 while following code will not
`GET http://localhost:3099/subscribers

GET http://localhost:3099/subscribers`

**Comment by AleksandrIvanov9655** [comment]
i dont understand well how to fix this error

**Comment by SagarBobade** [comment]
Under Headers section click for hidden(headers). And remove duplicate headers(key-values). 
that's it..!!! 
try again to call API(or run collection).

**Comment by ramos07** [comment]
> i dont understand well how to fix this error

@AleksandrIvanov9655 Leave an empty line between your request headers and request body

**Comment by Jiran03** [comment]
i can solve it by manually retyping the command

**Comment by mjmatthiesen** [comment]
This is closed, but I am bumping this because the error message should be clear, because currently it's not, I had to search here to figure it out.

**Comment by Radolumbo** [comment]
The above is still true, the error message is very unclear. I had to come here to figure it out, as well.

**Comment by Sanjit-Prasad** [comment]
Life Saviour @dcsan

**Comment by joyfullservice** [comment]
@Huachao - An improved error message would be very helpful, and probably collectively save hundreds of hours of developer time trying to figure out why the requests are failing.

**Comment by samirmorales** [comment]
POST http://localhost:55200/test HTTP/1.1

content-type: application/json
{
    "cname": "weile"
}

Inserta un salto de línea luego de la primera, eso me funcionó

**Comment by joyfullservice** [comment]
![image](https://user-images.githubusercontent.com/7254992/129761036-a2436b4b-f6d0-41cd-afd9-1f00779e3db6.png)

**Comment by gopalbogati** [comment]
Before 
<img width="961" alt="Screen Shot 2021-09-25 at 1 00 27 pm" src="https://user-images.githubusercontent.com/7541457/134755747-a757ad5f-8bc0-4f3a-9b62-3d6ad6ff5e01.png">

After removing space between POST and content-type fixed the issue of internal server error
<img width="899" alt="Screen Shot 2021-09-25 at 12 59 04 pm" src="https://user-images.githubusercontent.com/7541457/134755782-c31bbb99-4df1-47a9-8bd1-3e4809542f57.png">
e

**Comment by Huachao** [comment]
> Before 
> 
> <img width="961" alt="Screen Shot 2021-09-25 at 1 00 27 pm" src="https://user-images.githubusercontent.com/7541457/134755747-a757ad5f-8bc0-4f3a-9b62-3d6ad6ff5e01.png">
> 
> 
> 
> After removing space between POST and content-type fixed the issue of internal server error
> 
> <img width="899" alt="Screen Shot 2021-09-25 at 12 59 04 pm" src="https://user-images.githubusercontent.com/7541457/134755782-c31bbb99-4df1-47a9-8bd1-3e4809542f57.png">
> 
> e
> 
> 

Remove the blank line between request url line and content type header line

**Comment by ashiqqs** [comment]
Thanks @Huachao

**Comment by lazlanrafar** [comment]
![image](https://user-images.githubusercontent.com/52142835/181295091-270fca20-911a-47a3-983e-50f05597c420.png)

change to :
![image](https://user-images.githubusercontent.com/52142835/181295158-604696a4-91e6-4654-9dc3-6c27dbe4b150.png)

**Comment by joyfullservice** [comment]
@Huachao - Would you be willing to reopen this issue for the purpose of clarifying the error message that is sent to the user? That seems to be the greatest desire on the part of the people that have contributed to this thread. Yes, I understand that it is RFC compliant to have the blank line there, but the problem is that many users are spending hours trying to troubleshoot a very ambiguous error message.

What I think we would all love to see is a **helpful message during the validation process before the request fires**. It seems like this could be a simple RegEx expression to confirm that there is indeed a blank line between the headers and the body. If not, a message could be shown to the user.

> Invalid Request Format: Please include a blank line between the header and body of the request.

This simple validation could save a huge amount of frustration for new users that are using this tool for the first time.

Thank you for your consideration!!!

For anyone else that is browsing this thread, please add your upvote if you think this would be a helpful addition!  😄

**Comment by aj1603** [comment]
@joyfullservice Thank you! Your answer is working.

**Comment by WilHazz** [comment]
no puedo creer que el error que me aparece es por no separar el encabezado con los { } los separe y ya corrió

**Comment by daracenadevelop** [comment]
> ![image](https://user-images.githubusercontent.com/7254992/129761036-a2436b4b-f6d0-41cd-afd9-1f00779e3db6.png)

Very good, thanks for help.

**Comment by HannahNguyen6729** [comment]
> OK looks like the error is:
> 
> ```
> POST http://localhost:55200/test HTTP/1.1
> content-type: application/json
> {
>     "cname": "weile"
> }
> ```
> 
> where as this is OK:
> 
> ```
> POST http://localhost:55200/test HTTP/1.1
> content-type: application/json
> 
> {
>     "cname": "weile"
> }
> ```

thanks a lot

**Comment by MarleneGray** [comment]
Thanks! It took me 30 minutes before reading this post!

**Comment by yenmangu** [comment]
This fails

```
POST {{ContosoPizza_HostAddress}}/pizza/
Content-Type: application/json
{
	"name":"Hawaii",
	"isGlutenFree": false
}
```
The error received is this

`Header name must be a valid HTTP token ["{"]`

![image](https://github.com/Huachao/vscode-restclient/assets/70646989/60ac366f-80d4-441e-94b6-9ce8ff397f70)

But this
```
POST {{ContosoPizza_HostAddress}}/pizza/
Content-Type: application/json

{
	"name":"Hawaii",
	"isGlutenFree": false
}
```

Is successfull.

It has been documented above many times that a new line is necessary yet the error message is very unclear about this.

Can we reopen the issue, to provide a clearer message?
It took me half an hour of searching to understand why the request was failing before finding this.

**Comment by yenmangu** [comment]
> This is closed, but I am bumping this because the error message should be clear, because currently it's not, I had to search here to figure it out.

Again I am also bumping as this has STILL not been resolved.

**Comment by TheWrightDev** [comment]
Had to search the header error today which brought me here. Easy enough fix but definitely wouldn't have guessed the space was the issue.
