### ISSUE TITLE
Copy as cURL not working well for POST requests against ExpressJs

### ISSUE THREAD

**Issue by sinapis** [Huachao/vscode-restclient#431]
- VSCode Version: 1.38.1
- OS Version: Windows 10, 18995.1
- REST Client Version: 0.22.2
- cURL Version: curl 7.47.0

Steps to Reproduce:

1. Create the following HTTP request in VSCode:
post http://localhost/test/1

2. ctrl+p and Rest Client: Copy request as cURL

3. Paste

Expected: curl --request POST --url http://localhost/test/1

Actual: curl --request post --url http://localhost/test/1

when it used against ExpressJs server the returned output is:

curl: (52) Empty reply from server

with POST (in uppercase), it works as expected.

**Comment by Huachao** [comment]
@sinapis I have fixed this and will publish this in next release

**Comment by sinapis** [comment]
@Huachao thank you for the quick response!!

**Comment by Huachao** [comment]
@sinapis you can try the latest version 0.23.0 to verify

**Comment by sinapis** [comment]
verified!
