### ISSUE TITLE
Local datetime dynamic variable instead of UTC

### ISSUE THREAD

**Issue by schallm** [Huachao/vscode-restclient#433]
I need to send the datetime with local offset to an API (`2019-10-15T10:45:50.124-05:00`).  I see that you can use `{{$datetime iso8601}}` to get the current datetime, however that is returns a UTC date (`2019-10-15T15:45:50.124Z`).  Is this currently possible?  If not, maybe add:

* another dynamic variable like `{{$datetimeLocal}}`
* another modifier to datetime to make it local like `{{$datetime local iso8601}}`

I tried to use formatting `"timestamp": "{{$datetime 'YYYY-MM-DDTHH:mm:ss.SSSZZ'}}"`, but that still returns a UTC (`2019-10-15T15:45:50.124+0000`) since `$datetime` is actually UTC.

**Comment by Huachao** [comment]
@schallm I added a new variable named `$localDatetime`, just as your first solution. And this patch will be published in next release

**Comment by Huachao** [comment]
@schallm you can try the latest version 0.23.0 to verify it.

**Comment by schallm** [comment]
Works great!  Thanks!
