### ISSUE TITLE
Add config option to control auto Camel-Case feature when `previewOption` is set to `exchange`

### ISSUE THREAD

**Issue by wujunchuan** [Huachao/vscode-restclient#435]
Add a extension config option to control the **custom request header Camel-Case**

For example there is a HTTP request 👇 

```http
@HOST=http://localhost:8888
GET {{HOST}}/collect/mockindex/ HTTP/1.1
auth: "Coll 2.bQk0e2sNddsmNdNdYcaTPszg"
lang: "zh"
```

## Current

```http
GET http://localhost:8888/collect/mockindex/ HTTP/1.1
Auth: "Coll 2.bQk0e2sNddsmNdNdYcaTPszg"
Lang: "zh"
User-Agent: vscode-restclient
Accept-Encoding: gzip
```

The custom HTTP headers `auth` and `lang`  will auto uppercase its first letter

## Except

```http
GET http://localhost:8888/collect/mockindex/ HTTP/1.1
auth: "Coll 2.bQk0e2sNddsmNdNdYcaTPszg"
lang: "zh"
User-Agent: vscode-restclient
Accept-Encoding: gzip
```

**Comment by Huachao** [comment]
@wujunchuan I have fixed the issue and will always preserve the outgoing request headers case.

**Comment by Huachao** [comment]
@wujunchuan you can try the latest version 0.23.0 to verify it

**Comment by wujunchuan** [comment]
@Huachao  works well, it will not puzzle me again now
