### ISSUE TITLE
308 Permanent Redirect changes method to GET

### ISSUE THREAD

**Issue by razzfox** [Huachao/vscode-restclient#436]
- VSCode Version: 1.39.2
- OS Version: macOS 10.15
- REST Client Version: 0.22.2

Steps to Reproduce:

1. Send request using POST method.
2. Server responds with status 308 Permanent Redirect
3. REST-client resends request using method GET method.

According to [https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections#Permanent_redirections](these docs), the method and body should not change.

**Comment by Huachao** [comment]
@razzfox nice catch, this fix will be published in the next release.

**Comment by Huachao** [comment]
@razzfox you can try the latest version 0.23.0 to verify it
