### ISSUE TITLE
How to not show references?

### ISSUE THREAD

**Issue by rohitkrishna094** [Huachao/vscode-restclient#438]
Check the image below.

![Screenshot (5)](https://user-images.githubusercontent.com/18495886/68225506-86af1100-ffbe-11e9-85d1-af936ae868c3.png)

Is there a way to remove the word `references` if I don't want them to be displayed and take up space?

**Comment by Huachao** [comment]
@rohitkrishna094 you can achieve this by set the setting `rest-client.enableCustomVariableReferencesCodeLens` to `false`

**Comment by rohitkrishna094** [comment]
Thanks for your response. btw where can I find all these settings that I can change? Is there a doc somewhere? Thanks

**Comment by Huachao** [comment]
@rohitkrishna094 at the bottom of the README.md
