### ISSUE TITLE
How to upload multiple files?

### ISSUE THREAD

**Issue by ri8ika** [Huachao/vscode-restclient#445]
I am trying to upload multiple files. But I'm not sure if I'm doing it correctly. And obviously it does not work:
```
POST https://api.example.com/user/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="1.png"
Content-Type: image/png

< ./1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="2.png"
Content-Type: image/png

< ./2.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
```

If I print the request, I can see 1.png but not 2.png. So, how to upload multiple files? Sorry for this newbie and stupid question.

**Comment by Huachao** [comment]
@ri8ika can you ensure both the `1.png` and `2.png` exist in your directory, and I can succeed in my local test

**Comment by ri8ika** [comment]
Yes. Both exists.

But I'm surprised to know that I'm doing it right. Is it correct way by providing name for both the same? Or shouldn't it be something like an array?

I'm only able to see 1.png in my log.

**Comment by ri8ika** [comment]
Ah, finally I resolved it. I found the correct way after using postman. I have to remove the boundary line after `< ./1.png` .

**Comment by xiang-xx** [comment]
I found that `------WebKitFormBoundary7MA4YWxkTrZu0gW--` means end boundary, only appear at the end.


```
POST https://api.example.com/user/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="1.png"
Content-Type: image/png

< ./1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="2.png"
Content-Type: image/png

< ./2.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
```
