### ISSUE TITLE
Cannot read property "toFixed" of null 

### ISSUE THREAD

**Issue by katagaStyle** [Huachao/vscode-restclient#450]
- VSCode Version: 1.40.1
- OS Version: Linux
- REST Client Version: 0.23.0

Steps to Reproduce:
1. @host = https://xxx.xxx.xx
2. @serviceXXX = {{host}}/services/<service>
3. GET {{serviceXXX}}/actuator/health
4. issue: Cannot read property "foFixed" of null

Works fine with 0.22.x.

**Comment by Huachao** [comment]
Could you please provide the actual response and the screenshot of the duration breakdown when you hover on the timer icon?

**Comment by katagaStyle** [comment]
Within status bar i can see waiting message and when it disappears the error will be shown. 

No other message. No Result. 

![toFixed_of_null](https://user-images.githubusercontent.com/2486640/69735129-79ee8a80-1130-11ea-9bcf-d6f551c35c97.png)

**Comment by Huachao** [comment]
@katagaStyle thanks for your quick reply,    could you please also check the output named `REST` in the output channel of VSCode

**Comment by katagaStyle** [comment]
`[Error  - 08:50:29] Failed to send request:
TypeError: Cannot read property 'toFixed' of null
	at T.formatDurationStatusBar (/home/ad/.vscode/extensions/humao.rest-client-0.23.0/dist/extension.js:642:8115)
	at T.runCore (/home/ad/.vscode/extensions/humao.rest-client-0.23.0/dist/extension.js:642:6098)
	at processTicksAndRejections (internal/process/task_queues.js:89:5)
	at async T.run (/home/ad/.vscode/extensions/humao.rest-client-0.23.0/dist/extension.js:642:5559)`

**Comment by Huachao** [comment]
@katagaStyle I think I have fixed the issue, and could you please provide your actual request to help me verify the fix if convenient?

**Comment by katagaStyle** [comment]
> @katagaStyle I think I have fixed the issue, and could you please provide your actual request to help me verify the fix if convenient?

It is a pretty easy request to a health endpoint of an sprint boot webservice within our company network. 

`@host = https://xxx.xxx.de
@service = {{host}}/services/servicename/version

### status
GET {{service}}/actuator/health`

**Comment by SimonDever** [comment]
@Huachao at what times do you push fixes to the vscode marketplace? I am experiencing this issue as well.

**Comment by Huachao** [comment]
@SimonDever I am still working on some features, a newer release will be published after that. Before completion, you can still use the old version like **0.22.3** to test your APIs.

**Comment by SimonDever** [comment]
Thanks for the tip :)

**Comment by bendem** [comment]
Can you please release the bugfix? Or provide a workaround so we can keep using the extension in the meantime? ❤️

**Comment by Huachao** [comment]
@bendem Install the old version may work

**Comment by Huachao** [comment]
@SimonDever @bendem @katagaStyle @gustavoveronese I have published the latest version 0.23.1 and you can verify it.
