### ISSUE TITLE
Auto completion is partly broken

### ISSUE THREAD

**Issue by YorigamiShion** [Huachao/vscode-restclient#451]
- VSCode Version: 1.40.2
- OS Version: win10 18362.476
- REST Client Version: 0.23.0

Auto completion of headers (Content-Type) and variable does not work, while http methods and such as 'soap', 'fv', 'rv' still works.

**Comment by Huachao** [comment]
@YorigamiShion could you please provide the minimum sample http file to help me to identify the root cause?

**Comment by YorigamiShion** [comment]
> @YorigamiShion could you please provide the minimum sample http file to help me to identify the root cause?

I had found the reason, the extension `kite` is conflicted with rest client. When I disable it, all works well.
