### ISSUE TITLE
Post not passing body

### ISSUE THREAD

**Issue by idmacrae** [Huachao/vscode-restclient#452]
- VSCode Version: 1.40.2
- OS Version: Windows 10
- REST Client Version:

Steps to Reproduce:

1. I am able to successfully use to GET requests:
```
GET http://{{host}}/{{baseUrl}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer: {{authToken}}
```

However POST fails to send the body details
```
POST http://{{host}}/{{baseUrl}} HTTP/1.1
Authorization: Bearer: {{authToken}}
Content-Type: {{contentType}}

{
  "description": "Test description"
}
```
I get "Missing description" and the req.body is empty. When I post the _exact_ same from Postman it works correctly

**Comment by Huachao** [comment]
@idmacrae could you please replace the url with `http://httpbin.org/post`, and check the response? BTW, I think the correct `Authorization` header should be `Authorization: {{authToken}}`

**Comment by idmacrae** [comment]
Hi @Huachao 
Thanks for the response.
Replacing the url works fine. I know what you are attempting with the change in the `Authorization` header, but the endpoint requires the format `Bearer {{authToken}}`. Strictly speaking the colon is not necessary.
I am wondering if there is some sort of express config/middleware that needs to be added

**Comment by Huachao** [comment]
@idmacrae Can you show me the response when after the URL replacement?

**Comment by idmacrae** [comment]
Figured the problem. It was a missing middleware in the express configuration. It works now

**Comment by Huachao** [comment]
@idmacrae nice, I will close it
