### ISSUE TITLE
Linebreak in multipart/form-data

### ISSUE THREAD

**Issue by thilong** [Huachao/vscode-restclient#456]
When we use multipart/form-data as Content-Type, if there's no file to post in the request, RESTClient always use system EOL to combine lines. This makes requesting always failed on Macos with asp.net core.

**Comment by Huachao** [comment]
@thilong nice catch, I have fixed this issue and will publish it in the next release.

**Comment by Huachao** [comment]
@thilong I have published the latest version 0.23.1 and you can verify the fix.
