### ISSUE TITLE
Internet access failure

### ISSUE THREAD

**Issue by spidertong** [Huachao/vscode-restclient#457]
I can curl for the url in vscode terminal.
When I try the url by restclient, all of them are getting an error page saying that Internet Access Failure.
lm behind a corperate proxy, but those url are also behind the proxy, and they worked well arround one month ago.
Im not sure whether any setting changes, or the network blocking the request.

**Comment by Huachao** [comment]
@spidertong what are the values of the following settings in VSCode:

- `http.proxy`
- `http.proxyStrictSSL`
- `rest-client.excludeHostsForProxy`

As well as the following environment variable values:
- `HTTP_PROXY`
- `HTTPS_PROXY`
- `NO_PROXY`

**Comment by spidertong** [comment]
oh thx for remind. 
I double checked these setting, found that I should not enable these settings, as they're all behind the proxy. l enabled proxy setting for other plugins, after I remove them, it works now.
Thank you so much and thanks for the time for the reply.

**Comment by spidertong** [comment]
A very nice plugin, and you're so nice.
