### ISSUE TITLE
Don't change the focus to the response window

### ISSUE THREAD

**Issue by Deathhush** [Huachao/vscode-restclient#459]
Today, after submitting a request and get back the response, the focus of the editor will go to the window that contains the response. This can be annoying if you submitted a request, looked at the response and try to click another file for editing. The new file will be opened in the second window group where the response is displayed instead of the primary window group. 

Can the focus remain in the window that shows the ".http" file instead of switching to the response after submitting a REST request?

**Comment by Huachao** [comment]
@Deathhush set the `rest-client.previewResponsePanelTakeFocus` to `false`
