### ISSUE TITLE
Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by chrisolsen** [Huachao/vscode-restclient#46]
- VSCode Version:
1.7.1
- OS Version:
Windows 10
- REST Client Version:
0.10.1

Steps to Reproduce:

1.  Run GET request to api returning json payload

Error Message:

`Unable to open 'Response(375ms)': Cannot read property 'trim' of undefined.`

**Comment by Huachao** [comment]
@chrisolsen thanks for your finding, and I have published the latest version 0.10.2, could you please verify the bug? Sorry for the inconvenience. 😃

**Comment by chrisolsen** [comment]
All good now! Thanks for the quick fix.

This plugin is awesome 👍
