### ISSUE TITLE
Show request name in symbol list

### ISSUE THREAD

**Issue by Stadly** [Huachao/vscode-restclient#461]
For named requests, it would be great if the request name was shown in the symbol list (`Ctrl`+`Shift`+`O`).

This would be especially useful for files containing soap requests. In soap, the same endpoint is often used for multiple different actions, with the action specified in the request body. Therefore you can often end up with a symbol list like this:

![image](https://user-images.githubusercontent.com/7263579/70926463-76fb0180-202d-11ea-84ea-e662e94c5a24.png)

If the symbol list could display the request names, such as `GetDataVersions` and `HideDataVersions`, that would be really helpful!

**Comment by Stadly** [comment]
My best guess would be to use something similar to this inside the function `getRequestSymbolInfo` in `src/providers/httpDocumentSymbolProvider.ts`.

```js
const requestVariable = Selector.getRequestVariableDefinitionName(text);
```

**Comment by Huachao** [comment]
@Stadly nice suggestion, now the named request will just display the request name instead. I have implemented this and will publish this in the next release.

**Comment by Stadly** [comment]
Nice! Thanks :)

**Comment by Huachao** [comment]
@Stadly you can try this in the latest version 0.23.1

**Comment by Stadly** [comment]
It's working :)
