### ISSUE TITLE
怎么发送一个标准的RFC1123格式的时间?

### ISSUE THREAD

**Issue by hydrz** [Huachao/vscode-restclient#464]
- VSCode Version: 1.3.92

- OS Version: Linux  4.15.0-30deepin-generic

- REST Client Version: 0.23.0 (2019/11/20)

Steps to Reproduce:

我使用Readme中的方式添加时间头部:

`Date: {{$datetime rfc1123}}`

但是通过抓包发现传出去的时间是长这样的:

`Sat Dec 21 2019 18:50:37 GMT+0000`

通过[网上资料](http://www.csgnetwork.com/timerfc1123calc.html)的查询, 正确格式应该是这样的:

`Sat, 21 Dec 2019 18:51:54 GMT`

有一些接口验证会涉及到这个, 导致不能通过验证, 如[阿里云的API接口 ](https://help.aliyun.com/document_detail/31955.html?spm=a2c4g.11186623.6.1477.33bc79b55g4aej])

请问我可以怎么样发送长这样`Sat, 21 Dec 2019 18:51:54 GMT`的时间?

**Comment by Huachao** [comment]
@hydrz nice catch, currently there's a bug in the code and I have fixed it. I will notify you when a new release is available. The workaround now is to provide your own datetime format like `{{$datetime 'ddd, DD MMM YYYY HH:mm:ss [GMT]'}}`

**Comment by Huachao** [comment]
@hydrz this issue has been fixed in the latest version 0.23.1 and you can verify it

**Comment by hydrz** [comment]
@Huachao Great! I have verified it. It's really convenient now.Thanks.
