### ISSUE TITLE
Headers missing in Request

### ISSUE THREAD

**Issue by swiffer** [Huachao/vscode-restclient#465]
- VSCode Version: 1.41.1
- OS Version: Windows Version 1909 
- REST Client Version: 0.23.0

Steps to Reproduce:

1. Add Cookie to `rest-client.defaultHeaders`
2. Execute Request / Copy request as CURL

The request is getting executed without Headers added. Copy request as CURL is not adding the Headers from config. Headers defined in .http Request are applied to Copy request as CURL but not when sending the request. However the history is showing the requests with headers applied.

**Comment by Huachao** [comment]
@swiffer I have partially fixed the issue that user-provided `Cookie` headers (no matter in default headers config or `.http` file) will be respected when sending the request. And `Copy Request As cURL` behavior is unchanged and only `Cookie` headers provided in the `.http` file are respected, and this is the same behavior like other HTTP client tools like **Postman**. I think it's OK for now, so I'd like to close it for now.

**Comment by swiffer** [comment]
@Huachao Thanks! It would be really nice to have a fixed version released, downgraded to 0.22.2 temporary. (see #482 for same problem)

**Comment by Huachao** [comment]
@swiffer I have fixed this issue in the latest version 0.23.1 and you can verify it.
