### ISSUE TITLE
Cookie not in this host's domain

### ISSUE THREAD

**Issue by sandeep-khanna** [Huachao/vscode-restclient#466]
We have a public facing domain (sub.domain.io) and a private back-end API service (sub.domain.com). 

Using VSCode, going directly to the back-end service successfully works and returns a response with two cookies (one of which has Domain=.sub.domain.com).

Unfortunately, sending a request via Apigee API gateway (sub.domain.io) to a back-end API end-point causes the following error:

Cookie not in this host's domain. 
Cookie: sub.domain.com
Request: sub.domain.io

This request (via Apigee API gateway) works fine without any errors using the Postman API client!

Are there any REST Client extension settings to toggle?

**Comment by Huachao** [comment]
@sandeep-khanna Do you mean that you received a Cookie with host `sub.domain.com` and the outgoing request with the domain `sub.domain.io` can carry this cookie?

**Comment by sandeep-khanna** [comment]
> @sandeep-khanna Do you mean that you received a Cookie with host `sub.domain.com` and the outgoing request with the domain `sub.domain.io` can carry this cookie?

That's correct. The back-end API end-point generates the cookie not knowing which (sub)domain is fronting/proxying its APIs.

How come this works without any issues when using Postman, but has a problem only with VSCode Rest Client extension. This makes it a weaker case for us to switch from Postman to VSCode.

**Comment by Huachao** [comment]
@sandeep-khanna actually it seems unreasonable for me, since Cookies target domain `sub.domain.com` should not match the request domain `sub.domian.io` according to the RFC spec. And could you please more details about your actual request URL and cookie headers, as well as the saved managed cookies in Postman? A screenshot is also appreciated. Thanks in advance.

**Comment by sandeep-khanna** [comment]
I have fixed this issue by using a Javascript policy within the context of the Apigee API proxy's TargetEndpoint PostFlow.

Here is a setHeaders.js Javascript policy

```
var setCookie = context.getVariable("response.header.set-cookie");
setCookie = setCookie.replace(/(D|d)omain=.sub.domain.com($|;)/,"Domain=.domain.io");
context.setVariable("response.header.set-cookie", setCookie);
```

And here is the API proxy TargetEndpoint using it

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TargetEndpoint name="default">
    <Description/>
    <FaultRules/>
    <PreFlow name="PreFlow">
        <Request/>
        <Response/>
    </PreFlow>
    <PostFlow name="PostFlow">
        <Request/>
        <Response>
            <Step>
                <Name>setHeaders</Name>
            </Step>
        </Response>
    </PostFlow>
    <Flows/>
    <HTTPTargetConnection>
        <Properties/>
        <LoadBalancer>
            <Server name="UAT_Server"/>
        </LoadBalancer>
        <Path>/api/user/attributes</Path>
    </HTTPTargetConnection>
</TargetEndpoint>
```
