### ISSUE TITLE
Ignore proxy settings for some hosts

### ISSUE THREAD

**Issue by raycon** [Huachao/vscode-restclient#47]
- VSCode Version: 1.7.1
- OS Version: Win7
- REST Client Version: 0.10.2

Steps to Reproduce:

1. Working behind proxy
2. Set proxy host and port in VS Code
3. Start local server.
4. Send request to localhost (ex. GET http://localhost:8080/update)
5. Receive "HTTP/1.1 400 Bad Request" response

I suggest the `Proxy Excludes` option.
If some host(ex. localhost, 127.0.0.1) is in the option, request should not use proxy settings.

**Comment by Huachao** [comment]
@raycon thanks for your suggestion, I've added the config named `rest-client.excludeHostsForProxy` as you suggested. And I will deliver this feature in next release. 😄

**Comment by raycon** [comment]
@Huachao thanks for your work!

**Comment by Huachao** [comment]
@raycon I've published the latest version 0.10.3, you could have a try and verify it 😄

**Comment by raycon** [comment]
I've tested this feature using 0.10.4. `rest-client.excludeHostsForProxy` values like `localhost` and `localhost:8080` are works well! Thank you~
