### ISSUE TITLE
VSCode RESTclient XML set a Request Variables

### ISSUE THREAD

**Issue by betancour** [Huachao/vscode-restclient#471]
I would like to set a value to be catched from a XML body and save it as a Request Variables, but I can't understand the syntax to do this.

Incorrect request variable reference syntax, it should be "variableName.(response|request).(headers|body).(headerName|JSONPath|XPath|*)"

Someone can explain how this work with XML.
Example:
// @path
POST: xxx

@variable = {{path.body()}}

```
<Header> 
   <Body>
     <Parameter>Desired Parameter</Parameter> 
   </Body> 
</Header> 

```

**Comment by Huachao** [comment]
@betancour which part of the XML response do you want to save in the request variable?

**Comment by betancour** [comment]
Parameter desired

**Comment by Huachao** [comment]
@betancour your request variable should look like this `@varaible = {{path.response.body.//Header/Body/Parameter}}`

**Comment by betancour** [comment]
Not working, 

No value is resolved for given header name 
[Response-1579116528753.txt](https://github.com/Huachao/vscode-restclient/files/4067105/Response-1579116528753.txt)
