### ISSUE TITLE
How to send custom headers for Http Request

### ISSUE THREAD

**Issue by strings-code** [Huachao/vscode-restclient#473]
I am using Rest Client for the first time and when I send custom header like below in Https, the service response comes back saying that the request is missing MY-CUSTOM-HEADER. It makes me think that the custom header is not being sent, any special requirement to specify custom header? Thank you.

`POST https://example.com/abc/1.0/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer OGafjutE2QGd81z3BJ2Lpuu2suzaa6L3d5h8OTEUZ6S0GXdXMJqV0P
MY-CUSTOM-HEADER:  {"Id": "132182", "productId": "ABC", "appVersion": "1.0"}

{
  "transferabilityData": {
    "fundFamilyNbr": 1234
  }
}
`

**Comment by Huachao** [comment]
@strings-code I think the format is right, I am just curious that your header value is a bit strange

**Comment by strings-code** [comment]
@Huachao  Having json data in header value is perfectly acceptable. I tried sending simple value like 123 and it is the same result. Are we sure that it accepts JSON in header value? I am not convinced that it the issue should be closed.

**Comment by Huachao** [comment]
@strings-code replace the request url with https://httpbin.org/get to inspect the outgoing  request headers

**Comment by strings-code** [comment]
Ok thanks. I am not able to see where the outgoing headers are. Do I need to use Fiddler for that?

**Comment by Huachao** [comment]
@strings-code You can check the response,  and the outgoing headers are in the response.  And if you have Fiddler,  you can send the request unchanged, you can inspect the request header there

**Comment by strings-code** [comment]
Here is the response and I don't see any headers that I sent 

`HTTP/1.1 405 METHOD NOT ALLOWED
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Allow: GET, HEAD, OPTIONS
Content-Type: text/html
Date: Sun, 12 Jan 2020 17:27:48 GMT
Referrer-Policy: no-referrer-when-downgrade
Server: nginx
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
Content-Length: 178
Connection: Close

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>`

**Comment by strings-code** [comment]
Ok nevermind, I got the headers back and they are in Pascal Case as opposed to UPPERCASE which is what I sent, I thought the headers are case-insensitive. I sent CUSTOM-HEADER and I got Custom-Header back in response.

**Comment by Huachao** [comment]
@strings-code Does you server side case-insensitive in headers?

**Comment by strings-code** [comment]
Looks like the producer server api requires the Headers to be UPPERCASE and they are case sensitive. Does Rest Client always converts them to Pascal case? That's what it looks like. If yes, it should be a bug right?

**Comment by Huachao** [comment]
@stegano I think the Node.js (my extension relies on) internal behavior is consistent with the spec that HTTP request headers are case-insensitive. And the actual outgoing headers are all lowercased, instead of the `Pascal` case. The Pascal case displayed in `httpbin.org/get` is handled by that site internally. You can verify this by using Fiddler.

And this is an upstream limit from Node.js that it doesn't retain the header case, I am afraid that no ways to workaround. However, I think this behavior makes sense.

**Comment by strings-code** [comment]
thanks @Huachao  for your help.

**Comment by duanbiaowu** [comment]
REST Client  v0.25.1

---

### Use REST Client syntax
GET https://dbwu.tech/
Custom-Key: hello-world

### Use curl syntax
curl 'https://dbwu.tech/' \
--header "Custom-Key: hello-world"
