### ISSUE TITLE
How to view all responses to all the requests in a .http file 

### ISSUE THREAD

**Issue by mostafiz93** [Huachao/vscode-restclient#474]
In a `.http` file I've multiple requests. When I run `Ctrl+Alt+R(Cmd+Alt+R for macOS)` the response pane shows the response to only the last request on that `.http` file. 

How can I view responses to the other requests?

**Comment by Huachao** [comment]
@mostafiz93 you can set the setting `rest-client.showResponseInDifferentTab` to `true`.
