### ISSUE TITLE
variable  with response.body.$.value not working 

### ISSUE THREAD

**Issue by raleti123** [Huachao/vscode-restclient#476]
- VSCode Version:
- OS Version: 1.17.2
- REST Client Version: 0.18.4

Steps to Reproduce:

1.  when ever i am using a variable to capture the response.bday.value of previous request, the variable not holding any value but when i am using same code directly where ever i required it is working fine.
 for example consider below code .

@baseUrl = https://example.com/api

# @name login
POST {{baseUrl}}/api/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

name=foo&password=bar

###

@authToken = {{login.response.headers.X-AuthToken}}

# @name createComment
POST {{baseUrl}}/comments HTTP/1.1
Authorization: {{authToken}}
Content-Type: application/json

{
    "content": "fake content"
}

from above example the variable  "authToken" not holding any value .
but when i  have run it like mentioned below it is working fine.

@baseUrl = https://example.com/api

# @name login
POST {{baseUrl}}/api/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

name=foo&password=bar

###

@authToken = {{login.response.headers.X-AuthToken}}

# @name createComment
POST {{baseUrl}}/comments HTTP/1.1
Authorization: {{login.response.headers.X-AuthToken}}
Content-Type: application/json

{
    "content": "fake content"
}

it may be bug

**Comment by Huachao** [comment]
@raleti123 did you have a typo in the request variable `response.boday.$.value`, it seems that the body is not spelled correctly.

**Comment by raleti123** [comment]
Hi i have typed wrongly  here ,  it is not working  with correct syntax (name.response.body.param1) . 
the above code i have mentioned for reference. but my actual code is using correct syntax. 

please find below for my actual code.

# @name token
## Auth token for API gateway calls. 
POST  {{baseUrl}}/oauth/token 
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id=XXXXX
&client_secret=XXXXX_XXX-XXXX

###
@authToken =  {{token.response.body.access_token}}

this authToken variable not  working whenever i have passed it like {{authToken }}.

**Comment by Huachao** [comment]
@raleti123 could you please show me your response of `token` request in the above comment, since `{{token.response.body.access_token}}` can work requires Content-Type of your response is `application/json` and there is key named `access_token` at the top level of your JSON response.

**Comment by raleti123** [comment]
Hi  whenever i have passed {{token.response.body.access_token}} in another request directly it is working like below . 
 Authorization: Bearer {{token.response.body.access_token}} 
bit it is not working when i have passed like below  
 Authorization: Bearer {{authtoken}}
response body for  token test case :
{
  "access_token": "XXXXXXXXXXX",
  "expires_in": XXXXX,
  "refresh_expires_in": XXXX,  "refresh_token": "XXXXXXXXX",
  "token_type": "bearer",
  "not-before-policy": 0,
  "session_state": "XXXX-XXXX-XXXX-XXX-XXXXXXX",
  "scope": "email profile"
}}

**Comment by Huachao** [comment]
@raleti123 what's the message displayed when you hover over the `{{token.response.body.access_token}}`, and are there any warning/error messages? Could you please also take a screenshot of you http file

**Comment by raleti123** [comment]
when ever i hover i can see the token value  ,   
![image](https://user-images.githubusercontent.com/13975205/72245915-975fb100-3617-11ea-866c-55f59f212f18.png)

this is not working 
![image](https://user-images.githubusercontent.com/13975205/72246148-1fde5180-3618-11ea-8e56-77c548b66e4f.png)

**Comment by Huachao** [comment]
@raleti123 can you show me the file variable auth_token definition screenshot

**Comment by raleti123** [comment]
find below 
![image](https://user-images.githubusercontent.com/13975205/72248340-ef4ce680-361c-11ea-9035-2d74d5ab01f8.png)

**Comment by Huachao** [comment]
@raleti123 it seems that your extension version 0.18.3 is too old, the file variables can reference the request varaiables are supported in 0.20.0, so you can try to upgrade the extension.

**Comment by raleti123** [comment]
thank you , after upgrading  working fine . i am closing this issue.
