### ISSUE TITLE
Use environment variables from different locations

### ISSUE THREAD

**Issue by Gabsii** [Huachao/vscode-restclient#477]
Hello, 

first of all great extension! Only thing I find a bit annoying is that you have to put the `.env` file in the same folder as the `.http` files. This does not allow to structure the files within folders and can also lead to annoying redundancy if you have to edit two `.env` files (one in the root directory and another one in the folder with the HTTP requests).

**Comment by Gabsii** [comment]
Symlinks can fix that issue

**Comment by lukehmu** [comment]
Usually, we have a .env file in the root of our projects. We don't necessarily want to:
- Maintain multiple env files
- Keep our rest client (.http) files in the root of the project

Often we'd use this for API keys / usernames / passwords anyway, that our software is using, so it seems redundant to define them twice, they should be shared.

Would it be possible for a .http file to define where to load the .env file from? e.g. # env = ../../.env or something like that.

Thanks.
