### ISSUE TITLE
DELETE confirmation

### ISSUE THREAD

**Issue by mfulton26** [Huachao/vscode-restclient#478]
Some people may accidentally run a `DELETE` request in a file which can be detrimental.

I suggest adding a confirmation pop-up for, at a minimum, DELETE requests. Probably something that can be turned off/on in settings maybe per method type or something that is done via an annotation on the request itself.

e.g.

```http
@confirm-send("Task deletion cannot be undone. Are you sure you want to delete this task?")
DELETE /tasks/{{taskId}} HTTP/1.1
```

**Comment by ChayimFriedman2** [comment]
I'm taking this issue.

**Comment by Huachao** [comment]
@mfulton26 thanks for the great work from @ChayimFriedman2 , this will be published in the next release with following syntax:
```http
# @note
DELETE https://exmaple.com/
```
After clicking sending request, a warning message will be displayed.

**Comment by Huachao** [comment]
@mfulton26 @ChayimFriedman2 you can try this feature in the latest version 0.24.0. Again, thanks @ChayimFriedman2 for your great contribution.
