### ISSUE TITLE
Prompt for undefined variables

### ISSUE THREAD

**Issue by mfulton26** [Huachao/vscode-restclient#479]
I find for some HTTP requests I use I almost always use a unique value for a variable (e.g. `logId`, `sessionId`, etc.). I usually just change the variable in the file but I think it would be even nicer if I could get prompted in a pop-up/modal/dialog window for any undefined variables, they can default to the last used value but the first time it is used it could just be blank and allow me to enter it in.

**Comment by Huachao** [comment]
@mfulton26 what do you mean undefined variables in our scope?

**Comment by NearlyUnique** [comment]
I think I have a similar user case.

I use our own apis for a lot of diagnostics against our system. So I might en up with a customer or product id and need to make queries for that but the customer or product id will change almost every time I make the query

so given

```
###
GET https://example.com/{{customer_id}}/more/path
```

How would we elegantly allow the system to (probably prompt) for the unknown value `customer_id` per request (or at least if no default?) has been set.

**Comment by mfulton26** [comment]
yes, as @NearlyUnique describes it, I haven't placed `@foo=bar` anywhere but I'm using `{{foo}}` and it gets serialized over HTTP as `undefined` (or maybe the empty string, I don't recall at the moment)

instead of silently sending the request using an undefined variable I'd rather get prompted for what value to use in the request

**Comment by Huachao** [comment]
@mfulton26 @NearlyUnique sorry for the late reply, I am not sure if I totally understand your pain point, here I'd like to show you the two current offerings to help users to find out the **undefined** variables as following:
![屏幕快照 2020-03-03 下午11 27 25](https://user-images.githubusercontent.com/2796177/75791061-fd122300-5da6-11ea-9db9-89138ec11cd8.png)
One is the red break line under the **undefined** variables, the other is the VSCode *Problems* number indicators.

**Comment by mfulton26** [comment]
right, so for some requests I'll have some variable that will be unique for every single request, instead of defining the variable somewhere I'd rather get a pop-up window when I try to send the request asking me for the value of any variables in the request that are not defined, this way I can only temporarily define it for just that once when I send the request, the next time I click "Send Request" I'll get prompted/asked again for the value
