### ISSUE TITLE
Is it possible to cancel the request? 

### ISSUE THREAD

**Issue by ikesler** [Huachao/vscode-restclient#48]
Not an issue, it's more a question. 
Steps to reproduce:
1. Create a request and run it
2. Request takes a while to execute
3. No way to cancel the running request.

**Comment by Huachao** [comment]
@ikesler thanks for your suggestion, I will consider it carefully 😸

**Comment by Huachao** [comment]
@ikesler you could use latest version 0.11.0 to verify the fix, just simply use shortcut `Ctrl+Alt+Q` to achieve it.

**Comment by ikesler** [comment]
Working good, thank you! :)
