### ISSUE TITLE
How to pass Cookie header?

### ISSUE THREAD

**Issue by rohitkrishna094** [Huachao/vscode-restclient#482]
Below is the postman image. I am passing Cookie as the header.

![image](https://user-images.githubusercontent.com/18495886/72375802-becb8200-36da-11ea-9f3a-e54ba0fabac5.png)

I tried doing this in rest client 

```js
GET http://someUrl
Cookie: jsessionId=xxxx
```

The postman request works, but rest-client fails. In rest-client I am getting an error saying that cookie was not passed at all?

Note: someUrl is a validUrl.

**Comment by Huachao** [comment]
@rohitkrishna094 it's an known issue, and is already fixed. You can expect this can work in next release

**Comment by rohitkrishna094** [comment]
@Huachao Thanks for your prompt reply again. One last question, do you know when the next release is going to be?

**Comment by Huachao** [comment]
@rohitkrishna094 you can already experience this in version 0.23.1
