### ISSUE TITLE
Authorization with base64 string that has a space in it

### ISSUE THREAD

**Issue by AZ2Tonez** [Huachao/vscode-restclient#483]
I'm trying to call an OAuth token endpoint with a Basic hash that has a space in it. This is what the request looks like:

```
POST {{authUrl}}/oauth2/token
Authorization: {{SEC_HASH}}
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
```

Where SEC_HASH is an environment variable of the form "Basic xxxxxxxxx xxxxxxx" where the xxx parts are all a single base64 string (which happens to have a space in it). Is it possible it's getting interpreted as separate username/password strings instead of a single base64 string? I have also tried this format:

```
POST {{authUrl}}/oauth2/token
Authorization: Basic {{SEC_HASH}}
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
```

Where SEC_HASH only contains the xxx part and that doesn't work either. I have also tried a raw curl request which works from the command line (with all the secrets in-string instead of in env var) and that does not work either (and I am not using any unsupported flags, just -X, -H. and -d).

FWIW, when I say "not working" I mean I am getting a 400 response with the body { "error": "invalid_client" }.

This is such an amazing tool and one of the best features is the ability to use the results of a previous request for api testing with auth, but this little snag means I will have to keep getting tokens externally to VS code and copy/paste them in when they expire. Maybe there could be a flag in the settings that says interpret all authorization header strings as base64 whether they have spaces or not?

Thanks in advance for any help you can provide.

**Comment by Huachao** [comment]
@AZ2Tonez actually we support two forms of Basic auth syntax: one is the Base64 encoded `username:password` form like `Basic dXNlcm5hbWU6cGFzc3dvcmQ=`, the second form is put the username and password separately like `Basic username password`, and in this case, our extension will automaticlly do the base64 encode job. Your provided forms should match one one them

**Comment by AZ2Tonez** [comment]
@Huachao I understand that. I am using the pre-encoded form, but am receiving the 400 mentioned (which works in curl outside the rest-client environment with the same string).

**Comment by AZ2Tonez** [comment]
Didn't think of this before, but instead of pre-encoding, I tried using my app client id and client secret as username and password in the non-pre-encoded form and that worked. Apologies for overlooking this solution. Thanks for your assistance. 👍
