### ISSUE TITLE
Collapse all children in JSON response with modifier key

### ISSUE THREAD

**Issue by tuur29** [Huachao/vscode-restclient#484]
Most REST clients like Postman, Insomnia and many other programs that contain tree structures (Like VSCode) allow you to collapse all the children of a node at the same time as the node itself when pressing a modifier key (VSCode uses shift). This would greatly improve the experience while inspecting large responses.

Example of code editor in VSCode:
![2020-01-15_11-18-55](https://user-images.githubusercontent.com/2472626/72425863-dfeaac00-3788-11ea-88c9-6b963d54d304.gif)

**Comment by Huachao** [comment]
@tuur29 I have fixed the issue and will be published in next release.

**Comment by Huachao** [comment]
@tuur29 I have published the latest version 0.23.1 and you can verify it with the `Shift` modifier key

**Comment by tuur29** [comment]
Yes, it works! Thanks for implementing this 😄
