### ISSUE TITLE
How do I use env variables?

### ISSUE THREAD

**Issue by gjoforte** [Huachao/vscode-restclient#485]
I'm sorry for the question but I haven't really figured out how to use the environment variables.

I have an "api.http" file with the requests, and a "env.http" file with the variables, but I can't make it work. 

Can you please explain me how to do this?

Thanks

**Comment by emgood** [comment]
hey Gjoforte, 

You can add "rest-client.environmentVariables" to **Vscode user setting**  or to **Vscode workspace file** (".code-workspace") 

1. For user setting: press ctr + shift + p      =>   open setting (JSON).
2. For workspace : File-> 'save workspace as'  or edit existing one.

In the Json file , under setting add the _restCleint.code-workspace_  env config.
after saving the file, please press F1 and search for  Rest Client: **Switch Environment** , you should see it now.

hope you will find it useful.

i.e:
{
	"folders": [
		{
			"path": "C:\\XXX\\projects"
		},
		{
			"path": "."
		}
	],
	**"settings": {
		"rest-client.environmentVariables": {
			"$shared": {
				"version": "v1",
				"prodToken": "foo",
				"nonProdToken": "bar"
			},
			"local": {
				"version": "v2",
				"host": "https://www.cnn.com",
				"token": "{{$shared nonProdToken}}",
				"secretKey": "devSecret"
			},
			"production": {
				"host": "example.com",
				"token": "{{$shared prodToken}}",
				"secretKey" : "prodSecret"
			}
		}
	}
}**

Regards,
Eran

**Comment by Huachao** [comment]
@emgood thanks for your reply, @gjoforte you can follow the instructions from @emgood

**Comment by MacThanos** [comment]
hi all, 
how does it know which environment you are running in? e.g "local" or "production".
Where do you set this?

Thanks

**Comment by MacThanos** [comment]
oh I found the it in the documentation. thank you for this great extension Huacho.

"Currently, active environment's name is displayed at the right bottom of Visual Studio Code, when you click it, you can switch environment in the pop-up list. "

**Comment by venkatpoluri** [comment]
Thanks for the detailed explanation about the settings file configuration. Good work.
