### ISSUE TITLE
Similar to POSTMAN I should be able to Parse the API Response and Set into a Variable for my subsequent API Calls

### ISSUE THREAD

**Issue by ashokayengar** [Huachao/vscode-restclient#487]

**Comment by StoicPerlman** [comment]
@ashokayengar do you mean like this?

    # @name test
    POST https://httpbin.org/post
    Accept: application/json
    Content-Type: application/json

    {
        "foo": "foo",
        "bar": [1,2,3]
    }

    ###

    @origin = {{test.response.body.$.origin}}

    # @name whatever
    POST https://httpbin.org/post
    Accept: application/json
    Content-Type: application/json

    {
        "origin": "{{origin}}"
    }

**Comment by Huachao** [comment]
@ashokayengar I think [Request Variables](https://github.com/Huachao/vscode-restclient#request-variables) fits your case.

**Comment by ashokayengar** [comment]
Yes this is the scenario.. request variable cannot fit in this case..

If there is a mechanism to parse the response body as you suggested if it
will good to add to the documentation

**Comment by Huachao** [comment]
@ashokayengar we currently support creating variables based on parsing the JSON response with JSONPath and XML response with XPath. Could you please add more details about what it can't fit in your case.

**Comment by ashokayengar** [comment]
If that's the case it works for me however did not find documentation
around it and hence wondering whether it is possible of not. Could you
point to the documentation please.

**Comment by Huachao** [comment]
@ashokayengar https://github.com/Huachao/vscode-restclient#request-variables

**Comment by surfmuggle** [comment]
In my case we send a request and the response looks like this

```
HTTP/1.1 200 OK
Date: ....
Content-Type: text/plain; charset=utf-8
Content-Length: 67
Connection: close

Load your results with ID: CJoYTvh8
```

From the body we need the id `CJoYTvh8` to get details. The id must be used for the URL `/sales/GetResult/{{resultId}} ` . 

To get the details the request needs to have the id as part of the url like this

```
@resultId = {{myRequest.response.body}}  // this should only be CJoYTvh8

# @name getResult_for_id

POST /sales/getResult/{{resultId}} HTTP/1.1
Host:  {{our_host}}
Authorization: Bearer {{authToken}}
Content-Type: application/json
```
The handling that we would need is to split the response-body from the 1st request using `:` as the separator like this ` @resultId = response.body.split(':')[1].trim();` Then the 2nd request can be made with the id.

**Comment by psygo** [comment]
Damn, this is useful. This is a killer functionality, I didn't realize it existed for months using this extension. I think you guys should create a "best" or "highlighted" features section up at the top of the docs!
