### ISSUE TITLE
consistent naming of vsix files

### ISSUE THREAD

**Issue by mirekphd** [Huachao/vscode-restclient#488]
Can you please name your vsix files consistently with the repo name (e.g. `restlicent` or `vscode-restclient`)? A good example would be here:
https://github.com/Azure/vscode-kubernetes-tools/releases

**Comment by Huachao** [comment]
@mirekphd nice suggestion, however, the package name `rest-client` and author name `humao` are the identifier of an extension `humao.rest-client`, so if we update the package name, after updating will cause other upgrade issues.
