### ISSUE TITLE
Support send file with relative path

### ISSUE THREAD

**Issue by tangkhaiphuong** [Huachao/vscode-restclient#49]
Please support send file with relative path instead of absolute path.

https://github.com/Huachao/vscode-restclient/blob/master/src/httpRequestParser.ts  - line 85

POST https://example.com/comments HTTP/1.1
content-type: application/xml
authorization: token xxx

< ./demo.htt

**Comment by Huachao** [comment]
@tangkhaiphuong nice suggestion, or I should support both cases. And is the relative path relative to current opening workspace?

**Comment by tangkhaiphuong** [comment]
@Huachao Should support both cases. For relative path, it should same directory with current *.http/*.rest file.

**Comment by Huachao** [comment]
@tangkhaiphuong make sense, I will fix this in next release, and if you have interest, you could contribute to this code, and that will be warm welcome 😄

**Comment by Huachao** [comment]
@tangkhaiphuong I've fixed this issue and will be delivered in next version

**Comment by tangkhaiphuong** [comment]
In release note 0.10.4 support relative path but I install and found in source code extention doesn't have this features. :-)

**Comment by Huachao** [comment]
@tangkhaiphuong in 0.10.4, I didn't support this feature, it will be supported in next release like 0.10.5 which hasn't been published

**Comment by Huachao** [comment]
@tangkhaiphuong you can try the latest version 0.10.5 now, thanks 😊

**Comment by tangkhaiphuong** [comment]
Version 0.12.2 not doesn't work anymore. Please verify again.

I test with:

// [Document/Upload]: RealisIpadTest (Online) 
POST http://localhost:12001/api/1.0.0/document?secret-key=ferenteribledivageoustal&user-id=142&customer-id=680
Content-Type: multipart/form-data; boundary=-------------------------acebdf13572468

< ./upload-document.txt

**Comment by Huachao** [comment]
@tangkhaiphuong this is a regression bug, I will fix it ASAP

**Comment by Huachao** [comment]
@tangkhaiphuong you can try the latest version 0.12.3 to verify 😄

**Comment by tangkhaiphuong** [comment]
@Huachao  It work as charm!!! Thank you!  (y)
