### ISSUE TITLE
One SendRequest makes multiple API calls

### ISSUE THREAD

**Issue by nitinmahajan10** [Huachao/vscode-restclient#490]
Version: 1.41.1 (system setup)
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0 V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

- REST Client Version:  0.23.0 

**Steps to Reproduce:**
1. Define the Rest API request in "Request.rest" file
@authToken = ----AAD user Id Token Value----
@hostUrl = http://localhost:7071 
get {{hostUrl}}/api/GetUserResources
content-type: application/json
Authorization: Bearer {{authToken}}
fiscalYear: 2020

2. Start Debugging in VS 2019 for the Azure Function App and put the debug point in the entry function.

3. Click on the SendRequest link visible in the file.

4. For one time click, same api is called three times. Debug point hits 3 times. The response in VS code is shown after all 3 calls are complete. This causes very slow feedback loop.

**Comment by Huachao** [comment]
@nitinmahajan10 it seems doesn't possible for me. Did you Azure function app will return 3XX or 401 response? You can set the `rest-client.followredirect` to `false` to verify if redirection happens

**Comment by nitinmahajan10** [comment]
@Huachao thanks for quick response. I checked the behavior is when response is "500 Internal Server Error" or returning this:
return new ExceptionResult(ex, true);

This happens even after setting :
"rest-client.followredirect": false

**Comment by Huachao** [comment]
@nitinmahajan10 do you mean no matter enable redirection or not, click `Send Request` once will always hit your Azure Function App three times? And if so, what's the response of each call at the server side？

**Comment by brentahughes** [comment]
I'm getting the same behavior. If my rest service returns a 500 it will attempt 3 times before returning the response. If the response is a 200 it only makes a single call.

It seems as if there is some error handling to automatically retry the request up to 3 times. If this is the case then a setting to disable or set the number of retries would be nice.

**Comment by brentahughes** [comment]
Looks like this is coming from https://github.com/Huachao/vscode-restclient/blob/d47bc090d69fdc3b751b0faa7c2eedfd81f47a3f/src/views/httpResponseTextDocumentView.ts#L60

It's hardcoded to retry twice on EOL

**Comment by Huachao** [comment]
@brentahughes @nitinmahajan10  the root cause is that the underlying httpclient package `got` will automatically retry on specific response status codes. I have fixed this issue and will be published in the next release.

**Comment by Huachao** [comment]
@brentahughes @nitinmahajan10 you can verify this in the latest version 0.23.1

**Comment by dakaraphi** [comment]
@Huachao This update has broken my usage of the REST Client.  I'm not exactly sure which change broke, but I suspect this one.  There are a lot of redirects that happen on login attempt and now I can't successfully login after this update.

If there is some logging I can enable on the Rest Client or something, maybe I could be more specific.

**Comment by Huachao** [comment]
@dakaraphi you mean a lot of redirects happened in the login API? Are there any redirected URLs contains port number in it?

**Comment by dakaraphi** [comment]
I honestly don't know exactly what is happening.  I'm just aware that redirects are sometimes used.  It is not an area of code I work on, so I'm going to have to figure out a way to debug the problem.  It will not be easy from the server side as it is very complex, so I was hoping there was some way of logging in more detail what is happening with the client.

**Comment by Huachao** [comment]
@dakaraphi can you try if this version of extension works, you need to install it in the `Extensions` sidebar, and Click the `...` and the `Install from VSIX` option. Note, you need to first remove the trailing `.txt` text in the file name.

[rest-client-0.23.1.vsix.txt](https://github.com/Huachao/vscode-restclient/files/4171764/rest-client-0.23.1.vsix.txt)

**Comment by dakaraphi** [comment]
It does not work.  So must be some other change.  I will create a new issue.
