### ISSUE TITLE
Request 'claim' has not been sent

### ISSUE THREAD

**Issue by sonoftheweb** [Huachao/vscode-restclient#499]
- VSCode Version: 1.41.1
- OS Version: Ubuntu 19.10
- REST Client Version: 0.23.1

Steps to Reproduce:

1. Create a GET request 

```
### @name claim
GET {{baseUrlApi}}/v1/claims/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}
```
This would return some data like so:
```
"data": {
    "id": 1,
    "uuid": "e252355e-4173-11ea-84bc-0242ac160002",
    ....
}
```

2. Create a new request using the response from the previous request

```
### @name claims
@uudi = {{claim.response.body.$.data.uuid}}
POST {{baseUrlApi}}/v1/claims HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "claim_type_id":22,
    "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "objectUuid": {{uudi}},
    ....
}
```
Hover on the variable `@uudi = {{claim.response.body.$.data.uuid}}` and we find this pops up:

`Request 'claim' has not been sent`. 

Also the second request does not run as uuid is omitted. If I type in the uuid manually, it works as should be.

**Comment by Huachao** [comment]
@sonoftheweb the `###` is used as the request block separator, no used for defining request variable. The correct syntax should be following,
```http
###
# @name claim
GET {{baseUrlApi}}/v1/claims/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}
```

**Comment by sonoftheweb** [comment]
Seems like I keep having issues with implementation. I just got home and decided to try something:

```
@baseUrl = http://i1.abc.local
@user = caro@graf.ch
@password = password

# @name login
POST {{baseUrl}}/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "{{user}}",
    "password": "{{password}}"
}

### We define an accessToken variable we can easily reuse - cool stuff!
@accessToken = {{login.response.body.token.access_token}}
```

{{login.response.body.token.access_token}} says "Only JSON and XML response/request body is supported to query the result"

**Comment by Huachao** [comment]
@sonoftheweb sure
