### ISSUE TITLE
Under linux the results are not real 

### ISSUE THREAD

**Issue by NikosEfthias** [Huachao/vscode-restclient#5]
here is what i get ![](http://i.imgur.com/oG06T5l.png)
here what i should get ![](http://i.imgur.com/TDy7SC5.png)

**Comment by NikosEfthias** [comment]
ups i forget the port numbermy bad sorry :)

**Comment by NikosEfthias** [comment]
you got a star then this is just awesome

**Comment by Huachao** [comment]
@NikosEfthias, thanks you, really glad that this extension could help you.
