### ISSUE TITLE
allow refresh from results view

### ISSUE THREAD

**Issue by wprater** [Huachao/vscode-restclient#50]
It would be nice to allow the `cmd-r` action to trigger the request again when on the results view.  Like a replay action.

**Comment by Huachao** [comment]
@wprater nice suggestion, I will implement the replay function ASAP

**Comment by Huachao** [comment]
@wprater you could try the latest version 0.11.0 to verify this fix 😄

**Comment by wprater** [comment]
its working, but would be nice to have a visual indication that the request was taking place.  otherwise if the response is identical, it's harder for one to realize its been completed.

thanks!

**Comment by Huachao** [comment]
@wprater nice suggestion, I will consider this carefully
