### ISSUE TITLE
excludeHostsForProxy issue

### ISSUE THREAD

**Issue by katagaStyle** [Huachao/vscode-restclient#500]
Seems that excludeHostsForProxy isn't working wit 0.23.1. 
Rolled back to 0.22.2 and everything works fine.

**Comment by e14mattc** [comment]
Thanks for posting this.. I've been working with this extension over the past day and noticed it can't call out through the proxy I've got set up in VSC (which contains authentication in the form of http://user:pass@proxy:8080). Yet if I roll back to 0.22.2 everything works fine! 

I'd not have realised you could do that if you hadn't have posted!

Looks like the issues are related.

**Comment by Huachao** [comment]
@katagaStyle @e14mattc did you set the setting `http.proxySupport`

**Comment by e14mattc** [comment]
I've turned that off via VSC settings, and updated to 0.23.1 & it's unable to proxy out to the API I'm using. Rolled back to 0.22.2, but kept http.proxySupport = off & it works.

**Comment by Huachao** [comment]
@e14mattc can you confirm that after rollback to 0.22.2 and the `http.proxySupport` is `off`, the auth mechanism passed and the 0.23.1 failed at the **auth** step?

**Comment by Huachao** [comment]
@katagaStyle @e14mattc I'd like to close the issue since I think the `excludeHostsForProxy` setting can work if you set the `http.proxySupport` to `off`
