### ISSUE TITLE
Redirect 303 wants to use port of original request

### ISSUE THREAD

**Issue by pke** [Huachao/vscode-restclient#502]
- VSCode Version: 1.41.1
- OS Version: Windows 8.1
- REST Client Version: 0.23.1

Steps to Reproduce:

1. GET http://localhost:3000
2. This request returns 303 with a location header set to: `Location: https://www.google.com/search?q=whats%2042`
3. REST client seems to resolve the google IP and tries to connect to it using the port `3000` from the initial request
```Please check your networking connectivity and your time out in 0ms according to your configuration 'rest-client.timeoutinmilliseconds'. Details: RequestError: connect ETIMEDOUT 172.217.18.4:3000.```

Fix:

REST client should follow the location header verbatim without trying to resolve anything itself.

It works correctly, when no port is used in the initial request.

**Comment by Huachao** [comment]
@pke nice catch, I will publish this fix in the next release.

**Comment by Huachao** [comment]
@pke you can try this in the latest version 0.23.2

**Comment by pke** [comment]
Works. Thanks for fixing it!
