### ISSUE TITLE
Http Header  Accept */* causes rest of file to be formatted as a comment

### ISSUE THREAD

**Issue by KwalityKoder** [Huachao/vscode-restclient#504]
- VSCode Version: 1.41.1
- OS Version: Win 10 x64
- REST Client Version: v0.23.1

Steps to Reproduce:

1. Create a request which has an `Accept: */*` header.
2. All text following the `/*` bit appears in green like a comment

**Comment by Huachao** [comment]
I can't repro your case, could you please take a screenshot?

**Comment by Huachao** [comment]
I can't repro your case, could you please take a screenshot?

**Comment by KwalityKoder** [comment]
Hmmm. As a workaround I switched from */* to accept: application/xml.
Now I've switched back to */* and it's working fine.
Can only assume the editor has to be in a certain state for this to happen.
Feel free to close this bug.
If I can find out the additional steps to get a repro, I'll raise a new bug.
