### ISSUE TITLE
Cannot split URLs over multiple lines when they are embedded in an Odata batch request.

### ISSUE THREAD

**Issue by KwalityKoder** [Huachao/vscode-restclient#505]
- VSCode Version: 1.41.1
- OS Version: Win 10 x64
- REST Client Version: v0.23.1

Steps to Reproduce:

1. Create an Odata batch request with Odata URLs in the body.
2. Split the URLs on the query parameter delimiters & and ? to improve readability
3. The request fails 
4. Reformat the URL back to a single (unreadable line)
5. The request succeeds.

**SUCCEEDS**

`--batch_6b1f539a-b4d4-4225-9ea4-dfbf74d782ec
Content-Type: application/http
Content-Transfer-Encoding: binary

GET https://{{host}}/hrm/odata/ReferenceDataNames?$filter=ReferenceData/Id eq {{top_three_sickness_reason_ids.response.body.value[1].SicknessReason.Id}}  and (Culture eq @CultureCode or (@CultureCode eq {{cultureCode}}  and Culture eq ''))&@CultureCode={{cultureCode}} HTTP/1.1
Accept: application/json`

**FAILS WITH 500 error**

`--batch_6b1f539a-b4d4-4225-9ea4-dfbf74d782ec
Content-Type: application/http
Content-Transfer-Encoding: binary

GET https://{{host}}/hrm/odata/ReferenceDataNames
       ?$filter=ReferenceData/Id eq {{top_three_sickness_reason_ids.response.body.value[1].SicknessReason.Id}}  and (Culture eq @CultureCode or (@CultureCode eq {{cultureCode}}  and Culture eq ''))
        &@CultureCode={{cultureCode}} HTTP/1.1
Accept: application/json`

**Comment by Huachao** [comment]
@KwalityKoder can you succeed by removing the trailing HTTP/1.1 in the last query string line?

**Comment by KwalityKoder** [comment]
No - makes no difference.

**Comment by Huachao** [comment]
@KwalityKoder the embedded multiline query string is not supported
