### ISSUE TITLE
Send/Cancel/Rerun HTTP request in editor and view response in a separate pane with syntax highlight

### ISSUE THREAD

**Issue by TheDanishDynamo** [Huachao/vscode-restclient#508]
Issue Type: <b>Bug</b>

1) create new file dog.http
2) Paste this GET https://dog.ceo/api/breeds/image/random
3) Click api/breeds/image/random in OUTLINE pane

Note: Nothing happens

Extension version: 0.23.1
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (7.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Huachao** [comment]
Don't click the url itself, click the `Send Request` link above the URL

**Comment by TheDanishDynamo** [comment]
No send anymore

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Huachao** [comment]
@TheDanishDynamo Do you mean the extension works previously?

**Comment by TheDanishDynamo** [comment]
Only crtl alt r works there is no send link, also in your documentation there are no send above the get url

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Huachao** [comment]
@TheDanishDynamo what's your setting for `rest-client.enableSendRequestCodeLens`, it should be `true`.

**Comment by TheDanishDynamo** [comment]
"rest-client.enableSendRequestCodeLens": true

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by TheDanishDynamo** [comment]
Turning on Code Lens makes it work, however I don't want code lens

**Comment by Huachao** [comment]
@TheDanishDynamo So I am confused about what actually you want, could you please describe the issue more clearly including the issue title

**Comment by TheDanishDynamo** [comment]
Issue: Turning off code lens makes the Send Request disappear in rest-client extension.
Expected behavior: Turning off code lens SHALL NOT make the Send Request disappear in rest-client extension.

**Comment by Huachao** [comment]
@TheDanishDynamo this is an expected behavior not a bug since `Send Request` link is implemented with VSCode CodeLens feature. So they are the same thing.
