### ISSUE TITLE
Can't set any headers

### ISSUE THREAD

**Issue by suchy** [Huachao/vscode-restclient#509]
- VSCode Version:  1.41.1
- OS Version: Mac os Mojave 10.14.6
- REST Client Version: 0.23.1

Example http file: 

```
Content-Type: application/json
GET https://httpbin.org/get
```
Hi, when I'm trying to send this request I'm getting error: `Method must be a valid HTTP token ["CONTENT-TYPE:"]`. I'm not sure what I'm doing wrong. It also happens when trying to set any other header. Thanks ;-)

**Comment by Huachao** [comment]
@suchy headers must be written after the request url according to RFC
