### ISSUE TITLE
messy code in the response view when access the unicode website

### ISSUE THREAD

**Issue by superwangnan** [Huachao/vscode-restclient#51]
- VSCode Version: 1.7.2
- OS Version: mac 10.11.6
- REST Client Version: 0.10.6

Steps to Reproduce:

when you access the unicode website, for example: www.google.co.jp you will get messy code in the response view. I guess it's caused by charset setting.

**Comment by Huachao** [comment]
@superwangnan you're right, it's an encoding problem of response body. I will investigate how to fix. Thanks

**Comment by Huachao** [comment]
@superwangnan you could try the latest version 0.11.0 to verify this fix 😄
