### ISSUE TITLE
Unable to login to server with 0.23.1 update

### ISSUE THREAD

**Issue by dakaraphi** [Huachao/vscode-restclient#513]
- VSCode Version: 1.42.0
- OS Version: osx 10.14.6
- REST Client Version: 0.23.1

Steps to Reproduce:

I attempt to login to my server, but it continues to request authorization.

I reinstalled 0.23.0 and login is successful.
I'm not sure what change is causing an issue yet.

**Comment by dakaraphi** [comment]
So another hint, it might be session or cookie related.
The difference in behavior occurs after the login attempt.
So, I hit the login URL, and the response seems to be the same as 0.23.0
Now, when I hit a second URL on the server, 0.23.1 results in getting a response back that I'm not logged in.

**Comment by Huachao** [comment]
@dakaraphi I really did some change in the cookieJar, and what do you mean the second URL? And do you have `Cookie` header in your URL?

**Comment by Huachao** [comment]
@dakaraphi Maybe the bug occurs that on the redirection the outgoing request headers don't contain the previously received cookies.

**Comment by dakaraphi** [comment]
So, I was incorrect about the login URL.  I am getting a different response back from the server.
I have a login URL like

`{{host}}{{context}}/j_security_check?j_username={{username}}&j_password={{password}}`

This is the response shown in the result with `0.23.0`
```HTTP/1.1 200 OK
x-com-ibm-team-scenario: 127.0.0.1
X-XSS-Protection: 1; mode=block
Content-Type: text/html;charset=UTF-8
Content-Encoding: gzip
Connection: close
Server: Jetty(8.1.16.v20140903)
```

This is the response shown in the result with `0.23.1`

```HTTP/1.1 200 OK
Set-Cookie: JazzFormAuth=Form;Path=/jazz;Secure
Expires: Thu, 01 Jan 1970 00:00:00 GMT
X-com-ibm-team-repository-web-auth-msg: authrequired
X-XSS-Protection: 1; mode=block
Content-Type: text/html;charset=UTF-8
Content-Encoding: gzip
Connection: close
Server: Jetty(8.1.16.v20140903)
```

**Comment by Huachao** [comment]
@dakaraphi since multiple redirections happen in the full login flow, is this response you pasted the first response with 3XX and how did you get this response

**Comment by Huachao** [comment]
@dakaraphi I guess the root cause is that when I call the redirected URL, the request doesn't carry the cookies stored in cookieJar

**Comment by dakaraphi** [comment]
That response came from the response shown in VSCode window using the REST Client

**Comment by Huachao** [comment]
@dakaraphi I think I have fixed this issue, can you please try this version as before, 
[rest-client-0.23.1.vsix.txt](https://github.com/Huachao/vscode-restclient/files/4190615/rest-client-0.23.1.vsix.txt)

**Comment by dakaraphi** [comment]
@Huachao unfortunately it still does not work

**Comment by Huachao** [comment]
@dakaraphi could you please provide more details about your request, like if `Cookie` headers exists and your setting for `rest-client.rememberCookiesForSubsequentRequests`

**Comment by Huachao** [comment]
@dakaraphi could you please provide more details about your request, like if `Cookie` headers exist and your setting for `rest-client.rememberCookiesForSubsequentRequests? And how many redirections happen, and what's the request flow direction, like from site A to site B and finally site C? Also can you also paste the response as previously?

**Comment by Huachao** [comment]
@dakaraphi Please help to verify this version too which removes all the cookies related work in since version 0.23.0 
[rest-client-0.23.1.vsix.txt](https://github.com/Huachao/vscode-restclient/files/4196850/rest-client-0.23.1.vsix.txt)

**Comment by dakaraphi** [comment]
The version you posted still does not work.
`rest-client.rememberCookiesForSubsequentRequests` is set `true`

Could you point me to the REST client code I should try to debug?  I will try to see if I can see the problem.

**Comment by Huachao** [comment]
@dakaraphi if still not working, I think it's maybe not related to cookie jar. Previously I think the most possible code piece exsits in `httpClient.ts`. Especially the `preprareOptions` method https://github.com/Huachao/vscode-restclient/blob/32899a0e9f4cce0117b55973950027a632dda7d6/src/utils/httpClient.ts#L110

Thanks for you to help me to investigate the root cause 😄

**Comment by dakaraphi** [comment]
Just posting a status update:
Still looking into this issue; however, the problem does not occur for me when I run the code in the vscode debugger.  I will try to add logging into the code as next step since I can't seem to use the debugger.

**Comment by Huachao** [comment]
@dakaraphi thanks for the update, it's a little strange that the package I sent to you not working. If it really works, you can try the vsce package command, and try the version.

**Comment by dakaraphi** [comment]
So it seems that when I build the package, it works for me.  However, the packages you sent me or the one on the marketplace does not work for me.
I can only assume a difference in the node_modules from doing a fresh npm install.

**Comment by Huachao** [comment]
@dakaraphi the marketplace version is not working as expected since I haven't published a new release. Can you try the package built from my machine today? 
[rest-client-0.23.1.vsix.txt](https://github.com/Huachao/vscode-restclient/files/4222809/rest-client-0.23.1.vsix.txt)

**Comment by dakaraphi** [comment]
@Huachao yes, that build does work! :-)

**Comment by dakaraphi** [comment]
@Huachao yes, that build does work! :-)

**Comment by dakaraphi** [comment]
@Huachao yes, that build does work!

**Comment by Huachao** [comment]
@dakaraphi OK, I'd like to close the issue

**Comment by Huachao** [comment]
@dakaraphi you can try this in the latest verison 0.23.2.

**Comment by dakaraphi** [comment]
@Huachao it is working.  Thanks!
