### ISSUE TITLE
Improper lowercase handling

### ISSUE THREAD

**Issue by TOBACCOCN** [Huachao/vscode-restclient#516]
Issue Type: <b>Bug</b>

The REST Client extension makes word in header to lowercase when I send http request, I thought it is not necessary. And that make program in server run out error.

Extension version: 0.23.1
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Huachao** [comment]
@TOBACCOCN since this is done by Node.js internally (which VSCode extensions depend on) and it follows the RFC spec `http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html`.
