### ISSUE TITLE
Textmate lexer file is invalid

### ISSUE THREAD

**Issue by Chris2011** [Huachao/vscode-restclient#517]
- VSCode Version: - 
- OS Version: Windows [Version 10.0.18363.592]
- REST Client Version: -

Steps to Reproduce:

1. Go to this site: https://www.liquid-technologies.com/online-xml-validator
2. Paste the code from your textmate file https://github.com/Huachao/vscode-restclient/blob/master/syntaxes/http.tmLanguage and hit validate.
3. Problem is this line: **\<string\>^\s\*(?=\\\<\S)\</string\>**

I don't know how VS Code handles it, but the file is not valid. Apache NetBeans 11.3 (Beta 2) can handle Textmate too but It get's a parse error, because of this line. I think escaping it to **\&lt;** will fix the problem, but didn't test it yet.

**Comment by Huachao** [comment]
@Chris2011 nice catch, I guess VSCode internally transforms textmate files to its JSON format.
