### ISSUE TITLE
Allow Variables in < input

### ISSUE THREAD

**Issue by sduff** [Huachao/vscode-restclient#519]
When including an external file via the < input, once can not include a variable.

```
@filename = "demo.xml"

POST https://example.com/comments HTTP/1.1
Content-Type: application/xml
Authorization: token xxx

< {{filename}}
```

My use-case is that I define a filename once at the top of the file, and then this file can be used and uploaded in multiple requests. Right now, I need to manually update the filename in each request.

**Comment by Huachao** [comment]
@sduff I can't repro your issue since in my code, resolving variables happen before parsing http request text

**Comment by sduff** [comment]
Yes, this is a feature request.

**Comment by Huachao** [comment]
@sduff I think we already provided this feature, didn't it work at your side?

**Comment by sduff** [comment]
No, it didn't work for me. Code I was using was as per the example.

**Comment by Huachao** [comment]
@sduff remove the __"__ around the file name, and make sure the file exists in the workspace. And how do you verify that it's not working as expected.

**Comment by sduff** [comment]
Works awesome, sorry for raising as issue about this. Thanks for the awesome app!
