### ISSUE TITLE
remove info in status bar when response views are closed

### ISSUE THREAD

**Issue by wprater** [Huachao/vscode-restclient#52]
If one is to close (all of) the response view, it would be nice to remove the items in the status bar (timing, size, etc.).  Just a bit of cleanup.

**Comment by Huachao** [comment]
@wprater nice suggestion, I will implement it ASAP

**Comment by Huachao** [comment]
@wprater I didn't find a way to listen the document close event, so I'd like to postpone this feature

**Comment by Huachao** [comment]
It seems onDidTextDocumentClose event can be used to listen the preview html page close event, I will try to use this

**Comment by Huachao** [comment]
@wprater I have fixed it that if all the response preview pages are closed, the status bar will be cleaned up. And I will publish this fix in next release

**Comment by Huachao** [comment]
@wprater you can try the latest version 0.12.2 to verify it, thanks for your feedback
