### ISSUE TITLE
Setting rememberCookiesForSubsequentRequests to false continues to use prior cookies

### ISSUE THREAD

**Issue by murrayju** [Huachao/vscode-restclient#520]
- VSCode Version: 1.42.0
- OS Version: Darwin x64 19.3.0
- REST Client Version: 0.23.1

Steps to Reproduce:

1. Start with `rememberCookiesForSubsequentRequests` set to `true`
2. Make some request to a server that responds with Set-Cookie
3. Change `rememberCookiesForSubsequentRequests` to `false`
4. Make a request to the same server

Expected: cookies are not sent in request headers

Actual: cookies remain in cookie.json, and continue to be sent with every request to the server.

Workaround: delete `~/.rest-client/cookie.json`

**Comment by Huachao** [comment]
@murrayju this is the same reason as in #507, I already fix it and will publish it in the upcoming release.
