### ISSUE TITLE
more explicit docs on environment variables

### ISSUE THREAD

**Issue by tomdavidson** [Huachao/vscode-restclient#526]
### Feature / help request 

_More explicit docs on environment variables._ 

I am a decent case for this and have not been able to use environment variables for API credentials ever and am sure it is user error.

#### example 

I have tried file variable such as `@password = {{$processEnv PASSWORD_PRODUCTION}}` and indirect such as `@password = {{$processEnv %servicePassword}}` with the correct environment selected and the corresponding entry in settings.json ` "servicePassword": "%PASSWORD_PRODUCTION"`

The only way I can make a call is if I set password as a file variable to the actual password, so I can not commit my .http file to git.

**Comment by Huachao** [comment]
@tomdavidson before diving into the details, I'd like to show you there are two categories of variables in VSCode REST Client extension.

1. System Variables (Built-in Variables)
    1. `$guid`
    2. `$timestamp`
    3. `$processEnv` (Process Environment Variables)
   4. `$dotenv`
   5. ...
2. Custom Variables
   1. Environment Variables
    2. File Variables
   3. Request Variables

So what do you mean the environment variables?

If you mean the system variable `$processsEnv`, it allows the resolution of a local machine environment variable to a string value. A typical use case is for secret keys that you don't want to commit to source control. For example, you have a variable in your shell like `export PASSOWRD=123456` (you can examine this by `export | grep PASSWORD`). And you want to reference the password value __123456__ in your `.http` file, you can write `{{$processEnv PASSWORD}}`. If your variable name `PASSWORD` depends on the VSCode REST Client `Custom Environments`, that's what you stored in the `settings.json`, you can use the _%_ to refer the variable name indirectly. For example, if you defined two environments like `sandbox` and `prod`, they both defined a custom variable named `password` with values `SANDBOX_PASSOWRD` and `PROD_PASSWORD` separately.  Notice that you should make sure both `SANDBOX_PASSOWRD` and `PROD_PASSWORD` exist in your shell, and you expect their values.
```json
"rest-client.environmentVariables": {
    "sandbox": {
       "password": "SANDBOX_PASSWORD"
    },
    "prod": {
       "password": "PROD_PASSWORD"
    }
}
```
And in your `.http` file, you can reference the password `{{$processEnv %password}}` indirectly. You can switch the environment to select the sandbox or prod version as you wish.

If you mean the custom variables - environment variables, it does not depend on the variables exported in your shell. You just need to define the variable names and values in your `settings.json` as following.
```json
"rest-client.environmentVariables": {
    "$shared": {
        "version": "v1",
        "prodToken": "foo",
        "nonProdToken": "bar"
    },
    "local": {
        "version": "v2",
        "host": "localhost",
        "token": "{{$shared nonProdToken}}",
        "secretKey": "devSecret"
    },
    "production": {
        "host": "example.com",
        "token": "{{$shared prodToken}}",
        "secretKey" : "prodSecret"
    }
}
```
If your `.http` file expectes the `prodSecret` in `production` environment, and `devSecrect` n `localEnvironment`. You can write `{{secret}}` to achieve this.

**Comment by ToMakeSense** [comment]
@Huachao Is it possible to customize/reformat/pipe the $guid, let's say, I want guid without "-".
