### ISSUE TITLE
Import requests using swagger JSON

### ISSUE THREAD

**Issue by wmedali** [Huachao/vscode-restclient#529]
Hello, 
It would be cool to be able to import HTTP requests from Swagger JSON file.
This would reduce the requests implementation time and the errors that could be generated due to typos and will make requests build too fast. 
I hope you implement this soon if you find it valuable.

**Comment by Huachao** [comment]
@wmedali  nice suggestion, I am considering the feature that supports importing requests of postman, swagger and HAR format.

**Comment by verydemo** [comment]
up up up

**Comment by danishjoseph** [comment]
Check out my implementation in this PR https://github.com/Huachao/vscode-restclient/pull/1207

**Comment by Huachao** [comment]
Already fixed by @danishjoseph in PR #1207
