### ISSUE TITLE
Does any request/response data get sent to any servers anywhere?

### ISSUE THREAD

**Issue by kjjgibson** [Huachao/vscode-restclient#530]
When I perform requests using this add-on does any data about the request or response get sent to any Microsoft or third party servers?

(for example Postman syncs data about the requests and responses to their servers if you're logged in)

**Comment by Huachao** [comment]
@kjjgibson thanks for your question.  **No** request/response data will be sent to the Microsoft or 3rd party services. My extension will collect some usage data by default such as invoking commands(`Send Request` or `Save Response`), however, you can easily turn off this feature by setting `rest-client.enableTelemetry` to `false`.

**Comment by kjjgibson** [comment]
Thanks for the answer!
