### ISSUE TITLE
Hover peeking doesn't work for variables with hyphen

### ISSUE THREAD

**Issue by pt-br-ca** [Huachao/vscode-restclient#534]
- VSCode Version: 1.42.1
- OS Version: Windows 10
- REST Client Version: 0.23.1

Steps to Reproduce:

1. Create environment variable named "test-variable"
2. Create a .rest file and use the variable
3. Hover mouse over the variable
4. Tooltip/value does not show up

**Comment by Huachao** [comment]
@pt-br-ca I have fixed this and will be published in the next release.

**Comment by Huachao** [comment]
@pt-br-ca you can experience this in the latest version 0.23.2
