### ISSUE TITLE
Recommendation - Tabs

### ISSUE THREAD

**Issue by venki-onmail** [Huachao/vscode-restclient#536]
Hello,

I really like the rest-client, it's very very handy for developers, I really appreciate the contributors for making such a wonderful plugin. 
However, I would like to mention adding a feature for easiness. When the .http/.rest file is open in a tab I look forward to seeing the response in the same tab window instead of splitting the middle pane into 2 sections, it's very disturbing.

![image](https://user-images.githubusercontent.com/6507001/76013716-6aa48780-5f3e-11ea-81dc-79f0cb7e5b8c.png)

**Comment by Huachao** [comment]
@venki-onmail this is already supported, you can achieve this by setting `rest-client.previewColumn` to `current`.
