### ISSUE TITLE
Incorrect header check message if the bearer is too long (more then 182)

### ISSUE THREAD

**Issue by Roemer** [Huachao/vscode-restclient#539]
- VSCode Version: 1.42.1
- OS Version: Windows 10 1903
- REST Client Version: 0.23.1

Steps to Reproduce:

1. Create the following file:
```
@contentType = application/json
@token = <a very large token, for example like Home Assistant does>

### Get Services
GET https://<home assistant url>/api/services
Content-Type: {{contentType}}
Authorization: Bearer {{token}}
```
2. Run the request, an `incorrect header check` pops up and no request is done.

What I've seen is that if I remove one character from the token (it was 183 length before, so now 182), then the request is fired but of course ends in unauthorized.

**Comment by Huachao** [comment]
@Roemer could you please show me the error details in the REST channel under  output window of VSCode

**Comment by Roemer** [comment]
Not much:
```
[Error  - 19:54:23] Failed to send request:
ReadError: incorrect header check
	at EventEmitter.<anonymous> (c:\Users\rbaer\.vscode\extensions\humao.rest-client-0.23.1\dist\extension.js:566:33870)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by Huachao** [comment]
@Roemer I think it's not related to the token length, the cause should be that the received response with incorrect zip content, or the response body is plain text while the content-encoding header exists. Can you check the response with other tools like curl

**Comment by Roemer** [comment]
The response headers for a successfull call look like:
```
access-control-allow-origin: <mydomain>
content-encoding: deflate
content-length: 4
content-type: application/json
date: Sun, 08 Mar 2020 10:35:15 GMT
server: nginx/1.17.7
status: 200
```

**Comment by Huachao** [comment]
@Roemer does it work if you add `Accept-Encoding: gzip ` in the request header

**Comment by Roemer** [comment]
Gah I tried
`Accept-Encoding: gzip, deflate` yesterday which did not work (not sure if it should). Now with just  `Accept-Encoding: gzip` it works.

**Comment by Huachao** [comment]
@Roemer that means the server side prefers deflate over gzip if client supports both. However, the deflated response doesn't follow the strict format of deflate, so it raises an error.

**Comment by Huachao** [comment]
Related to sindresorhus/got#677, it's not the responsibility of the underlying http client package, it should be done by Node.js that be more lenient to an informal deflated response like browsers.

**Comment by Roemer** [comment]
Thanks a lot for helping out! Keep up the usefull addon.

**Comment by quammy** [comment]
I'm bumping the same issue. Tried to follow the related issues but got lost. Can you please share if there is a valid solution for this issue and what it is?
thanks!

**Comment by Huachao** [comment]
@quammy this should work for you
> @Roemer does it work if you add `Accept-Encoding: gzip ` in the request header

**Comment by quammy** [comment]
@Huachao yep! Sorry for missing that... Thanks for your quick reply and for a great extension!
Cheers.
