### ISSUE TITLE
Is there any way to improve the legibility of the text in Response tab?

### ISSUE THREAD

**Issue by aqeelb** [Huachao/vscode-restclient#54]
- VSCode Version: 1.7.2 
- OS Version: macOS 10.12.1
- REST Client Version: 0.11.0

Steps to Reproduce:

1. My user settings: 
{
    "editor.fontSize": 15,
    "editor.fontFamily": "MonacoB2",
    "editor.fontWeight": "bold"
}
2. Observe the response tab
![screen shot 2016-12-08 at 8 30 08 pm](https://cloud.githubusercontent.com/assets/2950322/21010282/2e974e7e-bd86-11e6-918a-5b5321299b14.jpg)

**Comment by Huachao** [comment]
@aqeelb  currently it's not supported, I am considering to implement this, thanks for your suggestion

**Comment by Huachao** [comment]
@aqeelb I've fixed the issue and will publish the new version later, thanks for your great suggestion to impove the usability.

**Comment by aqeelb** [comment]
@Huachao Awesome! 👏 As soon as you release v0.12.0. I will update and test 😊 Thank you

**Comment by Huachao** [comment]
@aqeelb you can try the latest version 0.11.2 to verify, thanks
