### ISSUE TITLE
URL including /http/ will throw error : Connection is being rejected

### ISSUE THREAD

**Issue by coolshijun** [Huachao/vscode-restclient#543]
- VSCode Version: 1.42.1
- OS Version: macOS 10.15.3
- REST Client Version: 0.23.2

Steps to Reproduce:

1. Accessing https://localhost/data/http will be successful
2. But if you append more like https://localhost/data/http/config, this will throw below error.

Connection is being rejected. The service isn’t running on the server, or incorrect proxy settings in vscode, or a firewall is blocking requests. Details: RequestError: connect ECONNREFUSED 127.0.0.1:443.

**Comment by Huachao** [comment]
@coolshijun sounds strange, did you use some reverse proxy to reject specific path

**Comment by coolshijun** [comment]
no, just local docker image, and as I described, the parent path can be accessed and if you have 'http/anything', it will throw this error, so I don't think it's related to environment.

**Comment by Huachao** [comment]
@coolshijun what's your hosted web server for your web app and your web framework?

**Comment by coolshijun** [comment]
just flask and connexion rest api, it's easy to reproduce, if you have any api like http://localhost/user/12345, and you can use http://localhost/user/12345/http to test, it will give you error message like user doen't exist, but at least the request is sent to the server to process, but if you have http://localhost/user/12345/http/test, this will trigger the error and the request never reach the server.

**Comment by Huachao** [comment]
@coolshijun can you work with cURL?

**Comment by coolshijun** [comment]
yes, same url can be accessed by cURL and postman even it will throw server error, but at least the request is sent to server, but use REST Client, the request is NOT sent to server at all.

**Comment by Huachao** [comment]
@coolshijun could you please paste the curl command details with `-v` option in curl and help me to investigate? Thanks in advance.

**Comment by coolshijun** [comment]
ok, I misunderstood your question,  I use "copy request as cURL" to see the details
for the working url like http://localhost/user/12345/http, you will see
curl --request GET \
  --url 'http://localhost/user/12345/http' \

bur for the call like http://localhost/user/12345/http/test, you will get empty url like

curl --request GET \
  --url '' \

So the transformation is going to be empty, I believe that's the reason for rejection.

**Comment by Huachao** [comment]
@coolshijun nice catch, I have fixed the issue and will be published in the next release. The root cause is that the url contains `http` word which causes parse error.

**Comment by coolshijun** [comment]
cool, thanks for quick response!!!

**Comment by Huachao** [comment]
@coolshijun as you wished. Thanks for your email
[rest-client-0.23.2.vsix.txt](https://github.com/Huachao/vscode-restclient/files/4328833/rest-client-0.23.2.vsix.txt)

**Comment by coolshijun** [comment]
Excellent! Thank you very much!

**Comment by Huachao** [comment]
@coolshijun you can try this in the latest version 0.24.0

**Comment by coolshijun** [comment]
Great! Thanks for keeping me posted.
