### ISSUE TITLE
Context creation failed - graphql

### ISSUE THREAD

**Issue by zAndrey95** [Huachao/vscode-restclient#545]
Hello, can you tell me

Have request:
`@authToken = {eyJraWQiOiIwN1Zj}

POST http://localhost:5000/graphql
Authorization: {{authToken}}
X-REQUEST-TYPE: GraphQL

query listProducts{
  fakturaAssist{
    listProducts{
      id
      name
      productNumber
    }
  }
}`

Getting an error:
`HTTP/1.1 500 Internal Server Error
content-type: application/json; charset=utf-8
access-control-allow-credentials: true
vary: origin
access-control-expose-headers: WWW-Authenticate,Server-Authorization
cache-control: no-cache
content-length: 222
Date: Fri, 13 Mar 2020 12:20:48 GMT
Connection: close

{
  "errors": [
    {
      "message": "Context creation failed: Cannot destructure property `payload` of 'undefined' or 'null'.. Request id: offline_awsRequestId_ck7q5gknc01d24oy29fet2gsi",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}`

if a send request:
`POST http://localhost:5000/graphql
Content-Type: application/json; charset=utf-8
Authorization: {{authToken}}

query listProducts{
  fakturaAssist{
    listProducts{
      id
      name
      productNumber
    }
  }
}`

Have answer:
`HTTP/1.1 200 OK
content-type: application/json; charset=utf-8
vary: origin
access-control-allow-credentials: true
access-control-expose-headers: WWW-Authenticate,Server-Authorization
cache-control: no-cache
content-length: 0
Date: Fri, 13 Mar 2020 12:22:09 GMT
Connection: close`

and warning:
`The content type of response is application/json, while response body is not a valid json string`

how can I get a response from a request for graphql?

**Comment by Huachao** [comment]
@zAndrey95 can you work with other tools, it seems that the error arises from some code like the following:
```js
const { payload } = xxx;
```

**Comment by zAndrey95** [comment]
@Huachao It worked for me if I wrote it like this:
`Authorization: JraWQiOiIwN1`

**Comment by Huachao** [comment]
@zAndrey95 do you mean you if you write `Authorization` header with plain text, the request works, however if you use the **File Variable** syntax, it failed?

**Comment by zAndrey95** [comment]
@Huachao Yes

**Comment by Huachao** [comment]
@zAndrey95 could you please paste the variable definition and request again with the markdown multi-line code fences block syntax **```http**  instead of **``**

**Comment by zAndrey95** [comment]
@Huachao I'm sorry I didn't understand you

**Comment by Huachao** [comment]
@zAndrey95 could you please show me your request that not works for you

**Comment by zAndrey95** [comment]
@Huachao 
Not work:
```@authToken = {eyJraWQiOiIwN1Zj}

POST http://localhost:5000/graphql
Authorization: {{authToken}}
X-REQUEST-TYPE: GraphQL

query listProducts{
fakturaAssist{
listProducts{
id
name
productNumber
}
}
}

**Comment by zAndrey95** [comment]
@Huachao 
Work:

```

POST` http://localhost:5000/graphql
Authorization: JraWQiOiIwN1Z
X-REQUEST-TYPE: GraphQL

query listProducts{
fakturaAssist{
listProducts{
id
name
productNumber
}
}
}

**Comment by Huachao** [comment]
@zAndrey95 could you also show me the `authToken` definition? BTW, if you can take a screenshot of the request and variable is appreciate

**Comment by zAndrey95** [comment]
@Huachao 
![image](https://user-images.githubusercontent.com/35850949/76732665-ee911780-6767-11ea-8079-e628f31813f2.png)

**Comment by zAndrey95** [comment]
@Huachao 
Work version:
![image](https://user-images.githubusercontent.com/35850949/76732761-1f714c80-6768-11ea-8d8f-f4df3a134fbb.png)

**Comment by Huachao** [comment]
@zAndrey95 the `Work version` seems to contain the error response content?

**Comment by zAndrey95** [comment]
@Huachao sorry, sorry, sorry...
i edit the message

**Comment by Huachao** [comment]
@zAndrey95 It seems that in the not-working version, the value of `authToken` is not the same as the inline one. The not-working one contains redundant `{` at the being of the value, please also check the end of the value to see if `}` exists.

**Comment by Huachao** [comment]
@zAndrey95 any updates?

**Comment by zAndrey95** [comment]
@Huachao There is an opening { and closing }. This method does not work

**Comment by Huachao** [comment]
@zAndrey95 I mean maybe you should remove the `{` and `}` in the file variable value. You can check the two screenshots you provided,  the worked version without `{` and `}`, the not-working one has

**Comment by zAndrey95** [comment]
@Huachao You are a great person and super support for the project! Good luck!
It worked, thanks!)
