### ISSUE TITLE
header 的值里面包含冒号时候无法正常解析

### ISSUE THREAD

**Issue by foxundermoon** [Huachao/vscode-restclient#55]
- VSCode Version: 1.8
- OS Version:  mac 10.12.1
- REST Client Version:   0.11.0
 
Steps to Reproduce:

既然都是中国人那就用中文了

1.  header里面的referer 后面的冒号会导致referer解析不出来，只有冒号前面的    解析header 不会是简单粗暴的以冒号分割吧

**Comment by Huachao** [comment]
@foxundermoon nice catch, I've fixed this bug, and will publish a new version ASAP. Thanks for your usage. 😄

**Comment by Huachao** [comment]
@foxundermoon you can try the latest version 0.11.2 to verify 😄

**Comment by foxundermoon** [comment]
@Huachao   thanks
