### ISSUE TITLE
post request occurs an error in basic authorize.

### ISSUE THREAD

**Issue by lorki** [Huachao/vscode-restclient#552]
- REST Client Version: lastest
- VSCode Version: lastest
- OS Version: windows 10

Steps to Reproduce:

``` rest
POST https://open.net/req HTTP/1.1

Content-Type: application/json
Authorization: Basic cm9vdDoxMjM0NTY=
# Authorization: Basic root:123456

[
    "xxxxxxxxx",
    "yyyyyyyyyy"
]
```
server ret:
``` json
HTTP/1.1 401 Unauthorized
X-Rqlite-Version: 1.0
Date: Mon, 23 Mar 2020 11:48:20 GMT
Content-Length: 0
Connection: close
```

In addition, using 'GET' is successful. Only can't 'POST'

**Comment by Huachao** [comment]
@lorki it seems that you have an extra blank line between request line and body,  try to remove it
