### ISSUE TITLE
The extension is realy great but, ... i can't run it

### ISSUE THREAD

**Issue by LeCanardNoir** [Huachao/vscode-restclient#554]
It must be me but,...
Every thing work fine, except i can't run any POST resquest
The response are allways "Token Denied".

My resquest http code work fine in every application or other extension.

I hope the problem is my Noob coder fault.

But if some one can help me with this it would be appreciate.

Sorry for my english

**Comment by Huachao** [comment]
@LeCanardNoir could you please show me your post request

**Comment by Huachao** [comment]
@LeCanardNoir I'd like to close it since no more updates. If you still have any questions, please feel free to reopen it.
