### ISSUE TITLE
Response return utf-8 chars  how to display chinese fonts

### ISSUE THREAD

**Issue by rainbow2019s** [Huachao/vscode-restclient#564]

**Comment by Huachao** [comment]
@rainbow2019s could you please provide the actual response received in my extension, especially the `Content-Type` header in response?

**Comment by tonnyyi** [comment]
@rainbow2019s  There is a configuration item called "Decode Escaped Unicode Characters". May it's what you want  😊

**Comment by Huachao** [comment]
@tonnyyi where is this configuration in my extension?

**Comment by Huachao** [comment]
@rainbow2019s thanks for @tonnyyi , you can try it and if it works for you

**Comment by Huachao** [comment]
@rainbow2019s I'd like to close it and pls feel free to reopen it if still not working
