### ISSUE TITLE
Evaluate variables in the response body property for next request

### ISSUE THREAD

**Issue by victorbernardino** [Huachao/vscode-restclient#565]
For example:
###
# @name firstRequest
GET http://hey.org 

@randomValue = {{$randomInt 0 100}}

###
# @name secondRequest
POST http://hey.org

{
   "hey": "{firstRequest.response.body.responseList[{{randomValue}}]}}"
}

or 

{
   "hey": "{firstRequest.response.body.responseList[{{$randomInt 0 100}}]}}"
}

**Comment by tdhung80** [comment]
@victorbernardino it's supported

@token = {{requestName.(response|request).(body|headers).(*|JSONPath|XPath|Header Name)}}

**Comment by ssnyder** [comment]
I am having the same problem.  My query is:
```
# @name loginAPI
post https://{{hostname}}:{{port}}/wf_nebula/interface/wf_login.do HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: {{authorization}}
identity: {{identity}}
password: {{password}}

```
The response I get is:
```
HTTP/1.1 200 
Content-Length: 90
Date: Tue, 14 Jul 2020 20:59:40 GMT
Connection: close

{"msg":"success.","success":true,"userid":1002,"token":"DEE2EC799429B54962DCE6E45BC66B60"}
```
When I try to reference the token value it complains that Only JSON and XML response/request body is supported to query the result.  Following the examples in the readme, I thought this should work...but apparently does not!
   
@token={{loginAPI.response.body.$.token}}

I'm sure there is something small that I'm missing....help would be appreciated!

**Comment by Huachao** [comment]
@ssnyder The extension infers the mime type of the response body from the `Content-Type` header in the response. For example, if the response is of JSON, the `Content-Type` of it is normally `application/json`. While in your request body, the `Content-Type` header doesn't exist
