### ISSUE TITLE
multipart/form-data request, return CSRF verification failed

### ISSUE THREAD

**Issue by marvel00000** [Huachao/vscode-restclient#567]
- REST Client Version:0.22.2
- VSCode Version:1.37.0
- OS Version:win10

Steps to Reproduce:

1.I seed a 'multipart/form-data request' request (do't contains file part),the server return 'CSRF verification';
 request info is :
![image](https://user-images.githubusercontent.com/16677459/79937445-75828f80-848c-11ea-979e-5b896302f9ef.png)

 response info is:
![image](https://user-images.githubusercontent.com/16677459/79937554-c4c8c000-848c-11ea-8db1-4ffe7fa4171b.png)

2. when i use postman or idea restclient,response is ok.
use idea request:
![image](https://user-images.githubusercontent.com/16677459/79941285-89cb8a00-8496-11ea-8851-5495be36f03c.png)

**Comment by Huachao** [comment]
Can you show me your actual request without sensitive information?

**Comment by marvel00000** [comment]
sorry，this ip is local network,can't ping it in out area。 So，i close the issue,when have this problem next time,i while commit a new issue。a
