### ISSUE TITLE
"Cancel Request" keyboard shortcut overrides @ sign on German Windows machine

### ISSUE THREAD

**Issue by luchsamapparat** [Huachao/vscode-restclient#57]
- VSCode Version: 1.8.1
- OS Version: Windows 10, Build 14393.576 (de-de)
- REST Client Version: 0.11.4

Steps to Reproduce:

1. Open Plain Text File
2. Press "Alt gr"+"Q"

Expected: The "@" sign
Actual: Warn: command 'rest-client.cancel-request' not found

On a German Keyboard layout, the "@" sign is entered by pressing "Alt gr"+"Q" which is equivalent to "Ctrl"+"Alt"+"Q" which is mapped to `rest-client.cancel-request`. Is there a way to just deactivate a keyboard shortcut?

**Comment by Huachao** [comment]
@luchsamapparat you can follow the vscode doc [here](http://code.visualstudio.com/docs/customization/keybindings#_removing-a-specific-key-binding-rule) to remove a keybinding rule. In your case, just add following code in you `keybindings.json`:

```json
{ "key": "alt+ctrl+q",             "command": "-rest-client.cancel-request"}
```

**Comment by luchsamapparat** [comment]
Thank you! I looked for that doc but couldn't find it.

**Comment by Huachao** [comment]
@luchsamapparat does it work now as I suggested?

**Comment by luchsamapparat** [comment]
yep
