### ISSUE TITLE
Cursor in VSCode disappear after execute a request

### ISSUE THREAD

**Issue by reob-info** [Huachao/vscode-restclient#572]
- REST Client Version:0.23.2
- VSCode Version:1.44.2
- OS Version:Ubuntu 18.04

Steps to Reproduce:

1. Select a command to run
2. Run the command with ctrl-alt-r

After  run the command, the cursor disappear from the selected line.
I need to execute many commands in a certain time, but it is impossible having to click again over the file after execute each command.
Appear that it is related with show the server answer at another window.

**Comment by Huachao** [comment]
@reob-info Set `"rest-client.previewResponsePanelTakeFocus": false` in your settings should work for you.

**Comment by reob-info** [comment]
Thanks.
