### ISSUE TITLE
[Remote-SSH]Installed on remote server but request still sent from local host

### ISSUE THREAD

**Issue by CodingPapi** [Huachao/vscode-restclient#573]
Hi, I install your plugin on remote server but http request still sent from local host.
I started a rest api server on remote linux, and fire a request to an address like 127.0.0.1:8000.It cannot complete this request successful

**Comment by Huachao** [comment]
@CodingPapi can you confirm my exntension is installed on remote server by using the **Developer: Show Running Extensions** command to see whether VS Code is running the extension locally or remotely

**Comment by CodingPapi** [comment]
@Huachao I can see that REST Client is running remotely in the result

**Comment by Huachao** [comment]
@CodingPapi so it may be other reason that request fails, could you check your request again and ensure the endpoint really works

**Comment by CodingPapi** [comment]
@Huachao I running a restapi server in a linux server, and using vscode remotessh plugin on this server. Let's say it's IP is a.b.c.d. I send a post request using http://127.0.0.1:8080/xxxxx with restclient running in remote, it returns 403 forbidden. After change it to http://a.b.c.d:8080/xxxxx it works well.
curl --request GET  --url http://127.0.0.1:8801/xxxxx  also works well on remote server

**Comment by Huachao** [comment]
@CodingPapi what confused me is that your curl example with `127.0.0.1` is a `GET` request while the HTTP message request is of `POST`, can you try it in the same scenario?

**Comment by CodingPapi** [comment]
@Huachao Post or Get both fail, Just an example to clear my situation in my previous comment

**Comment by Huachao** [comment]
@CodingPapi could you please show me  your 403 response

**Comment by CodingPapi** [comment]
@Huachao 
I figure this out, I set a http proxy in user side of vscode, and our proxy server allow accessing  127.0.0.1 from it.
But I have another question: I set the proxy in user side, not in remote side. as your plugin working in remote , how this proxy affect your plugin?

Anyway, thank you for you efforts investigating this issue, I will close this
