### ISSUE TITLE
x-request type: rest header in order to make graphql request as default.

### ISSUE THREAD

**Issue by collegeimprovements** [Huachao/vscode-restclient#576]
Almost all the request we make are `graphql` requests. 
Is it possible to set `X-REQUEST-TYPE: GraphQL` as default and set `X-REQUEST-TYPE: REST` only when we are making rest calls ?

**Comment by Huachao** [comment]
@collegeimprovements I have fixed this and you can use default headers in setting
```json
"rest-client.defaultHeaders": {
        "X-Request-Type": "GraphQL"
}
```
You can expect this in the next release.
