### ISSUE TITLE
"application/graphql" Content-Type header support

### ISSUE THREAD

**Issue by mfulton26** [Huachao/vscode-restclient#577]
From [Serving over HTTP | GraphQL](https://graphql.org/learn/serving-over-http/):

> If the "application/graphql" Content-Type header is present, treat the HTTP POST body contents as the GraphQL query string.

this would be, IMO, a great alternative to needing to specify `x-request-type: GraphQL`

**Comment by Huachao** [comment]
@mfulton26 I think this is supported natively. The reason we need users to specify the `x-request-type: GraphQL` header, is that they need some extra processing for the normal GraphQL query to be compatible with the `Content-Type: application/json`. We need some hints to know if we need to do some extra processing for request body tagged with `application/json`. You can try the `application/graphql` if your server-side supports this.
