### ISSUE TITLE
Space in URL causes wrong colorization

### ISSUE THREAD

**Issue by cilerler** [Huachao/vscode-restclient#584]
REST Client Version: 0.23.2
Version: 1.44.2 (system setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. copy the following snippet into a `.HTTP` file
```HTTP
@host = localhost:44302
@baseUrl = https://{{host}}/odata

### @name GetRecordWithExtensionTables
GET {{baseUrl}}/MyModel1(1)?$expand=MyModel3 HTTP/1.1
Host: {{host}}
Cache-Control: no-cache

### @name GetLastThreeRecordIdsAndSoftDeletes
GET {{baseUrl}}/MyModel1?$count=true&$orderby=Id desc&$top=3&$select=Id,SoftDelete HTTP/1.1
Host: {{host}}
Cache-Control: no-cache
```

![image](https://user-images.githubusercontent.com/385958/81421729-eded7f80-911f-11ea-8dea-94ff638c1cd1.png)

**Comment by Huachao** [comment]
@cilerler I have fixed this issue and will publish it in the next release.

**Comment by Huachao** [comment]
@cilerler you can try the latest version 0.2.4.0 to verify it.

**Comment by cilerler** [comment]
Thanks @Huachao 
confirming that it is working as expected.
