### ISSUE TITLE
Query string parameters not accepting variables as values

### ISSUE THREAD

**Issue by shadabtamboli** [Huachao/vscode-restclient#588]
Can variables be added as values for query string parameters? It doesn't seem to be working.

https://{{host}}/employees/report?startDate={{@startDate}}&endDate={{endDate}}

**Comment by Huachao** [comment]
@shadabtamboli do you mean the `startDate` variable not working, it seems you add a redundant leading `@` before `startDate`

> https://{{host}}/employees/report?startDate={{@startDate}}&endDate={{endDate}}

**Comment by Huachao** [comment]
@shadabtamboli do you still meet this issue, I'd like to close it since it seems you add the extra `@` before variable references
