### ISSUE TITLE
Performance issue when rendering large response

### ISSUE THREAD

**Issue by Huachao** [Huachao/vscode-restclient#59]
- VSCode Version: 1.8.1
- OS Version: 
- REST Client Version: 0.11.4

Steps to Reproduce:

1. As title, previously mentioned in #58 and #56

**Comment by Huachao** [comment]
@albertywu @sfertman I have improved the performance of rendering large response, and I will publish this fix in next release.

**Comment by Huachao** [comment]
@albertywu @sfertman now you can try the latest version to verify it.

**Comment by sfertman** [comment]
@Huachao thanks for the updates. Rendering does feel to be faster; however, scrolling still sluggish... The workaround I've been using so far for very large responses (~400KB or more) is to save the response and open it in VSCode editor.
