### ISSUE TITLE
Response body should not be parsed for "204 No Content" code

### ISSUE THREAD

**Issue by YBogomolov** [Huachao/vscode-restclient#598]
- REST Client Version: 0.23.2
- VSCode Version: 1.45.1
- OS Version: macOS 10.15.5

Prerequisites:

1. REST API which responds to POST verb with `204 No Content` code, `Content-Type: application/json` headers and empty body.

Steps to Reproduce:

1. Create the following REST request:

```
POST http://host.tld/some-api HTTP/1.1
Content-Type: application/json

{}
```

2. Execute the request.

Actual behaviour:

1. A warning message in the lower right corner stating: `The content type of response is application/json, while response body is not a valid json string`.
2. The request is executed successfully.

Expected behaviour:

1. No warning is displayed.
2. The request is executed successfully.

Comments:

As per RFC 2616, the server can respond with both `Content-Type` header and empty body under 204 HTTP code. Please see these links for details:
http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.2.5
http://www.w3.org/Protocols/rfc2616/rfc2616-sec7.html#sec7.1

Suggested changes:

1. Parse response body only if the response code supposes presence of that body.

**Comment by Huachao** [comment]
@YBogomolov nice catch, I have fixed this issue and will publish it in the next release.

**Comment by Huachao** [comment]
@YBogomolov you can verify this in the latest version 0.24.0

**Comment by YBogomolov** [comment]
@Huachao It works as intended, thank you!
