### ISSUE TITLE
invalid multipart/form-data  payload

### ISSUE THREAD

**Issue by newbienewbie** [Huachao/vscode-restclient#599]
- REST Client Version: 0.23.2
- VSCode Version: 1.15.1
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

send a  `multipart/form-data` HTTTP  request as below:
```
POST http://localhost:8848/api/Tag/ReceiveHighFreqData
Authorization: DAC-Key siphtum.dac.key
Content-Type: multipart/form-data; boundary=----MYBOUDNRY

----MYBOUDNRY
Content-Disposition: form-data; name="sn"

0000000000000008
----MYBOUDNRY
Content-Disposition: form-data; name="ch"

2
----MYBOUDNRY
Content-Disposition: form-data; name="hf"; filename="1.txt"
Content-Type: application/octet-stream

< .\asdf.txt
----MYBOUDNRY--
```

However, the actual payload captured using Wireshark is :

![image](https://user-images.githubusercontent.com/10741879/83356017-c643ad00-a395-11ea-82eb-fed54e9561fb.png)

Note there's a  **trailing "...Connection Age 18248 0.3  > 850..".**

In contrast, a correct payload sent by PostMan looks like below:

![image](https://user-images.githubusercontent.com/10741879/83356155-a365c880-a396-11ea-9fdc-0fc67a00231c.png)

**Comment by Huachao** [comment]
@newbienewbie since the boundary is `----MYBOUDNRY `, the boundaries used in the request body should add two extra `--` before the boundary, as well as append `--` for the last boundary. The correct one should look like following:

```http
POST http://localhost:8848/api/Tag/ReceiveHighFreqData
Authorization: DAC-Key siphtum.dac.key
Content-Type: multipart/form-data; boundary=----MYBOUDNRY

------MYBOUDNRY
Content-Disposition: form-data; name="sn"

0000000000000008
------MYBOUDNRY
Content-Disposition: form-data; name="ch"

2
------MYBOUDNRY
Content-Disposition: form-data; name="hf"; filename="1.txt"
Content-Type: application/octet-stream

< .\asdf.txt
------MYBOUDNRY--
```

**Comment by newbienewbie** [comment]
My Bad. Thanks for your detailed explanation.  :)
