### ISSUE TITLE
after closing the pane once cannot send request 

### ISSUE THREAD

**Issue by NikosEfthias** [Huachao/vscode-restclient#6]
i get following error if i click to the cross over the request pane and try to send another requests afterwards .

It just hangs and does nto let me close even
![](http://i.imgur.com/Ktqb4nZ.png)

**Comment by NikosEfthias** [comment]
i am under arch linux and vscode version is 1.2.1

**Comment by Huachao** [comment]
@NikosEfthias, thanks, I want to confirm the issue with you, do you mean that after you sent out one request, and close the request pane. Then you reopen a request pane, the response pane doesn't show

**Comment by NikosEfthias** [comment]
yes exactly @Huachao if you wish we can make a fazt zoom meeting to show yu the issue

**Comment by Huachao** [comment]
@NikosEfthias, now I can't reproduce the bug on my machine (Windows 10, vs code 1.2.1). Could you please attach a screen shot of that time? Thanks. And from the image you posted above, I found the error call stack seems not related to my extension, it's about extension `chrmati.regext-0.0.2`. Could you please show me the related screen shot, sorry for the inconvenience. BTW, what's the `fazt zoom meeting`?

**Comment by NikosEfthias** [comment]
it was supposed to be fast zoom meeting :)

**Comment by Huachao** [comment]
@NikosEfthias, is this bug still existed?

**Comment by NikosEfthias** [comment]
i cannot reproduce this after changing to ubuntu from arch linux either its solved by an update or it was os specific problem
