### ISSUE TITLE
post和get时怎么没带上数据？？

### ISSUE THREAD

**Issue by tygogo** [Huachao/vscode-restclient#60]
- VSCode Version:1.81
- OS Version:macOS 10.12.2
- REST Client Version:0.11.4

Steps to Reproduce:

1. 完全是复制的你说明里的代码，改了下网址
2.右键发送

可是我在服务器上看收到的post字典是空的，，get的时候数据也没有加在url后面，这是为什么？我试了很多次都是这样
为了排除我自己的问题，我特意用百度搜索来试了下,结果这两个结果都不一样，第一个真的没有带上数据
```
###

GET https://m.baidu.com/ssid=ca21b6e0b4ced5fcbec8b5d8c7f29435/s HTTP/1.1

{
    "word":"haha",
}
###

GET https://m.baidu.com/ssid=ca21b6e0b4ced5fcbec8b5d8c7f29435/s?word=haha HTTP/1.1

###
```

**Comment by Huachao** [comment]
@tygogo in your case, is the response got from my extension right or as expected? And what did you see in your server, you said no data after url, does it mean no query string? Could you show me the server result?

**Comment by Huachao** [comment]
@tygogo still having the problem?

**Comment by Huachao** [comment]
@tygogo I'd like to close the issue, if you still meet this issue, just reopen it. 😄
