### ISSUE TITLE
POST body data is not being sent

### ISSUE THREAD

**Issue by druffner924** [Huachao/vscode-restclient#600]
- REST Client Version: 0.23.2
- VSCode Version: 1.45.1
- OS Version: Ubuntu 20.04 LTS
- PHP Version: 7.4.3
- Apache Version: 2.4.41
- NodeJS Version: 12.16.3
- Nginx Version: 1.17.10

Hi,

I am running an API endpoint on my local machine. To start, I tried a simple test that looks like this:
POST http://[my local IP address]/post_test.php HTTP/1.1

Content-Type: application/json

{
    "token": "Test"
}

The PHP file simply grabs $_POST['token'] and echos it if it exists, otherwise it echos an error message. I've been finagling with the settings for over an hour, and unfortunately I cannot get the body data to be sent over. I also tried sending it over in application/x-www-form-urlencoded type to no avail. I've tried this on a PHP file running on Apache (see version above), and on a node js endpoint running Nginx, and could not get any POST data to send. Please feel free to ask for any more info if needed.

**Comment by druffner924** [comment]
I also want to add, that I've verified my endpoints are working properly using Postman to pass the data.

**Comment by Huachao** [comment]
> POST http://[my local IP address]/post_test.php HTTP/1.1
> 
> Content-Type: application/json
> 
> {
> "token": "Test"
> }

You have added an extra line between request line and headers, the correct syntax should look like following:
```http
POST http://[my local IP address]/post_test.php HTTP/1.1
Content-Type: application/json

{
"token": "Test"
}
```
