### ISSUE TITLE
How to return paginated output altogether?

### ISSUE THREAD

**Issue by rdhar** [Huachao/vscode-restclient#606]
Hi there,

Love this extension for its ease of use when pinging a RESTful API!

I'm trying to return the complete set of results of an array split over several pages using this example.

```http
# @name read_posts
GET https://jsonplaceholder.cypress.io/posts?_page=1
```

There are typically 2 types of paginated API content traversal:

1. **Body: `more` and `offset` attributes**
E.g., [PagerDuty](https://developer.pagerduty.com/docs/rest-api-v2/pagination/). Here, we parse the body to determine whether there are `more` results and, if so, increment the `offset` to get the next batch.

2. **Header: Link `rel` pages**
E.g., [GitHub](https://developer.github.com/v3/guides/traversing-with-pagination/). Here, we parse the header to determine the relational `rel` links to other pages and, if available, query the next page.

The example endpoint shown above is using the [latter](https://github.com/typicode/json-server#paginate) but I would really appreciate it if you could demo how to return paginated output altogether for either of these methods.

Thanks for your time.

**Comment by devlie** [comment]
Here's a way to get all pages for paginated API that returns URL to next page in either response body or headers. You can try modifying it to suit your API. 

1. Create request to get first page
2. Create second request to get second page using link from first page.
3. Create a third request, but name it identically to second request to get subsequent page using link from itself.

```
###
# @name enumOperations
GET {{base_url}}/updates/operations?$top=100

###
# @name enumOperationsNextPage
GET {{host}}{{enumOperations.response.body.nextLink}}

###
# @name enumOperationsNextPage
GET {{host}}{{enumOperationsNextPage.response.body.nextLink}}
````

Sort of hacky, but it works. I wish there's a simpler way to do this too.

**Comment by rdhar** [comment]
Thanks for the workaround, @devlie, appreciate it. I wonder if it's possible to chain together requests to run in bulk.
