### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by telegu** [Huachao/vscode-restclient#609]
- REST Client Version: 0.24.0
- VSCode Version:  1.46.0
- OS Version: MacOs 10.14.6

Steps to Reproduce:
When I send a request I receive this message:
**Cannot read property 'toLowerCase' of undefined**
[](url)

**Comment by Huachao** [comment]
@telegu can you show me the output in the *Output* window of VS Code for the `REST` channel?

**Comment by telegu** [comment]
This https://github.com/Huachao/vscode-restclient/issues/607 fixed the issue

**Comment by Huachao** [comment]
@telegu glad to hear that 😄

**Comment by telegu** [comment]
🔝
