### ISSUE TITLE
Problem with application/x-www-form-urlencoded request

### ISSUE THREAD

**Issue by rbierowiec** [Huachao/vscode-restclient#613]
Hi,
Yesterday everything working as expected. Today I had some VS Code updates and Oauth2 token request stopped working. After investigation I can see that there is problem with request parameters.

This is my token request:
![image](https://user-images.githubusercontent.com/18077823/84767165-3e36e780-afd2-11ea-8539-2fec44c9e969.png)

And see what is being sent (from the Fiddler)
![image](https://user-images.githubusercontent.com/18077823/84767237-5e66a680-afd2-11ea-9283-acfeb086d314.png)

It is not stopping parameter on the end of the line but putting also few next lines to the parameter value. Is this a some kind of bug or should I use some special character to mark request body end?

Regards,
Rafal

**Comment by rbierowiec** [comment]
I checked right now. Case above is working fine with version 0.23.2, the problem occurs since version 0.24.0.

**Comment by rbierowiec** [comment]
Another update, putting ### in line before assigning @token variable doing the job. Is this expected behavior?

**Comment by Huachao** [comment]
@rbierowiec you are right, you should add the `###` separator, and this is a breaking change. The reason is described in other thread https://github.com/Huachao/vscode-restclient/issues/607#issuecomment-643340438
