### ISSUE TITLE
Support for API documentation.

### ISSUE THREAD

**Issue by SutharMukesh** [Huachao/vscode-restclient#618]
The extension works great when creating REST calls and maintaining them in `.http` files, I can also specify a description for an API inside a comment but there is no sperate support for documenting all APIs.  
> I liked how _postman_ creates the API document for us.  

Is there any way I can export the `.http` file into postman collection format? as I can generate docs inside postman.  
or can the extension have swagger like API docs support?

**Comment by Huachao** [comment]
Duplicate of #67

**Comment by verydemo** [comment]
up up up
