### ISSUE TITLE
请求参数里  带‘$’的无法正确解析

### ISSUE THREAD

**Issue by wodesj33** [Huachao/vscode-restclient#622]
- REST Client Version:0.24.1
- VSCode Version:1.46.1
- OS Version:win10 v2004

Steps to Reproduce:

- [ 地址] http://zjy.jxjst.gov.cn/w/dataQuery/getCompDate

- [ 请求参数] 
parameter:=
&$pgsz=15
&$pg:=15
期望的返回json结果里
应该是
 "page": 15,
  "pageSize": 15,

**Comment by Huachao** [comment]
@wodesj33 could you please both paste the actual URL in `.http` file and the one you can work in the cURL format?

**Comment by wodesj33** [comment]
我搞错了  是他们网站做了限制
