### ISSUE TITLE
normalizeHeaderNames - option to disable lowercase the header

### ISSUE THREAD

**Issue by leodinas-hao** [Huachao/vscode-restclient#623]
Thank for sharing this awesome tool.  However I recently had some issues where the vendor applications consider header names are case-sensitive, the requests sent via this client converts the header names to lowercase automatically and this brought me some headache.

Currently `normalizeHeaderNames` function of "[utils/httpClient.ts](https://github.com/Huachao/vscode-restclient/blob/master/src/utils/httpClient.ts)" converts headers to lowercase, some applications do not appreciate this feature and cause some issue with unidentified header. I know according to the Standards header names should be case-**in**sensitive.  Is there any chance that we have an option/settings to disable such auto case converting?

Thank you again and look forward to hearing your thoughts.

Regards,

**Comment by Huachao** [comment]
@leodinas-hao actually this is not related to the code you've pointed out. It's responsible for prettifying the **response** header names. The outgoing request header names are lowercased by the Node.Js framework internally, and we can't control its behavior.
