### ISSUE TITLE
Parse url incorrectly when contains space

### ISSUE THREAD

**Issue by InfiniSuite** [Huachao/vscode-restclient#63]
Executing a rest call that includes json with REST Client mangles any json element with a space in the contents. Running the same call with Postman works. 

- VSCode Version: Version 1.8.1 (1.8.1)
- OS Version: OSX 10.12.2 (16C67)
- REST Client Version: v0.12.0

**Steps to Reproduce:**

**Parse and execute (get) this rest call:**
```
GET http://localhost:8080/api/transaction_view/?filter={"fields":{"rowid":true,"transactiondate":true,"description":true,"totalamount":true},"where":{"or":[{"and":[{"transactiondate":{"gte":"2016-12-01"}},{"transactiondate":{"lte":"2017-01-01"}}]}]},"order":"rowid desc"}
token: sd0iwer90sdflksdf
```
**The string that REST Client is actually sending to the server is:**
`"{"fields":{"rowid":true,"transactiondate":true,"description":true,"totalamount":true},"where":{"or":[{"and":[{"transactiondate":{"gte":"2016-12-01"}},{"transactiondate":{"lte":"2017-01-01"}}]}]},"order":"rowid"`

**Note** that `"order":"rowid desc"}` has been changed to `"order":"rowid"`

**Comment by Huachao** [comment]
@InfiniSuite I have fixed the bug and will publish in next release. The root cause is that the request line contains space in url, here is the space after `rowid`. Currently, you can work around by making query string in another line, like:
```http
GET http://localhost:8080/api/transaction_view/
?filter={"fields":{"rowid":true,"transactiondate":true,"description":true,"totalamount":true},"where":{"or":[{"and":[{"transactiondate":{"gte":"2016-12-01"}},{"transactiondate":{"lte":"2017-01-01"}}]}]},"order":"rowid desc"}
token: sd0iwer90sdflksdf
```

This should be work now.

**Comment by Huachao** [comment]
@InfiniSuite you can try the latest version 0.12.1 to verify it, thanks for your feedback 😃

**Comment by InfiniSuite** [comment]
Thanks!
