### ISSUE TITLE
Allow {{...}}  in comments and strings without linting error

### ISSUE THREAD

**Issue by tvld** [Huachao/vscode-restclient#631]
Right now {{}}  gives an error if we have a comment:
```inf
# This is an old  {{variable}}
```
I think comments should not lint.

By coincidence we also have POST parameters that need {{ }} , and that also generates undesired linting errors: 

```js
POST {{host}}/mail HTTP/1.1
content-type: application/json

{
  "to": [
    "tom@lorinthe.com"
  ],
  "subject": "New Password",
  "body": "Hello <b>{{name}}</b>, this is your new password: {{password}}.",
  "type": "html",
  "data": {
    "name": "John Doe",
    "password": "secret"
  }
}
```

**Comment by Huachao** [comment]
@tvld I have fixed the problem that linting errors occur in comments, for the latter one, this is by design since the variable evaluation logic takes effect in body strings

**Comment by tvld** [comment]
@Huachao super, thank you.

 For the strings we can now use a work-around to comment them out, before saving.

**Comment by Huachao** [comment]
@tvld you can try the latest version 0.24.2

**Comment by tvld** [comment]
Great thank you ))
