### ISSUE TITLE
Getting parameter from a request

### ISSUE THREAD

**Issue by ygavrishov** [Huachao/vscode-restclient#633]
Hi! I'm trying to get a parameter value from an HTTP request that is generated randomly. This is my code:
```
#create auth user
# @name createUser
POST {{authServiceUrl}}/api/v1/users
content-type: application/json

{
    "email": "test-{{$guid}}@example.com",
    "passwordhash": "XXX"
}

@email = {{createUser.request.body.$.email}}
```

As a result I get the error:

> Unexpected token @ in JSON at position 187

What is the correct way to do it?

Thanks in advance

**Comment by Huachao** [comment]
@ygavrishov Please add a request delimiter `###` before the `email` file variable definition as following
```http
#create auth user
# @name createUser
POST {{authServiceUrl}}/api/v1/users
content-type: application/json

{
    "email": "test-{{$guid}}@example.com",
    "passwordhash": "XXX"
}

###

@email = {{createUser.request.body.$.email}}
```

**Comment by ygavrishov** [comment]
Doesn't help... The same error

**Comment by Huachao** [comment]
@ygavrishov did you meet this error when you try to send the request, could you please paste your request after modification?

**Comment by kabrau** [comment]
```
### create auth user
# @name createUser
POST {{authServiceUrl}}/api/v1/users
content-type: application/json
 
{
     "email": "test-{{$guid}}@example.com",
     "passwordhash": "XXX"
}

### 
@email = {{createUser.request.body.email}}
```
1) Insert ### before @email = 
2) and, in this case, without $

**Comment by Huachao** [comment]
@kabrau do you mean you can only work when you remove the `$` in the request variable path?

**Comment by Huachao** [comment]
@ygavrishov in which case did you meet the following error?

> Unexpected token @ in JSON at position 187

**Comment by ygavrishov** [comment]
> @kabrau do you mean you can only work when you remove the `$` in the request variable path?



> @ygavrishov in which case did you meet the following error?
> 
> > Unexpected token @ in JSON at position 187

I used the snippet that you recommended. This is the only content of the file:
```json
@authServiceUrl=https://vs-auth-dev01.azurewebsites.net
#######################
#create auth user
# @name createUser
POST {{authServiceUrl}}/api/v1/users
content-type: application/json

{
    "email": "test-{{$guid}}@example.com",
    "passwordhash": "XXX"
}

###

@email = {{createUser.request.body.$.email}}
```

**Comment by ygavrishov** [comment]
> ```
> ### create auth user
> # @name createUser
> POST {{authServiceUrl}}/api/v1/users
> content-type: application/json
>  
> {
>      "email": "test-{{$guid}}@example.com",
>      "passwordhash": "XXX"
> }
> 
> ### 
> @email = {{createUser.request.body.email}}
> ```
> 
> 1. Insert ### before @email =
> 2. and, in this case, without $

Yes, it works!

**Comment by Huachao** [comment]
@ygavrishov I still don't understand when you meet this error, sending the createUser request or hovering the email variable value

**Comment by ygavrishov** [comment]
I realized that both options (with or without $) work if I close the editor and open it again. Seems the error depends on previous changes in the document.

**Comment by Huachao** [comment]
@ygavrishov so adding `###` work for you, right? I'd like to close this issue. If you still have any questions, please feel free to reopen it.
