### ISSUE TITLE
可以require其他文件吗？ 

### ISSUE THREAD

**Issue by mztlive** [Huachao/vscode-restclient#634]
比如说，我有一个login.http的文件。

# @name mobileLogin
POST {{host}}/xxxxx/login HTTP/1.1
Content-Type: application/json

{
       "mobile": "186xxxxxx",
	"loginType": "1",
	"password": "123456",
	"source": 12
}

@token = {{mobileLogin.response.body.data.token}}

现在在另外一个 userInfo.http的文件里面我希望能直接复用login.http里面的请求和变量。 请问如何能做到呢？
（复制粘贴过来我知道，除了这个）

另外，还想问一下。 因为有些项目在api报错的时候是会返回html页面的， 有设置html preview的功能吗？

**Comment by Huachao** [comment]
Duplicate of #182

**Comment by Huachao** [comment]
Duplicate of #146
