### ISSUE TITLE
$filter GET query param broken in 0.24.1 (but works in 0.23.2)

### ISSUE THREAD

**Issue by vobu** [Huachao/vscode-restclient#635]
- REST Client Version: 0.24.1 (but **works with v0.23.2**)
- VSCode Version: 1.46.1
- OS Version: macOS 10.15.5

Steps to Reproduce:

1. construct an (OData) GET query with a `$filter` parameter, e.g.
```
https://{{host}}/some/odata/endpoint
?$top=100
&$filter=property eq null
```

2. `Send Request` -> error:
```
RequestError: Method must be a valid HTTP token ["HTTPS://HOST.EX.ORG/SOME/ODATA/ENDPOINT?$TOP=100&$FILTER=PROPERTY"]
	at L (/Users/<user>/.vscode/extensions/humao.rest-client-0.24.1/dist/extension.js:252:3866)
	at async Immediate.<anonymous> (/Users/<user>/.vscode/extensions/humao.rest-client-0.24.1/dist/extension.js:252:4514)
```
Looks like some `RegEx` going wild 😄

**Comment by Huachao** [comment]
@vobu I have fixed this issue and will be published in the next release.

**Comment by Huachao** [comment]
@vobu you can try the latest version 0.24.2

**Comment by vobu** [comment]
works! thanks!
🥳
