### ISSUE TITLE
Variable passed to request header is incorrect (a previous copy, or from another file?)

### ISSUE THREAD

**Issue by dancherb** [Huachao/vscode-restclient#636]
- REST Client Version: 0.24.1
- VSCode Version: 1.42.1
- OS Version: Windows 10 Pro - Version 1809 - OS build 17763.379

This has begun occurring fairly randomly over the last few weeks. Calls will start passing through the wrong variable to headers, even after previous calls worked correctly (and no variables were changed). This seems to happen after re-opening the .http file.

```
@token = 456

### TEST ROUTE
GET {{URL}}/example
Auth: {{token}}
```

And then in logs:

`req.headers.Auth = 123`

Copying the token directly without using a variable works correctly.

```
### TEST ROUTE
GET {{URL}}/example
Auth: 456
```

After doing this, switching `{{token}}` back in seems to work and pass through the correct variable

**Comment by Huachao** [comment]
@dancherb did you have multiple definitions for the variable `token`, and can you show me the screenshot when you hover over the variable `token`?

**Comment by dancherb** [comment]
> 
> 
> @dancherb did you have multiple definitions for the variable `token`, and can you show me the screenshot when you hover over the variable `token`?

The value for token within the file does change periodically yes. I also have other .http files in the same folder that have their own @token variables. This error seems to occur after re-opening the .http file - editing the file and typing some stuff seems to "refresh" it and then it uses the correct variable. Maybe it's using a cached version up until then.

![tokens](https://user-images.githubusercontent.com/32280121/87002820-c4270680-c1fd-11ea-9169-ffde81c5bfcd.png)

**Comment by Huachao** [comment]
@dancherb so when you open the `.http` file, the variable value seems incorrect, is the value the exact one defined in other `.http` file?

**Comment by dancherb** [comment]
> 
> 
> @dancherb so when you open the `.http` file, the variable value seems incorrect, is the value the exact one defined in other `.http` file? Is the `token` variable value references other variables? We really have some file variable cache, but the key is the document uri.

The incorrect value is not one that appears presently in another .http file.

I have 3 .http files in the folder. The same error occurs in another one of them - here there is a _different_ incorrect value that also is not one that is actually present in another .http file.

The final .http file actually works fine straight away - the correct variable is referenced. This is a .http file that I have _not_ been working on this session.

The token variable value does not reference other variables - it's always just a long string passed in.

I think this points to a file caching issue - this must have come from a recent update because I didn't have this issue until recently.

(p.s. awesome extension and thanks for the quick help)

**Comment by Huachao** [comment]
@dancherb you mean the incorrect value happens to be the previous values in that file?

**Comment by dancherb** [comment]
> 
> 
> @dancherb you mean the incorrect value happens to be the previous values in that file?

Yes - after some experimentation, I've found:

The incorrect value is the value of that variable _when VScode is opened_. If you change the variable in the .http file, it picks up the latest one while the file is open. _However,_ if you close and then re-open the .http file, the value will revert to what the value was at the start of the VScode session (even though the value actually written in the .http file is different).

**Comment by Huachao** [comment]
@dancherb I can't reproduce your case, did you save the `.http` file after you changed the `token` variable value?

**Comment by dancherb** [comment]
> @dancherb I can't reproduce your case, did you save the `.http` file after you changed the `token` variable value?

Yes I saved. When I re-open the .http file it shows the latest saved version, but it still "uses" the version cached when VScode was first opened that session.

**Comment by Huachao** [comment]
@dancherb I cached the `FileVariables` based on the document Uri and document version (https://code.visualstudio.com/api/references/vscode-api#TextDocument). And in my test, if VSCode itself is not closed, the version of the document is always strictly increased. The case of you seems VSCode doesn't follow this rule and the document version of the same file is reset back to the previous ones. And I can't reproduce it. I can add some defense code that deletes all the cached versions of the same document when the document is closed.

**Comment by Huachao** [comment]
@dancherb One more question, did you open the `.http` file in the same VSCode instance?

**Comment by Huachao** [comment]
@dancherb I have fixed this and will publish it in the next release.

**Comment by dancherb** [comment]
Awesome, love you @Huachao

**Comment by Huachao** [comment]
@dancherb you can try the latest version 0.24.2
