### ISSUE TITLE
auth not working

### ISSUE THREAD

**Issue by romanown** [Huachao/vscode-restclient#638]
- REST Client Version: last
- VSCode Version: last
- OS Version: win7
i tryed making to request. but website need authorisation
GET https://mywebsite.com/api/view?id=14  HTTP/1.1
Authorization: Basic myusername:mypassword
Content-Type: application/json
and response is auth reqired
when i past this heders in the any brauser it worked

**Comment by Huachao** [comment]
@romanown could you please show me the request that you worked in the browser?

**Comment by romanown** [comment]
i changed hostname

    GET /api/view?id=14 HTTP/1.1
Host: mywebsite.com
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Authorization: Basic myusername:mypassword
Connection: keep-alive
Cookie: _ym_uid=1572089948816216782; _ym_d=1587901216; _ga=GA1.2.1227489136.1572081951; _fbp=fb.1.1572258632292.103892603; _gid=GA1.2.742085029.1593295618; sidePanelIsShow=1; YII_CSRF_TOKEN=eDlvN1Bibfk3aURN095TMm9DY2dWM2FLN0tfTkxRUFhEUT_EOmOubIlycYZFRbgaaLm9nO_mDQOKnvBzkpMX-Q%3D%3D; _ym_isad=2; _ym_visorc_23216866=w; sessionHash=1a32335b0947d8fe347331875a36b384
Upgrade-Insecure-Requests: 1
Pragma: no-cache
Cache-Control: no-cache
DNT: 1

**Comment by Huachao** [comment]
> GET /api/view?id=14 HTTP/1.1 Host: mywebsite.com User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8 Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3 Accept-Encoding: gzip, deflate, br Authorization: Basic myusername:mypassword Connection: keep-alive Cookie: _ym_uid=1572089948816216782; _ym_d=1587901216; _ga=GA1.2.1227489136.1572081951; _fbp=fb.1.1572258632292.103892603; _gid=GA1.2.742085029.1593295618; sidePanelIsShow=1; YII_CSRF_TOKEN=eDlvN1Bibfk3aURN095TMm9DY2dWM2FLN0tfTkxRUFhEUT_EOmOubIlycYZFRbgaaLm9nO_mDQOKnvBzkpMX-Q%3D%3D; _ym_isad=2; _ym_visorc_23216866=w; sessionHash=1a32335b0947d8fe347331875a36b384 Upgrade-Insecure-Requests: 1 Pragma: no-cache Cache-Control: no-cache DNT: 1

Is this the request you copied from the Chrome network tab? I found your request sent in the browser has an extra `Content-Type` header, how about remove it?

**Comment by romanown** [comment]
from mozilla. i added Content-Type: application/json and its worked also in the browser. not worked from 
vscode-restclient  becose need authorisation

**Comment by Huachao** [comment]
@romanown could you please show me the curl format request from firefox?

**Comment by romanown** [comment]
![изображение](https://user-images.githubusercontent.com/7169357/87279153-3e51d680-c4ef-11ea-9776-de781f7e9070.png)
screen. i can not curl.

**Comment by romanown** [comment]
i can.curl "https://mywebsite.com/api/view?id=14" -H "User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" -H "Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3" --compressed -H "Authorization: Basic login:password" -H "Connection: keep-alive" -H "Content-Type: application/json" -H "Cookie: _ym_uid=1594189948816621782; _ym_d=1532105196; _ga=GA1.2.1225629136.1572089951; _fbp=fb.1.1572345630392.103899603; _gid=GA1.2.734585029.1593295618; sidePanelIsShow=1; YII_CSRF_TOKEN=eDlv1FoUkHk3aURNYX5TMm9DY2dW3CcLN0tfTkxRUFhEUT_EOmOubIlycYZFRbgaaLm9nO_mDQlKnvBzkpMX-Q"%"3D"%"3D; _ym_isad=2; _ym_visorc_24216866=w; sessionHash=1a32324bbd47d8fe1803eb65a36b384" -H "Upgrade-Insecure-Requests: 1" -H "Pragma: no-cache" -H "Cache-Control: no-cache" -H "DNT: 1" -H "TE: Trailers" 13.07.2020, 09:44, "Huachao Mao" <notifications@github.com>: @romanown could you please show me the curl format request from firefox?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.  -- Roman

**Comment by Huachao** [comment]
@romanown I guess it's related with the Cookie header, could you please copy the whole Cookie header into your `.http` file

**Comment by romanown** [comment]
![изображение](https://user-images.githubusercontent.com/7169357/87288921-a828ab00-c504-11ea-9ad4-34ec73b5bc3a.png)

this I immediately tried to do

**Comment by romanown** [comment]
the request is being processed. the authorization page is returned in response. I use yii.

**Comment by Huachao** [comment]
@romanown did you mean it's still not working even if you set the cookie header, hmm, how about set `rest-client.rememberCookiesForSubsequentRequests` to `false`? Another question is that will redirections happen in this API?

**Comment by romanown** [comment]
I made a logout in the browser and got the authorization page the same way. the browser cannot log in with the header. but your module is able to log in.

**Comment by Huachao** [comment]
@romanown so I guess it's related with the Cookie header value, so can I close this issue?

**Comment by romanown** [comment]
but your module was not able to log in. but the browser could. so you need to do something so that your plug - in can log in as a browser. otherwise, most of its functionality is useless.

**Comment by romanown** [comment]
close issue. but let this become a plan to improve the module.

**Comment by Huachao** [comment]
> I made a logout in the browser and got the authorization page the same way. the browser cannot log in with the header. but your module is able to log in.

@romanown as you said, you can't log in either after logging out? Can you work with the browser now?

**Comment by romanown** [comment]
I logged in again in the browser and am working. this is the standard backend functionality. the browser could not get data after logging out and sending messages via devtool. if You have the desire to continue, I can continue as well.

**Comment by romanown** [comment]
how i can rememberCookiesForSubsequentRequests = falsh?

**Comment by Huachao** [comment]
@romanown what's the Auth scheme for your API, `Basic Auth`? I suddenly find that you didn't invoke the login API in my extension, did you know the login API endpoint?



> how i can rememberCookiesForSubsequentRequests = false?

In the settings.json

**Comment by romanown** [comment]
i can not find settings

**Comment by Huachao** [comment]
@romanown just as normal VSCode settings, and could you first call the Login API in my extension?

**Comment by romanown** [comment]
i installed it and create the .http file.

**Comment by romanown** [comment]
i tryed rememberCookiesForSubsequentRequests = false. it not helped me

**Comment by romanown** [comment]
i can not call the Login API. in the POST auth worked but not redirected

**Comment by Huachao** [comment]
@romanown I think you first need to call the Login API and the server-side will return some cookies in the response headers. After that, you can trigger your normal API calls
