### ISSUE TITLE
Post and Put data not added to the request

### ISSUE THREAD

**Issue by udoniyor** [Huachao/vscode-restclient#64]
- VSCode Version: 1.8.1
- OS Version: Windows 10 Pro 1607 Build 14393.693
- REST Client Version: 0.12.0

I was trying to put a document into ElasticSearch via using the extension, but wasn't getting anything back. I checked if the extension is sending out the request details, by looks of it is not grabbing the post data. 

I used the example from the readme page

```
POST https://example.com/comments HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

```

To see if it is getting grabbed by the extension correctly I generated the code for Java, Jquery and Go, none of which included the post data. 

```
var settings = {
  "async": true,
  "crossDomain": true,
  "url": "https://example.com/comments",
  "method": "POST",
  "headers": {
    "content-type": "application/json"
  }
}

$.ajax(settings).done(function (response) {
  console.log(response);
});
```

**Comment by Huachao** [comment]
@udoniyor I found this bug in generating code snippet, I will fix it ASAP, while for sending request, the request body is along with the request. So do you met the issue only in generating code snippet case?

**Comment by Huachao** [comment]
@udoniyor I have fixed the bug in code generation, will publish a new version later, and if you have no body in sending request, please tell me 😄

**Comment by udoniyor** [comment]
@Huachao it seems to be only in the code generation. I was able to succesfully send post and put data to ElasticSearch through the extension.

**Comment by Huachao** [comment]
@udoniyor you can try the latest version 0.12.1 to verify it, thanks for your feedback 😃

**Comment by udoniyor** [comment]
@Huachao it is all working, thanks! Great extension
