### ISSUE TITLE
localDatetime timezone discrepancy in iso8601 format

### ISSUE THREAD

**Issue by rdhar** [Huachao/vscode-restclient#648]
### Summary

There is no difference in output between `datetime` and `localDatetime` in `iso8601` format. I would expect the local timezone to be taken into account for `localDateTime`.

### Replication Steps

Using [PostBin](https://postb.in/) as a free API client to test requests using this script:

```http
POST https://postb.in/###?
  &iso8601_datetime={{$datetime iso8601}}
  &iso8601_localDatetime={{$localDatetime iso8601}}
  &rfc1123_datetime={{$datetime rfc1123}}
  &rfc1123_localDatetime={{$localDatetime rfc1123}}
```

#### Expected Behavior

In the UK, which is currently observing UTC +1 timezone.

| Variable         | Format    | Result                          |
| ---------------- | --------- | ------------------------------- |
| `$datetime`      | `iso8601` | `2020-07-28T14:30:00.000Z`      |
| `$localDatetime` | `iso8601` | `2020-07-28T15:30:00.000+01:00` |

#### Actual Behavior

In the UK, which is currently observing UTC +1 timezone.

| Variable         | Format    | Result                     |
| ---------------- | --------- | -------------------------- |
| `$datetime`      | `iso8601` | `2020-07-28T14:30:00.000Z` |
| `$localDatetime` | `iso8601` | `2020-07-28T14:30:00.000Z` |

For comparison, this difference is reflected correctly in `rfc1123` format.

| Variable         | Format    | Result                           |
| ---------------- | --------- | -------------------------------- |
| `$datetime`      | `rfc1123` | `Tue, 28 Jul 2020 14:30:00 GMT`  |
| `$localDatetime` | `rfc1123` | `Tue, 28 Jul 2020 15:30:00 0100` |

Thanks for your time and effort for this extension and wish you the best with development on #628!

<details><summary>

### Version

</summary>

| REST Client | VS Code | OS               |
| ----------- | ------- | ---------------- |
| v0.24.1     | v1.47.3 | Windows 10 v2004 |

</details>

**Comment by Huachao** [comment]
@rdhar nice catch, I have fixed it, and before I publish a new version, you can try the format like following to achieve this `{{$localDatetime 'YYYY-MM-DDTHH:mm:ss.SSSZ'}}` with a specified format string.

**Comment by rdhar** [comment]
Thanks for such a prompt response, @Huachao, really appreciate it! Current behaviour is as follows:

| Variable         | Format                     | Result                          |
| ---------------- | -------------------------- | ------------------------------- |
| `$datetime`      | `iso8601`                  | `2020-07-28T14:30:00.000Z`      |
| `$localDatetime` | `iso8601`                  | `2020-07-28T14:30:00.000Z`      |
| `$localDatetime` | `YYYY-MM-DDTHH:mm:ss.SSSZ` | `2020-07-28T15:30:00.000 01:00` |

This is much closer to the expected value, with exception to the missing timezone signage i.e., `+01:00`. Without the `+/−`, there is no basis for relation with UTC so it's not a [valid ISO 8601 timezone](https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators) designator representation.

I understand you're using Day.js, where the relevant docs page for [Local](https://day.js.org/docs/en/manipulate/local#docsNav) time appears to suggest that a signed timezone is possible with:

```js
dayjs.extend(utc);

var a = dayjs.utc();
a.format(); // 2019-03-06T00:00:00Z
a.local().format(); //2019-03-06T08:00:00+08:00
```

Wonder if this would be possible to leverage the output for `{{$localDateTime iso8601}}`?

**Comment by Huachao** [comment]
@rdhar I will use your suggestion, however, the format `YYYY-MM-DDTHH:mm:ss.SSSZ` works on my machine

**Comment by rdhar** [comment]
Oh, in that case, I wonder if the issue is on my end. Sorry if I've caused a hassle, I'll double-check my output to be sure.

What's your output for `YYYY-MM-DDTHH:mm:ss.SSSZ` and your local timezone? How does this compare after your latest commit ba88dcb?

**Comment by Huachao** [comment]
@rdhar you can try the latest version 0.24.2

**Comment by rdhar** [comment]
The results are perfect, as shown in the screenshot from [Postb.in](https://postb.in/) below. Many thanks once again for your prompt resolution, @Huachao!

![image](https://user-images.githubusercontent.com/19497993/92166502-9d1d3780-ee30-11ea-9819-556c1efee16e.png)
