### ISSUE TITLE
Unable to send multipart/form-data 

### ISSUE THREAD

**Issue by arao5** [Huachao/vscode-restclient#66]
- VSCode Version: 1.8.1
- OS Version: Win7
- REST Client Version: 0.12.1

Tried the following code but i get bad response. but when tried with postman i get good response. am i doing anything wrong while sending request?

POST https://www.mysite.com/oauth2/token HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="type"

credentials
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="id"

12345
------WebKitFormBoundary7MA4YWxkTrZu0gW--

**Comment by Huachao** [comment]
@arao5 I will fix this ASAP, it's a bug of my code to parsing request body.

**Comment by Huachao** [comment]
@arao5 I have fixed the bug and will publish it in next release, sorry for the inconvenience.

**Comment by Huachao** [comment]
@arao5 you can try the latest version 0.12.2 to verify this fix, thanks for your feedback 😄

**Comment by arao5** [comment]
thanks.. it's working ..
