### ISSUE TITLE
[suggestion] Make virtual document preview as default view for responses

### ISSUE THREAD

**Issue by rafek1241** [Huachao/vscode-restclient#667]
As in topic.
Benefits:
* better performance.
* copy & paste working for any text.

**Comment by Huachao** [comment]
@rafek1241 what do you mean the *virtual document preview*, the webview mode or the text document mode?

**Comment by rafek1241** [comment]
@Huachao I mean the `text document mode` but after I reviewed it on my another computer I see that copy & paste working correctly for both modes and I just have problems (maybe because of other plugins) with vscode. Your text document mode is done based on https://code.visualstudio.com/api/extension-guides/virtual-documents.

**Comment by Huachao** [comment]
@rafek1241 the copy and paste function in webview mode doesn't work well in VS Code 1.40. After upgrading to the latest version 1.41, everything should work as expected. If you want to use text document mode as the default preview mode, you can set the `rest-client.previewResponseInUntitledDocument` to `true`

**Comment by rafek1241** [comment]
@Huachao I understand that there's no issue but why don't you want to set it as default on the extension level? Is the webView, that you're currently using, performant enough?

**Comment by Huachao** [comment]
@rafek1241 good question, actually we can set the text document view as the default one. The reason may be that the webview was implemented almost in the first version of the extension. The other reason is that no other users complain about this. Personally I think the switch to the text document view makes sense. Nonetheless, before other users voted for this, I still would like to keep it as is.

**Comment by rafek1241** [comment]
@Huachao I think people won't complain because they won't see any difference. Nowadays PCs are really strong and I guess that every user uses vscode not only with the `Rest client` plugin. In this way went they experience that performance drops they can assume that it doesn't related to the `Rest client`.
