### ISSUE TITLE
No response when result contains encoded string with double forward slash

### ISSUE THREAD

**Issue by warrenchin** [Huachao/vscode-restclient#676]
When response contains encoded string with double slash, the result just gone missing.

- REST Client Version: 0.24.2
- VSCode Version: 1.47.2
- OS Version: Mac 10.15.6

Steps to Reproduce:

1. Not OK
```
###
POST https://postman-echo.com/post
content-type: application/json; charset=utf-8

{
  "config": "{\"url\": \"https://google.com\"}"
}
```
2. OK
```
###
POST https://postman-echo.com/post
content-type: application/json; charset=utf-8

{
  "config": "{\"url\": \"https:/google.com\"}"
}
```

**Comment by Huachao** [comment]
@warrenchin I think it's related to your server-side logic, how does your server handle the unescaped slash?

**Comment by tangdw** [comment]
#620

**Comment by Huachao** [comment]
@warrenchin @tangdw can you work with old versions?

**Comment by tangdw** [comment]
> @warrenchin @tangdw can you work with old versions of my extension?

0.24.2 is ok

**Comment by Huachao** [comment]
@warrenchin @tangdw I have fixed the issue and will publish a new version soon.

**Comment by warrenchin** [comment]
Thank you guys, and thanks again for the great plugin.

**Comment by Huachao** [comment]
@warrenchin @tangdw you can try the latest version 0.24.3
