### ISSUE TITLE
No Send Request link

### ISSUE THREAD

**Issue by jalezi** [Huachao/vscode-restclient#677]
Hello,

Why I don't have Send Request  link above GET url ?

My file is with .http extension.

Best regards,
Jaka

**Comment by rafek1241** [comment]
@jalezi  
Can you provide us your http call preview?

**Comment by jalezi** [comment]
@rafek1241 
I hope this will help.

![Screenshot 2020-09-02 12 44 02](https://user-images.githubusercontent.com/44704999/91977148-7a9cf880-ed22-11ea-9f77-a9a3227c2f72.png)

**Comment by rafek1241** [comment]
@jalezi 
Can you disable other extensions that affect codelens or http extension file? In this way we can find out if the extension doesn't work in accompany of some other extension.

**Comment by jalezi** [comment]
@rafek1241 
Sorry.
Code Lens was disabled :)

**Comment by rafek1241** [comment]
@Huachao can you close the issue?

**Comment by dineshKumar777** [comment]
Can you mention this info in readme doc.
I was about to create an new issue and saw this existing one. After enabling codelens I am seeing send request link now.
Thanks.
