### ISSUE TITLE
Allow per request settings override Rest Client system settings

### ISSUE THREAD

**Issue by johnwebbcole** [Huachao/vscode-restclient#680]
I'd like to be able to set per-request settings and change the value of a Rest Client setting.

Reading [this](https://github.com/Huachao/vscode-restclient#per-request-settings) made it appear that it was possible, but reading the syntax regex's, it looks like only `@note` is currently supported.

In my case, I'd like to disable `followRedirect` for a single request.

```
###
# @name login
# @followredirect=false
GET http://localhost/login HTTP/1.1
```

I imagine other settings would be nice to override as well. :-)

**Comment by xmedeko** [comment]
I would welcome to change `@previewOption` in http file to change it for one reqeust only and no need to go to settings.

**Comment by itslooklike** [comment]
The ability to override all settings in general would be very cool. For some it is necessary to disable redirects, for others sometimes a detailed output is needed

+1 to redirect per request

**Comment by Huachao** [comment]
@johnwebbcole @kherock @druppelt @zigiprimo @AlexanderButs @timlynch2k @svi3c @xmedeko @itslooklike request level metadata/settings are supported now, and the `no-redirect` setting can be added when you don't want to follow redirects. And more request level settings will be added.

Example:
```http
// @no-redirect
GET https://exmaple.com
```

**Comment by JefSchraag** [comment]
The example setting for a local request is not working for me.

```
// @no-redirect
GET https://exmaple.com
```


I can only get a  `HTTP/1.1 301 Moved Permanently` result changing the global setting ` "rest-client.followredirect": false`

**Comment by Huachao** [comment]
@JefSchraag it's not released
