### ISSUE TITLE
No Auth header sent when re-running a request

### ISSUE THREAD

**Issue by the-docta** [Huachao/vscode-restclient#682]
- REST Client Version: 0.24.2
- VSCode Version: 1.49.0
- OS Version: MacOS Catalina 10.15.6

Steps to Reproduce:

1. run a request with auth header (in current example, a POST with "Authorization: Basic user:pw" )
2. Pressing Command-Option-L reruns last request, but gets 401 unauthorized

**Comment by Huachao** [comment]
@the-docta nice catch, I have fixed the issue and will publish this in the next release.

**Comment by Huachao** [comment]
@the-docta you can try the latest version 0.24.3 to verify
