### ISSUE TITLE
Headers are converted to lowercase

### ISSUE THREAD

**Issue by JtMotoX** [Huachao/vscode-restclient#688]
- REST Client Version: v0.24.2
- VSCode Version: v1.48.2
- OS Version: macOS Catalina 10.15.6 (19G2021)

First of all I want to give a huge thank you for making this extension.  I use it on a daily basis 👍

### Issue:

Some API endpoints expect the headers as case-sensitive.  When I try to make api calls to these endpoints using this rest client, the api endpoint does not recognize the headers because the rest client is converting them to lowercase.

### Steps to Reproduce (method 1):

1. Make an API call with a custom header (with at least 1 uppercase letter).
2. On the server side, the custom header will be lowercase.

### Steps to Reproduce (method 2):

1. Paste the following into a blank .http file:
```
GET https://example.com
X-Foo: myval
BAR: myval
```
2. Select "Rest Client: Copy Request As cURL" to copy it as a curl request to your clipboard.
3. Paste into notepad.
4. You will see that the headers in the Curl request are all lowercase.

Example Result:
```
curl --request GET \
  --url https://example.com/ \
  --header 'bar: myval' \
  --header 'user-agent: vscode-restclient' \
  --header 'x-foo: myval'
```

**Comment by Huachao** [comment]
@JtMotoX this is by design since the underlying Node.js http module will convert all header names to their lower case.

**Comment by tianmiaohu-fis** [comment]
The "Copy Request as cURL" function also converts all headers into lower case.  This is not desired behavior.
