### ISSUE TITLE
Reference saved HTTP calls from code

### ISSUE THREAD

**Issue by Req** [Huachao/vscode-restclient#689]
My idea is that I could reference a request from my .http file, such as

    ### foobar
    GET localhost:3000/api/foo

And reference it directly from code

    // ### foobar
    fooHandler = async () => { return await axios(something); };

And I would be able to trigger the request directly from code. I such a thing possible by extensions? It would be handy to tinker with my handlers and trigger their saved test requests

**Comment by Huachao** [comment]
@Req it's not supported and is out of the scope of my extension
