### ISSUE TITLE
Support of 307 and 308 HTTP Status Codes

### ISSUE THREAD

**Issue by JCloudYu** [Huachao/vscode-restclient#69]
Rest client doesn't automatically redirect 307 and 308 status

**Comment by Huachao** [comment]
@JCloudYu does your request a GET request or non-GET(like POST) request, or can you check your 307 response contains Location header?

**Comment by Huachao** [comment]
@JCloudYu is the issue still happens, or could please provide me the failed request details? Thanks in advance.

**Comment by Huachao** [comment]
@JCloudYu I'd to close the issue if you don't have any further update, please feel free to reopen it.

**Comment by snadn** [comment]
@Huachao 307 is ok but 308 not

**Comment by Huachao** [comment]
@snadn I can succeed with 308 response, can you confirm that your 308 response has a `Location` header?

**Comment by snadn** [comment]
@Huachao my mistake！vscode-restclient is ok。 my nginx is 1.12 😂
when 308

![image](https://user-images.githubusercontent.com/1269858/38126680-ae7056de-3424-11e8-9df1-99cbc029239b.png)

when 307
![image](https://user-images.githubusercontent.com/1269858/38126406-039d503c-3423-11e8-8066-be5717dc6635.png)
![image](https://user-images.githubusercontent.com/1269858/38126461-64976c2e-3423-11e8-8459-9413787deb80.png)

when update nginx to 1.13

![image](https://user-images.githubusercontent.com/1269858/38127235-d2a1bb9e-3427-11e8-805d-0147ab19e84e.png)

**Comment by Huachao** [comment]
@snadn glad to here this. Thanks for your feedback.
