### ISSUE TITLE
Support .env file on the root of the project

### ISSUE THREAD

**Issue by joaogsleite** [Huachao/vscode-restclient#690]
This extension do not support `.env` files that are not on the same folder as the `.http` file

Imagine this project structure:
```
.env
src/
  users/
    create/
      handler.ts
      doc.http
    list/
      handler.ts
      doc.http
```
On each subfolders `doc.http` file, it would be great to use variables that are defined on the project root `.env` file.

**Comment by Huachao** [comment]
@joaogsleite @JPedroBorges I have published a new version 0.24.4. and you can have a try.
