### ISSUE TITLE
Renderer very slow for big JSON

### ISSUE THREAD

**Issue by matthieusieben** [Huachao/vscode-restclient#696]
A very big json response breaks the response renderer by making it so slow it is un-usable.
Additionnaly, the rendering of the response using a webview does not respects vs-code's color style.

Would it be possible to use vs-code's native code renderer instead of a webview to render responses ? It works so well for requests...

**Comment by avkonst** [comment]
you can choose in settings to use native editor viewer instead of html renderer. It solves the issue

**Comment by avkonst** [comment]
can we have it reopened? it is still worth fixing it
