### ISSUE TITLE
GraphQL file import fails

### ISSUE THREAD

**Issue by jluterek** [Huachao/vscode-restclient#699]
- REST Client Version: 0.24.3
- VSCode Version: 1.50.1 (user setup)
- OS Version: Windows_NT x64 10.0.19041

Embedding GraphQL in http file works:

`
POST {{host}}/{{projectKey}}/graphql
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}
X-REQUEST-TYPE: GraphQL

query project {
  project {
...
`

Trying to use a gql file fails:

`
POST {{host}}/{{projectKey}}/graphql
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}
X-REQUEST-TYPE: GraphQL

<@ ./query.gql
`

Having the GraphQL in a standalone file allows the use of graphql plugins for auto-complete and formatting.

**Comment by Huachao** [comment]
@jluterek nice catch, I have fixed the issue and will publish it in the next release

**Comment by Huachao** [comment]
@jluterek I have published a new version 0.24.4. and you can try the fix

**Comment by jluterek** [comment]
Thank you for this quick fix, I tested it and everything worked as expected.  This plugin looks amazing and I look forward to leveraging it.  Keep up the great work!
