### ISSUE TITLE
Variable in URL - transformed to lowercase?

### ISSUE THREAD

**Issue by chrlic** [Huachao/vscode-restclient#700]
Hi,

in a request like this:
```http
### 
# get Application By Bane via REST API
@applicationName = "vSphereMonitor"

# @name getApplicationRest
GET https://{{hostname}}/controller/rest/applications/{{applicationName}}
```

the content of the variable applicationName is transformed to lowercase, so https://real-hostname/controller/rest/applications/vspheremonitor is sent - is there any way to prevent that?

Thanks,

Martin

**Comment by Huachao** [comment]
@chrlic in my test the URL sent out is not converting to its lower case, how did you find the issue?

**Comment by chrlic** [comment]
Oh, I get it - the problem was the quotes in the variable assignment and that the server returned an error message like this:
invalid application id &amp;quot&#59;**vspheremonitor**&amp;quot&#59; is specified

so the lowercase conversion was apparently done by the server.

Apologies, it's working fine when variable assigned without the quotes, e.g.
@applicationName = vSphereMonitor

BTW I love the extension, much easier to work within the IDE than with Postman or alike. Great idea and a great job!
