### ISSUE TITLE
Add Support for non-ASCII characters

### ISSUE THREAD

**Issue by aderchox** [Huachao/vscode-restclient#704]
I think the title of this feature request says most of what I'm trying suggest here, but only as an example, let's say I'm making a request which will have non-English letters in its response, currently, the response is shown like this:
```
  "success": false,
  "message": "\u0627\u0637\u0644\u0627\u0639\u0627\u062a \u0648\u0631\u0648\u062f \u0635\u062d\u06cc\u062d \u0646\u0645\u06cc \u0628\u0627\u0634\u062f",
  "data": []
}
```
Thank you.

**Comment by Huachao** [comment]
@aderchox set VS Code setting `rest-client.decodeEscapedUnicodeCharacters` to `true` should work
