### ISSUE TITLE
Azure AD - callback

### ISSUE THREAD

**Issue by mskuratowski** [Huachao/vscode-restclient#707]
Hi, 

Currently, I use Postman to test my API where I can put my 

- Grant Type (implicit)
- Callback URL (https://www.postman.com/oauth2/callback)
- Auth URL (https://login.microsoftonline.com/TENANT_ID/oauth2/v2.0/authorize)
- ClientId (CLIENT_ID)
- Scope (api://CLIENT_ID/Y)

When I get the token I am redirected to the login page and then I come back to Postman where I can reuse my token.

Is it possible to do it using VSCode RestClient?

**Comment by Huachao** [comment]
@darrelmiller is it possible in the extension? Thanks in advance.

**Comment by darrelmiller** [comment]
@mskuratowski You can't do implicit grant, but you can do client credentials and device code flow with the aadV2Token.  There is a bug with the scopes for custom APIs so the device code flow path needs a fix which I hope to get to very soon.

**Comment by mskuratowski** [comment]
@darrelmiller Thanks for the explanation. I think we can close the issue. thanks.

**Comment by Rainier-MSFT** [comment]
Hey @darrelmiller, would you open to sharin details on custom APIs bug? We need this tso happy to contribute and propose a fix.
