### ISSUE TITLE
XML not formatted with response

### ISSUE THREAD

**Issue by dakaraphi** [Huachao/vscode-restclient#71]
XML is not formatted when response is 
`Content-Type: application/atom+xml`

**Comment by Huachao** [comment]
@dakaraphi nice catch, and I will publish this in next release

**Comment by Huachao** [comment]
@dakaraphi you can try the latest version 0.12.3 to verify

**Comment by dakaraphi** [comment]
@Huachao verified, it is working now.  Thanks!
