### ISSUE TITLE
Http headers always gets sent as lowercase

### ISSUE THREAD

**Issue by tangmark** [Huachao/vscode-restclient#714]
Hi! 
Great extention to VSCODE!
I found that the http headers sent gets put to lowercase even though the preview of Request/Response displays how they where initially written.

- REST Client Version: v0.24.4
- VSCode Version: 1.51.0
- OS Version: Windows 10

Steps to Reproduce:

1. set header "**Content-Type: application/json**" to a request, doesnt matter which method.
2. In the receiving end you will see that "**content-type: application/json**" is received. 
   (Even though the preview tab of req/resp shows "Content-Type" etc.)

**Comment by Huachao** [comment]
@tangmark this is the underlying Node.js behavior.
