### ISSUE TITLE
outline can't correct show Chinese.

### ISSUE THREAD

**Issue by piumnl** [Huachao/vscode-restclient#719]
- REST Client Version: v0.24.4
- VSCode Version: 1.51.1 (user setup)
- OS Version: Windows_NT x64 10.0.18363

Look this image: ![图片](https://user-images.githubusercontent.com/24371189/100303413-68f08780-2fd7-11eb-8d0e-0059005b2f56.png)

**Comment by Huachao** [comment]
@piumnl thanks for your question, since the request variable requires its name of regex `\w+`, it's by design
