### ISSUE TITLE
Binary Files does not work with Rest client

### ISSUE THREAD

**Issue by PPInfy** [Huachao/vscode-restclient#729]
- REST Client Version: v0.24.4
- VSCode Version: 1.5.1
- OS Version: WIN10

Steps to Reproduce:

1. Try testing with binary data file
2. eg:- 
```http
POST file/upload
Host: localhost:80
Authorization: {{token}}
Content-Type: multipart/form-data; boundary=MyBoundary

MyBoundary
Content-Disposition: form-data; name="file"; filename="1.dat"
Content-Type: application/octet-stream
< ./1.dat
--MyBoundary--
```

**Comment by Huachao** [comment]
> ```httpspec
> POST file/upload
> Host: localhost:80
> Authorization: {{token}}
> Content-Type: multipart/form-data; boundary=MyBoundary
> 
> MyBoundary
> Content-Disposition: form-data; name="file"; filename="1.dat"
> Content-Type: application/octet-stream
> < ./1.dat
> --MyBoundary--
> ```

The first boundary should be write as `--MyBoundary` as following:
```http
POST file/upload
Host: localhost:80
Authorization: {{token}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="file"; filename="1.dat"
Content-Type: application/octet-stream
< ./1.dat
--MyBoundary--
```
