### ISSUE TITLE
'Run Request' issues when using folding

### ISSUE THREAD

**Issue by dakaraphi** [Huachao/vscode-restclient#73]
It seems that 'Run Request' does not always appear when using folding.  If I scroll down and back up, or switch to another document and back, then it usually will appear.  In the screenshot below, you will see it appeared for the first request, but not the second.

Note: I don't know if this would be possible, but it would be pretty nice if the 'Run Request' could appear inline to the right or left of the folded text when using folding.

![image](https://cloud.githubusercontent.com/assets/10656375/23226639/448ec0ea-f904-11e6-8e47-d687d05752b3.png)

**Comment by Huachao** [comment]
@dakaraphi I will investigate the cause of disappearance

**Comment by Huachao** [comment]
@dakaraphi I think it should be related to VSCode, I have created a issue[Microsoft/vscode#21258] there to tract this.

**Comment by Huachao** [comment]
@dakaraphi latest vscode 1.11.0 already solved this issue, you can try it 😄

**Comment by dakaraphi** [comment]
@Huachao I was already checking it out :-) 
Confirmed this issue is fixed. thx.
