### ISSUE TITLE
how can i use custom variables

### ISSUE THREAD

**Issue by Jeongdaeho** [Huachao/vscode-restclient#734]
I tried this

@VariableName = VariableValue

POST http://site.com/{{VariableName}}

but i can't get the VariableValue 
just got the crush value like this '&#039;76ce8bfa-58ef-4b44-8f09-1bdcd6626327&#039;'

and then 
I tried this

POST http://site.com/VariableName

It's working.

what's wrong with this code?

**Comment by Huachao** [comment]
@Jeongdaeho the variable is case-sensitive, so you need to use `{{variablename}}` as your defined to reference the variable
