### ISSUE TITLE
Response Window not showing after closing it VS Code (Ubuntu Budgie - 20.04)

### ISSUE THREAD

**Issue by Metrophobe** [Huachao/vscode-restclient#739]
- REST Client Version: V0.24.4
- VSCode Version:1.52.1
- OS Version: Ubuntu Budgie 20.04

Steps to Reproduce:

1. Closed the Preview and was unable to bring it back (on Ubuntu) 
2. Tried replicating this on Windows but it works fine (response window)

Things I have tried so far to fix the issue: 
1. Since VS Code was installed using  Snap, I removed it using remove command 
2. Removed the settings folder located in the .config/shared for vscode 
3. Reinstalled using apt .... (through official repository)
4. To my dismay I noticed that upon reinstall vscode STILL showed that rest-client was installed meaning that not all settings were removed!  If anyone can point out any additional settings that had to be removed, I will re-attempt to see if the problem persists after a completely clean install (with 100% settings removed). So far the problem is still there.

**Comment by Huachao** [comment]
@Metrophobe did it work in previous versions?

**Comment by Metrophobe** [comment]
no it did not as per point 4 of my explanation above. To replicate the problem, what i did was I closed the response window and was unable to show it up again. The only way that fixed it was to do a complete re-install of Ubuntu.

**Comment by Huachao** [comment]
@Metrophobe I mean did you try to reinstall the previous versions of the extension with the command `Install Specific Version of Extension..`

**Comment by Metrophobe** [comment]
@Huachao Yes i did try the previous 2 versions and still no go.

**Comment by ghoshsanjeev** [comment]
Any update on this issue? Is there are keyboard shortcut to open the response window?

**Comment by Metrophobe** [comment]
currently working on c++ so moved away from VSCode .... sorry
