### ISSUE TITLE
HTTP request with custom method

### ISSUE THREAD

**Issue by azazar** [Huachao/vscode-restclient#755]
As far as I know, HTTP request methods aren't limited to GET/POST/PATCH/DELETE/PUT. It allows use of any arbitrary string. So the question is how to send HTTP request with custom HTTP method?

**Comment by Huachao** [comment]
* HTTP Request: Only GET/POST/PUT/DELETE/PATCH/HEAD/OPTIONS/CONNECT/TRACE
*Curl Request: Any custom methods

So you can write the request in the curl syntax, any custom method can work
