### ISSUE TITLE
rest-client.fontSize Default Value is Invalid

### ISSUE THREAD

**Issue by SethFalco** [Huachao/vscode-restclient#760]
- REST Client Version: 0.24.4
- VSCode Version:  1.53.0-insider
  Version: 1.53.0-insider
  Commit: 861a88ebadb4335df92251faf6420b598440e082
  Date: 2021-01-29T21:49:47.914Z
  Electron: 11.2.1
  Chrome: 87.0.4280.141
  Node.js: 12.18.3
  V8: 8.7.220.31-electron.0
  OS: Linux x64 5.4.0-64-generic snap
- OS Version: Ubuntu 18.04.5 LTS x86_64

Steps to Reproduce:

1. If not configured, visit the Visual Studio Code Settings menu via the GUI.
2. Find "Rest-client: Font Size", with the ID: `rest-client.fontSize`
3. Observe the warning shown to users despite never having configured it.

![image](https://user-images.githubusercontent.com/22801583/106398467-387ffc00-6413-11eb-9576-bdb467c57632.png)

The default configuration should not trigger any warning/error to be displayed to the user, this should instead allow for the field to be empty, or default to a value like -1 to mean the default behavior.

**Comment by ZooDoo4U** [comment]
Along with the issues for the font size, it appears upon installing the plug-in, i'm seeing an error for the font name as well.

**Comment by Huachao** [comment]
@SethFalco @ZooDoo4U I have fixed the issue and will publish it in the next release.

**Comment by Huachao** [comment]
@ZooDoo4U @SethFalco this has been published in the latest version 0.24.5 and you can have a try
