### ISSUE TITLE
PROPFIND (webdav/caldav)

### ISSUE THREAD

**Issue by mitsol** [Huachao/vscode-restclient#766]
Would there be the possibility to also extend the HTTP operations with the ones from webdav/caldav (PROPFIND, PROPPATCH, REPORT, MKCOL, MKCALENDAR, ACL). I would find it a nice feature for testing caldav applications.

**Comment by georghub** [comment]
Same for me, additional http methods would be very helpful for testing WebDAV calls:
PROPFIND, PROPPATCH, MKCOL, LOCK, UNLOCK, SEARCH
