### ISSUE TITLE
大兄弟支不支持上传和预览

### ISSUE THREAD

**Issue by kids-return** [Huachao/vscode-restclient#77]
类似POSTMAN 里面的 
有时接口会报错，返回直接的HTML代码不方便查看报错信息

上传是不是需要自己构建body

**Comment by kids-return** [comment]
### 上传测试
```
POST {{base_url}}/user/upload
{{headers}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="1.png"
Content-Type: image/png


------WebKitFormBoundary7MA4YWxkTrZu0gW--
< ./1.png
```
我测试 这样上传不行啊， 有没有查看请求头的方法呢

**Comment by Huachao** [comment]
@kids-return It's not supported now, I will implement this ASAP, thanks for your question.

**Comment by Huachao** [comment]
@kids-return I have already supported to upload files in multipart/form-data request body in following raw request format:

> POST {{base_url}}/user/upload
> {{headers}}
> Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
> 
> ------WebKitFormBoundary7MA4YWxkTrZu0gW
> Content-Disposition: form-data; name="image"; filename="1.png"
> Content-Type: image/png
> 
> 
> ------WebKitFormBoundary7MA4YWxkTrZu0gW--
> < ./1.png

However, the `Upload and Preview` is not supported and out of my recent scope, and I will support following format

**Comment by Huachao** [comment]
@kids-return you can try the latest version 0.13.0 to verify 😄

**Comment by kids-return** [comment]
@Huachao thanks 大兄弟 有我空试下

**Comment by kids-return** [comment]
```
### 本地上传测试
POST http://127.0.0.1/upload.php?id=1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text[]"

test
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text[]"

test2
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="1.png"
Content-Type: image/png

< ./1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
```

upload.php

```
<?php
print_r($_GET);
print_r($_POST);
print_r($_FILES);
```

php file
Local test failed    http://127.0.0.1/upload.php?id=1
The server test was successful  http://serverIP/upload.php?id=1

**Comment by kids-return** [comment]
Can support the preview on the perfect  👍  :)

**Comment by Huachao** [comment]
@kids-return I will consider the preview feature request and do you mean you still fail in local, while succeed in server?

**Comment by kids-return** [comment]
@Huachao  yes

**Comment by Huachao** [comment]
@kids-return what do you mean fail, can you provide more details?
