### ISSUE TITLE
POST cannot handle JSON body with unquoted numbers

### ISSUE THREAD

**Issue by JulianNF** [Huachao/vscode-restclient#774]
- REST Client Version: v0.24.4
- VSCode Version: 1.53.0
- OS Version: w10 1909

Steps to Reproduce:

1. Express/Node post code:
```
app.post('/tempdata', (req, res) => {
  console.log('new data to add: ', req.body);
  res.sendStatus(200);
});
```

2. HTTP Client POST:

**Comment by tcodes0** [comment]
having a similar issue, @JulianNF did you solve it?
