### ISSUE TITLE
How can I set cookie in the header?

### ISSUE THREAD

**Issue by sdancer75** [Huachao/vscode-restclient#782]
Is there any way to set the cookies in the header before I make any api calls to the server?

**Comment by izatwin** [comment]
![image](https://github.com/user-attachments/assets/27411f89-fcbc-4d6a-9b50-26c563612541)

I got this picture from here:
https://marketplace.visualstudio.com/items?itemName=humao.rest-client

Is this what you are looking for?

**Comment by sdancer75** [comment]
Excellent thank you !
