### ISSUE TITLE
Idempotency-Key header being converted to lowercase

### ISSUE THREAD

**Issue by jamie-burks** [Huachao/vscode-restclient#796]
- REST Client Version: 0.24.4
- VSCode Version: 1.54.3
- OS Version: macOS 10.15.7

Steps to Reproduce:

1. Add "Idempotency-Key: SomeValue" to a request
2. Submit the request
3. Server actually receives "idempotency-key: SomeValue" (only header name is lowercased)

Could not find any settings that control this.

**Comment by shoffmeister** [comment]
FWIW, header names (field names) are not case-sensitive, following https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html

Obviously that does not help you if your application / your route to the application treats the field name exactly as-is (been there, suffered from it)

**Comment by jamie-burks** [comment]
Yes, that is correct. And after further research, we _think_ this has to do with API Gateway and HTTP/2, which apparently does state headers should be converted to lowercase. We're working around it. Sorry for the false alarm.

**Comment by Huachao** [comment]
@jamie-burks This is the expected behavior of the underlying Node.js built-in framework, it will convert all the header names to its lowercase
