### ISSUE TITLE
Use cookies

### ISSUE THREAD

**Issue by ganlhi** [Huachao/vscode-restclient#8]
As far as I can see, cookies received by previous requests are not automatically sent with subsequent requests to the same host. Woul it be possible?

**Comment by Huachao** [comment]
@ganlhi, thanks for your suggestion. If implement this, I may need to implement a cookie storage, I think this is low priority now. I will consider this later.

**Comment by Huachao** [comment]
@ganlhi, I am considering the automatically sending/storing cookie feature, and I have a question that wants to discuss with you. As we all know, cookies can be **persistent cookie**(_for browser, normally stored on disk and available until expire time_), or **session cookie**(_temporary and erase when browser close, no expire time in `Set-Cookie` header_).
So I am not sure how we should handle the session cookie in my extension?

**Comment by ganlhi** [comment]
Well... I'm not an expert on implementing these things, but maybe you can consider a vscode window to be a browser instance, and so delete session cookies when window is closed?

**Comment by Huachao** [comment]
@ganlhi , or if I can handle these 2 kind of cookies in the way like browser, for persistent cookie, I will save them to local file system which can be reused next time; for session cookie, I will only save them in memory, and if VS Code is closed, our extension are inactive, and all the session cookie in memory are automatically removed. Next time you open vs code and activate our extension, you can only use the persistent cookie stored in file.

**Comment by ganlhi** [comment]
That seems a good idea!

**Comment by Huachao** [comment]
@ganlhi , this feature has been implemented in latest version 0.7.0, please help to verify it :rocket:

**Comment by ganlhi** [comment]
Hey there! Good news!
Just got back from vacation. Will try this ASAP.
