### ISSUE TITLE
😿🤸‍♂️🕳 IS THIS PROJECT ABANDONED? 👻⁉🆘

### ISSUE THREAD

**Issue by mnsc** [Huachao/vscode-restclient#805]
Ping @Huachao 

This is a very good tool that I use daily. I have some small improvements though and looking through all the unanswered questions and open PR:s I get the feeling that there's not much activity here. Hope you are well and not run over by a bus. But I think I speak for many of the users when I say that some official statement from you would be appreciated. OSS burnout is real and not a failure!

**Comment by Huachao** [comment]
@mnsc the project is not abandoned, since I am quite busy with my daily work, and the response will be much slower than before. However, a new release will be published in the coming days.
