### ISSUE TITLE
`showResponseInDifferentTab` creates a new tab for each response, but updates all response tabs with the latest response.

### ISSUE THREAD

**Issue by robgough** [Huachao/vscode-restclient#81]
- VSCode Version: 1.10.2
- OS Version: MacOS Sierra 10.12.3 (16D32)
- REST Client Version: 0.12.3

Steps to Reproduce:

Assumption: `"rest-client.showResponseInDifferentTab": true` is set in your user settings file.

1. Make a request in one tab, response appears in split on right hand side.
2. In left split make a second, different, request.
3. A second response opens in new tab on right pane, but _both_ response tabs have the same contents (though their tab titles remain correct) of the latest request.

**Comment by Huachao** [comment]
@robgough I found this seems to be a vscode bug, and this steps can work before vscode 1.8, so I opened an issue in Microsoft/vscode#22775 to see some updates. Sorry for the inconvenience.

**Comment by robgough** [comment]
Thanks for the quick response, your extension has saved me a lot of time already so thanks for that too!

**Comment by Huachao** [comment]
@robgough I have fixed the bug, will publish this in next release

**Comment by Huachao** [comment]
@robgough you can try the latest version 0.14.0 to verify. 😄

**Comment by robgough** [comment]
@Huachao Just tried, and it's all working fine now. 👍 Thank you!
