### ISSUE TITLE
Cooke was not sent when set-cookie has expires field.

### ISSUE THREAD

**Issue by taka2021** [Huachao/vscode-restclient#811]
- REST Client Version: 0.24.5
- VSCode Version: 1.55.0
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Get a cookie with a set-cookei header as following:

Set-Cookie: sid=s%3AU_mFoW99zpABg0QgElbRzgA2q98XC3t5.kkId2JGnM1bBRt7DYGHC%2BK1LEBhok1dIKIP99LvaqnU; Path=/; Expires=Wed, 07 Apr 2021 02:25:18 GMT; HttpOnly; SameSite=Lax

2. Send a get request as following(there is no cookie header)

GET http://localhost:5000/v1/auth/cookie/login HTTP/1.1

**Comment by Huachao** [comment]
@taka2021 could you please check the content of `~/.rest-client/cookie.json`, this file stores all the stored cookies, could you find out the ones you need?

**Comment by taka2021** [comment]
@Huachao 

Thank you for your reply.

It is seams that the expires date was too old to sent the cookie.
