### ISSUE TITLE
Add support to another JSON Content-Type (like application/x-amz-json-1.1)

### ISSUE THREAD

**Issue by mayconfsousa** [Huachao/vscode-restclient#812]
Maybe, the function `isJSONString` is enough in the following clause

https://github.com/Huachao/vscode-restclient/blob/6f0b1575656ce79110f69d506597f08aa24af78b/src/utils/requestVariableCacheValueProcessor.ts#L61

**Comment by AnWeber** [comment]
see #771

**Comment by fxalgrain** [comment]
#771 has been merged :)

**Comment by Huachao** [comment]
@AnWeber @fxalgrain @mayconfsousa I have published the latest version 0.24.6 and you can have a try.

**Comment by fxalgrain** [comment]
Thanks for the release. Works well on my side ;)
