### ISSUE TITLE
unable to use REST Client in wsl windows subsystem for linux (Ubuntu-20.04)

### ISSUE THREAD

**Issue by bartsimp** [Huachao/vscode-restclient#815]
- REST Client Version: v0.24.5
- VSCode Version: 1.55.1
- OS Version: Microsoft Windows [Version 10.0.19041.867]

Steps to Reproduce:

1. create a file test.http in a local project (on my win10 machines)
```
###
https://example.com/comments/1
```
the "Send Request" snippet in shown and works properly

2. open a new window Remote-WSL: Ubuntu-20.04
3. create a file test.http with the same content
4. the "Send Request" snippet is NOT shown

**Comment by pa-ulander** [comment]
Hi, just to confirm, I have encountered the same issue. Cheers!

**Comment by bartsimp** [comment]
thanks for the tips, I confirm your workaround
