### ISSUE TITLE
HTTPS with self-signed certificate

### ISSUE THREAD

**Issue by pberenyi** [Huachao/vscode-restclient#83]
- VSCode Version: 1.9.1
- OS Version: Win 7
- REST Client Version: 0.12.3

Steps to Reproduce:
1. Try to access a site with a self-signed certificate via HTTPS
2. Even if the certificate chain is imported to Windows I'm getting an error "unable to verify the first certificate".

It would be nice to have an option to ignore certificate warnings.

**Comment by Huachao** [comment]
@pberenyi our extension doesn't hornor the certificate on OS, after next release, you can specify the cert, key, pfx or passphrase in setting for specofic host. By now, our extension doesn't support certificate authentication. Amd I will notify you when newer version is punlished

**Comment by pberenyi** [comment]
Thanks, I don't need certificate authentication, just the ability to use development certificates on the servers for https connections. I'm happy to test if you add any improvements.

**Comment by Huachao** [comment]
@pberenyi do you mean that you want to send request with your specified certificate?

**Comment by pberenyi** [comment]
No. I'm using in my development environment HTTPS with certificates issued by my own CA. The certificate chain is trusted by my PC, but still I'm getting a certificate error and no response when I try to send a request via HTTPS from VS Code. So either I would need an option where I could specify the certificates to trust, or an option to disable certificate validation (like the -k when using curl).

**Comment by Huachao** [comment]
@pberenyi so if I can let you specify the cert and key like curl, can you succeed the request?

**Comment by pberenyi** [comment]
I would think so. If you can provide some option for this, similar to the ones described in https://curl.haxx.se/docs/sslcerts.html, it should work.

**Comment by Huachao** [comment]
@pberenyi I have implemented the feature to send request with cert, key or pfx recently(not published), I wish that in next release when I published it, you can use this feature to solve your problem, if still not, feel free to tell me. And I will notify you when next version is available

**Comment by Huachao** [comment]
@pberenyi you can try the latest version 0.14.0 to check if it can works for you, you need to set the cert, key paths in the settings. You can follow the `READEME` for more details. If you still find any questions, pls feel free to reopen the issue.

**Comment by jlg-io** [comment]
Hello @Huachao, as @pberenyi said already, do you think it's psosible to implement a "ignore certificate" feature like -k/--insecure in Curl or verify=False in Python ?
It would make it easier to use with self-signed certificate system.
Great work on this plugin by the way!

**Comment by Huachao** [comment]
@jlg-io  Do you mean that rest client ignore self-signed certificate from server side, it should be supported two years ago. Hmm, could you please provide more details, like some screenshots

**Comment by martin-minkov** [comment]
I am unable to find how to ignore certificate verification when I do a HTTPS request. All I see is how to configure certificates to be considered as valid and I'm guessing that I can configure the self-signed ones . What if I want to disable certificate verification - may I kindly ask you to point me at the relevant documentation/instructions to do so.
