### ISSUE TITLE
How to display Unicode charactor correctly?  

### ISSUE THREAD

**Issue by johnnylq** [Huachao/vscode-restclient#834]
Postman can show the return string with correct char-set,  but RRES Client couldn't, just display the unicode instead of the corresponding charactor,   something like: 
"msg": "\u62b1\u6b49\uff0c\

Any way to enable RESET client support unicode charactor?

**Comment by kthy** [comment]
This is most likely an issue with the endpoint encoding the unicode characters. I whipped up a quick server in Flask and queried it with restclient:

#### No server-side encoding
```python
@api.route('/')
def encoding_test():
    return json.dumps(dict(msg='抱歉，'), ensure_ascii=False)
```
`GET http://localhost:5000/ HTTP/1.1` returns
```
HTTP/1.0 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 11
Access-Control-Allow-Origin: *
Set-Cookie: session=867a1e92-5476-4c56-89f4-411ce6c08173; Expires=Thu, 03-Jun-2021 22:59:50 GMT; HttpOnly; Path=/
Server: Werkzeug/1.0.1 Python/3.7.10
Date: Mon, 03 May 2021 22:59:50 GMT

{
  "msg": "抱歉，"
}
```

#### Forced server-side encoding
```python
@api.route('/')
def encoding_test():
    return json.dumps(dict(msg='抱歉，'), ensure_ascii=True)
```
`GET http://localhost:5000/ HTTP/1.1` returns
```
HTTP/1.0 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 20
Access-Control-Allow-Origin: *
Set-Cookie: session=867a1e92-5476-4c56-89f4-411ce6c08173; Expires=Thu, 03-Jun-2021 23:01:27 GMT; HttpOnly; Path=/
Server: Werkzeug/1.0.1 Python/3.7.10
Date: Mon, 03 May 2021 23:01:27 GMT

{
  "msg": "\u62b1\u6b49\uff0c"
}
```

**Comment by supersansan** [comment]
Rest-client have a 'Decode Escaped Unicode characters' in its setting.
Just checked it.
