### ISSUE TITLE
why can't I use Ctrl + Alt + R in other files ?

### ISSUE THREAD

**Issue by me-nkr** [Huachao/vscode-restclient#835]
why can't I use Ctrl + Alt + R in other files ?

It would be great if I can make a request from a js file with keyboard shortcut than opening command pallete

**Comment by cplussharp** [comment]
The actions/commands you can perform in a file in VSCode depend on the "language" this file was opened with. The Ctrl+Alt+R command is only bound to the "http" language this extension introduced.
If you want to execute the command in a file that was not opened with this language, you need to switch the language of the current file to "http" first. (with [Ctrl+K M](https://code.visualstudio.com/docs/languages/overview))
