### ISSUE TITLE
Fails on versions > 0.24.3

### ISSUE THREAD

**Issue by quammy** [Huachao/vscode-restclient#837]
- REST Client Version: 0.24.4 or 0.24.5
- VSCode Version: 1.56.0 (and also previous versions)
- OS Version: Win10 Home x64

issue:
After upgrading to 0.24.4 or 0.24.5, the extension stops working. 
When clicking a 'Send Request' link, nothing happens. Not even an error notification.
When hovering a parameter (like {{server}}), the tooltip just shows as "Loading..." instead of the value. 

When downgrading to 0.24.3, all start to work again.

Looking around seems like no one else encounter this phenomenon, so please let me know what info should I supply more in order to solve the problem. This extension **rocks** and is one I used a lot!! 

Steps to Reproduce:

1. just have the extension enabled
2.

Thanks!

**Comment by chriseaton** [comment]
can confirm is broke for me as well.

**Comment by Huachao** [comment]
@quammy @chriseaton did you still have this problem?

**Comment by quammy** [comment]
@Huachao yes, still have this issue. Thanks for approaching!

**Comment by quammy** [comment]
With latest release (v0.24.6) the bug is solved and all work like a charm ;)
Thanks!
