### ISSUE TITLE
req.body is empty 

### ISSUE THREAD

**Issue by CodingJoshi** [Huachao/vscode-restclient#841]
POST http://localhost:5000/api/register 

Content-Type: application/json

{
    "name":"Name",
    "email": "email@gmail.com",
    "password": "Scret89@#",
    "repeat_password": "Scret89@#"
}

![image](https://user-images.githubusercontent.com/54803922/117527522-5ea4d180-afea-11eb-95d6-7ced833f361d.png)

what is the mistake???

**Comment by AnWeber** [comment]
"Content-type" header will be sent in the request body because of the empty line between url and header
