### ISSUE TITLE
Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by Givo29** [Huachao/vscode-restclient#871]
**Bug Description:**
Getting `Cannot set headers after they are sent to the client` error on any http request.
![image](https://user-images.githubusercontent.com/21019692/123567193-eba72280-d804-11eb-93a3-cccc78aa9bb1.png)

Works on other clients such as postman:
![image](https://user-images.githubusercontent.com/21019692/123567127-cd412700-d804-11eb-8398-fed035c39a41.png)

**Versions Affected:**
- 0.24.4
- 0.24.5

**VSCode Version:**
1.57.1

**To Reproduce:**
1. Install rest client
2. Create request:
```http
GET http://google.com
```
3. Attempt to send request

This only occurs with http requests, https requests work fine.
This is still a problem for me as the server I'm trying to send the request for is http only.

**Comment by Huachao** [comment]
@Givo29 I can't repro

**Comment by Givo29** [comment]
@Huachao Just looked further into it, turns out it had to do with our proxy, I've fixed it now. 

I assumed it wasn't the proxy originally as it worked through `https` but not `http`.  
Thanks for checking it out.
