### ISSUE TITLE
HTTP/2 support?

### ISSUE THREAD

**Issue by Marvin-Brouwer** [Huachao/vscode-restclient#873]
Hi,

I was troubleshooting an issue where we think we might be sending HTTP/2 requests to a server that just responds HTTP/1.1 so I tried it with rest-client but the requests always seem to send HTTP/1.1

Are there any plans to supporting HTTP/2?
I realize it's not that useful for a tool that does one-by-one requests perhaps.

**Comment by Huachao** [comment]
Duplicate of #271
