### ISSUE TITLE
How can I prevent REST Client adds any default header to requests?

### ISSUE THREAD

**Issue by AllanXu49** [Huachao/vscode-restclient#875]
I am trying to may sure REST Client does not do any modification to my REST calls.

While I have nothing in the setting `rest-client.defaultHeaders`, I've learned that still REST client adds the following header to my calls. 

`accept-encoding: gzip, deflate`
`user-agent: vscode-restclient`

Is there any way to make sure that REST client does not modify the REST calls behind the scene?

**Comment by Huachao** [comment]
@AllanXu49 currently it's not supported
