### ISSUE TITLE
.rest files do not set language when opened in new vscode 1.11

### ISSUE THREAD

**Issue by dakaraphi** [Huachao/vscode-restclient#88]
- VSCode Version: 1.11
- OS Version:  OSX
- REST Client Version:

Steps to Reproduce:

1. Open a .rest file
2. It is not recognized as a .rest file.  You must manually set language to http

**Comment by Huachao** [comment]
@dakaraphi do you installed some extensions related to reStructedText, it also associates `.rest` file extension. And I think it's better to name file extension with `.http` which won't conflicts with other languages, and if you still want to use `.rest` extension, you can add setting in vscode like 
```json
"files.associations": {"*.rest": "http"}
```
Do you think we'd better remove support for `.rest`?

**Comment by dakaraphi** [comment]
Ok, I have a lot of extensions, so one of them must have updated at the same time I upgraded vscode.
Seems reasonable to me if support is removed for `.rest`

**Comment by Huachao** [comment]
@dakaraphi decide to close it since many users already use heavily in `.rest` extension.
