### ISSUE TITLE
Reference count not shown for variables after first with comment

### ISSUE THREAD

**Issue by Danysan1** [Huachao/vscode-restclient#883]
- REST Client Version: v0.24.5
- VSCode Version: 1.58.2
- OS Version: Windows 10 Pro 21H1

## Steps to Reproduce:

1. Create a `.http` file
2. Insert multiple variable declarations separated by a comment line
3. Reference count for variables after the first are not shown, while I would expect to see them just like without the comment line

## Example

This works correctly:
```http
# Foo
@foo = abc
@bar = xyz
@quz=ijk

GET https://abc.xyz?foo={{foo}}&bar={{bar}}
```
![image](https://user-images.githubusercontent.com/8406735/126777765-3df4da4a-188d-4e7c-98a5-7315a69e3ea0.png)

But after adding a comment before the second variable it does not work:
```http
# Foo
@foo = abc
# Bar
@bar = xyz
@quz=ijk

GET https://abc.xyz?foo={{foo}}&bar={{bar}}
```
![image](https://user-images.githubusercontent.com/8406735/126777834-94011b38-1272-488a-a63b-9ed38b191e20.png)

**Comment by Huachao** [comment]
@Danysan1 this has been published in the latest version 0.24.6 and you can have a try.
