### ISSUE TITLE
Paste curl command into the correct *.http syntax?

### ISSUE THREAD

**Issue by mattalexx** [Huachao/vscode-restclient#899]
It would be really cool to have a curl command in my clipboard and be able to paste the command into an *.http file and have it converted to the correct syntax. The feature would go well with the existing "Copy as curl command" feature.

**Comment by Huachao** [comment]
@mattalexx @gonzaloverussa @rickh57 do you mean covert a curl request into its HTTP format, if so current we support `Generate Code Snippet`, which you can choose the `HTTP` language.
