### ISSUE TITLE
Error: Unable to open 'Response(516ms)': Could not resolve any model with provided uri..

### ISSUE THREAD

**Issue by sfertman** [Huachao/vscode-restclient#90]
- VSCode Version:
- OS Version: 1.10.2
- REST Client Version: 0.14.0

Steps to Reproduce:
1. Send a request and wait for the response window to pop up
2. Once up, switch focus to it (click on it)
3. Switch to a different editor window in vscode
4. Try to switch back to Response window
5. Below error message will pop up at the top of the window; response window will not open
![image](https://cloud.githubusercontent.com/assets/17301942/24762778/58b3c68a-1abd-11e7-8b25-66838d8af62d.png)
6. Any subsequent requests will result in the same behaviour until vscode is restarted

**Comment by Huachao** [comment]
@sfertman I have fixed the issue, will publish the new version ASAP

**Comment by sfertman** [comment]
@Huachao, thank you very much. You're building a great and useful tool!

**Comment by Huachao** [comment]
@sfertman you can try the latest version 0.14.1, but you need to upgrade to latest vscode
