### ISSUE TITLE
Can you give an example of sending a POST with a JSON structure and a text file

### ISSUE THREAD

**Issue by mchassy** [Huachao/vscode-restclient#900]
I have looked through the documentation and the issues. In the documentation, I don't see a simple example of doing a  POST with a JSON structure and  a text file. The issues have to do with more complex issues.

Thanks

Mark

**Comment by Huachao** [comment]
@mchassy do you mean you want to send a JSON file? If so it should look like as following:
```http
POST https://example.com/comments HTTP/1.1
Content-Type: application/json
Authorization: token xxx

< C:\Users\Default\Desktop\demo.json
```
