### ISSUE TITLE
Does not Seem to work with proxies 

### ISSUE THREAD

**Issue by TechWatching** [Huachao/vscode-restclient#91]
- VSCode Version: 1.12
- OS Version: Windows 8 
- REST Client Version: 0.14.1

Steps to Reproduce:

1. Send a request from a vs code window on a network with proxy

**Comment by Huachao** [comment]
@TechWatching have you set the setting `http.proxy` in vscode?

**Comment by TechWatching** [comment]
I restarted Vs code and it seems to work now. I don't know why. My http.proxy setting was already set in vs code settings file. I am closing the issue.

**Comment by TechWatching** [comment]
In fact the issue is happening from time to time with the following error : "tunneling socket could not be established, statusCode=407", might be an issue not linked with the extension, what do you thing ?

**Comment by Huachao** [comment]
@TechWatching  any updates?

**Comment by TechWatching** [comment]
Sorry I forgot this thread. I have no issue doing other proxy related tasks, or using other extensions which use the proxy setting. I don't need to authenticate. I didn't check to see if it always works when I restart and I am not at the office these days. But the behavior is strange, it works perfectly and 5s later doesn't. I have no clue about that. I guess it might be a problem with our proxy. I close the issue, I will re-open it if I have more clues to bring.
