### ISSUE TITLE
right-click copy does not work in response window

### ISSUE THREAD

**Issue by nessatse** [Huachao/vscode-restclient#911]
- REST Client Version: v0.24.5
- VSCode Version: 1.61.0
- OS Version: Windows 10

Steps to Reproduce:

1.  Select text in response window
2.  Right click and select 'Copy'
3.  Paste the selected text in another window
4.  Selected text was not copied to clipboard

crtl-C works as expected though

**Comment by Huachao** [comment]
@nessatse I can't repro the issue
