### ISSUE TITLE
Add support for auto lock Response in editor

### ISSUE THREAD

**Issue by tehho** [Huachao/vscode-restclient#912]
In vsc 1.61 there is a possibility to lock a editor to not open new files in that editor.
Setting -> Workbench -> Editor: Auto Lock Groups

I would like to be able to add the Response to Auto Lock so when i open a new file i don't hide the response i just got back.
I find this useful when copying the response to save to a json file, just ctrl+n and save as new file. 

Problems to look for:
Shooting a new request should not open multiple editors but be able to reuse the locked editor.

**Comment by Huachao** [comment]
@tehho actually I didn't find the VSCode API to add my extension into the auto lock groups, if you see any other extensions can achieve this, please feel free to reopen it.
