### ISSUE TITLE
Response preview is no longer searchable anymore

### ISSUE THREAD

**Issue by xjevvvv7** [Huachao/vscode-restclient#916]

**Comment by Huachao** [comment]
@wotmshuaisi I can't repro, could you please show me a screenshot?

**Comment by wotmshuaisi** [comment]
![image](https://user-images.githubusercontent.com/16408269/139525453-5e95aad3-7ee1-4421-bd04-810e56af89cf.png)

If I downgrade vscode to 1.58.0, It works fine.

![image](https://user-images.githubusercontent.com/16408269/139525565-78e52ee7-19bc-407c-b86d-7ada36244b61.png)
