### ISSUE TITLE
GraphQL request don't support operationName

### ISSUE THREAD

**Issue by FreshPer** [Huachao/vscode-restclient#919]
Right now, rest-client supported GraphQL requests already, when I request something 

```
query testquery {
    getSomething{...}
}

```
the request body like this
```
{
    "query": "query testquery{...}",
   "variables": { some varibale }
}
```
In fact, in GraphQL the name `testquery` is called `operationName`, so the request body should like this
```
{
   "operationName": "testquery"
   "query": "query testquery{...}",
   "variables": { some varibale }
}
```
so right now, rest-client don't support `operationName` in request body, hope rest-client can take this in to consider.

**Comment by Huachao** [comment]
@FreshPer I have fixed this in the commit b60f628, and it will be published in the next release

**Comment by Huachao** [comment]
@FreshPer you can try this in the latest version 0.24.6

**Comment by docwarems** [comment]
I didn't get the idea. I tried it and got this

![grafik](https://user-images.githubusercontent.com/29914148/153359557-ec6c3026-648d-45d8-b17b-18bb1d149e50.png)
