### ISSUE TITLE
Switch on/off VS Code proxy

### ISSUE THREAD

**Issue by GaryGao829** [Huachao/vscode-restclient#92]
- VSCode Version:1.11.2
- OS Version:Windows10 10586
- REST Client Version:0.14.1

Steps to Reproduce:

1. In VS settings, I configed proxy because in office I could not install plug-in directly.
2. But it couldn't access to company's server using proxy
3. So I hope your client could support an switch to choose whether using proxy in VS-code

Thanks

**Comment by Huachao** [comment]
@GaryGao829 this can be easily achieved by another extension named [toggle](https://marketplace.visualstudio.com/items?itemName=rebornix.toggle). After you installed this extension, just put following sample code in the keybindings.json, after that, just use the shortcut like `F3` below to achieve what you want. The first time you press `F3`, the proxy will become empty string, and press again, it will become the url I assigned. 

```json
{
        "key": "F3",
        "command": "toggle",
        "args": {
            "id": "proxy",
            "value": [
                {
                    "http.proxy": ""
                },
                {
                    "http.proxy": "http://127.0.0.1:8005"
                }
            ]
        }
    }
```
