### ISSUE TITLE
"Save Response Body" to get output filename from Content-Disposition (if available)

### ISSUE THREAD

**Issue by mbronk** [Huachao/vscode-restclient#924]
Currently, the **Save Response Body** option does auto-pick an extension based on Content-Type
Ref:
https://github.com/Huachao/vscode-restclient/blob/98fcad29c7d9416133df23129730253045662f29/src/views/httpResponseWebview.ts#L147

It would be nice, if it also picked up the server-provided name, provided through **Content-Disposition** (for "downloads").
E.g. save to _test.zip_, for a `Content-Disposition: attachment; filename="test.zip"` (similar to what curl's _--remote-name --remote-header-name_ does)

**Comment by Huachao** [comment]
@mbronk this has been published in the latest version 0.24.6 and you can have a try

**Comment by mbronk** [comment]
@Huachao - Just gave 0.24.6 a spin - works nicely! Thanks for integrating this enhancement.
