### ISSUE TITLE
Parse '\uXXXX'

### ISSUE THREAD

**Issue by programus** [Huachao/vscode-restclient#931]
Sometimes, the json response may include `\uXXXX`, which is hard to read for human. 
I hope there is a feature to parse these characters to the readable ones. 

This is how I think the feature works: 

The default result is the raw response with `\uXXXX`,and user can check 'parse unicode' or something from menu any time and also can switch it back.

**Comment by Huachao** [comment]
@programus as the README documented, you can try set `rest-client.decodeEscapedUnicodeCharacters` to `true`
