### ISSUE TITLE
Can't copy request and response in clipboard

### ISSUE THREAD

**Issue by ndinev** [Huachao/vscode-restclient#932]
- REST Client Version: v0.24.5
- VSCode Version: 1.62.3
- OS Version: Windows 10

Steps to Reproduce:

1. setup your plugin so you can see both request and response 
2. execute some simple request - request and response appear in new tab - ok
3. go to this new tab and select all and then copy

BUG: Nothing copied in clipboard

**Comment by Huachao** [comment]
@ndinev I can't repo the issue, did it work with Ctrl+C

**Comment by ndinev** [comment]
Sorry for the late response

I does not work with keyboard and from context menu as well

**Comment by ndinev** [comment]
I decided to uninstall and reinstall the extension - now works file

**Comment by Huachao** [comment]
Glad to hear that, thanks for your response
