### ISSUE TITLE
GraphQL directives are being sent as operationName

### ISSUE THREAD

**Issue by beppler** [Huachao/vscode-restclient#934]
- REST Client Version: v0.24.6
- VSCode Version: 1.62.3
- OS Version: Windows 10 (21H2)

Hi, b60f628 (that resolves #919) just broke the case where we pass directives to the graphql query, directives can appear like this:

```graphql
query @directive {
  field1
  field2
}
```

With b60f628 the directives are being sent as operationName and this make the server respond that the operation does not exist.

Steps to Reproduce:

1. Create a query using one or more directives
2. Send request, the directives are being sent as operationName.

**Comment by Huachao** [comment]
@beppler thanks for your response, do you mean that we should treat the word followed by `query` not as an operation name if has the `@` prefix

**Comment by Huachao** [comment]
@beppler I have fixed the issue and will publish in the next release
