### ISSUE TITLE
arabic characters appears in a wrong formart

### ISSUE THREAD

**Issue by mohadel92** [Huachao/vscode-restclient#935]
- REST Client Version:v0.24.6
- VSCode Version:1.62.3

- OS Version: macos 11.3

Steps to Reproduce:

1. send request 
2. receive data with wrong formart
`"details": "\u0633\u0628\u0648\u0631\u0647 \u0628\u0631\u0648\u062c\u064a\u0643\u062a\u0648\u0631 \u0627\u0635\u0644\u064a\u0647 3\u0627\u0633\u0637\u0648\u0627\u0646\u0627\u062a 28\u0634\u0643\u0644 \u0645\u062e\u062a\u0644\u0641 \u0635\u0648\u062a \u0648\u0646\u0648\u0631 12\u0644\u0648\u0646 \u0647\u062f\u064a\u0647 \u0628\u0634\u0627\u0648\u0631\u0647 \u0648\u0643\u0631\u0627\u0633\u0647 \u0631\u0633\u0645 \u0627\u0637\u0644\u0628\u0647\u0627 \u0627\u0644\u0627\u0646 \u0648\u0627\u062d\u0635\u0644 \u0639\u0644\u064a \u0647\u062f\u064a\u0647 \u0645\u0645\u064a\u0632\u0647",`

**Comment by Huachao** [comment]
@mohadel92 how about set the setting `rest-client.decodeEscapedUnicodeCharacters` to `true`
