### ISSUE TITLE
cannot show raw big-data. [ 613361 bytes]

### ISSUE THREAD

**Issue by elky84** [Huachao/vscode-restclient#94]
- VSCode Version: 1.121.1
- OS Version: Windows 10
- REST Client Version: 0.14.2

Steps to Reproduce:

1. request big-data REST call.
2. can't show data. that's never server problem. another client has no problem. [e.g postman, firefox httprequester]

solve please! and thanks make this extensions.

**Comment by Huachao** [comment]
@elky84 what do you mean big-data, does it mean the response body size is very large?

**Comment by Huachao** [comment]
@elky84 this is a known issue #59 , and can you see results if you set the flag `rest-client.previewResponseInUntitledDocument` to `true`

**Comment by elky84** [comment]
@Huachao set `rest-client.previewResponseInUntitledDocument` to `true `.
resolve this issue.

but i think this solution is temponary. [no highlight result]

is that right?

if right, you will fix this issue?

fast reply thank you.

**Comment by Huachao** [comment]
@elky84 this is a temporary fix. And I am considering a way to fix this and notify you as soon as the issue is totally fixed. Sorry for the inconvenience.

**Comment by elky84** [comment]
I like this extension. And often used.

thanks!

**Comment by Huachao** [comment]
@elky84 I have improved the performance of rendering large response like hundreds of KB, decrease the latency of highlight the response body from 30s to less than 3s. And the time you experience of rendering the page may still be less than 10s(still much better than previously), the gap(5-6s) is mainly from vscode to render large html page(here is my response).

I will publish this fix in next release, and you can verify then.

**Comment by Huachao** [comment]
@elky84 you can try the latest version to verify

**Comment by elky84** [comment]
wow! fix it!

very fast, very nice fix.

thanks!
