### ISSUE TITLE
Response opens in the same tab with request file

### ISSUE THREAD

**Issue by denismaitak** [Huachao/vscode-restclient#940]
- REST Client Version: 0.24.6
- VSCode Version: 1.63
- OS Version: Ubuntu x64 5.4.0-91-generic

Steps to Reproduce:

1. Send Request
2. Move Response to another tab
3. Send Request again

Response always opens in the same tab with a request. It was very usable to watch response in the tab beside. I see the option in settings and looks like the settings is ignored. One-two weeks ago it worked as expected.

**Comment by MofX** [comment]
It is even worse:

I have a notebook with several requests. When I send the first request from this notebook, it opens in split tab. When I send the next one, the response output is moved to the same split window as the notebook.
And if the notebook is temporarily opened (I don't know how this is called in vscode, when you click a file in the editor and it is shown in recursive and closed, when you click the next file), the notebook with the requests is closed and replaced with the response after I send the second request from this notebook.

Something else I've noticed:
After disabling "Preview Response Panel Take Focus", the response is always opened in the same split as the notebook, even with "Preview Column" set to "beside"

**Comment by simonstey** [comment]
> One-two weeks ago it worked as expected.

I downgraded to v0.24.5 and still get this behavior.. I have the sneaking suspicion this might have something to do with vscode directly 🤔 (I'm on vscode 1.63)

**Comment by denismaitak** [comment]
>

**Comment by Huachao** [comment]
It seems to be related to the microsoft/vscode#138914

**Comment by opensas** [comment]
Just to confirm, this is the workflow that is currently happening to me (and the lousy workaround I'm following)

- click on `Send request`
- the response opens at at the side of the current active column (ok)
- click again on `Send request`
- the response moves to another tab in the current active column

The workaround is to press `ctrl-w` to close the response window before clicking again on `Send request`

I hope vscode fixes this soon as it's rather annoying

**Comment by matiasg77** [comment]
I have the same issue

**Comment by parmouraly** [comment]
I may have found a workaround. Set:

```
"rest-client.previewResponseInUntitledDocument": true
```

and now every response seems to respect the `beside` setting for the preview.

```
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
OS: Linux x64 5.13.0-27-generic snap
```

**Comment by Huachao** [comment]
@denismaitak @MofX @simonstey @parmouraly @matiasg77 @opensas this should be fixed after VS Code upgraded to the latest version 1.64
