### ISSUE TITLE
Custom headers case is not respected (turned lower-case)

### ISSUE THREAD

**Issue by nimatrueway** [Huachao/vscode-restclient#954]
### Issue statement and analysis

As I understood, the underlying http client used is [got](https://github.com/sindresorhus/got/) and this library [turns all header names into lowercase](https://github.com/sindresorhus/got/issues/1551) and they request for respecting the case was rejected because by http-spec headers are case sensitive.

However not all applications are fully http-spec compliant, like the services I'm dealing with daily.

### Example

```
GET http://localhost:8080/blahblah/34451776
X-As-Member-Id: 13419686
```
is sent as

```
GET http://localhost:8080/blahblah/34451776
x-as-member-id: 13419686
```

### Workaround

I found a quick way to patch **got** library on rest-client extension directly on the bundle

```
~/.vscode/extensions/humao.rest-client-0.xx.x/dist/extension.js
```

Find `Object.keys(Object` then find the `export` behind it and replace the js module's only exported function to **identity**

```
.exports=function(\w+){ ... }
```
to

```
.exports=function(e) { return e; }
```

Note: you will patching this file essentially https://github.com/sindresorhus/lowercase-keys/blob/main/index.js turning it into an identity function.

**Comment by Huachao** [comment]
@nimatrueway I think the root cause is the underlying nodejs `http` module will send all the request headers in the lower case

**Comment by hudsonventura** [comment]
Thanks @nimatrueway. The perfect information. It works!
