### ISSUE TITLE
vscode rest client extention sending content as octet-stream instead of json

### ISSUE THREAD

**Issue by NooneXe** [Huachao/vscode-restclient#959]
I have following rest service in java spring

```java
@PostMapping("/create")
public void createstuff(@RequestBody @Valid SomeClass obj) {
   //some stuff
}

```

I can successfully send the obj json with curl and hoppscotch(similar to postman)

```bash
curl -X POST http://0.0.0.0:8080/create \ 
  -H 'Content-Type: application/json' 
  -d '{"field1" : "and its value"}'
```

same request made with hoppscotch also works

but this request

```http
POST http://localhost:8080/create

content-type: application/json

{
    "field1" : "and its value"
}
```

made from vscode [rest client][1] does not works. 

in spring terminal, I get follwoing:-

```
2022-01-14 17:01:45.303  WARN 26935 --- [nio-8080-exec-2] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpMediaTypeNotSupportedException: Content type 'application/octet-stream' not supported]
```

  [1]: https://github.com/Huachao/vscode-restclient

**Comment by AnWeber** [comment]
There is no empty line between request line and headers

```
POST http://localhost:8080/create
content-type: application/json

{
    "field1" : "and its value"
}
```

**Comment by Huachao** [comment]
> ```httpspec
> POST http://localhost:8080/create
> 
> content-type: application/json
> 
> {
>     "field1" : "and its value"
> }
> ```

@AnWeber is right, remove the blank line between request line and headers
