### ISSUE TITLE
getting error "Unable to open'Response(xxxms)': Cannot read property 'toLowerCase' of null"

### ISSUE THREAD

**Issue by beomagi** [Huachao/vscode-restclient#96]
- VSCode Version: 1.12.1
- OS Version: Windows 7 Enterprise
- REST Client Version: 0.14.3

Steps to Reproduce:

1. highlighted a url and pressed ctrl+alt+r
url is "http://10.249.145.83:8084/key/test"

expected:
{ ~ }  » curl http://10.249.145.83:8084/key/test
123

2. The url was the only thing in the editor window.

**Comment by Huachao** [comment]
@beomagi I guess the cause is that the response doesn't have a `Content-Type` header, if so, I know how I can fix the issue. Can you set `rest-client.previewResponseInUntitledDocument` to `true` in setting file, and then check if the response has this header. Sorry for the inconvenience.

**Comment by Huachao** [comment]
@beomagi you can try the latest version 0.14.4 to verify

**Comment by beomagi** [comment]
Thanks, seems to work fine after the change. Update works too!
