### ISSUE TITLE
Response preview not consistently opened to where it should be

### ISSUE THREAD

**Issue by ashalfarhan** [Huachao/vscode-restclient#961]
- REST Client Version: 0.24.6
- VSCode Version: 1.63.2
- OS Version: Darwin arm64 21.2.0

I don't know if this is a bug or the actual behaviour, but why is the response preview is not consistently opened to the `right`. 

With Reload or fresh open: 

https://user-images.githubusercontent.com/70800415/151650845-9cd04fa8-794b-4ca1-b826-97465b549c3d.mov

After closing the response tab:

https://user-images.githubusercontent.com/70800415/151650954-2142c7e0-da61-4a09-a8b0-411d35998985.mov

Steps to Reproduce:

1. Open vscode or reload the current window
2. Open the .http or .rest file, send the request more than once in sequential
3. The preview response tab should stay still on the right,
4. But, if you close the response tab, and .rest / .http file, and then open the file again, send the request more than once again, the response tab isn't consistently opened to the right editor.

**Comment by Alukardz** [comment]
The same is happening to me while the debug python is running in another vs window, sending the request will open it in a new tab or to the right 50/50 chance apparently.

**Comment by bjorkstromm** [comment]
Same here. First response always opens to the right, But if I don't close the response, and run another request, then response opens in a new tab covering the `http` file.

**Comment by Huachao** [comment]
This should be fixed automatically after VS Code upgrades to latest 1.64
