### ISSUE TITLE
Quickpick Filter does not reset after selecting a language when Generating Code Snippet

### ISSUE THREAD

**Issue by TheBinaryGuy** [Huachao/vscode-restclient#963]
- REST Client Version: 0.24.6
- VSCode Version: 1.63.2
- OS Version: 22000.469

Steps to Reproduce:

1. Open Generate Code Snippet Quickpick: Rest Client: Generate Code Snippet
2. Search for a language: java
3. Select a language: javascript
4. Filter text doesn't go away, and filters the next step, which hides the actual entries

Gif of the issue:
![Code_PojtjzqbcG](https://user-images.githubusercontent.com/13674136/152119475-97710da9-5dd0-4d35-bda4-79d62e9e1998.gif)

**Comment by TheBinaryGuy** [comment]
I can take this issue if you want me to.

**Comment by Huachao** [comment]
@TheBinaryGuy this fix has been released in the version 025.0, thanks for your contribution

**Comment by TheBinaryGuy** [comment]
> @TheBinaryGuy this fix has been released in the version 0.25.0, thanks for your contribution

Thank you!
