### ISSUE TITLE
Button to send different request on the same file is not available.

### ISSUE THREAD

**Issue by SumentsJavi** [Huachao/vscode-restclient#964]
- REST Client Version: v-0.24.6
-  VSCode Version: 1.63.2
- OS Version Ubuntu 20.4
Steps to Reproduce:

Image attached
![image](https://user-images.githubusercontent.com/57916256/152318639-60a5c953-52c4-4e2c-97b0-07ed43b43fbc.png)

**Comment by Huachao** [comment]
@SumentsJavi Requires the separator `###` between different requests
