### ISSUE TITLE
request with client certificate

### ISSUE THREAD

**Issue by ridicoulous** [Huachao/vscode-restclient#97]
- VSCode Version: 1.12.2
- OS Version: Windows 10
- REST Client Version: 0.14.4

Steps to Reproduce:

If I use curl on Linux, this request  returns OK: curl --cert-type P12 --cert myfuel.p12:certpassword -u "username:userpassword" -v -X GET -H "Content-Type: application/json" "https://api.sandbox.gateway.com/ping" But in VS Code I have an exception. Any ideas?

**Comment by Huachao** [comment]
@ridicoulous could you also please provide your request and exception details to help to investigate the issue?

**Comment by Huachao** [comment]
@ridicoulous can you repro this, I'd like to close it now, since no one else reporting this issue. Please feel free to reopen it if you still meet this problem.
