### ISSUE TITLE
"Generate code snippet" does not encode basic authorization

### ISSUE THREAD

**Issue by codeborn** [Huachao/vscode-restclient#98]
- VSCode Version: 1.12.2
- OS Version: Mac OS X 10.11.6
- REST Client Version: 0.14.4

Steps to Reproduce:

1. Create a file auth.http:
GET https://example.com/api/some/endpoint
Authorization: Basic my-user my-password

2. Right-click and select "Generate code snippet". Select "Shell" and then "cUrl".

Result:
curl --request GET \
  --url https://example.com/api/some/endpoint \
  --header 'authorization: Basic my-user my-password'

Expected result:
curl --request GET \
  --url https://example.com/api/some/endpoint \
  --header 'authorization: Basic bXktdXNlcjpteS1wYXNzd29yZA=='

That is, with the basic authorization replaced with a base64 encoded representation, like what you would get when sending the request directly from the extension.

Anyway, thanks for creating the best HTTP-client for VSCode (that I have found this far ;) )!

**Comment by Huachao** [comment]
@codeborn I have fixed this issue, and will publish it in next release ASAP

**Comment by Huachao** [comment]
@codeborn you can try the latest version 0.14.5 to verify, sorry for the late

**Comment by codeborn** [comment]
Works great now! Thanks!

However, I just noticed that when using POST the body data is not included. I will file a separate issue regarding that.
