### ISSUE TITLE
Cookie is used even if header "Authorization" was changed

### ISSUE THREAD

**Issue by gerritgriebel** [Huachao/vscode-restclient#983]
- REST Client Version: v0.24.6
- VSCode Version: 1.65.2 using ssh remote plugin
- OS Version: macOS 12.3

Steps to Reproduce:

1. Use Authorization header with "Basic" login and password: Authorization: Basic <login> <password>
2. Send it successfully
3. Change Authorization header, for example change password
4. Send it again successfully, even with incorrect password

Seems client memorizes credentials and uses them with 2nd send. Also changing login has no effect: old login is used.

**Comment by gerritgriebel** [comment]
found problem: rest-client.rememberCookiesForSubsequentRequests ... It's not a bug, it's a feature :) I think opt-in would be better that opt-out

**Comment by verydemo** [comment]
> found problem: rest-client.rememberCookiesForSubsequentRequests ... It's not a bug, it's a feature :) I think opt-in would be better that opt-out. Maybe not use cookie, when Authorization was changed?

Hello, I have also encountered this problem, how to clear vscode cookies? Thank you

**Comment by Huachao** [comment]
@verydemo currently you have to clear the content in `~/.rest-client/cookie.json`. And I will add a command to achieve this, sorry for the inconvenience
