### ISSUE TITLE
Can i read in resquest variable a property inside of another property?

### ISSUE THREAD

**Issue by MarianoGomezBidondo** [Huachao/vscode-restclient#985]
I'm calling a a login endpoint to get a "AccessToken" in this way but i cant get the "AccessToken" property from inside of receibed 

```
###LOGIN
# @nane loginrequest
POST https://someurl
content-type: application/json

{ "username":"someuser",	"password":"somepassword",	"refresh_token": null }

// THE RESPONSE IS:
//// {
//     "Error": false,
//     "Success": true,
//     "Message": "Login ok.",
//     "Data": {
//       "IdToken": "xxxxx",
//       "RefreshToken": "yyyyy",
//       "AccessToken": "zzzzz",
//       "ExpiresIn": 21600
//     },
//     "ResultCode": 200
//   }

### VARIABLE RESPONSE TO FILL TOKEN
@authtoken= {{loginrequest.response.body.$.Data.AccessToken}

### VCloud Stores API Gateway . GetOrdersIds
GET https://someurl  HTTP/1.1
Content-Type: application/json
Authorization: {{authtoken}}

```

read properties from inside of a json object is supported?

**Comment by owns** [comment]
Yes!  I use this within an oauth2.0 flow and grabbing the token is just
`@token = {{loginrequest.response.body.access_token}}`
The 2 issues I see in your example are:
1. The `$` in the variable.  Not sure that's needed: `@authtoken= {{loginrequest.response.body.Data.AccessToken}`
2. Authorization is usually prefixed with 'Bear ', depending on your auth type (but nearly all I've used have it).  So you should have
````
Authorization: **Bearer** {{authtoken}}
````

**Comment by brianbcampbell** [comment]
@MarianoGomezBidondo 
I'll add 2 more typos i see:

1. `# @nane loginrequest`   << @name misspelled
2. `@authtoken= {{loginrequest.response.body.$.Data.AccessToken}`  <<missing one } at the end

Here is a working example:
```
@token={{loginrequest.response.body.access_token}}

###  GET BEARER TOKEN  =========================================
# @name loginrequest
POST {{auth-host}}/token
content-type: application/json

{"username": "USER@SERVER.com","password": "PWPWPWPW"}

### ======= GET DATE ============================================
GET {{host}}/guest/getDate
Authorization: Bearer {{token}}
```
Please close the issue if this helps. Thanks!
