### ISSUE TITLE
Documentation needs update?

### ISSUE THREAD

**Issue by MrAmericanMike** [Huachao/vscode-restclient#988]
So I was reading on the way to use .env variables inside different requests and the documentation mentions to do it like so (https://marketplace.visualstudio.com/items?itemName=humao.rest-client)

```js
{{$dotenv [%]variableName}}
```

However, after looking around a bit more I found that the correct way is with (https://github.com/Huachao/vscode-restclient/issues/489)

```js
{{$dotenv variableName}}
```

Is this something that needs to be updated, or both methods should work?

**Comment by mrverdant13** [comment]
There is an specific line that describes this:

	%: Optional. If specified, treats envVarName as an extension setting environment variable, and uses the value of that for the lookup.
